### ISSUE TITLE
Use Case Notebook for "Statistical Downscaling"

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#11]
I will be working on developing a use case notebook that covers statistical downscaling of climate model datasets. 

### Summary

Excerpt from [NSF Earthcube Proposal](https://figshare.com/articles/Pangeo_NSF_Earthcube_Proposal/5361094):

> Downscaling is a procedure that relates information at large scales (ESMs) to local scales. With the common goal of addressing the issues described above, a range of downscaling methodologies have been developed that span a broad range of complexities from simple statistical tools to full dynamic atmosphere models. Ongoing research in the NCAR Water Systems Program (partially supported by NSF award AGS-0753581) is developing tools [22, 21] for understanding how methodological choices in the downscaling step impact the inferences end-users may draw from climate change impacts work.
>
>The specific workflow to be implemented will enhance ongoing research in the NCAR Water Systems Program by developing a Python-based toolkit for circulation-based statistical downscaling. We will leverage the tools developed in this project to build an extensible and user-friendly interface for existing tools currently written in low level languages (C and Fortran), specifically the Generalized Analog Regression Downscaling (GARD) toolkit. Using this interface, GARD will be extended to support additional downscaling methodologies that utilize high-level machine learning packages available in Python (e.g., scikit-learn, PyMVPA) and to operate on larger datasets than is currently possible. The end product will be an open-source package that enables future downscaling work throughout the climate impacts community.

### Workplan
My proposed work plan will follow these steps:

1. Implement traditional statistical downscaling methods in  (linear/analog/regression, see [GARD](https://github.com/NCAR/GARD)) in Python/Scipy/Xarray.
    - > *TODO: decide if we should write the GARD functions in Python or write a Python wrapper around existing Fortran code.*
2. Implement new machine learning downscaling method (artificial neural networks) in Python/Scikit-learn.
3. Apply these methods at individual grid points, use interactive Python/Jupyter notebooks to explore skill and parameter space.
4. Apply these methods to large spatial domains (CONUS), evaluating skill of downscaling method and computational performance

### Data:

I will be using the WRF 50-km CONUS downscaled CMIP5 dataset developed here at NCAR. I can provide more details on the dataset if others are interested.

### Requirements (for use case notebooks):

- [ ] Carefully explain the science behind the calculation in words and equations.
- [ ] Clearly document the input dataset (preferably a standard product like ERA-interim or NCAR large ensemble)
- [ ] Use Xarray to load the dataset and, as much as possible, to make the calculations
- [ ] Where Xarray can't accomplish the necessary tasks, clearly document the other functions and / or outside packages that need to be employed
- [ ] If the analysis has been implemented in other languages (e.g. MATLAB, Ingrid, etc.), provide a link to the code and, if possible, the output (which can be used as validation)

cc @gutmann

**Comment by rabernat** [comment]
Just a heads-up that the lack of any use case notebooks is now blocking progress on our project. It would be great to get some basic use cases checked in. They don't have to be fancy! Any sort of semi-realistic workflow on real data is enough for the systems people to move forward with analyzing performance.

**Comment by rabernat** [comment]
@jhamman: it would also be great to have the very simple demo notebook you showed last week checked in. Not all of the use cases have to be big and complicated. That demo was a great example of a strongly I/O bound workflow.

**Comment by jhamman** [comment]
@rabernat - its [here](https://anaconda.org/jhamman/cheyenne_xarray_dask_example) for now. Once we move on #12, I'll push it there.
