### ISSUE TITLE
Scikit-image biological example on pangeo platform

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#113]
I've placed about 100GB of biological imaging data onto GCS and produced a small example loading and manipulating that data.  See [this screencast](https://youtu.be/fRQZUyv1eJg).

My hope is to attract someone with more imaging experience to use the pangeo platform to do some non-earth-system-science with the same toolset

-  [Data explanaiton from Janelia](https://www.janelia.org/project-team/flyem/data-and-software-release)
-  [Data storage on GCS](https://console.cloud.google.com/storage/browser/pangeo-data/FIB-25/?project=pangeo-181919)
-  [Youtube screencast](https://youtu.be/fRQZUyv1eJg) (4 minutes)
-  [Notebook Gist](https://www.youtube.com/redirect?redir_token=kj4LvIWQeWLN1s9gVX-JrpCNXFl8MTUxODUzMDI3NkAxNTE4NDQzODc2&event=video_description&v=fRQZUyv1eJg&q=https%3A%2F%2Fgist.github.com%2F891885124c7c8ae3c3140186e4e56fe0)

This was run from a vanilla version of pangeo.  So anyone watching that video should be able to trivially reproduce it today by logging into http://pangeo.pydata.org with github credentials.

cc @shoyer (thanks for the data link) skimage folks: @stefanv @nellev @emmanuelle @jni and @jakirkham 

@rabernat any objection to spending resources going outside of earth-science scope?

**Comment by rabernat** [comment]
This is a pretty small amount of data, so the cost is minimal. No problem with me. I'm sure both NSF and Google will appreciate the fact that we have built something with interdisciplinary value.

**Comment by jni** [comment]
Ah! I still am interested in playing with this, but haven't had the time! I probably won't till SciPy. It's on my to-do, so feel free to close the issue, as long as the data sticks around. I also understand if you want to remove the dataset due to lack of activity.

**Comment by rabernat** [comment]
The dataset is very small, so no worries leaving it up.

We look forward to working with you whenever you're ready!
