### ISSUE TITLE
Include high-resolution WRF data and use case

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#114]
This [tweet thread](https://twitter.com/climatedynamics/status/963034545179242496) motivated Matthew Huber to suggest a new Pangeo use case:

> It’s the fine spatial res high temporal res files that are the main challenge. Make sure you include 4x daily 0.25 deg global gcm files and hourly 3km large domain WRF output as tests.

Matt offered to contribute some use cases and data. This could be a good point to entrain some new collaborators.

**Comment by areminusfarestar** [comment]
This is Matt. I have 300 TB of WRF data I can make available via globes. Lemme know.

**Comment by areminusfarestar** [comment]
Globus. Auto incorrect

**Comment by jhamman** [comment]
@areminusfarestar - I'd be interested in working with you on getting your data (or some of your data) onto GCP. Where is it currently and what is its current storage format?

**Comment by areminusfarestar** [comment]
Will do. Im busy next three days though. Data is WRF output mostly in
netcdf. I’ll make it available via Purdue globus portal.
