### ISSUE TITLE
Workers are slow to kick in (slow transfer of zarr objects)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#117]
I am running one of my use cases on the GCS deployment.

It's a very simple case where I load a dataset and calculate the timeseries.
```python
gcsmap = gcsfs.mapping.GCSMap('pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt')
ds = xr.open_zarr(gcsmap)
sla_timeseries = ds.sla.mean(dim=('latitude', 'longitude')).persist()
```

The image below shows what I commonly experience. One set of workers starts right away (I assume they are running close to the notebook). But it takes a long time (~20 s) for any other nodes to kick in. There is some communication process blocking the start of the computation.

![image](https://user-images.githubusercontent.com/1197350/36196287-1cb99f1a-1125-11e8-8918-7b0f76c9a460.png)

The names of those red communication tasks are `zarr-sla-transfer-` and they take about 20s.

Could this have to do with any of the recent xarray / gcsfs bugs that were fixed?  My understanding is that here we are using all the latest version (as of #115).

This gets worse for a bigger calculation on more nodes.

**Comment by mrocklin** [comment]
See https://github.com/pangeo-data/pangeo/issues/112

**Comment by rabernat** [comment]
Now that dask/gcsfs#57 has been merged, I guess we are just waiting for a dask release before marking this closed?

**Comment by rabernat** [comment]
closed by #128

**Comment by mrocklin** [comment]
Trying things out on the cluster now it's not clear to me that this is
resolved.

**Comment by rabernat** [comment]
Yes, you're right. I closed prematurely.

It is resolved if you do
```python
! pip install --upgrade --user git+https://github.com/dask/gcsfs.git
cluster = KubeCluster(n_workers=20,
                      env={'EXTRA_PIP_PACKAGES': '--upgrade git+https://github.com/dask/gcsfs.git'})
```

I assumed that, since gcsfs is pip installed from git in the worker dockerfile
https://github.com/mrocklin/pangeo/blob/4ac556385f89a28e78c4d79d03cc7a4ea3d79b96/gce/worker/Dockerfile#L35
and the docker images have been rebuild, that this would now be resolved be default. But it is not.

**Comment by mrocklin** [comment]
Hrm, that's surprising.

**Comment by rabernat** [comment]
Ok, I'm glad you're confused too. That makes my confusion feel more acceptable. 😬

**Comment by mrocklin** [comment]
This may now be resolved.  @rabernat if you're able to test with a clean-ish environment that would be welcome.

**Comment by rabernat** [comment]
Do you know the best way to remove things that may have been `pip install`ed in my user home directory and revert to the cluster defaults?

**Comment by mrocklin** [comment]
Unfortunately I do not.  I would resort to google searching for this.

**Comment by rabernat** [comment]
I was able to remove the user installs by doing this.

```python
>>> import sys
>>> sys.path.remove('/home/jovyan/.local/lib/python3.6/site-packages')
>>> import gcsfs
>>> gcsfs
<module 'gcsfs' from '/opt/conda/lib/python3.6/site-packages/gcsfs/__init__.py'>
```
so I assume I am getting the default environment.

Performance is much better now. 1s instead of 20s to to `transfer-zarr`.

This is a success story!

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by rabernat** [comment]
@mrocklin, what did you do to resolve this? Just redeploy the cluster?

**Comment by mrocklin** [comment]
@martindurant released a new version of gcsfs.  I then made new docker
images, pushed them, and then upgraded the cluster to point to them

**Comment by martindurant** [comment]
Hurray!

**Comment by rabernat** [comment]
I'm confused why a release of gcsfs was necessary. In the docker files, e.g.
https://github.com/pangeo-data/pangeo/blob/master/gce/worker/Dockerfile#L35
gcsfs is installed via `pip install git+https://github.com/dask/gcsfs`.

**Comment by mrocklin** [comment]
My guess is https://github.com/dask/gcsfs/issues/81

**Comment by martindurant** [comment]
pip will not update by default regardless of version; however passing --upgrade or -U can be dangerous as it considers updating other packages too. I'm not sure what's generally the best way to ensure using the latest version.

**Comment by rabernat** [comment]
But Matt made *new* docker images. There is nothing getting upgraded when the docker images are built. Since nothing in the Dockerfile installs gcsfs from pip / conda, I still don't understand why a release was necessary. I know this is a minute detail, but it just doesn't make sense to me.

**Comment by mrocklin** [comment]
I now pin directly

RUN pip install daskernetes==0.1.3 \
                git+https://github.com/zarr-developers/zarr \
                git+https://github.com/pydata/xarray \
                gcsfs==0.0.5 \
                --no-cache-dir

**Comment by rabernat** [comment]
So https://github.com/pangeo-data/pangeo/blob/master/gce/worker/Dockerfile is out of sync with what is running now? That's why we need #131 I guess.

**Comment by mrocklin** [comment]
https://github.com/pangeo-data/pangeo/pull/138
