### ISSUE TITLE
.load() only triggers computation on two workers

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#118]
We noticed a version of this bug earlier on, but I just wanted to note that it is still going on.

My normal way of interacting with dask is to call `.load()` at the end of some pipeline to bring the (usually small) data to my local notebook for plotting. On GCP, calling load only triggers two workers to start computing, leaving the rest of the cluster idle. Instead if I do `.persist()`, everybody joins in.

Here is an example anyone can run
```python
gcsmap = gcsfs.mapping.GCSMap('pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt')
ds = xr.open_zarr(gcsmap)
# this only uses two workers
sla_timeseries = ds.sla.mean(dim=('latitude', 'longitude')).load()
# this uses all workers
sla_timeseries = ds.sla.mean(dim=('latitude', 'longitude')).persist()
```

It would be great if we could resolve this, because I like using `.load()` and this is what most existing xarray users are used to.

**Comment by jhamman** [comment]
@rabernat, what happens if you do 
```python
sla_timeseries = ds.sla.mean(dim=('latitude', 'longitude')).persist().load()
```

**Comment by rabernat** [comment]
`.persist().load()` does not resolve the problem. Only two workers participate.

Instead, if I wait for persist to actually finish and *then* call load, this works.

**Comment by rabernat** [comment]
@mrocklin do you have any thoughts on this issue? I can't figure out how to reproduce it outside of the GCP environment, so I am hesitant to open a dask issue.

**Comment by mrocklin** [comment]
This has been resolved in https://github.com/dask/distributed/pull/1777 

You should only need to update your notebook environment to see it work well.  It was only a problem when launching a cluster from a Jupyter Notebook (where parts of the scheduler accidentally shared the Jupyter IOLoop).
