### ISSUE TITLE
Cabled Array Hack Week

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#123]
Hi. I'm hoping to run a Pangeo demo for [Cabled Array Hack Week](https://oceanhackweek.github.io/cabled_array_hw2018/). Hopefuly I will be running this on https://pangeo-aws.cloudmaven.org, but if we don't get it working properly, I would like to run the demo on pydata.org. In testing the demo on pydata.org, I appear to have done something that may have crashed nginx, and I can no longer talk to my notebook server. Can I ask someone to shutdown my notebook server on pangeo.pydata.org? Or maybe there is a way that I can do this myself so that I don't have to bug anyone? Thanks!

**Comment by mrocklin** [comment]
You may be able to do this yourself by navigating to
http://pangeo.pydata.org/hub/login

**Comment by mrocklin** [comment]
Just checking, but if you are looking for a hosted notebook experience and don't need distributed computing then https://mybinder.org/ is probably a more stable solution.

**Comment by jhamman** [comment]
@tjcrone - It seems like your notebook server had fully crashed. I shut it down for you. You can try logging in again.

**Comment by tjcrone** [comment]
@jhamman Thanks! @mrocklin My goal is to show everyone some specific capabilities of Pangeo, including daskernetes. Hopefully I can get it working on pangeo-aws.cloudmaven.org! Wish me luck. Thanks for your help.

**Comment by rabernat** [comment]
Just for some context here, Tim is a colleague at Lamont. I encouraged him to try this.

**Comment by tjcrone** [comment]
yeah, @rabernat made me do it.

**Comment by tjcrone** [comment]
@mrocklin I found that http://pangeo.pydata.org/hub/home takes me to the old jupyterhub server control page. This may be the link that will allow me to shutdown my server on my own.

**Comment by jhamman** [comment]
I sat down with @tjcrone earlier today. I'm hoping he can share what we came up with.  His workflow is something we haven't explored yet (extensive use of dask.delayed) with pangeo yet and I think would make a good use case example.

**Comment by mrocklin** [comment]
+1 on sharing examples.  It would be really valuable to have a few that represented different classes of workflows.

**Comment by rabernat** [comment]
@tjcrone--it would be great to get your examples archived someone.
