### ISSUE TITLE
Max number of workers

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#126]
Are users limited to the number of workers they can spawn? If so, what is the default limit? Is there a way to change it? Is there an easy way to kill workers not being used in one notebook so that more can be launched for another notebook? Thanks!

**Comment by rabernat** [comment]
They are limited by kubernetes, which restricts the total size of the cluster. This limit can be adjusted by the cluster admin via the cloud console or kubectrl command.

Right now we show 22 nodes in the pangeo.pydata.org node pool, with a max of 100.

**Comment by mrocklin** [comment]
> Is there an easy way to kill workers not being used in one notebook so that more can be launched for another notebook?

You can always scale down a cluster

    cluster.scale(0)

Turn it onto adaptive mode so that it scales down automatically

    cluster.adapt()

Or just restart the notebook kernel, which will cause an automatic cleanup

**Comment by tjcrone** [comment]
Thanks. Can you tell me how this limit is set with kubectrl? I noticed in the setup.sh script this line

`gcloud container clusters create pangeo --num-nodes=10 --machine-type=n1-standard-2 --zone=us-          central1-b  --cluster-version=1.8.4-gke.1`

appears to launch 10 nodes. Are these ten nodes used for running the notebook servers? And is where the limit is set? Might be overkill for me to run this many nodes to accommodate notebook servers.

Sorry for all the beginner questions. I'm a beginner.

**Comment by mrocklin** [comment]
These ten nodes are on all the time.  They are used for both notebook and dask worker pods.  You can also enable auto-scaling at the google cloud or aws layer to have the number of nodes on which pods can be launched also increase or decrease with use.

**Comment by tjcrone** [comment]
Thanks Matt. Very much looking forward to learning how to do this!
