### ISSUE TITLE
gcsfs branch for pangeo

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#127]
I would like to push up new worker and notebook images.  What branch of gcsfs should I use?  

Short term it might be good to have a `pangeo-deploy` branch that was always the right choice for this group.  That might also help to avoid the habit of pushing to master.

**Comment by jacobtomlinson** [comment]
Is this still relevant?

**Comment by rabernat** [comment]
I believe that we are now using the current master branch of gcsfs.
