### ISSUE TITLE
Add Docker image selector to login page

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#133]
This would allow research groups (like @rsignell-usgs and @tjcrone) to craft their own software environments rather than depend on our vanilla environment. 

A path to support this is described by @minrk and @choldgraf at https://github.com/pangeo-data/pangeo/issues/109

The steps there seem somewhat accessible if anyone wants to take a crack at it.  This would, I think, have a large impact.  If I were to start this I would experiment locally with a vanilla [Zero-to-JupyterHub](http://zero-to-jupyterhub.readthedocs.io/en/latest/) deployment on [minikube](https://github.com/kubernetes/minikube)

**Comment by mrocklin** [comment]
cc @rabernat in case you're still looking for intern projects.  My take on this is that it requires coming up to speed on a few things, but it's mostly about following pretty-good documentation.

**Comment by rabernat** [comment]
Very useful idea. You're right that this sounds like a good intern project. I'll talk to @tjcrone and see what he thinks.

**Comment by rabernat** [comment]
@jacobtomlinson pointed us to this:

https://github.com/jupyterhub/kubespawner/issues/135#issuecomment-369599900

**Comment by mrocklin** [comment]
@jhamman if you're interested in another JupyterHub related task, this would be a very valuable one :)

**Comment by mrocklin** [comment]
https://github.com/jupyterhub/kubespawner/pull/137 was just merged if anyone wants to investigate this.  I think it would help out users with different environment needs like @rsignell-usgs and @ocefpaf

**Comment by dopplershift** [comment]
(not actually merged yet)
