### ISSUE TITLE
Layered docker/user environment

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#136]
The UK Met office is currently thinking about supporting custom user environments by layering two environments:

1.  A conda environment from the docker container, defined by whoever made the image (presumably some IT professional or group leader)
2.  A user environment stored in some mounted home directory

With `pip` this is fairly easy to accomplish by using `pip install --user`, but what is the right way to do this with conda?

**Comment by mrocklin** [comment]
My first guess at an answer to this question is "it's not possible".  While pip environments are just a set of packages in a few locations that are searched in order, conda environments are verified to work together.  Changing a single package often results in resolving the dependencies.  It might not be trivial to merge two layered environments together.

I don't know though, there might be tricky ways around this.  I'll ping some conda folks I know.

**Comment by msarahan** [comment]
I think it's possible, just a question of how nice it will work.  Ultimately, all of this stuff respects lower-level rules (search paths).

As long as the things installed in some mounted user home dir are compatible with the conda environment (i.e. any binary dependencies match up, and any .pyc's files lying around are ignored/cleaned up/overwritten), I see no fundamental reason why this shouldn't work.

FWIW, I do something very similar for developing conda-build.  I have a docker image that I use to bootstrap miniconda and conda-build's dependencies.  I then mount my home "code" folder, and do a ``pip install -e .`` of conda-build from there.

This may be an actual valid use case for setting PYTHONPATH - but of course be extremely careful with that.

**Comment by mrocklin** [comment]
cc @jacobtomlinson

**Comment by msarahan** [comment]
One further tip: I set the PYTHONDONTWRITEBYTECODE environment variable, just so I avoid conflicts/confusion with pyc files.

**Comment by mrocklin** [comment]
Correct

**Comment by msarahan** [comment]
Let's assume binary compatibility (if someone is using a mac, and they run a docker container, their mac conda environment will not run in the linux container).

You can, in fact, have multiple conda environments "activated" at a time.  We do this in conda-build to support cross compiling, and the notion of one env for "build tools" and another for libraries and things like python.  I think that you basically want to utilize this.  You would not be able to import libraries from the outer environment, but you could run executables from it.  If you hacked PYTHONPATH, that might work, but would be more fragile.  The code that does this for conda-build is at https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1037-L1069

Activate the higher priority env last.

If this is still not what you want, then I'm not sure it's possible to do what you want.  I don't know how to mount something into a folder structure while also preserving the contents of that folder structure.  That's fundamentally what it would take to have outer and inner truly behave as one.

**Comment by jacobtomlinson** [comment]
Yes binary compatibility is not an issue. Everything will be in linux containers.

The kind of thing I had in mind would be for your default environment to be in the docker image. Then if I did something like `conda install boto3` that package would be installed to my home directory. That directory would be first in my python path, before the default environment. 

If that package caused a downgrade of one of the system packages for compatibility then I would expect the downgraded version to also be installed in my home directory and therefore loaded first.

**Comment by rabernat** [comment]
@jacobtomlinson: under this scenario, would the conda environment where the notebook is running automatically be the same as the one where the dask workers run? Can they all see the same home directory?
