### ISSUE TITLE
500 internal server error on server startup

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#139]
When I try "start my server" this morning (http://pangeo.pydata.org/hub/user/rsignell-usgs/) I'm getting a 500 internal server error (after 15 minutes of "starting my server"!)

**Comment by mrocklin** [comment]
Confirmed on my end as well:

```
mrocklin@carbon:~$ kubectl logs jupyter-mrocklin -n pangeo
Copy files from pre-load directory into home
+ echo 'Copy files from pre-load directory into home'
+ cp --update -r -v /pre-home/. /home/jovyan
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
no environment.yml
+ '[' '' ']'
+ '[' '' ']'
+ '[' pangeo-data ']'
+ echo 'Mounting pangeo-data to /gcs'
Mounting pangeo-data to /gcs
+ /opt/conda/bin/gcsfuse pangeo-data /gcs --background
+ start-singleuser.sh '--ip="0.0.0.0"' --port=8888 '--NotebookApp.default_url="/lab"'
Execute the command: jupyterhub-singleuser --ip="0.0.0.0" --port=8888 --NotebookApp.default_url="/lab"
[W 2018-03-05 11:45:50.400 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2018-03-05 11:45:51.021 SingleUserNotebookApp manager:40] [nb_conda_kernels] enabled, 2 kernels found
[I 2018-03-05 11:45:51.469 SingleUserNotebookApp extension:53] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2018-03-05 11:45:51.469 SingleUserNotebookApp extension:54] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2018-03-05 11:45:51.480 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[I 2018-03-05 11:45:51.487 SingleUserNotebookApp notebookapp:1445] Serving notebooks from local directory: /home/jovyan
[I 2018-03-05 11:45:51.487 SingleUserNotebookApp notebookapp:1445] 0 active kernels
[I 2018-03-05 11:45:51.487 SingleUserNotebookApp notebookapp:1445] The Jupyter Notebook is running at:
[I 2018-03-05 11:45:51.487 SingleUserNotebookApp notebookapp:1445] http://0.0.0.0:8888/user/mrocklin/
[I 2018-03-05 11:45:51.487 SingleUserNotebookApp notebookapp:1446] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by mrocklin** [comment]
Raised upstream: https://github.com/jupyter/docker-stacks/issues/569

**Comment by mrocklin** [comment]
Although I have no idea why things would have changed recently.  

Ah, that issue may not be relevant actually, digging deeper.

**Comment by rabernat** [comment]
Thanks for your quick reply @mrocklin!

I'm sure you are not eager to assume the role of on-call sysadmin for pangeo.pydata.org. If you would care to share some notes about how your debugged and fixed the kubernetes problem, that would help spread the knowledge around. Then someone else can do it next time. In particular, how did you "upgrade the version of Kubernetes on the cluster"?

**Comment by mrocklin** [comment]
Google has been bugging us to do this for some time with warnings on the console page console.cloud.google.com/kubernetes/list?project=pangeo-181919

I just followed their instructions on the website

**Comment by rabernat** [comment]
I am getting 500 server errors again when starting my server. This is fairly urgent to fix, as I am giving a big demo of pangeo.pydata.org today at Lamont.

**Comment by rabernat** [comment]
Ok, nevermind, I tried again and it worked ok.

**Comment by rsignell-usgs** [comment]
Getting 500 server errors again this morning.

**Comment by jacobtomlinson** [comment]
This is most likely related to the failed deployments I've been having this morning. Currently looking into it.

**Comment by jacobtomlinson** [comment]
Error log is showing an issue with the jupyterhub oauth module.

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/github.py", line 119, in authenticate
        access_token = resp_json['access_token']
    KeyError: 'access_token'
```

**Comment by jacobtomlinson** [comment]
The issue is now fixed, however I accidentally caused the IP of the service to change. A request has been made for pangeo.pydata.org to be updated to the new IP but in the mean time you can add `35.226.234.19	pangeo.pydata.org` to your `/etc/hosts` file to get access to the service.

Sorry for any inconvenience!

**Comment by srjkrl20011991** [comment]
Please HELP ----------I am new in angular ... getting error
CREATE UserApp/e2e/tsconfig.e2e.json (213 bytes)
npm ERR! code E500
npm ERR! 500 Internal Server Error: autoprefixer@^8.4.1

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\suraj.karale\AppData\Roaming\npm-cache_logs\2018-07-03T06_16_43_259Z-debug.log
Package install failed, see above.

Version Details -

Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular:
...

Package Version

@angular-devkit/architect 0.6.8
@angular-devkit/core 0.6.8
@angular-devkit/schematics 0.6.8
@schematics/angular 0.6.8
@schematics/update 0.6.8
rxjs 6.2.0
typescript 2.7.2

**Comment by rabernat** [comment]
> The issue is now fixed, however I accidentally caused the IP of the service to change.

Can you explain how this happened? The following lines of the `jupyter-config.yaml` point to the static IP address we have reserved for pangeo.pydata.org?

https://github.com/pangeo-data/pangeo/blob/060ae7a0f419e54c60012241f73267248e1362d9/gce/jupyter-config.yaml#L62-L64

Rather than updating the DNS, which is slow to propagate, I would prefer if you could re-deploy the cluster at its correct IP address.

Are you not using this version of  `jupyter-config.yaml` anymore? If not, we need a PR with an update so that others are capable of deploying the cluster.

**Comment by rabernat** [comment]
Ak, sorry for my last comment. I didn't realize how old this thread was...
