### ISSUE TITLE
http://pangeo.pydata.org hangs while creating a new env

### ISSUE THREAD

**Issue by ocefpaf** [pangeo-data/pangeo#140]
@rsignell-usgs motivated me to try pangeo and instructed me to try creating our own env like this:

- open a terminal
- create a `.condarc` file with

```
channels:
 - conda-forge
 - defaults
envs_dirs:
 - /home/jovyan/my-conda-envs/
```

- `wget` our [env file](https://raw.githubusercontent.com/ioos/notebooks_demos/master/environment.yml)
- and create the new env `conda env create --name IOOS --file environment.yml`.

However, after 4 attempts, it always hangs at some point, sometimes at the solving stage, sometimes installing the packages.

Am I doing something wrong?

**Comment by mrocklin** [comment]
I don't know of anything in particular.  My first guess would be that you're running out of memory somehow.  I haven't kept track of conda in this regard, would a 3-4GB memory limit cause issues?

**Comment by ocefpaf** [comment]
> I haven't kept track of conda in this regard, would a 3-4GB memory limit cause issues?

It should be OK.

@rsignell-usgs created the same env without problems, right?

**Comment by rsignell-usgs** [comment]
@ocefpaf , yes, I created the same environment.   But I did it several weeks ago.  Could something have changed?

**Comment by rabernat** [comment]
Are there logs somewhere that can help us understand what is failing here?

**Comment by mrocklin** [comment]
```
mrocklin@carbon:~$ kubectl get pods -n pangeo
NAME                      READY     STATUS    RESTARTS   AGE
hub-75769fcfc4-hp5js      1/1       Running   0          3h
jupyter-mrocklin          1/1       Running   0          1h
jupyter-rsignell-2dusgs   1/1       Running   0          2h
proxy-6f9df67cb4-vtp48    2/2       Running   0          1h
mrocklin@carbon:~$ kubectl logs jupyter-mrocklin
Error from server (NotFound): pods "jupyter-mrocklin" not found
mrocklin@carbon:~$ kubectl logs jupyter-mrocklin -n pangeo
Copy files from pre-load directory into home
+ echo 'Copy files from pre-load directory into home'
+ cp --update -r -v /pre-home/. /home/jovyan
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
+ '[' '' ']'
+ '[' '' ']'
+ '[' pangeo-data ']'
+ echo 'Mounting pangeo-data to /gcs'
+ /opt/conda/bin/gcsfuse pangeo-data /gcs --background
no environment.yml
Mounting pangeo-data to /gcs
+ start-singleuser.sh '--ip="0.0.0.0"' --port=8888 '--NotebookApp.default_url="/lab"'
Execute the command: jupyterhub-singleuser --ip="0.0.0.0" --port=8888 --NotebookApp.default_url="/lab"
[W 2018-03-05 15:13:12.012 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
```

These are also available from the kubernetes dashboard

**Comment by mrocklin** [comment]
I can replicate this.  It froze at `r-ggfortify`.  I don't know why.

**Comment by ocefpaf** [comment]
> I can replicate this. It froze at r-ggfortify. I don't know why.

It froze on random packages/stages of the build when I tried it multiple times. Not sure it has anything to do with a particular package.

**Comment by mrocklin** [comment]
The rest of the system seems operational.  Which is odd. I'm used to issues that just cause everything to crash.  My next step to diagnose this would be to try to replicate locally, and figure out what kinds of diagnostic information conda puts out.

**Comment by ocefpaf** [comment]
> It froze on random packages/stages of the build when I tried it multiple times. Not sure it has anything to do with a particular package.

I take that back. If I remove the env and try again it always freezes on `r-ggfortify`. Maybe that is the last package before the next step in the installation? Don't know...

The random freezes happened when I `ctrl-c`ed from there and tried again in the same session. Then it freezes usually before any package is retrieved, sometimes it does retrieve a few packages.

> My next step to diagnose this would be to try to replicate locally

I cannot replicate that locally on my machine.

**Comment by mrocklin** [comment]
Then I might try replicating on a similar system, like mybinder.org .  If so then you could re-raise upstream where I suspect they have more expertise in this sort of issue.

**Comment by ocefpaf** [comment]
> Then I might try replicating on a similar system, like mybinder.org .

We do mybinder.org that for this environment and its notebooks here: https://mybinder.org/v2/gh/ioos/notebooks_demos/master?filepath=notebooks

everything seems to work there, sometimes it does require a few "retries" though.

>  If so then you could re-raise upstream where I suspect they have more expertise in this sort of issue.

Maybe @yuvipanda has some insight on what may be going on here.

PS: at this point feel free to close the issue :grimacing:
