### ISSUE TITLE
Installing custom libraries

### ISSUE THREAD

**Issue by trygvefossum** [pangeo-data/pangeo#142]
I want to leverage the unique solution you guys have running on the pangeo.pydata.org

I usually stay on my personal computer when I'm doing python, but currently I'm doing statistical analysis on large scale ocean modeling data.

So, I need to install a few packages on from the terminal in order to have my code work: opencv.

I can do pip install opencv-python, but there are some supporting libraries that I need to include to avoid getting: ImportError: libSM.so.6: cannot open shared object file: No such file or directory

I think I need root priv. to do commands such as: apt update && apt install -y libsm6 libxext6

Is this possible from the current setup of your solution?

Thank you.

Regards,
Trygve

**Comment by jacobtomlinson** [comment]
I just noticed that nobody got back to you! Sorry about that.

This is something we are aware of. Yes you should have sudo access within your image. This is a setting which can be customized if you are looking to install Pangeo for yourself, but it looks like it has been enabled on pangeo.pydata.org.
