### ISSUE TITLE
Pangeo use case - when dask.array and xarray.apply_ufunc are not the answer 

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#143]
I have a few workflows where I'd like to use be able to connect xarray and dask but where traditional `dask.array` or `apply_ufunc` approaches don't work. I'm wondering what others have done, possibly using `dask.delayed` or `dask.bag` and how those applications have performed. 

Here is an example (pseudo code) workflow. In the full implementation, using a `delayed` approach (shown below) along with `distributed` results in a bottleneck in the serialization of xarray objects. 

## Example workflow

We start with a single xarray dataset (usually with dask arrays but this isn't a hard requirement):
```Python
In [1]: import xarray as xr

In [2]: ds = xr.open_dataset('/glade/u/home/jhamman/workdir/GARD_inputs/newman_ensemble/conus_ens_001.nc')

In [3]: ds
Out[3]:
<xarray.Dataset>
Dimensions:    (lat: 224, lon: 464, time: 12054)
Coordinates:
  * time       (time) datetime64[ns] 1980-01-01 1980-01-02 1980-01-03 ...
  * lon        (lon) float64 -124.9 -124.8 -124.7 -124.6 -124.4 -124.3 ...
  * lat        (lat) float64 25.06 25.19 25.31 25.44 25.56 25.69 25.81 25.94 ...
Data variables:
    elevation  (lat, lon) float64 ...
    pcp        (time, lat, lon) float64 ...
    t_mean     (time, lat, lon) float64 ...
    t_range    (time, lat, lon) float64 ...
    mask       (lat, lon) int32 ...
    t_max      (time, lat, lon) float64 ...
    t_min      (time, lat, lon) float64 ...
```

And I want to apply a function along each lat/lon pair:
```Python
In [4]: def science_happens_here(df_point):
   ...:     # start with one dataframe of shape (time, nvars)
   ...:     #
   ...:     # do some science where we disaggregate the variables in df_point
   ...:     #
   ...:     # return a second dataframe of shape (time*X, nvars+Y)
   ...:     return df_point_disagg
```

For a single point, the usage may be something like:

```Python
ds_new = xr.Dataset(...)  # a new dataset with more/larger arrays
ilat, ilon = 85, 43  # i,j location for this example
# perform out computation
df_new = science_happens_here(ds.isel(lat=ilat, lon=ilon).to_pandas())
# unpack the results
for key, series in df_new.iteritems():
    ds_new[key][:, ilat, ilon] = series
```

### Why `apply_ufunc` won't work

A key difficulty here is that science routines I'm calling are called in a many-to-many configuration. So I pass in 3 arrays and get out 7. This is not currently possible in xarray due to https://github.com/pydata/xarray/issues/1815).

Lower level paralyzation using `apply_ufunc` is also not really an option for the same reasons, i.e. some quantities are calculated together using an iterative approach.

### Using `dask.delayed`

My naive approach to using dask for this workflow was to wrap the `science_happens_here` function using `dask.delayed`. 

```Python
df = ds.isel(lat=ilat, lon=ilon).to_pandas()
delayed_objs = [delayed(science_happens_here)() 
                for ilat, ilon in zip(ilats, ilons)]:
```

While this "works", the serialization of each of the xarray/pandas object is non-trivial. One thing we tried is persisting each delayed object immediately after creating it.

```Python
delayed_objs = [delayed(science_happens_here)(df).persist() 
                for ilat, ilon in zip(ilats, ilons)]:
```

This actually illustrated the bottleneck in the construction of the delayed task nicely (see example when using a `LocalCluster`).

![image](https://user-images.githubusercontent.com/2443309/37062816-6352f3a4-214c-11e8-85b3-2c39048be744.png)

### Other ideas/questions

- One thing I'm not clear on is how my `delayed` approach differs from the `dask.bag` approach (not shown here but something we've looked at). 
- My `delayed` approach just wraps the top level function. It is possible to perform some of the lower level stuff but as you can see, that is not the current bottleneck. 
- Item assignment. Noting that dask does not support item assignment, is there an established way to construct a dask array from delayed objects?

That's it (this may already be too long to be useful for discussion).

**Comment by mrocklin** [comment]
When doing something like this:

```python
delayed_objs = [delayed(science_happens_here)(df).persist() 
                for ilat, ilon in zip(ilats, ilons)]
```

You'll want to ensure that `df` is also a delayed object.  Every time you put an object into a delayed call that object will be serialized within that task.  If you were to instead call delayed on it then dask will track it

```python
df = delayed(df)
delayed_objs = [delayed(science_happens_here)(df).persist() 
                for ilat, ilon in zip(ilats, ilons)]
```

**Comment by tjcrone** [comment]
@rabernat just dropped the [dask.array.from_delayed() function](http://dask.pydata.org/en/latest/delayed-collections.html) on me today, and it rocked my world. He showed me how to build an Xarray dataset from a Dask array built from delayed functions, which appears to allow all kinds of awesome out-of-memory possibilities. I am considering building a lazy Xarray dataset with 200M images now. I am just beginning to wrap my mind around it, but I wonder if this could helpful here @jhamman?

**Comment by PhenoloBoy** [comment]
Could be possible to revamp this Issue !? I'm fighting with the exact problem !!! 
Instead of using the delayed approach I took the road of futures but it would be nice to discuss more about this.

**Comment by El-minadero** [comment]
@tjcrone Not sure if this is appropriate for this thread, but I'm very interested in learning how to create views of XArrayDatasets, subsets of which I can compute lazily. I posted my exact problem on [stackoverflow](https://stackoverflow.com/questions/56603257/how-to-efficiently-merge-many-xarray-objects-created-via-custom-function-from-o), but I think loading custom binary parsing function per file -> dask -> xarray.DataSet is a useful/generalized workflow.

I'm the guy that emailed you last night btw
