### ISSUE TITLE
enable bokeh / holoviews / geoviews in pangeo.pydata.org

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#145]
Next Monday we will be giving a demo to some NASA folks of pangeo.pydata.org. I would like to show some example of visualization with holoviews. But, as pointed out in #144, the bokeh jupyterlab extension evidently doesn't work. And I don't think that holoviews is installed at all.

cc @mrocklin, @jbednar

**Comment by jhamman** [comment]
@rabernat - have you tried using the legacy notebook interface? We're currently defaulting to to the /lab interface but you access the default interface just the same (/tree): http://pangeo.pydata.org/user/rabernat/tree.

This seems to work for me when using the legacy interface:

![bokeh](https://user-images.githubusercontent.com/2443309/37106334-6d06edc0-21e6-11e8-91bb-7a12bb2a9609.png)

**Comment by jhamman** [comment]
It looks like we would need the jupyter lab extension for bokeh: https://github.com/bokeh/jupyterlab_bokeh

I think this would need to go in the notebook image. In the short term, I think you can run `jupyter labextension install jupyterlab_bokeh` in a terminal to get the equivalent functionality. This worked for me.

**Comment by philippjfr** [comment]
We only merged JupyterLab support into HoloViews last week so there is not yet a release that includes it. That said I think we are ready to have a beta release tomorrow or shortly after you'll be able to get it going with:

```
conda install -c ioam/label/dev holoviews geoviews
conda install -c bokeh/label/dev bokeh
jupyter labextension install @pyviz/jupyterlab_holoviews
```

I'll let you know when that release is available, otherwise you could just grab holoviews/geovies from master.

**Comment by mrocklin** [comment]
Agreed.  Short term I think the solution is for someone to push this and
holoviews into the notebook image. That person is probably me.  I'm
probably occupied this afternoon on dask things though (recent tornado
release has triggered some high priority work).  Someone else could also
try following the instructions in update.md though if they're interested.

**Comment by rabernat** [comment]
I will try to update the notebook image myself. We'll see if I succeed.

**Comment by mrocklin** [comment]
You'll need a place to push the images.  I recommend creating a pangeo
account on docker hub

**Comment by jhamman** [comment]
We already have one: https://hub.docker.com/u/pangeo

**Comment by jhamman** [comment]
I've added @rabernat and @mrocklin to the pangeo team on dockerhub. If there are others that need push access, please send me a dm.

**Comment by rabernat** [comment]
Actually, this is still not working 100%. I can load holoviews in jupyterlab, but certain updates with holomaps and datashader don't work properly.

**Comment by mrocklin** [comment]
Yup.  I'm building new docker images now.

**Comment by rabernat** [comment]
We can always fall back on the legacy notebook, which seems to work great.

**Comment by philippjfr** [comment]
When I tried it earlier today it wasn't yet using bokeh 0.12.15devX, so upgrading that should fix it. Separately after some profiling I opened https://github.com/ioam/holoviews/pull/2434 which should be a huge improvement in responsiveness. We'll have new HoloViews and GeoViews alpha releases later today.

**Comment by jacobtomlinson** [comment]
Just FYI I've raised bokeh/jupyterlab_bokeh#9 as I've noticed code cells disappearing when saving if they produce a bokeh plot.

**Comment by rabernat** [comment]
When I tried holoviews today in pangeo.pydata.org, using lab, it did not work. No output from `holoviews. hv.__version__ ==  1.9.2`, `bokeh.__version__ == 0.12.15dev1`

**Comment by mrocklin** [comment]
It would be useful if someone could come up with a working configuration
for holoviews on jupyterlab.

**Comment by philippjfr** [comment]
I've been trying to debug the issues with holoviews in JupyterLab today, but it's been hampered by the fact that I can't reproduce any issues locally. It should at least be partially working using holoviews 1.9.5 though.

**Comment by philippjfr** [comment]
The good news is, I just updated to bleeding edge JupyterLab and can now reproduce the issues I've been seeing on pangeo on my own machine, so I should be able to get a ``jupyterlab_holoviews`` release out to fix it very soon.

**Comment by mrocklin** [comment]
Huzzah!  Thank you for handling this Philipp.

**Comment by rabernat** [comment]
FWIW, whatever is in the current pangeo notebook docker images *does work now* on pangeo.pydata.org:
https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/Dockerfile

**Comment by rsignell-usgs** [comment]
@rabernat, my workflow uses `geoviews`, which the current pangeo notebook image does not seem to have.

**Comment by philippjfr** [comment]
Currently I would recommend:

```
conda install -c pyviz holoviews geoviews
conda install bokeh
jupyter labextension install @pyviz/jupyterlab_holoviews
```

and for the latest dev releases:

```python
conda install -c pyviz/label/dev holoviews geoviews
conda install -c bokeh/label/dev bokeh
jupyter labextension install @pyviz/jupyterlab_holoviews
```

**Comment by chiaral** [comment]
Geoviews is still not in pangeo.pydata.org - is there any plan to include it? 
or should I install it in my directory?

**Comment by mrocklin** [comment]
Does it depend on the GDAL stack?  Do we plan to add this to our
dependencies?  If so how much larger does this make images?

**Comment by rsignell-usgs** [comment]
We have [EarthSim](https://pyviz.github.io/EarthSim/user_guide/Visualizing_Meshes.html) (datashader, holoviews, geoviews) working in our Pangeo instance on AWS (http://pangeo.esipfed.org). 

Here's the Dockerfile we are using for both Notebook and worker:
https://github.com/rsignell-usgs/helm-chart/blob/conda-forge/docker-images/notebook/Dockerfile

Just FYI, I gave a live demo of this yesterday as part of a plenary talk at the [ECM15 Meeting](https://ecm.github.io/ECM15/) here in Seattle,  using Dask with 30 workers to compute the maximum water levels during Hurricane Ike on a 9 million node unstructured mesh, crunching 50GB in less than a minute, then using geoviews to display the mesh interactively in the notebook!  The Coastal and Estuarine Modeling community was wowed by Pangeo!   😸

**Comment by mrocklin** [comment]
Whoa!  Nice.  Any chance this was recorded?

**Comment by rabernat** [comment]
@rsignell-usgs that sounds amazing!

We would *love* to include this use case in the gallery! Any chance you could submit your notebook via PR?

**Comment by rsignell-usgs** [comment]
@mrocklin, unfortunately not recorded, but I can show this demo at ESIP summer meeting, which will be recorded.  

@rabernat, sure, I can submit a PR, although obviously the notebook won't work on pangeo.pydata.org if geoviews is not working.     I guess I should also switch the data source bucket from AWS to GCS, right?

**Comment by rsignell-usgs** [comment]
@rabernat , okay, cool.  I'll fix the metadata in the dataset, add a bit more descriptive text in the notebook and submit.

**Comment by rsignell-usgs** [comment]
@rabernat & @jhamman, I'm ready to submit at PR for this Hurricane Ike example notebook, but I'm not at all sure where!

**Comment by martindurant** [comment]
Into https://github.com/pangeo-data/pangeo-example-notebooks ?

**Comment by rsignell-usgs** [comment]
I've [submitted my trimesh hurricane notebook and updated the SSH example notebook with `hvplot`](https://github.com/pangeo-data/pangeo-example-notebooks/pull/4)  but to run these on pangeo.pydata.org would require adding `geoviews` and `hvplot` to the  environment.

I saw that a request to add `cartopy` was met with a [suggestion to install a custom pangeo instance](https://github.com/pangeo-data/pangeo/issues/423#issuecomment-427988594).

So I'm not sure if the same logic applies here, or whether is sufficient general interest to warrant the inclusion of these packages in the pydata instance?

**Comment by jhamman** [comment]
@rsignell-usgs - for context, I think some of the slow movement on these sorts of issues falls into these categories:

1. pangeo.pydata.org's environment image is somewhat fragile and building those images has led to some unpleasant effort by maintainers
2. we're moving away from pangeo.pydata.org as a one-stop-shop and encouraging smaller deployments that can be more easily customized
3. adding some of these packages results in some fairly large increases in docker image sizes which has a negative impact on the UX. 

In total, we just don't have a way to make cost/benefit based decisions on stuff like this. I recognize this is probably frustrating as someone who developing some really cool demonstrations (like you). The binder deployment is meant to help with some of this but obviously doesn't hit all of the points.

**Comment by mrocklin** [comment]
Perhaps we can make Rich a custom deployment that he can control?  Probably
not rich.pangeo.io (though I'm sure that would be a fun place), perhaps
there is some domain that a few colleagues would enjoy collaborating on as
well?

**Comment by jhamman** [comment]
@rsignell-usgs - you should call it pangeo.esipfed.org 😉 😉 😉

**Comment by rsignell-usgs** [comment]
Hee hee.  Yes, @jhamman, our pangeo.esipfed.org instance on AWS is working quite nicely with the [full PyViz stack](http://pyviz.org/) enabled (including `geoviews`, `cartopy` and `panel`).  

I just wanted to share with a broader community.  😸  

I understand the fragility of the current pangeo.pydata.org environment, with a [pool of five channels to pull from and numerous pinned package versions](https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/Dockerfile#L13-L17).   I think a safer approach would be to [specify conda-forge only as the channel to draw from, and only pull specific packages from specific channels if needed](https://github.com/rsignell-usgs/helm-chart/blob/conda-forge/docker-images/notebook/Dockerfile#L12-L74). 

I would love to have a site on pangeo.io to test this potentially-more-robustly-built notebook container out.   Maybe something like  `dev.pangeo.io` ?
