### ISSUE TITLE
Hello Pangeo from JHU

### ISSUE THREAD

**Issue by malmans2** [pangeo-data/pangeo#151]
Hi all,
I'm opening this issue just to introduce myself and our group to the Pangeo community. 
My name is Mattia Almansi and I'm a Ph.D. student in Tom Haine group at Johns Hopkins University.
We run high-resolution ocean models, and we are particularly interested in the Subpolar North Atlantic.
We are involved in [SciServer](http://www.sciserver.org/), which is a NSF funded platform developed by [IDIES](http://idies.jhu.edu/) and JHU to bring the analysis to the data. Here is the link to the [SciServer-Oceanography webpage](http://www.sciserver.org/integration/oceanography/). We provide user-friendly matlab tools to facilitate extracting information from our model output fields, and SciServer users can either download subsets of data on their own machines, or run our tools online and store post-processing files on our servers. Step-by-step instructions for the eulerian framework are available [here](https://malmans2.github.io/JHU-MITgcm_Tools/), while the lagrangian framework will be available soon.

We recently discovered Pangeo, and we are in the process of switching the eulerian framework from matlab to python. Indeed, most of the packages involved in Pangeo perfectly suit our needs. The idea is to build a python package based on xarray/dask/xgcm/... and our main goal is to facilitate the post-processing of our datasets stored on  [SciServer](http://www.sciserver.org/). At the same time, we'll try to write and organize our package in such a way that it can be used by anyone dealing with physical oceanography data.

I'm looking forward to interacting with the Pangeo community!

**Comment by rsignell-usgs** [comment]
Is the funding for SciServer ending in September?
https://www.nsf.gov/awardsearch/showAward?AWD_ID=1261715

**Comment by mrocklin** [comment]
Welcome @malmans2 !

**Comment by rabernat** [comment]
This is great to hear @malmans2. Let us know how we can help you get up and running. So far we have been focused on deploying on either HPC or commercial cloud platforms. I'm curious whether SciServer is more similar to HPC or to cloud.

**Comment by malmans2** [comment]
@rsignell-usgs and @rabernat SciServer is still evolving and has big future goals, so I'm sure it will continue after September. Check out the following papers: the [first one](https://dl.acm.org/citation.cfm?id=2949700) describes how SciServer has been built, while the [second one](http://journals.sagepub.com/doi/abs/10.1177/0002716217745816) talks about the evolution and future plans of SciServer (the most relevant section starts at page 213).
