### ISSUE TITLE
Greetings from NASA-GSFC

### ISSUE THREAD

**Issue by ebo** [pangeo-data/pangeo#153]
I was told that it was OK to introduce ourselves here.  If that is not OK, please accept my apologies.

I am a programmer/analyst working as a contractor at NASA Goddard Space Flight Center.  My current project is working on identifying trees in VHR imagery.  Each image is typically 2.5 gigapixels with 2 to 8 bands and/or stacked intermediate products.  I started playing with dask to provide better out-of-core processing.  I just recently learned about pangeo and xarray, and need to take a quick poke at that.  I have a simple set of test cases in an automated test suite, and I will likely polish them up a little into a dask, or other tutorial on large image processing examples.  I have to put that off until I crank out some deliverables, but I can get the meet working as I test dask and xarray on some largish images.  

Since I cannot share any of the commercial imagery, I talked to one of my colleagues who pointed me to some LANDSAT GeoTIFF mosaics.  We grabbed one that is 14,274x24,388 (or 348MP). While that is 1/10'th the size I will use internally to stress test, it is something we all can use, and is freely distributable without requiring special permissions.  I am also talking to some of the modelers and see if we can have access to suitable datasets.

From a presentation I saw today, maybe this dataset is not of general interest, but it will help me test my reimplemented dask/xarray distributed algorithms.

**Comment by jhamman** [comment]
@ebo - Thank you for introducing yourself. 

I think we'd all love to see some examples come out of the remote sensing sphere. If you can work with the LANDSAT dataset, I think that would be a good starting place. One nice thing about this dataset is that it is already on google public storage (https://cloud.google.com/storage/docs/public-datasets/landsat) and that means we can easily work with it from http://pangeo.pydata.org/.

**Comment by ebo** [comment]
thank you jhamman.  I just started a fork of the pangeo-tutorials, so that I can poke away.  

Originally I wanted to use some sample commercial images that are 1 to 3 gigapixels and up to 8 bands to both test how the algorithms scale, and also to stress test small VMs.  All of the free sample commercial images I can find are all small (maybe 2,000x3,000), and will not work for scaling or stress testing.  That is why I was looking at mosaicing LANDSAT images.  We have one that is 14274 x 24388, 3 band images.  Which might function as a start for my needs outside of the commercial imagery, so that I can share code and test data, and exactly replicate bugs.

BTW, I really like the parsing rasterio’s geocoordinates example in the docs:  http://xarray.pydata.org/en/stable/auto_gallery/plot_rasterio.html#sphx-glr-auto-gallery-plot-rasterio-py and will likely follow after that example.

**Comment by ebo** [comment]
BTW, I am going to have to look into http://pangeo.pydata.org/ asking to access my account.  Not sure why that is necessary, and I am not sure I can allow it -- at the moment I do not have much that matters on github, but we have recently been authorized to open-source one of our in-house CI/CD dashboard tools.  I will need to be mroe careful to who writes to that repository.

**Comment by jacobtomlinson** [comment]
Authenticating via GitHub is just a pragmatic decision for now as most people using the platform are also developing it and therefore have GitHub accounts. When institutions deploy themselves it is likely they will link with their Office 365,  Google Apps or whatever their org uses.

The demo deployment only asks for the bare minimum access to your GitHub which is read only access to publicly accessible information. This is just enough to validate that it is a real user who has verified their email. Do not worry about access to private repos or anything like that, Pangeo does not have permission to any of that.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/1610850/37334070-cdc6d506-26a2-11e8-90e9-fb7ad6ef9da8.png">

**Comment by TomAugspurger** [comment]
@ebo If you're able to say, what technique are you using for identifying features in the image? I put some work in [dask-ml](http://dask-ml.readthedocs.io/en/latest/) that may be relevant. I was told that spectral clustering was sometimes used for this sort of thing, so we implemented a scalable version in http://dask-ml.readthedocs.io/en/latest/auto_examples/plot_spectral_clustering.html. I'm not sure if it's seen real use yet, but it may be useful.

**Comment by ebo** [comment]
On Mar 13 2018 9:57 AM, Tom Augspurger wrote:
> @ebo If you're able to say, what technique are you using for
> identifying features in the image? I put some work in
> [dask-ml](http://dask-ml.readthedocs.io/en/latest/) that may be
> relevant. I was told that spectral clustering was sometimes used for
> this sort of thing, so we implemented a scalable version in
> 
> http://dask-ml.readthedocs.io/en/latest/auto_examples/plot_spectral_clustering.html.
> I'm not sure if it's seen real use yet, but it may be useful.

I had just stumbled onto dask-ml and was poking around (great timing 
;-).  The first attempt that some of my colleagues started and I took 
over used Random Forest.  I'm not sure I am allowed to talk much about 
what we are currently doing until it is published, but I will take a 
look at your dask implementation of spectral clustering.  Is there some 
way to contact you off-list to poke at the details?

   Thanks and best regards,

   EBo --

**Comment by TomAugspurger** [comment]
Thanks. tom.w.augspurger@gmail.com

On Tue, Mar 13, 2018 at 11:28 AM, John (EBo) David <notifications@github.com
