### ISSUE TITLE
Writing to pangeo google cloud storage buckets

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#155]
@rabernat added my google account to the `pangeo` Google project:

>  I've given you the "storage admin" role: https://cloud.google.com/iam/docs/understanding-roles#cloud_storage_roles

and I can now see the different buckets:
![2018-03-13_13-31-07](https://user-images.githubusercontent.com/1872600/37359010-e1bfe0dc-26c2-11e8-8791-67ffbcc484f2.png)

but before I use code like this on my local machine:
```python
fs = gcsfs.GCSFileSystem(project='pangeo-181919')

compressor = zarr.Blosc(cname='zstd', clevel=3, shuffle=2)
encoding = {vname: {'compressor': compressor} for vname in ds.variables}
dsname = 'ocean_his_tide_zeta'
gcsmap = gcsfs.mapping.GCSMap('pangeo-data/rsignell/' + '/' + dsname,
                              gcs=fs, check=True, create=False)
with dask.set_options(get=dask.threaded.get):
    with ProgressBar():
        ds.to_zarr(store=gcsmap, encoding=encoding)
```

I assume I'll have to authenticate somehow, right?  

Ideally I'd be able to do this with python or a dotfile in my `/home` directory.

**Comment by rsignell-usgs** [comment]
I also tried doing `conda install google-cloud-platform`  and using `google-oauthlib-tool `, but when I tried to follow these steps:

> Download the client_secret_XXXXX.json file from the Google API Console Project credentials section and generate credentials:

I am not able to generate credentials:
![2018-03-13_14-41-27](https://user-images.githubusercontent.com/1872600/37362881-e16457bc-26cc-11e8-8ea3-d26558fca89c.png)

Is this expected?

**Comment by rabernat** [comment]
Did you actually try to run this code yet? Did you encounter an error?

> Ideally I'd be able to do this with python or a dotfile in my /home directory.

Authentication options are completely determined by gcsfs:
http://gcsfs.readthedocs.io/en/latest/api.html#gcsfs.core.GCSFileSystem

You should raise any authentication issues directly on the gcsfs repo. There are lots of kinks still being sorted out (e.g. dask/gcsfs#90 , dask/gcsfs#89).

**Comment by rabernat** [comment]
In my experience, gcsfs provides an authentication dialog when you first try to connect. Did that not happen here?

**Comment by rsignell-usgs** [comment]
I did not get an authentication dialog.

When I run:
```python
compressor = zarr.Blosc(cname='zstd', clevel=3, shuffle=2)
encoding = {vname: {'compressor': compressor} for vname in ds.variables}
dsname = 'ocean_his_tide_zeta'
gcsmap = gcsfs.mapping.GCSMap('pangeo-data/rsignell/' + '/' + dsname,
                              gcs=fs, check=True, create=False)
with dask.set_options(get=dask.threaded.get):
    with ProgressBar():
        ds.to_zarr(store=gcsmap, encoding=encoding)
```
I get: 
```
RefreshError: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdcfae3eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by rabernat** [comment]
Can you try adding `token='browser'` to `GCSFileSystem`?

I recommend reading this:
http://gcsfs.readthedocs.io/en/latest/#credentials

**Comment by rabernat** [comment]
Also, we figured out how to use the distributed scheduler in dask/gcsfs#90. This is nice so you can monitor the progress of the upload. I do this like

```python
# depends on the machine you are using
cluster = LocalCluster(processes=False, n_workers=1, threads_per_worker=16)
client = Client(cluster)
client # displays the link to the dashboard

ds.to_zarr(...)
```

**Comment by jhamman** [comment]
minor point but you can write the cluster/client initialization as a single line: 

```Python
client = Client(processes=False, n_workers=1, threads_per_worker=16)
client
```

**Comment by rabernat** [comment]
I'm guessing that Rich got it working. 😄 

![image](https://user-images.githubusercontent.com/1197350/37365613-640fb15a-26d4-11e8-9fe6-ed4484bd9099.png)

**Comment by rsignell-usgs** [comment]
@rabernat , yep!   

`token='browser'` was the ticket!
as in:
```
fs = gcsfs.GCSFileSystem(project='pangeo-181919', token='browser')
```
which linked me to a web page that provided a token that I entered into the notebook.   

Pretty cool!
