### ISSUE TITLE
PDF export bug

### ISSUE THREAD

**Issue by CommonClimate** [pangeo-data/pangeo#160]
Just tried to export one of the pangeo examples notebook as PDF and got the following error message:

> nbconvert failed: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.

Might be something to consider if you think other users will want to export notebooks to keep a trace of them outside the cloud. 

Best,
J.E.G.

**Comment by rabernat** [comment]
I agree this should be fixed. But just out of curiousity, why not just download the notebook itself? PDF seems far less useful than the actual notebook.

**Comment by CommonClimate** [comment]
In order to share with Muggles who live outside of notebookland.

Julien Emile-Geay, associate professor
University of Southern California
http://<https://scholar.google.com/citations?user=OVti4jEAAAAJ&hl=en>climdyn.usc.edu<http://climdyn.usc.edu>



On Mar 14, 2018, at 13:17, Ryan Abernathey <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree this should be fixed. But just out of curiousity, why not just download the notebook itself? PDF seems far less useful than the actual notebook.

**Comment by rabernat** [comment]
A temporary workaround: download the notebook (right click from the file browser). Then use [nbconvert](https://nbconvert.readthedocs.io/en/latest/) locally to convert to whatever format you wish.

**Comment by CommonClimate** [comment]
Exporting to html was faster, and just as general.

Julien Emile-Geay, associate professor
University of Southern California
http://<https://scholar.google.com/citations?user=OVti4jEAAAAJ&hl=en>climdyn.usc.edu<http://climdyn.usc.edu>



On Mar 14, 2018, at 13:44, Ryan Abernathey <notifications@github.com<mailto:notifications@github.com>> wrote:


A temporary workaround: download the notebook (right click from the file browser). Then use nbconvert<https://urldefense.proofpoint.com/v2/url?u=https-3A__nbconvert.readthedocs.io_en_latest_&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=sm7R-KWGS-qL7K-XLvSPqQ&m=N5WYubYcZPdkLtH60WcGci2c4RbG-HYqOE1zS69bras&s=YZEcON3bPIxa48KfQ_zVxHSn15NZnDI9Q62Wn6kl1fY&e=> locally to convert to whatever format you wish.
