### ISSUE TITLE
KubeCluster console looks different for different users

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#161]
When I create a KubeCluster in pangeo.pydata.org, it looks like this

![image](https://user-images.githubusercontent.com/1197350/37429199-077b8dde-27a5-11e8-82f8-8832a5dcdc32.png)

However, in @mrocklin's recent demo, I noticed a fancier dialog with autoscaling options.

I thought we were all using the same environment? Why would I have an out-of-date version of daskernetes?

```python
>>> import daskernetes
>>> print(daskernetes)
>>> print(daskernetes.__version__)
<module 'daskernetes' from '/opt/conda/lib/python3.6/site-packages/daskernetes/__init__.py'>
0.1.3
```

**Comment by mrocklin** [comment]
Switch from daskernetes to dask_kubernetes

**Comment by mrocklin** [comment]
http://dask-kubernetes.readthedocs.io/en/latest/history.html
