### ISSUE TITLE
server startup time

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#164]
Why I "start my server" on pangeo.pydata.org, it often takes several minutes for the server to start. It feels a bit clunky.

Is there any way to reduce this startup time?

**Comment by mrocklin** [comment]
This time *might* be due to a large docker image.  We would remove things
from the docker image to solve this.

**Comment by jhamman** [comment]
Could something like #88 (*Expose user home directories to dask workers*) also help with this? Since the user home directories are a more persistent storage layer, it seems like this would allow us to skip the repeated download of the worker image.

**Comment by mrocklin** [comment]
We'll always have to download *some* image onto the node that runs the pod,
but yes, relying on the user to define their own environment on their
persistent drive would allow us to drop many dependencies.  This system
would become a bit less plug-and-play though for new users.
