### ISSUE TITLE
I'm getting a 504 error this morning on pangeo

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#168]
I'm getting a 504 error on http://pangeo.pydata.org/user/rsignell-usgs/ this morning

**Comment by rabernat** [comment]
My server is working for me. But I got a 504 when I tried to access your server.

I recommend stoping and restarting your server. Do you know how to do that?

**Comment by rsignell-usgs** [comment]
@rabernat, do you mean to access pangeo.pydata.org from a terminal instead of browser and restart my server?   No, I don't know how to do that.

I know how to restart from the browser, but when I go to pangeo.pydata.org, I get redirected to pangeo.pydata.org/user/rsignell-usgs, which gives me a 504 Gateway Time-out.     I tried on multiple browsers, and multiple computers (and also in incognito mode).    

So yes, I guess my server is "hung" somehow, but I don't know how to restart.

**Comment by rabernat** [comment]
Go to http://pangeo.pydata.org/hub/home and click "Stop my server"

**Comment by rsignell-usgs** [comment]
Doh!   Yep, that worked!   Feeling a bit :sheep:ish here...

**Comment by rabernat** [comment]
I wish there were a way to expose this to users more easily. Right now you just have to know that the /hub/home link exists. Whereas on other jupyterhub servers I have used, there is a top-level menu bar with "control panel" and "logout" options.

**Comment by mrocklin** [comment]
The way to resolve this is probably to raise this upstream so that the
people who work on JupyterHub can be made aware of the issue and its
importance to users.

**Comment by rabernat** [comment]
@rsignell-usgs: do you think you could raise the JupyterHub issue?

**Comment by willirath** [comment]
As far as I remember, the Iink to the control panel _is_ present in the classic Jupyter view while it's gone in Jupyterlab.

**Comment by willirath** [comment]
This should bring the buttons back in lab: https://github.com/jupyterhub/jupyterlab-hub

**Comment by jacobtomlinson** [comment]
I have that extension installed but it doesn't show the menu.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/1610850/37607167-309d22ca-2b8f-11e8-8440-4381e079b69e.png">

**Comment by rabernat** [comment]
Do we need a new issue related to the hub buttons? Or is there an upstream issue we can link to?

**Comment by jacobtomlinson** [comment]
I did raise an issue on z2jh as the default install should show the menu and it doesn't. jupyterhub/zero-to-jupyterhub-k8s#539
