### ISSUE TITLE
enable Jupyterhub buttons in jupyterlab

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#171]
We would like to make it easier for a user to log out / shutdown / restart their server on pangeo.pydata.org.

This is what the jupyterlab-hub extension is for:
https://github.com/jupyterhub/jupyterlab-hub
It is not currently enabled on pangeo.pydata.org, so hopefully an easy fix.

However, @jacobtomlinson has reported that this doesn't work in his similar deployment (see #168).

**Comment by jacobtomlinson** [comment]
Related to jupyterhub/zero-to-jupyterhub-k8s#539

**Comment by tjcrone** [comment]
cc @friedrichknuth
