### ISSUE TITLE
How to run packages that need jupyter extensions in pangeo?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#173]
I wanted to use `ipyleaflet` with `pangeo.pydata.org`, and I created a custom `[ipyleaflet]` environment thusly:
```
conda create -n ipyleaflet python=3 ipyleaflet ipykernel
```
but although I could select the `ipyleaflet` kernel in pangeo and then run an `ipyleaflet` [example notebook](https://github.com/ellisonbg/ipyleaflet/blob/master/examples/Primitives.ipynb),  unfortunately no maps get displayed.  

If I then activate the `[root]` environment, install `ipyleaflet`
```
conda install ipyleaflet
```
and then try running the example notebook with the `[root]` environment, it works fine.   But when I restart my system of course I lose that package. 

Is there any way to get `ipyleaflet` working in my persisted, custom `[ipyleaflet]` environment?

It's supposed to look like this:
![2018-03-21_12-05-27](https://user-images.githubusercontent.com/1872600/37729212-c1464502-2d12-11e8-9f54-8c38c5f1f52e.png)

**Comment by mrocklin** [comment]
One solution would be to let you construct your own docker image.  https://github.com/pangeo-data/pangeo/issues/133
