### ISSUE TITLE
Create an official helm chart

### ISSUE THREAD

**Issue by jacobtomlinson** [pangeo-data/pangeo#178]
Pangeo is effectively comprised of the [zero-to-jupyterhub helm chart](https://zero-to-jupyterhub.readthedocs.io/en/latest/) (`jupyterhub/jupyterhub`) with a custom Docker image and additional configuration.

As some of the packages within the custom Docker image may require extra kubernetes resources (such as RBAC roles for dask-kubernetes in #172 ) it would be sensible to create a pangeo helm chart which inherits ([docs on inheritance](https://docs.helm.sh/developing_charts/#chart-dependencies)) from zero-to-jupyterhub. This allows Pangeo to be installed as a single chart that includes any Pangeo specific resources.

At the Met Office we currently have a [`jadepangeo` helm chart](https://github.com/met-office-lab/jade-pangeo) which inherits from `jupyterhub/jupyterhub` and adds some extra manifests for RBAC, domain redirection and monitoring. I would like to get to a position where our chart depends on a Pangeo chart instead as it would allow me to move things upstream more easily. 

It would be good for the chart to be called `pangeo/pangeo` which would allow us to sensibly rename `jadepangeo` to `metoffice/pangeo`, as the Pangeo project has superseded the Jade project now.

The current `jadepangeo` chart would make a good starting point so I'll look at making it more generic and getting that into this repo.

**Comment by mrocklin** [comment]
+10 on this :)  Thank you for leading the charge here @jacobtomlinson .  I
really appreciate it.
