### ISSUE TITLE
issues scaling up the dask clusters on pangeo.pydata.org

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#180]
I have been putting some bigger datasets (~10 TB) into GCS and playing around with bigger dask clusters (e.g. 500 workers). We routinely do dask jobs on clusters with 1000+ cores, so getting to this size on the cloud is important.

I temporarily increased the size of the preemptible node pool to 1000 and then tried to create a dask cluster with 500 workers.

Now I am see these errors on the cloud console
```
Problem
Your cluster has 422 unschedulable pods

Details
Unschedulable pods
dask-rabernat-84a265f5-322lr4
dask-rabernat-84a265f5-325mkm
dask-rabernat-84a265f5-327j86
dask-rabernat-84a265f5-329mgb
dask-rabernat-84a265f5-32bdtp
and other 417 unschedulable pods.

Possible Actions
Increase maximum size limit for autoscaling in one or more node pools that have autoscaling enabled.
```

I tried restarting my notebook and cluster a few times. Now I have shut everyhing down. But I can see on the cloud console that there are a bunch (hundreds!) of `dask-rabernat-` pods running. I want to kill them. Can someone tell me how?

**Comment by mrocklin** [comment]
You might try using [kubectl delete](https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_delete/)

I've done this now with the following command:

    kubectl delete pods -n pangeo -l component=dask-worker

FWIW I didn't know how to do this before this question.  I found the syntax for the command by googling for it.  I found the labels we use by looking at the source code for dask-kubernetes.  You can also add labels to your worker-template.yaml file.  Documentation for the kubectl command at least is pretty good.  It's probably a tool that people running early experiments on this cluster should become comfortable using.

**Comment by rabernat** [comment]
Yes I considered that, but doesn't it delete *everyone's* pods? Is there a way to just delete my own pods?

**Comment by tjcrone** [comment]
one way:
```
kubectl get pods -n pangeo | grep "^dask-rabernat" | cut -d' ' -f1 | xargs kubectl delete pods -n pangeo
```

**Comment by jacobtomlinson** [comment]
@tjcrone that would also be my approach.

Perhaps it would be useful to add an `owner` tag to the default `worker-template.yaml` to allow the use of the command @mrocklin suggested.

**Comment by tjcrone** [comment]
Plus one on that @jacobtomlinson. Any way to avoid that sort of command line kluge would be preferred!

**Comment by rabernat** [comment]
FYI, the preemptible-pool size is still at 564, despite the fact that I have manually set the size of the pool to 10. I did this from the console, but I think you can do it on the command line as
```
gcloud container clusters resize pangeo --node-pool preemptible-pool --size 10 --zone=us-central1-b
```

We are burning money right now. I don't know how to terminate all those nodes!

**Comment by rabernat** [comment]
I am going to delete the current `gke-pangeo-preemptible-pool-5d3e63a0` instance pool via compute engine. I don't know what the impact will be and whether the cluster can recover. But it's better than continuing to burn money.

**Comment by rabernat** [comment]
Actually I decided to resize the instance group from the compute engine console. Seemed to work.

**Comment by jacobtomlinson** [comment]
It's always a bit scary when things like that happen. 🙃
