### ISSUE TITLE
analysis and visualization of pangeo.pydata.org cluster logs

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#184]
At an NSF cloud workshop in January, David Culler of Berkeley gave a great presentation on their use of jupyterhub for teaching large-scale intoductory data science. Presumably this is the same deployment that @yuvipanda works on.

He showed some great visualizations of timeseries of cluster usage, presumably generated from logs.

Does anyone (e.g. @yuvipanda, @choldgraf) know how these were created? Could we do something similar for pangeo.pydata.org.

**Comment by choldgraf** [comment]
yep, that's our deplyoment :-)

for those plots, I believe that @yuvipanda generated the raw data and we made some nifty visualizations from this. However, I think you could definitely create similar viz. For example, at `mybinder.org` (which runs on jupyterhub) we have this link:

grafana.mybinder.org

which has a ton of cool graphs about the current cluster utilization. We combine that with google analytics to get a decent idea of how people are using the service. Would something like this work in your case?

**Comment by rabernat** [comment]
Thanks for the info! Very useful. The grafana link is amazing?

Are there any open repos that show how those dashboards or visualizations are created? And what is the source of the raw data? The stackdriver logs?

I created a sink for our kubernetes logs into bigquery: https://bigquery.cloud.google.com/table/pangeo-181919:pangeo_kubernetes_logs.cloudaudit_googleapis_com_activity_20180327

Hopefully this will make it easy to analyze in the future.

What I most want to measure is user engagement. How many users log in, how long do they stay, how often do they return, how many dask workers do they user?

We don't have many users yet. But soon we will advertise this service more widely. In order to sustain pangeo in the long term, we need to demonstrate that people actually use it. These sort of visualizations are crucial for that purpose.

**Comment by jacobtomlinson** [comment]
We were having a conversation here about what should and shouldn't be included in Pangeo. Monitoring came up.

We are currently using InfluxDB and Heapster for metric storage and Grafana for visualisation. These is deployed at a cluster level as a separate helm chart. One of the customisations we have made to our Pangeo is to add telegraf which collects custom metrics and feeds them into InfluxDB, I'm looking to write some scripts for telegraf to get custom metrics from the JupyterHub API.

From our point of view where we are running a large cluster with many applications running on it and Pangeo is just one of those it makes sense to install and manage the monitoring separately at a cluster level. But for those who are purely using the cluster for Pangeo we could incorporate a generic monitoring stack for these purposes.

**Comment by choldgraf** [comment]
@rabernat the raw data comes out of the [mybinder prometheus service](https://prometheus.mybinder.org/graph) which is a tool for logging info on a deployment. Grafana just dashboarderizes it :-)

Grafana has its own syntax for creating the visualizations and you can make them interactively from within the dashboard (if you have admin privileges)

to both your and @jacobtomlinson 's point, I think there's a broader question here which is "how can we give deployers introspection into what their users are doing?" I think that question has a much broader interest in the community. E.g., I know that @ellisonbg is interested in this.
