### ISSUE TITLE
can't import a local module from dask workers

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#187]
In my research, I commonly write a module where I dump longer functions / classes and import it from my notebooks. This reduces clutter in the notebook. Perhaps these functions are used in multiple notebooks, but I don't consider them reusable  / general / stable enough to actually package, distribute, etc. I imagine many people work this way.

As a concrete example, I have a file in my `examples` directory on pangeo.pydata.org called 'foo.py':
```python
class Foo(object):
    def __init__(self):
        pass
```

I import this from a notebook and create an instance
```python
import foo
f = foo.Foo()
```

Now I create a cluster and try to scatter this object
```python
from dask.distributed import Client
from dask_kubernetes import KubeCluster
cluster = KubeCluster(n_workers=1)
client = Client(cluster)
client.scatter(f)
```

I get a long error, the gist of which is `distributed.core - ERROR - No module named 'foo'`.

What is confusing to me is that this example would work perfectly fine if I just defined `Foo` within a cell in the notebook.

We should think about how to support this sort of thing, because I feel like lots of people work this way.

Obviously related to other customizable environment issues such as  #136, #133, #125, #67, etc.

**Comment by mrocklin** [comment]
If you have a fixed set of workers then use Client.upload_file

If you are willing to push this module to github then consider adding a pip
install line to your worker-template with the EXTRA_PIP_PACKAGES
environment variable

For changing the behavior of how functions in other files serialize you'll
have to take that upstream with cloudpickle/pickle
