### ISSUE TITLE
HPC issues, workers not showing up ... everywhere

### ISSUE THREAD

**Issue by apatlpo** [pangeo-data/pangeo#188]
Hi all,

I am searching for advice from HPC users about issues encountered after upgrading from dask 0.15.4 to latest.
These issues were initially posted at dask/distributed#1869 but @mrocklin suggested I asked pangeo folks.

Here are the symptoms:
- workers show up in dask dash board but in jupyter notebooks client tells me however that there are no workers available
- I have multiple FileNotFoundError errors in worker logs that seem to indicate that workers are deleting each other work directories. Example:
```
(pangeon) aponte@datarmor2:~/iwave_sst/datarmor> grep worker-i0oaruup dask*
dask-worker.o967959:FileNotFoundError: [Errno 2] No such file or directory: '/home1/datawork/aponte/dask/worker-i0oaruup/storage'
dask-worker.o967962:distributed.diskutils - WARNING - Found stale lock file and directory '/home1/datawork/aponte/dask/worker-i0oaruup', purging
```
Has anybody encountered similar issues?

Another detail of much lesser importance is that jupyterlab takes noticeably more time to be available (30 seconds vs seconds)

**Comment by mrocklin** [comment]
You might raise the jupyterlab issue upstream.  They might be able to help
you separately and perhaps their advice would apply here.

The fact that JupyterLab behavior has also changed means that it might not
be a dask issue, but might be something else, like Tornado.

**Comment by jhamman** [comment]
> `dask-worker.o967962:distributed.diskutils - WARNING - Found stale lock file and directory '/home1/datawork/aponte/dask/worker-i0oaruup', purging`

This is something we routinely see. While a bit annoying, I don't think its an actual problem.

> `dask-worker.o967959:FileNotFoundError: [Errno 2] No such file or directory: '/home1/datawork/aponte/dask/worker-i0oaruup/storage'`

My understanding is that distributed should handle this one too. @mrocklin can correct me if I'm wrong.

-----

Can you describe the process you're using to launch your dask cluster? We now have at least three ways that I'm seeing folks try this.

- dask-mpi (as described [here](https://pangeo-data.github.io/pangeo/setup_guides/cheyenne.html))
- dask-mpi (as implemented in [`launch-dask.sh`](https://github.com/pangeo-data/pangeo/blob/master/utilities/cheyenne/launch-dask.sh))
- and dask-jobqueue (https://github.com/dask/dask-jobqueue)

My inclination is that `dask-jobqueue` offers the most potential but we don't have thorough documentation on the package yet.

**Comment by apatlpo** [comment]
I am using a slightly modified [launch-dask.sh](https://github.com/apatlpo/iwave_sst/blob/master/datarmor/launch-dask.sh) 
It has been working so far with dask 0.15.4 

I was not aware of dask-jobqueue, I'll try to look whether I can go somewhere with it.

**Comment by apatlpo** [comment]
Using dask-jobqueue (dask/dask-jobqueue#25) seems to work much more smoothly, namely I do see the correct number of workers (even though I have witnessed some workers drop eventually).

See:
[launch.ipynb](https://github.com/apatlpo/iwave_sst/blob/master/datarmor/launch.ipynb)

I struggled a bit spinning up jupyter lab on a compute node but it's working now thanks to:
[jlab.pbs](https://github.com/apatlpo/iwave_sst/blob/master/datarmor/jlab.pbs)
[jlab.py](https://github.com/apatlpo/iwave_sst/blob/master/datarmor/jlab.py)

Next step is to launch computations to see how things go.

Questions:
- where is the dask dashboard?
- there is an ipywidget error in the notebook, does anybody has an idea where it may be coming from?

**Comment by guillaumeeb** [comment]
The scheduler is launched on the node where you create the PBSCluster object. So in your case it must be on the JupyterLab node. Standard dask bokeh port 8787.

**Comment by apatlpo** [comment]
thanks Guillaume, dash board is back.

I wrapped routines mentioned above in a bash script [launch_openq.sh](https://github.com/apatlpo/iwave_sst/blob/master/datarmor/launch-openq.sh)
which I can launch as `launch-dask.sh`

Some workers are still dying out of the blue, this will have to be investigated but I really need to make some science now ... hopefully I'll be able to work with it.
Here is one error in a worker log file that may be relevant if this is obvious to anybody: 

```
tornado.application - ERROR - Exception in Future <Future finished exception=TimeoutError()
> after timeout
Traceback (most recent call last):
  File "/home1/datahome/aponte/.miniconda3/envs/pangeon/lib/python3.6/site-packages/tornado
/gen.py", line 936, in error_callback
    future.result()
  File "/home1/datahome/aponte/.miniconda3/envs/pangeon/lib/python3.6/site-packages/tornado
/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/home1/datahome/aponte/distributed/distributed/nanny.py", line 478, in _wait_until_
started
    raise gen.TimeoutError()
tornado.util.TimeoutError
```

I have notices PBS output and error file are spilled in the directory where scripts are submitted.
This is expected but I find it not super handy.
I can push something about this if you feel it may be useful.
