### ISSUE TITLE
Preservation of user workspace state

### ISSUE THREAD

**Issue by jgerardsimcock** [pangeo-data/pangeo#189]
I've just logged back into `pangeo.pydata.org` and I have noticed that my jupyterlab notebook is the same state as I left it last time I logged in. How was this accomplished? 

I am trying to provide users some kind of persistent state for their workspace where they can push, pull, notebooks and code to and from github. Similar to this: (https://github.com/pangeo-data/pangeo/issues/46).

**Comment by jhamman** [comment]
@jgerardsimcock - each user is given a small persistent disk (10gb IIRC). I think this section of the jupyterhub docs describes the configuration: https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html#configuration

**Comment by jgerardsimcock** [comment]
Thank you @jhamman
