### ISSUE TITLE
Temporary Freeze on Modifying GCE JupyterHub

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#193]
@kmpaul and I will be giving a tutorial on Thursday morning where we plan to use pangeo.pydata.org. Things seem to be working right now so in the interest of not breaking anything at the last minute, I'd like to suggest a collective hold on any helm/docker updates until after our tutorial. 

If anyone had planned significant updates in the next few days, please speak up. Otherwise, let's just leave things as is until Thursday afternoon (MDT).  Thanks! 

cc @jacobtomlinson @mrocklin @rabernat

**Comment by mrocklin** [comment]
No objection from me.  You may want to set a higher minimum value on the
number of nodes prior to the tutorial to ensure that people can log in
without waiting for a new node to spin up.

**Comment by jacobtomlinson** [comment]
I will leave it alone :).

**Comment by rabernat** [comment]
I was using (but not modifying) the cluster today. I was running a notebook and cluster. Now it appears to have crashed, at least for me. I just got the following error:

> 500 : Internal Server Error
Redirect loop detected. Notebook has jupyterhub version unknown (likely < 0.8), but the Hub expects 0.8.1. Try installing jupyterhub==0.8.1 in the user environment if you continue to have problems.

**Comment by rabernat** [comment]
It seems to be resolved for me as well.

**Comment by jhamman** [comment]
Thanks all. Open season on modifying pangeo.pydata.org now.
