### ISSUE TITLE
500: Internal Server Error on Dask Dashboard Workers Tab

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#195]
I installed a few extra packages on my Azure Pangeo deployment, and most everything seems to be working fine, however I am getting a 500 error when opening the Dask dashboard Workers tab. The Status tab is working fine, showing worker progress during computations. Any suggestions on how to troubleshoot this? Where are the logs kept for the Dask dashboard?

**Comment by mrocklin** [comment]
Update to distributed == 1.21.5 or downgrade bokeh to 0.12.14.  See
https://github.com/dask/distributed/pull/1872

**Comment by tjcrone** [comment]
Thanks @mrocklin! Rolling back bokeh to 0.12.14 fixed this and a couple of other strange issues.
