### ISSUE TITLE
How fast can the Met Office's solution pull data from S3?

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#198]
I'm curious what the read bandwidth is on HDF/NetCDF data from S3 using the Met Office's custom FUSE system.  I would be interested in what this is for a single thread as well as for a few threads on a single machine.

I'm not sure if people over there have time to run this experiment, but I think it would be a useful data point in a few conversations.  If it's low then the UK Met Office might also be a good place to start work on profiling and improving this performance.

cc @niallrobinson @jacobtomlinson

**Comment by mrocklin** [comment]
also cc @llllllllll

**Comment by jacobtomlinson** [comment]
This is definitely something we can look more seriously at. Just as a quick test I've loaded a 181MB slice from the same file from local disk (EBS in this case), S3 via [pysssix](https://github.com/informatics-lab/pysssix) and S3 via [goofys](https://github.com/kahing/goofys).

<img width="818" alt="image" src="https://user-images.githubusercontent.com/1610850/38430284-c2072a80-39b8-11e8-9b5c-49718ce66f6a.png">

**Comment by rabernat** [comment]
@kaipak is working on benchmarking I/O performance in https://github.com/pangeo-data/storage-benchmarks. It would be great to incorporate this into his benchmark suite.

**Comment by jacobtomlinson** [comment]
@rabernat that would be great. Currently pysssix doesn't support writing so we would need to take that into account.

**Comment by ah-** [comment]
It'd be interesting to see how long it takes to load the file directly with boto3 transfer, without any FUSE overhead.

**Comment by mrocklin** [comment]
@jacobtomlinson if I can ask for one more experiment.  How long does it take to read this data from your laptop's hard drive after it has been downloaded.

Building on @ah- 's quesiton, my experience has been that S3 gives between 100-200MB's bandwidth, so if we were only bound by raw network bandwidth (which I think is a reasonable goal for us) then I would expect to see these computations finish in 1-2s rather than 30s.

**Comment by jacobtomlinson** [comment]
@mrocklin local disk is faster, but not to the order you expect.

![image](https://user-images.githubusercontent.com/1610850/38493134-00c50e0e-3be9-11e8-92a2-0c85ec55d43e.png)

**Comment by mrocklin** [comment]
Wow, ok that's interesting.  I'm quite curious about what is taking up the time there.  It sounds like you're operating at 10MB/s, which seems quite slow to me.  Do you have a sense for if this is disk bandwidth (usually in the 400MB/s-2GB/s range) decompression (varies widely, as you know) overhead in Iris (I don't know much here) or something else?

**Comment by rabernat** [comment]
It would be great if the benchmarks being developed by @kaipak and @jreadey could cover these same cases and get the same results. Then we could be sure we are all on the same page.

**Comment by mrocklin** [comment]
My sense is that we're not yet at the point where cross-project
benchmarking makes sense.  I think we need to do a bit of basic
investigation into the relevant systems before we consider comparing them.

**Comment by kaipak** [comment]
> It would be great if the benchmarks being developed by @kaipak and @jreadey could cover these same cases and get the same results. Then we could be sure we are all on the same page.

I will include this in the use case document @jreadey and I are writing up this week. Also should start getting some published results in this week. See issue pangeo-data/storage-benchmarks#24

**Comment by niallrobinson** [comment]
It could easily be Iris overhead (@dpeterk, @pelson, @bjlittle?) When we do proper benchmarking, we should obv just stick to one way of pulling so that we can compare like with like i.e. not user Iris for one and Xarray or something for the other.

I'm at EGU *waves to other Pangeo ppl* and there was a good talk yesterday from the CEDA people in the UK. https://github.com/cedadev/S3-netcdf-python see #203

**Comment by jacobtomlinson** [comment]
Just done a couple of quick comparisons with iris and xarray. It does seem like xarray is faster but it is still a similar ballpark. The time must be taken up by the slicing operation.

![image](https://user-images.githubusercontent.com/1610850/38552000-9effe296-3cb2-11e8-9b2a-fe1caf59ed35.png)

![image](https://user-images.githubusercontent.com/1610850/38552024-addbfa48-3cb2-11e8-8388-567685e4371a.png)

It is also possible the speed differences are down to caching happening between the two calls resulting in xarray being faster. If I run the cells again they all complete in roughly 10 seconds. 

It would be nice to test this without the caching but I'm not sure how to turn it off.

**Comment by jacobtomlinson** [comment]
A different comparison doing a 100MB continuous read from the file.

![image](https://user-images.githubusercontent.com/1610850/38552287-9b2df436-3cb3-11e8-8499-a694720cdd01.png)
![image](https://user-images.githubusercontent.com/1610850/38552296-a34beeac-3cb3-11e8-8eef-2290f38d233c.png)

**Comment by jacobtomlinson** [comment]
I started exploring this again and thought I'd post an update. I wanted to create a more sensible test, so I converted ~80GB of netCDF data into zarr and then timed taking a mean through various access methods with a 100 worker dask cluster.

The three methods I've tried all involve loading the same zarr using xarray.

- [s3fs](https://github.com/dask/s3fs) - directly access S3
- [goofys](https://github.com/kahing/goofys) - an S3 FUSE driver written in go
- [pysssix](https://github.com/informatics-lab/pysssix) - our own S3 FUSE driver written in python

I've put [the notebook](https://gist.github.com/jacobtomlinson/8ef089b52531cfbf4624a8dc433bfb21) on GitHub Gists if anyone wants to check I haven't done anything spurious. The results surprised me to be honest.

My hypothesis going in would be that all options would be of the same order of seconds but s3fs would be faster.

However it seems pysssix is much slower and s3fs and goofys are similar.

![image](https://user-images.githubusercontent.com/1610850/43588501-88f26f58-9664-11e8-9434-cd5001e04e5c.png)

I'll take a punt that the reasons for this are as follows:
 - goofys is golang which is very fast, but has the overhead of FUSE.
 - s3fs is pure python which interpreted and therefore slower but directly accesses S3.
 - pysssix is pure python and FUSE resulting in a double penalty.

The fact still remains that the FUSE setup is less flexible as it requires [a Kubernetes plugin](https://github.com/informatics-lab/s3-fuse-flex-volume) to be installed and extra config on the notebook and workers. However it does allow us to use tools which currently only support POSIX access to files.

I would be keen to run more experiments which result in more random access as I expect that to be more punishing. Suggestions welcome!

**Comment by mrocklin** [comment]
I wouldn't expect the Python/Go interpretted/compiled difference to make any significant difference when the task is pulling down MB+ chunks from the web.  We're not doing anything CPU-intensive here.

Similarly I'm not sure that FUSE inherently produces any direct overhead.

I suspect that the costs here are incidental to the implementations at hand, and not due to the underlying choice of technologies.

**Comment by mrocklin** [comment]
Some questions I would have:

1.  What about all of the other stuff going on here, like compression?  What fraction of the time is spent in gathering data vs decompressing or decoding?  What are the worker threads actually doing here?
2.  Are we saturating bandwidth in any of these cases?

To help answer these questions I would usually use the Dask dashboard.  In particular the following two pages:

-  Profile: to determine what threads are doing (are they pulling data or are the decompressing)
-  Workers: to see the network bandwidth reported by each of the workers

**Comment by mrocklin** [comment]
To expand on the Python comment, we often say things like "Python + Numpy is fast because all Python is doing is calling C code, which is fast".  Similarly with network traffic "all Python is doing is asking a socket to send or recv data, which is as fast as the system call can make it"

**Comment by ah-** [comment]
It might also be different block sizes for prefetching, I think s3fs requests something like 5MB at once.

**Comment by martindurant** [comment]
> I think s3fs requests something like 5MB at once.

True, but I expect that zarr requests whole data files only for this workflow.

**Comment by jacobtomlinson** [comment]
@mrocklin 

In the example zarr I used there is no compression. The main different between the profile of the different methods is the time spend in `__getitem__` in the zarr storage module.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/1610850/43630788-35053188-96f9-11e8-8090-caefe9fec8c5.png">


As for network use workers seem to get up to around 100MiB in `read_bytes` when using `s3fs`. However as the other two are using FUSE the operating system handles the network traffic and I can't see that.

**Comment by kaipak** [comment]
I just did a fairly major refactor on `storage-benchmarks` so please excuse the lack of fancy plots at this time. I've been getting fairly similar results on GCP. Part of the changes I've implemented include some variety in size of dataset as I get different results due to up-front overhead costs. Essentially, I have ~10/100/1000 GB dataset sizes to run IO tests against. 

For example for the ~110 GB dataset, a Zarr read test I just ran averaged 5.37 GB/sec reads for 100 workers.

```
               ========= ============= ============= =============
               --            z_chunksize / n_workers / run_num
               --------- -----------------------------------------
                backend   1 / 100 / 1   1 / 100 / 2   1 / 100 / 3
               ========= ============= ============= =============
                  GCS        23.05s        19.00s        19.32s
               ========= ============= ============= =============
```

Whereas for the a ~1.06 TB read test, I get 5.87 GB/sec.

```
               ========= ============= ============= =============
               --            z_chunksize / n_workers / run_num
               --------- -----------------------------------------
                backend   1 / 100 / 1   1 / 100 / 2   1 / 100 / 3
               ========= ============= ============= =============
                  GCS        3.19m         3.07m         2.98m
               ========= ============= ============= =============
```
1.06 TB of netCDF via FUSE is much slower
```
               ========= ============== ============== ==============
               --             z_chunksize / n_workers / run_num
               --------- --------------------------------------------
                backend   10 / 100 / 1   10 / 100 / 2   10 / 100 / 3
               ========= ============== ============== ==============
                  FUSE       6.57m          6.27m          5.73m
               ========= ============== ============== ==============
```

Which works out to about 2.92 GB/sec on average. I once had Zarr on FUSE datasets but haven't updated them as I wasn't sure that would be a popular use case. I should note that all tests only gather stats on time it takes to read the data (in this case, getting a max value). Setting up the object in Python is not counted towards read speeds, e.g., `ds = xr.open_mfdataset('/data/*.nc')`. This can take a considerable amount of time especially for FUSE cases (up to 25-30 minutes with netCDF on FUSE for the ~1.06 TB case).

**Comment by jacobtomlinson** [comment]
@kaipak looks interesting? Out of curiosity which FUSE driver were you using?
