### ISSUE TITLE
xarray / pangeo at EGU 2018

### ISSUE THREAD

**Issue by fmaussion** [pangeo-data/pangeo#200]
Hi all,

For the second year in a row there will be an xarray/pangeo talk at EGU, this time given by @jhamman at the [big data session](https://meetingorganizer.copernicus.org/EGU2018/session/28374) on Monday.

We'll meet on Monday after the poster session for some drinks and important discussions: let me know via PM if you'd like to join!

**Comment by jacobtomlinson** [comment]
Ping @niallrobinson @rprudden

**Comment by benbovy** [comment]
Ping @Chilipp

**Comment by jhamman** [comment]
@rabernat - I think it went pretty well. In hindsight, I think we could use some definitive benchmarks describing how dask+xarray scales for one or two "common" workflows. It was also quite well attended, perhaps 150 or more folks showed up. Slides are in [this](https://www.dropbox.com/s/o1i42au76ksmfwk/pangeo_egu_presentation.pdf?dl=0) dropbox link.

**Comment by fmaussion** [comment]
I can confirm: it was a great talk! There were many (technical) questions and obviously a strong interest from the crowd. Let's see if http://pangeo.pydata.org/ can handle the hundreds of connections that will follow ;)

**Comment by fmaussion** [comment]
@benbovy 's [xarray-simlab](https://github.com/benbovy/xarray-simlab) presentation also raised a strong interest

**Comment by niallrobinson** [comment]
To add to that
https://meetingorganizer.copernicus.org/EGU2018/EGU2018-14402.pdf
the GSKY project is also using k8s to scale for data analysis. Had some good chats with Joseph Antony from NCI in Australia

**Comment by benbovy** [comment]
> @benbovy - do you know the authors of the abstracts listed above?

No. Unfortunately, I was too late for the poster session so I haven't has the opportunity to chat with them.
