### ISSUE TITLE
Creating Directories in a fuse mount from Jupyter container

### ISSUE THREAD

**Issue by kaipak** [pangeo-data/pangeo#202]
Touching files works fine and indeed, files I copy/create in the terminal show up in the console. However, if I try to create directories, I get the following:
```
[jovyan@jupyter-kaipak /gcs/storage-benchmarks
 :) ]$ mkdir foo
mkdir: cannot create directory ‘foo’: Bad address
[jovyan@jupyter-kaipak /gcs/storage-benchmarks
 :( ]$
```
Stranger still are the timestamps:
```
 :) ]$ ls -la
total 0
drwxrwxrwx 0 jovyan 1000 0 Jan  1  1970 .
drwxrwxrwx 0 jovyan 1000 0 Jan  1  1970 ..
drwxrwxrwx 0 jovyan 1000 0 Jan  1  1970 test_fuse
drwxrwxrwx 0 jovyan 1000 0 Jan  1  1970 test_zarr
```
Finally, if I delete a directory in the console, it doesn't register in my mounted filesystem until much later, as if it's not updating frequently. I don't get any of these problems from my local laptop. I tried giving my account full ownership access to a different bucket, but this doesn't seem to work either.

**Comment by mrocklin** [comment]
The FUSE system currently attached to pangeo.pydata.org is based on a
pretty experimental system in gcsfs that was made very quickly.  I would
not expect particularly smooth functioning.  If you wanted to raise this
issues upstream at https://github.com/dask/gcsfs that would be welcome.
PRs moreso :)

**Comment by mrocklin** [comment]
Relevant code is here:
https://github.com/dask/gcsfs/blob/master/gcsfs/gcsfuse.py

**Comment by kaipak** [comment]
I take it there isn't a huge issue with installing the Google's gcsfuse for now? 

I mean, I'd be happy to also take a swag at a PR :).

**Comment by jgerardsimcock** [comment]
@kaipak please see https://github.com/dask/gcsfs/issues/96

Did you pass values to `project-id` and `token`?
