### ISSUE TITLE
Engagement with industry startups in climate fields

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#204]
There is a growing list of tech-savvy companies / startups focused on climate-related issues. Many of these are oriented heavily towards remote sensing, but others are using models etc. in a way similar to academic scientists. There is a good opportunity here for Pangeo to partner with such organizations. We have common needs for cloud infrastructure and scalable computing tools. A great outcome would be for developers in those companies to contribute to pangeo-related open-source projects.

Some of the companies I have in mind are.

- [Planet](https://www.planet.com/) - kind of the big one, they launch their own satellites
- [Development Seed](https://developmentseed.org/) - very active in ESIP
- [Rhodium Group](https://rhg.com/) - folks from their Climate Impact Lab are already involved in xarray
- [Descartes Labs](https://www.descarteslabs.com/) - several ex colleagues are there
- [Jupiter Intel](https://jupiterintel.com/) - new kid on the block, more focused on long-term climate modeling

Who else should be on this list?

Should we try to engage with these companies? If so, what do they have to gain from collaborating with us?

**Comment by kmpaul** [comment]
Several ex-NCAR people are at Jupiter Intel, and NCAR has a fledgling project with them to set up data analysis in the cloud. We are talking with them about setting up a Pangeo JupyterHub on AWS to test with the LENS dataset. My understanding is that some of this has already been done on the Pangeo side, but I haven’t had time to catch up on it.

**Comment by darothen** [comment]
The company where I currently work, [ClimaCell](https://www.climacell.co/), is leaning heavily on the Pangeo stack on our science/tech teams. We're integrating components of the stack for background for various different purposes, particularly for more easily working with large datasets split up into collections of GeoTiffs and stored on Google Storage. There's been parallel talk on the xarray forum about a GeoTiff writer/backend beyond what rasterio currently offers, and I'm seeing if we might be able to open source our internal solution there, as well as finding other ways we can contribute back to xarray and the other core projects in the stack.

I evangelize Pangeo every chance I can, and have won a lot of converts internally. We've even got a day carved out next week to set up the Pangeo JupyterHub instance on our dev project on GCP :)

**Comment by NickMortimer** [comment]
@darothen ClimaCell looks interesting do you do much ocean weather prediction?

**Comment by jgerardsimcock** [comment]
Maybe some of these companies too?
https://darksky.net/about
http://echoparklabs.io/
https://new.surfline.com/

**Comment by rabernat** [comment]
> There's been parallel talk on the xarray forum about a GeoTiff writer/backend beyond what rasterio currently offers, and I'm seeing if we might be able to open source our internal solution there, as well as finding other ways we can contribute back to xarray and the other core projects in the stack.

This comment from @darothen exemplifies what I hope to get out of partnership with such companies. They have similar problems to us, strong motivation to solve them, and substantial developer resources. They can potentially move the dial significantly on important features.

Thoughts on how to most effectively engage? Mine are as follows:
- Finish the website update (#134)
- Write some text on the website about how Pangeo can benefit companies and vice-verse
- Develop a specific list of "top priority" issues we don't have the resources to solve ourselves in the near term
- Conduct outreach to these companies via personal contacts, hoping to get our message to the CTO level
