### ISSUE TITLE
Open Data Science Conference Boston May 2018

### ISSUE THREAD

**Issue by NickMortimer** [pangeo-data/pangeo#205]
Hi I'm off to ODSC conference in Boston and would be keen to meet up with any Pangeo developers there. We are looking at Pangeo for working with nearshore models here in Perth WA

**Comment by darothen** [comment]
@NickMortimer Would love to meet in person and grab coffee with anyone who's coming out to the conference. I'm delegating someone on my team to attend the conference but I'll be around town for any other simultaneous meet-ups/events.
