### ISSUE TITLE
potential 'write' band bug triggers "Source shape is inconsistent with given indexes" error

### ISSUE THREAD

**Issue by ebo** [pangeo-data/pangeo#207]
I am not sure if this is a rasterio, xarray, or dask issue, but...

```
     pds = xr.open_rasterio(pan_file, chunks={'band': 1, 'x': 256, 'y': 256})
     bands = pds.band.compute().variable.data
     print("bands=",bands,type(bands[0]))
     for i in range(rpan.count):
         print ("indx:",i, type(i+1))
         print ("shape:",pds.variable.data.shape)
         print (dst.shape,pds.shape)
         print (pds.variable.data[i].shape)
         # this failes
         #dst.write(pds.variable.data[i].compute(), bands[i])
         # this works
         dst.write(pds.variable.data[i].compute(),i+1)
```

bands is an array (the first element is 1), and the index 'i' is 0.  So when I pass in bands[0]  (ie with a value 1 of type <class 'numpy.int64'>) I get the "Source shape is inconsistent with given indexes" error.  When  I pass in "i+1" (which also passes in 1, and I checked the type is <class 'int'>), then it works.  Does this make any sense to anyone?  I thought numpy.int64 evaluated to a int type.    Is this a bug?

As a note, here is the output from the prints:

> bands= [1] <class 'numpy.int64'>
> indx: 0 <class 'int'>
> shape: (1, 38050, 35698)
> (38050, 35698) (1, 38050, 35698)
> (38050, 35698)

**Comment by jhamman** [comment]
what are `dst`, and `rpan`?  Typically, debugging things like this is easiest if a minimal example can be shared. 

A general comment: indexing into the underlying array somewhat defeats the purpose of xarrays labeled indexes. Is there a reason you can't use xarray's indexing in your use case?

**Comment by ebo** [comment]
On Apr 11 2018 5:03 PM, Joe Hamman wrote:
> what are `dst`, and `rpan`?  Typically, debugging things like this is
> easiest if a minimal example can be shared.
>
> A general comment: indexing into the underlying array somewhat
> defeats the purpose of xarrays labeled indexes. Is there a reason you
> can't use xarray's indexing in your use case?

Right.  This chunk of code can be shared.  I will post the entire test 
code tomorrow when I get back to work in the morning.

**Comment by mrocklin** [comment]
It looks like you're trying to put an xarray.DataArray into a rasterio call

```python
(Pdb) pp dst
<open RasterUpdater name='myoutfile.tif' mode='w'>
(Pdb) pp mds.band[i]
<xarray.DataArray 'band' ()>
array(1)
Coordinates:
    band     int64 1
```

Rasterio is upstream of xarray and won't understand its objects.  I recommend converting this object to an integer beforehand by sending `int(mds.band[i])` instead

**Comment by ebo** [comment]
On Apr 12 2018 1:01 PM, Matthew Rocklin wrote:
> It looks like you're trying to put an xarray.DataArray into a 
> rasterio call
>
> ```python
> (Pdb) pp dst
> <open RasterUpdater name='myoutfile.tif' mode='w'>
> (Pdb) pp mds.band[i]
> <xarray.DataArray 'band' ()>
> array(1)
> Coordinates:
>     band     int64 1
> ```
>
> Rasterio is upstream of xarray and won't understand its objects.  I
> recommend converting this object to an integer beforehand by sending
> `int(mds.band[i])` instead

I thought I had converted it to an int array, but I see that I was 
mistaken.
