### ISSUE TITLE
"cluster has unschedulable pods"

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#21]
I tried to follow the [instructions](https://github.com/pangeo-data/pangeo/wiki/Getting-Started-with-Dask-on-Google-Clould-Platform) on the wiki for launching dask-kubernetes on our GCP project.

I got this error on the console 

![image](https://user-images.githubusercontent.com/1197350/31858195-c494dde6-b6bf-11e7-926c-73ae49fb2bcc.png)

**Comment by rabernat** [comment]
However, I can still connect to the notebook, so I guess the cluster is running.

**Comment by jhamman** [comment]
@rabernat - not 100% sure but I think https://github.com/pangeo-data/dask-kubernetes/pull/1 could be the solution to what you're seeing. I realized I had downsized the cluster specs before we had our GCP credits and had not switched it back.
