### ISSUE TITLE
Request header or cookie too large

### ISSUE THREAD

**Issue by kaipak** [pangeo-data/pangeo#210]
I've been doing a significant amount of work on Pangeo recently and for the most part, things work pretty great. What I run into somewhat frequently (maybe once or twice a day), is that my session will become unresponsive and I'll get a screen like this:

![screen shot 2018-04-11 at 6 48 09 pm](https://user-images.githubusercontent.com/9453271/38647201-1159d98a-3db9-11e8-823d-21f390b600a9.png)

It's an easy fix and I just have to clear out cookies related to Pangeo, but I'm wondering if we can have a more consistent fix.

**Comment by jhamman** [comment]
It would be good to know if this is something that is a known problem with JupyterHub or our specific deployment. I'm guessing @yuvipanda would know the answer to this question.

**Comment by yuvipanda** [comment]
I haven't encountered this before in JupyterHub deployments. Can you show us your cookies related to pangeo - redacting anything that looks sensitive but keeping the size intact?

**Comment by tjcrone** [comment]
i've had similar but different issues a long while back. is this something that could be fixed by upping the nginx client_max_body_size?

**Comment by tjcrone** [comment]
looks like it might be a different nginx setting, large_client_header_buffers: https://kx.cloudingenium.com/technologies/web/nginx/resolved-400-bad-request-request-header-cookie-large-using-nginx/. this would probably need to be fixed by applying this nginx setting to the helm config somewhere.

**Comment by jacobtomlinson** [comment]
I remember encountering this a few times in the past. I while back we raised jupyterhub/zero-to-jupyterhub-k8s#346 and haven't seen the issue since that was merged. Do you have any idea how big your notebooks are getting?

**Comment by kaipak** [comment]
It seems this issue may be browser dependent. I primarily use Firefox, but last night, I launched a job from Chrome and saw this morning that the issue hadn't cropped up.
