### ISSUE TITLE
Pangeo Tutorial at AGU 2018 Fall Meeting

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#211]
I think we should submit a tutorial proposal for AGU 2018 Fall Meeting
https://fallmeeting.agu.org/2018/session-proposals/tutorial-proposals/

> Understanding a different field of study from one’s own provides opportunities not only for learning, but also can spark ideas for a new way to approach a problem or new collaborations.  The new Tutorial Talks provide an expert review and synthesis of multiple results from a number of researchers, so that the audience can gain a current understanding of the topic.
>
> These talks should be designed to have a broad appeal to participants seeking an overview of a given topic, and are not primarily a presentation of the proposer’s own work. View the Tutorial Talks presented at the 2018 Ocean Sciences Meeting as a reference.
>
> Accepted talks will be grouped into dedicated 30-minute concurrent sessions by the Program Committee, and consist of a 25-minute presentation with time for questions and for changeover of each tutorial program.
>
>There will be no submission fee charged for Tutorial Talks. Acceptance notifications for talks will be distributed in early June 2018. Accepted tutorial speakers will also be allowed to submit an abstract for topical sessions if they choose.
>
>Tutorial Talks must include an informative title (20–180 characters) and brief description of the session topic (limit 200 words). The proposal must be submitted by a presenter of the tutorial. Up to one (1) co-presenter may be entered at the time of submission.
>
>There will be a limited number of Tutorial Talk sessions; proposals will be reviewed and selected by the Fall Meeting Program Committee.
>
> Proposals for Tutorial Talks are being accepted for the first time in 2018. The deadline for proposals is 18 April 2018, 11:59 PM ET and are submitted via the same system as session proposals.

I imagine this would probably be presented myself and @jhamman. But we would seek as much community input as possible into the tutorial content.

**Comment by jhamman** [comment]
@rabernat - I put this very rough cut together: https://docs.google.com/document/d/1ISJq17ZHq7AOp3Cv5QIlDg2D7LCvOvH_d-Ug3iC4JOg/edit?usp=sharing

Input from others is welcome. One thing to remember is that this is just 25 minutes so we can't cover all that much ground.

**Comment by jacobtomlinson** [comment]
Ping @niallrobinson who may potentially be at AGU.

**Comment by niallrobinson** [comment]
I think this is a great idea - I think I'm going to struggle to get to AGU this year unfortunately. We'll try really hard to send someone though.
