### ISSUE TITLE
Killer Demo

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#213]
With all of the amazing work that this community has done over the last year, I'm wondering if anybody can share what they think is the "killer demo" of the Pangeo platform.  That is, a demo notebook that shows a hard problem working on a "big" dataset that...well...just makes the audience's jaws drop and drool!

The motivation to that question is that I am putting a presentation together for the whole of NCAR on the Pangeo project / platform / community.  I only have about 10 minutes MAX for a killer demo, which makes this a hard request.  So, I'm welcoming any suggestions!  (The presentation will be on April 20.)

**Comment by rabernat** [comment]
Will you be using cheyenne or pangeo.pydata.org?

**Comment by rabernat** [comment]
Have a look at the `sea-surface-height` demo notebook on pangeo.pydata.org. See if you think this is sexy enough.

It's a real-world calculation using "medium" data (hundreds of GB) that can run more-or-less instantly in pangeo-pydata.org. The end result is a curve of global sea-level rise. Not the most cutting-edge analysis, but a problem everyone can relate to. For a 10 minute demo, you have to keep it relatively simple.

I have working examples using GFDL CM2.6 or CESM high res ocean models that operate on TB of data. But those are not particularly stable yet, but If you really want to show the analysis of NCAR model data, I can try to make that happen.

-Ryan

**Comment by kmpaul** [comment]
I'll take a look.  Thanks, @rabernat!

**Comment by kmpaul** [comment]
Just ran through it.  I think it will work very well for the demo.  I think it shows the daskboard really effectively, too.  Thanks!

**Comment by rabernat** [comment]
A presentation technique that works well with this demo is to start off with only one worker in your cluster. The dashboard will show the calculation proceeding basically in serial--at this rate it would take hours. Then you can flip to the cluster control widget and scale up to like 30 workers, then flip back to the dashboard. You will see 29 more workers come on line dynamically and start participating in the calculation. At that point it will finish in a few seconds. 

Note that it is good to practice this before trying it live and to run it before starting the demo to make sure the nodepool has already scaled up enough to provide new workers right away. (It can take several minutes if GKE has to provision new compute instances.)

**Comment by kmpaul** [comment]
Oh, that's a great idea!  I demonstrates a capability that most people at NCAR are pretty unfamiliar with (elasticity).  

Thanks for the tips!

**Comment by kmpaul** [comment]
Just gave my demo this morning. It went very well. I had problems earlier this week manually scaling. However, adaptive scaling actually worked really well after first running through the notebook with the max-provisioned workers a few minutes before the talk. Basically, I set up the cluster with 4 workers minimum and 60 workers maximum, and switching to the dashboard after starting all of the intensive tasks. Everyone was able to see in real time as the job started slowly with 4 workers and then ramp up the number of workers and fly through the calculation. I couldn’t hear it from the front of the room, but people told me afterwards that there were gasps from the audience. Absolutely awesome!

Thanks @rabernat for pointing me to the demo.
