### ISSUE TITLE
Update `Getting-Started-with-Dask-on-Cheyenne` with proper memory usage

### ISSUE THREAD

**Issue by jmills-ncar** [pangeo-data/pangeo#217]
The current example shows 24GB of RAM for workers, this has been shown to be an issue on Cheyenne PBS jobs per PR https://github.com/pangeo-data/pangeo/pull/27

Please update https://github.com/pangeo-data/pangeo/wiki/Getting-Started-with-Dask-on-Cheyenne with the proper memory usage from the linked PR above.

Once I get these bumps ironed out, what you all have put together will greatly help our work.
Thank you!

**Comment by jhamman** [comment]
@rabernat is working on an update to the pangeo documentation and I image when that effort is done, we can remove the wiki page you linked to all together.

**Comment by jmills-ncar** [comment]
Fantastic, thank you! I will check it out

**Comment by jhamman** [comment]
@jmills-ncar - make sure to checkout https://pangeo-data.github.io/pangeo/setup_guides/hpc.html
