### ISSUE TITLE
Help with documentation on dask-jobqueue

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#218]
Hi All, 

The PBSCluster that was incubated in this repository was moved over to [dask-jobqueue](https://github.com/dask/dask-jobqueue/) where it grew friends like SGECluster, SLURMCluster, as well as improved stability, continuous integration, and maintainers.  That project could use your help in a few ways:

1.  If you're using Dask/XArray on an HPC system, please give it a shot
2.  If you're able to provide examples on how to set up dask-jobqueue on your cluster please consider submitting that example to live in [the examples documentation](http://dask-jobqueue.readthedocs.io/en/latest/examples.html).  This could either be a PR to that github repository or just a comment to [this issue](https://github.com/dask/dask-jobqueue/issues/40) on improving documentation in that library.  It would be nice to see examples that engage keywords like project id, queue id, network interface, resource spec, etc..  

3.  If these keywords are new to you then please speak up and lets sort things out to make sure that things work cleanly on your system so that others who come later can see these examples and copy-paste to get something reasonable.

Thank you all for your help

**Comment by jgerardsimcock** [comment]
@mrocklin I am trying to setup `dask_jobqueue` on the HPC at Berkeley. They use slurm. I've got it loaded following the instructions on the docs. We have a compute allocation but we never use it for computing directly.  For large scale jobs we tend to use low-pri nodes that can get pre-empted. I've added those args to the initialization. I run the following in a jupyter notebook on brc since they have a jupyterhub deployment available for users. 

```
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(processes=6, 
                       threads=4, 
                       memory="16GB", 
                       account="co_laika", 
                       qos="savio_lowprio", 
                       partition='savio2_bigmem',
                       env_extra=['export LANG="en_US.utf8"',
                                  'export LANGUAGE="en_US.utf8"',
                                  'export LC_ALL="en_US.utf8"'])
cluster.start_workers(10)  
from dask.distributed import Client
client = Client(cluster)
```
I create a function to compute the mean of a global temperature dataset using xarray and I map that  with `client.map` over a set of file inputs. I get back my futures object and my jobs are in status `pending`. Everything looks normal. I then go check slurm to see if my jobs have been registered (`squeue -u {user}`) and they have not. Usually, even if the jobs had not started (due to low-pri request) slurm would have some record of the job request. There is nothing. The jobs in the future object never move out of `pending`. 

Its not obvious to me that this should succeed or fail with low-priority nodes so I tried it from one of our dedicated nodes and get similar behavior with the futures object. 

Do we know of any other users of `dask_jobqueue` on slurm systems? I did not see anything obvious in the hpc docs about to merged.

**Comment by rabernat** [comment]
I know this is off topic, but I'm curious about this part:

> I create a function to compute the mean of a global temperature dataset using xarray and I map that with client.map over a set of file inputs.

None of that complexity should be necessary. Once you create a `Client`, you should be able to simply use xarray as you normally would, e.g.
```python
ds = xr.open_mfdatset('/path/to/globally/accessible/netcdf_files_*.nc')
ds_mean = ds.mean().load()
```
Dask should automatically use the cluster for the computation.

To debug, I recommend trying something really simple with the client, such as the [example from the dask docs](http://distributed.readthedocs.io/en/latest/client.html#concurrent-futures).

**Comment by jgerardsimcock** [comment]
Thank you for your feedback @rabernat! This is now working with some tweaks to the arguments we needed to pass to the initialization, which I misunderstood on first read.

**Comment by rsignell-usgs** [comment]
@jgerardsimcock, I'm also using `dask_jobqueue` successfully on Slurm on our USGS "Yeti" HPC system in Denver.   What were the tweaks you needed, just out of curiosity?

**Comment by guillaumeeb** [comment]
Glad to hear it works for you!

Could you raise these kind of issues upstream in [dask_jobqueue](https://github.com/dask/dask-jobqueue/issues) in the future?

Also, can you put the solution to your problem? I see that you tried to use keywords that probably don't exist like `qos` or `account`. 

Thanks.

**Comment by mrocklin** [comment]
I'm also curious about the use of the following:

```
                       env_extra=['export LANG="en_US.utf8"',
                                  'export LANGUAGE="en_US.utf8"',
                                  'export LC_ALL="en_US.utf8"'])
```

I'm aware that the CLI library we use, click, requires these.  My hope was that they were commonly set by default.  Was that not the case with `savio`?

**Comment by mrocklin** [comment]
Also, to help diagnose your original problem I would do two things:

1.  As @rabernat  suggests, try a much simpler problem, like `client.submit(lambda x: x + 1, 10).result()`
2.  Use the SLURM command line utilities to verify that your workers have started and are running happily, and, if they are not, inspect the logs for reasons why they might have failed.  You might also look at `cluster.scheduler.workers` to verify that some workers have connected up.  If that dictionary is empty then no one has connected.

**Comment by willirath** [comment]
```

                              env_extra=['export LANG="en_US.utf8"',

                                                    'export LANGUAGE="en_US.utf8"',

                                                    'export LC_ALL="en_US.utf8"'])

```


I've also needed to set these environment variables on all the HPCs (all running CentOS / Redhat, I think) I spun up dask clusters on.

**Comment by guillaumeeb** [comment]
I've encoutered the need for LC_ALL env variable when working on PBS and SLURM Docker images for dask_jobqueue continuous integration. But in a Docker light os this can be expected. 

I had to use the `-V` option from PBS `qsub` submit command for the tests though, as jobs were run in a minimal environment where LC_ALL or LANG were not positionned. This command allows to propagate env variable from user session in the job env.

You can also do that with Slurm using following option `--export=<environment variables [ALL] | NONE>`, see https://slurm.schedmd.com/sbatch.html.

In the CNES HPC based on PBSPro and Centos, it is correctly set, no need for that.

**Comment by mrocklin** [comment]
Reference to a click issue for the locale problem:
https://github.com/pallets/click/issues/448#issuecomment-389506283

**Comment by jhamman** [comment]
@rsignell-usgs, @jgerardsimcock, and @willirath - Can we encourage you to add your typical SLURM cluster setups to the dask-jobqueue documentation?

http://dask-jobqueue.readthedocs.io/en/latest/examples.html

Despite the pain points described here, I'm quite happy to see that dask-jobqueue is being used by a growing number of folks.

**Comment by jgerardsimcock** [comment]
@rsignell-usgs. I had to go and read the docstring from slurm.py file to better understand what `dask_jobqueue` arguments mapped to which slurm params. Since we use low pri nodes I needed to add the `qos` to the `extra_env` list. 

```
cluster = SLURMCluster(processes=5, 
                       threads=4, 
                       memory="16GB", 
                       project="co_laika", 
                       queue='savio2_bigmem',
                       env_extra=['export LANG="en_US.utf8"',
                                  'export LANGUAGE="en_US.utf8"',
                                  'export LC_ALL="en_US.utf8"', 
                                  'qos="savio_lowprio"', 
                                  'nodes="20"'])
```
