### ISSUE TITLE
AMS 2019 Pangeo Short Course?

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#221]
The 2019 AMS Annual Meeting (January 6-10 in Phoenix, AZ) is a potential venue for a Pangeo course.  This venue provides the possibility of a half-day, full-day, or two-day course.  These courses are usually the weekend before the AMS Annual Meeting, so this course would be either on January 5 and/or 6.  

In the past, @dopplershift has hosted a MetPy short course, @marylhaley from NCAR has hosted a PyNGL short course, and @jwblin has hosted a 2-day course on beginner python.  Based on information I know about those courses in the past, I would suspect around 15-25 people would register for a Pangeo course.

Does anybody want to help me host a course on Pangeo?  The deadline for signing up for a short course is May 15.

**Comment by darothen** [comment]
I'd definitely support this... the only short course proposal we've seen on the Python committee thus far is a beginner Python tutorial from Johnny Lin. I'm not sure I have the bandwidth to volunteer to help host it, @kmpaul, but I'd be happy to help recruit someone and champion it on the AMS side. There was also a lot of interest in a deep learning / Python short course - if anyone is using Pangeo as a vehicle to ingest data into TensorFlow or other frameworks, then I'd strongly encourage you to reach out to the Python and AI committees.

**Comment by dopplershift** [comment]
I may be able to help (as someone in the room), but I've also submitted a MetPy tutorial that will (hopefully) be my focus.
