### ISSUE TITLE
Add branding to the GitHub org

### ISSUE THREAD

**Issue by jacobtomlinson** [pangeo-data/pangeo#223]
It would be nice to update the logo on https://github.com/pangeo-data to use the [branding](https://github.com/pangeo-data/branding).

I don't have appropriate permissions to change it. Could someone do it or give me the perms?

**Comment by rabernat** [comment]
Thanks for doing this!

However, I have to admit that I really dislike the color scheme on that particular permutation of the logo. (I made the same comment here: https://github.com/pangeo-data/pangeo/issues/78#issuecomment-373582558)
The dueling green blue gradients look super clashy to me.

Could we standardize around this one instead?
![logo](https://raw.githubusercontent.com/pangeo-data/branding/master/logo/pangeo_card_white.png)

Or perhaps do another design iteration?

**Comment by jacobtomlinson** [comment]
Happy to go with the white background!
