### ISSUE TITLE
Issue labels

### ISSUE THREAD

**Issue by jacobtomlinson** [pangeo-data/pangeo#224]
As we seem to have a growing list of issues I've added a bunch of issue labels and tagged up a load to make it easier to keep track of things.

I may have gone a little wild, so happy for input. 

_This is more of an announcement so I'll close it straight away._

**Comment by rabernat** [comment]
This is great. 118 open issues is perhaps a lot for a project with no real code base! We are using the issues as an open-ended discussion forum.

I appreciate your efforts to help organize!
