### ISSUE TITLE
ESIP Summer Meeting, July - Arizona 

### ISSUE THREAD

**Issue by jreadey** [pangeo-data/pangeo#225]
The ESIP summer meeting will be held July 17-20 in Tucson AZ.  (great if you like warm weather!) 
 @rabernat gave a nice talk at the winter meeting last Jan, and I think it would be valuable for Pangeo to keep up the engagement with the ESIP community.

The summer meeting typically has larger and more diverse attendance compared with the Winter meeting.

We (The HDF Group) will be submitting some sessions covering: HDF in the cloud, Jupyter, and general HDF info.  If Ryan or someone else from the Pangeo team would like to give a 15-20 minute talk, we can add you into one of our sessions.  

Deadline for submission is Monday, May 30, so if we could get to a decision by eod Friday, that would be best.

**Comment by jhamman** [comment]
cc @kmpaul

**Comment by kmpaul** [comment]
Yes!  Sorry for the delay.  

Thanks, @jreadey!  I will be attending the ESIP summer meeting, and I'm happy to speak.

**Comment by kmpaul** [comment]
Excellent!  It looks like we have all of the responses that I was expecting to receive.  My next step is to put together another survey that will have a quick turn-around.  I'll accumulate the responses from this last survey from those who said they can host, and I will put together a location/time survey to gather people's preferences on the day and location.  I will send the survey directly to the emails given in the last survey as well as post the survey here.

Give me just a little time to put the new survey together and you'll hear back from me shortly.

**Comment by kmpaul** [comment]
Okay.  I've sent the site and time preferences survey to everyone who filled out the last survey.  If you don't get the link in the email, it is here:

https://docs.google.com/forms/d/17QoPRiOBvcy8QqcgaJpNWcmnM0tZE5Fcl9pH4ole-Yg

I am hoping that I can get a very rapid turn around with this survey.  Once we have responses, then I will summarize the responses here to let everyone know.  I understand that we may not find an ideal solution for everyone, but I will try to accommodate as many people as possible.

**Comment by rsignell-usgs** [comment]
One of the ESIP Summer sessions proposed was "How Jupyter Project technologies are used in the ESIP community" with this description:

**Comment by mrocklin** [comment]
Interesting... :)  I may be able to swing by if useful, but haven't confirmed anything.  I suspect that Thomas just needed to put down some names.

**Comment by kmpaul** [comment]
@jreadey What happened with this?  I never heard anything back.

**Comment by jreadey** [comment]
Hey @kmpaul - Sorry for the lack of feedback.  We actually just got together today to start planning for ESIP.  
Would you be talking about the Pangeo project in general?  Of interest to the HDF5 community would be covering different means of enabling HDF5/NetCDF4 data in the cloud: FUSE Drivers, conversion to Zarr, etc.

**Comment by kmpaul** [comment]
Well.  I'd be comfortable talking about Pangeo in general, but I'm not the one you want talking about enabling HDF5 and NetCDF4 data on the cloud.  And I doubt I will have the time to come up to speed on that before July.

**Comment by jreadey** [comment]
Are you more focused on Pangeo in HPC environments?  
We at the HDFGroup can be a bit myopic in terms of thinking about everything in terms of the HDF5 api.  Covering tools/packages up the stack would be great: Dask, JupyterLab, xarray, etc.

**Comment by kmpaul** [comment]
Yeah, I'm more on the HPC end.  I'd be happy to talk about the general stack.

**Comment by jreadey** [comment]
@kmpaul - Sorry, but we ended up with too many other talks for the HDF Townhall and the powers-that-be decided to limit presenters to HDFGroup people.  I do hope we can have a talk on Pangeo at ESIP...  @rsignell-usgs: Is there a spot in the Jupyter session for Kevin?

**Comment by kmpaul** [comment]
@jreadey Well.  That's okay.  I'm wondering if I should go anyway.

@rsignell-usgs You are working on Pangeo-related stuff.  Are you planning on talking about any of it at your Jupyter session already?  Do you feel there is something missing?  I'm not sure I can talk to the Jupyter parts of Pangeo as well as other Pangeo community members, though.

**Comment by rsignell-usgs** [comment]
@jhamman , there is definitely still room to present Pangeo talks in any or all of these sessions:
* http://meetings.esipfed.org/event/Eyph/optimizing-data-for-the-cloud
* http://meetings.esipfed.org/event/Eype/introduction-to-jupyter-technologies-and-how-they-are-used-in-the-esip-community
* http://meetings.esipfed.org/event/Eyqd/using-cloud-object-stores-for-data-storage-and-data-services
* http://meetings.esipfed.org/event/Eyqg/interactive-data-analysis-on-cloud-environment

**Comment by rsignell-usgs** [comment]
Okay, sounds like @jhamman  and @kmpaul are *not* attending, so @jreadey and I can give the "Pangeo update" and "ndarray formats for the Cloud" presentations that ESIP organizers are looking for. 

Obviously we would give these talks from our perspective and knowledge base, but also include an overview of what others are doing on these projects and where they are heading.  @jhamman has agreed to help us with the material, and we will likely be pinging others.  Would sharing presentations in advance with entire group (say on Google docs) be a good idea?

I'll be at SciPy in Austin the week before ESIP (July 11-15) and hope to spend the code sprint time over the weekend to delve a bit deeper into FUSE and s3netcdf and the [storage tests](https://github.com/pangeo-data/storage-benchmarks) on AWS.

Does this plan sound okay?
