### ISSUE TITLE
make gitter channel

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#227]
it would be useful to have a gitter.im channel for pangeo, specifically `pangeo-data/pangeo`

However, I can't get gitter to see the pangeo-data org.

It would be great if someone with gitter experience could sort this out.

cc @mrocklin @jacobtomlinson

**Comment by rabernat** [comment]
xref pangeo-data/helm-chart#19

**Comment by dopplershift** [comment]
Weird, I’ve never had any problems. What do you mean you can’t get it to see the org?

**Comment by rabernat** [comment]
I mean I am the owner of the `pangeo-data` org, but it doesn't show up in my gitter page:
![image](https://user-images.githubusercontent.com/1197350/39442700-28e74c38-4c80-11e8-91cb-513f204eaf8f.png)

**Comment by jhamman** [comment]
done: https://gitter.im/pangeo-data/Lobby

(required a few changes including relaxing our "Third-party application access policy").

**Comment by rabernat** [comment]
Too bad gitter just went down! 😝
