### ISSUE TITLE
Jupyter Containers?

### ISSUE THREAD

**Issue by kaipak** [pangeo-data/pangeo#228]
Anything going on with the environment? I try to start my Jupyter container and the console just keeps showing 'Pod initializing' but it never comes up and eventually fails. Notice in logs that it says 'Error: InvalidImageName'.

**Comment by jhamman** [comment]
@rabernat and @jacobtomlinson are currently working on getting it back up. xref: https://github.com/pangeo-data/pangeo/pull/206#issuecomment-385422368

**Comment by rabernat** [comment]
I broke it and can't even roll it back. So we are kind of screwed. I don't have time this afternoon to fix it unfortunately.

**Comment by rabernat** [comment]
@kaipak things should be working again, although some issues remain with the new docker images: https://github.com/pangeo-data/pangeo/pull/206#issuecomment-385582070
