### ISSUE TITLE
environment.yml no longer works?

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#23]
I'm just curious if anyone else sees this error, but when I try to create a fresh conda environment using the `pangeo/environment/environment.yml` using:

    conda env create -f environment/environment.yml

from the repo root directory, I get this:

```
Fetching package metadata .....

ResolvePackageNotFound: 
  - numba
```

I suspect that this must have to do with `environment.yml` being outdated, but is this true?  Or is something more serious wrong?

**Comment by jhamman** [comment]
@kmpaul - can you try adding the default channel to the yml file:

```
channels:
  - conda-forge
  - defaults
```

**Comment by kmpaul** [comment]
Yes.  That worked.  I will make the change and submit a PR.
