### ISSUE TITLE
Rework setup guides

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#230]
We currently have a handful of setup guides for dask/xarray/pangeo for Cheyenne and Geyser/Caldera. These are quite out of date now and seem to be causing potential users/adopters all sorts of problems.  I am proposing that we create more general setup guides:

### HPC systems
In this, we'll discuss how to:
 1. setup a conda environment,
 1. launch jupyter,
 1. connect via an ssh tunnel,
 1. launch dask distributed via dask-jobqueue or dask-mpi

I'm open to suggestions on how much detail we really want to include here. These steps can be somewhat machine specific so we'll want to separate those parts. 

### Cloud systems
In this, we'd want to leverage the zero-to-jupyterhub but cover the pangeo specific bits. There may also be an argument for contributing some "cloud for dummies" content to zero-to-jupyterhub since we've been developing some new user know-how in this area.

**Comment by kmpaul** [comment]
I'm in favor of this.  I like the idea of a "general" HPC system, and I think the listed approach is appropriate.  I think it's reasonable to compare it to a real world example, such as Cheyenne, too.  I'm not sure if that means embedding the example(s) into the general HPC system, or if it should be stand-alone.

**Comment by rabernat** [comment]
Who is the point person for updating the cloud setup guide in the documentation? I think either @jacobtomlinson or @tjcrone is the most qualified tow write this. Any volunteers?

**Comment by jacobtomlinson** [comment]
I would be happy to dedicate some time to this. Although it probably wont be until next week.

**Comment by jhamman** [comment]
Given the recent conversation between @kaipak and @mrocklin, I think a subsection of the cloud docs for deploying the dask helm chart would also be appropriate.

**Comment by jgerardsimcock** [comment]
I can also help. @jacobtomlinson @rabernat Where can I start?

**Comment by rabernat** [comment]
> I can also help. @jacobtomlinson @rabernat Where can I start?
> 
> Do we just want to make this more current and comprehensive? https://github.com/pangeo-data/pangeo/blob/master/docs/setup_guides/cloud.rst

Yes, something like that. We would like to update that guide to include the new Pangeo [helm chart](https://github.com/pangeo-data/helm-chart) and other customizations. In the process, we may want to refactor how we organize the config files. Right now the custom config for pangeo.pydata.org lives in [this main pangeo repo](https://github.com/pangeo-data/pangeo/tree/master/gce). Maybe they make more sense elsewhere.

**Comment by tjcrone** [comment]
I am very happy to help. I have been in Seattle for meetings this week but I should be able to contribute early next week. The deploy_gcp and deploy_azure scripts in my fork (pycamhd and gcp branches) are fully functional, do all steps cleanly (using the old helm chart), and have a lot of comments regarding steps that need to be taken on the google/azure consoles in case anyone wants to check them out. I will be starting with these as a base for generating a set of deployment instructions.

**Comment by kaipak** [comment]
I would like to help out on this as well.

**Comment by jhamman** [comment]
I just merged a fairly large set of HPC updates. Now would be a good time to get started on the cloud docs.

**Comment by rsignell-usgs** [comment]
Our USGS Cloud team would like to try installing Pangeo on AWS using EKS.   
Are these the best up-to-date instructions?
http://pangeo.readthedocs.io/en/latest/setup_guides/cloud.html

**Comment by mrocklin** [comment]
No.  Those instructions seem to only create a single deployment for a
single user.  If they want JupyterHub then I encourage them to look at the
helm chart: https://github.com/pangeo-data/helm-chart

I suspect that @jacobtomlinson or @rabernat would have a more up-to-date
understanding of where ideal documentation is for this.

**Comment by jhamman** [comment]
Has anyone started revising the cloud setup docs? It would be great if we can get things moving in this area sooner rather than later.
