### ISSUE TITLE
Yes, pangeo.pydata.org is down

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#233]
We are trying (and failing) to make some updates to the cluster. 

See #206 and pangeo-data/helm-chart#21 if you want to follow the gory details.

At this point it is just a DNS issue. Hopefully it will be resolved by tomorrow. If you are desperate to access pangeo.pydata.org, add the following line to `/etc/hosts`
```
35.224.8.169 pangeo.pydata.org
```

**Comment by mrocklin** [comment]
This appears to be resolved
