### ISSUE TITLE
Explanatory video

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#237]
We would like to have a short explanatory video for the main webpage.  @AlexHilson has already done some work here that might provide a base for such an effort.

There was a brief discussion on gitter but we decided to move it to github for longevity.

**Comment by mrocklin** [comment]
> From @AlexHilson

Hiya, I've heard from Jacob that there's some interest in having a short demo video that could act as an intro the project
Like a more stylish version of https://www.youtube.com/watch?v=BZKpGH4VZew

 (which I put together at the last minute to give as an internal presentation :smile: )
We could put this together, is there anything you'd like to see in the video?
For that one above I was particularly trying to get across - a) browser based b) tooling to make working with large datasets easier, but not in an opinionated way, and c) Jupyter at the core but that's not the whole story

**Comment by mrocklin** [comment]
> From @mrocklin

Hi @AlexHilson , first, let me say that that's an awesome video. Thanks for putting it together and thanks even more for offering to put together another one :grinning:
Some things that I like:

-    As you say, it establishes that it runs on a web browser and is easy to use
-   It shows actual data and actual computation
-    It highlights that people are placing important datasets onto the cloud
-    It generally feels nicely styled. Text is nicely sized, images look pretty, no cruft on the sides

I think that people were considering using it as front-page material on a website, for this I suspect that we would want to change a few things:

Obscure your web address if you'd like to keep it private

Front-load an interesting and exciting computation. If we start with hello world then we might lose viewers. We might instead go from the address bar, to the Pangeo splash page, to a notebook that creates a KubeCluster and then starts a computation immediately.

I think that the elements that I find motivating (or at least that the naive viewer persona in my head finds motivating are, in chronological order)


-    The KubeCluster interface
-    Seeing a sizable cluster be allocated (I would go wild at this point, aiming for a TB of memory or something)
-    Pointing to cloud-accessible data (perhaps add a markdown header to a cell in the notebook that says something like "access data on the cloud")
-    Seeing relevant metadata, while still having the "Access data on the cloud header" visible in the notebook
 -   Seeing the dashboard light up
 -   Seeing a fancy plot


I suspect that some Pangeo folks would prefer to see XArray over Iris, but I suspect that for this audience it might not matter much

**Comment by mrocklin** [comment]
> From @jhamman 

related to xarray vs iris, I think it would serve us all well if we could put together a clear pangeo-stack schematic that demonstrates how specific components can be swapped out (xarray for iris, cloud for hpc, Jupyter for batch, etc). I’m not quite sure the best way to show all of this but if we could work toward having something to this effect, I don’t really mind showing iris over xarray in a demo like this

**Comment by mrocklin** [comment]
> From @rabernat 

@AlexHilson This is great! 

Also cc @jacobtomlinson

**Comment by rsignell-usgs** [comment]
I have shown a bunch of people this [3 minute video](https://www.youtube.com/watch?v=rSOJKbfNBNk) by @mrocklin  and I think it gets the main points across really well.   I like that there is audio commentary, and it even uses xarray and zarr.

**Comment by jhamman** [comment]
Something I'd really like to highlight, is the interoperability within the Python/Pydata/Pangeo ecosystem. The following figure is a very rough illustration of what I mean. 

![slide3](https://user-images.githubusercontent.com/2443309/39601908-67804936-4ed8-11e8-9c41-f2bcaa333245.jpeg)

In my view, and this largely was inspired by conversations with @niallrobinson, that one of the key strengths of what we are doing is that we're building an ecosystem, not a monolithic application. Inside the ecosystem, there are multiple options that one can choose from for any given component of an analysis pipeline. Xarray vs Iris is just one example. HPC vs AWS vs GCP is another. 

The figure above does not do this concept justice, so perhaps we can get someone with some actually design skills to take it a step further.

**Comment by jreadey** [comment]
Add a row for storage format?  E.g. HDF5, Zarr, (TileDB?)

**Comment by rabernat** [comment]
> I suspect that some Pangeo folks would prefer to see XArray over Iris, but I suspect that for this audience it might not matter much

I have to admit that it is somewhat important to me that the video highlight the xarray / dask / cloud stack. While I 100% support the notion of the interoperability, we have received considerable NSF funding (and Google credits) to work on this particular set of tools, and if we are going to showcase something on the front page, I think it should be this.

However, beggars can't be choosers! So I am very happy with whatever @AlexHilson is able to put together.

**Comment by jhamman** [comment]
@AlexHilson - this sounds great. Keep us posted and let us know how we can help come up with the topical video concepts.

**Comment by AlexHilson** [comment]
I'm not sure if I'll have any particularly exciting big data processing demos to work with, so I'm thinking we might use @rabernat's code from #244. If there's anything else anyone would like to highlight about xarray within this project just let me know 🙂

**Comment by mrocklin** [comment]
I used the sea level altitude notebook in a recent talk.  This video might
be helpful: https://youtu.be/Iq72dt1gO9c?t=10m36s

**Comment by rabernat** [comment]
Justing pinging this issue now that we have the new website up: pangeo-data.org.

It would be great to replace the static "E" logo on the landing page with a dynamic video.

@AlexHilson, let us know what you need from us in order to move forward.

**Comment by jacobtomlinson** [comment]
Just to revisit this. @AlexHilson and @meganfitzsimons have put together an updated version of the video. We'll get it up here for a preview before the meeting next week and we can discuss it then.
