### ISSUE TITLE
pangeo.pydata.org success story

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#244]
Over the pass few months, I have raised several issues (e.g. #196, #180, #117) about the stability / scalability of pangeo.pydata.org on larger datasets (> 1 TB). My goal has been to get to the point where I feel that I can stably work with the full datasets I need for my science use case. At times I have been frustrated by mysterious, intermittent errors.

Today I am reporting that, in it's latest deployment (with the latest versions of dask, gcsfs, etc., etc.), the cluster is performing fantastically on these datasets. Here is an example workload:

```python
import xarray as xr
import gcsfs
gcsmap = gcsfs.mapping.GCSMap('pangeo-data/cm2.6/control/temp_salt_u_v-5day_avg/')
ds = xr.open_zarr(gcsmap, decode_cf=True, decode_times=False)
full_temp_ts = ds.temp.mean(dim=('st_ocean', 'yt_ocean', 'xt_ocean'))
# make sure you create a KubeCluster before running the next line...
# it will load and reduce 2.83 TB of data!
%time full_temp_ts.load(retries=10)
```

In this example, the `full_temp_ts` dask graph contains 221921 items. It takes about a minute for the cluster to get going after running the last line, presumably the overhead involved in sending the graph to the scheduler. But once it gets started, it works flawlessly. (This was definitely not the case two months ago.)

Here is a plot of the throughput I get on this calculation as a function of the number of workers:
![image](https://user-images.githubusercontent.com/1197350/39780214-9217c458-52d9-11e8-8bed-95a58fbf97f1.png)

Not the most scientific analysis, but the bottom line is that we are getting close to 10 GB / second read speed and near perfect linear scalability. As a result, I can process down nearly 3 TB of data in a few minutes. 

Thanks to everyone who has worked hard to make this possible!

...now on to the actual science.

**Comment by mrocklin** [comment]
I'm very glad to hear it!

Thank you for being diligent about reporting issues when they occur.
