### ISSUE TITLE
What is WORKDIR in utilities/cheyenne/launch-dask.sh?

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#25]
The WORKDIR environment variable is used in the `utilities/cheyenne/launch-dask.sh` script, but it is not set.  As far as I know, this is not a standard environment variable on Cheyenne.  Should we default it to something reasonable?  Otherwise, the script will attempt to place the `scheduler.json` file in the / directory, and nobody but admins have permission to do that.

**Comment by kmpaul** [comment]
Of course, I cannot check if it is a standard environment variable on Cheyenne because it is down right now.  Perhaps someone can correct me if I'm wrong.

**Comment by mrocklin** [comment]
I think that @jhamman added that bit.  Perhaps this should be `$HOME` or `$PWD`?

**Comment by kmpaul** [comment]
Yeah.  I think either of those are reasonable.  Though, since Cheyenne is down right now, I can't verify if `WORKDIR` is a variable set in the standard user environment or not.  Perhaps I should ask @davidedelvento ...

**Comment by davidedelvento** [comment]
As far as I remember, there is no WORKDIR directory set on Cheyenne.

**Comment by jhamman** [comment]
Apologies, I forgot this is not a variable set for everyone. `WORKDIR=/glade/scratch/$USER`.

**Comment by kmpaul** [comment]
Ah!  That works, too.

**Comment by kmpaul** [comment]
I'll add `WORKDIR=/glade/scratch/$USER` to the script and commit.

**Comment by jhamman** [comment]
please do something like: 

```
if [[ -z $WORKDIR ]]; then
    WORKDIR=/glade/scratch/$USER
fi
```

**Comment by kmpaul** [comment]
Oh.  That's a good idea.  I'll wrap in in an `if` block.
