### ISSUE TITLE
Example Notebooks

### ISSUE THREAD

**Issue by gmsiv** [pangeo-data/pangeo#252]
The example notebooks could include a `cluster.close()` cell at the bottom. I shutdown a pangeo.pydata.org notebook kernel without closing the cluster and had a rough time getting another one to start up (needed to log out and back in again).

Also, the hyperlink created in the second cell output for the example notebooks (`c = Client(cluster)`) does not point to the correct URL, resulting in a 404.

For example: It points to http://pangeo.pydata.org/user/gmsiv/files/user/gmsiv/proxy/33883/status instead of http://pangeo.pydata.org/user/gmsiv/proxy/33883/status .

New to git/github, so I will try to use pull requests for things like this once I get the hang of them. (If I know how to fix something)

**Comment by jacobtomlinson** [comment]
In my experience restarting or stopping a notebook kernel resulted in the `dask-kubernetes` cluster closing automatically as the scheduler is a subprocess of the kernel and the workers exit if the scheduler goes away.

I'm wondering if the problems you've had is a symptom of something else.

**Comment by kaipak** [comment]
> In my experience restarting or stopping a notebook kernel resulted in the dask-kubernetes cluster closing automatically as the scheduler is a subprocess of the kernel and the workers exit if the scheduler goes away.
> 
> I'm wondering if the problems you've had is a symptom of something else.

I've found this to be hit-or-miss. Usually, I see pods stick around in Completed/Successful status pretty much forever (or a very long time) or until the cluster is restarted. I'm not entirely sure what this means from an allocation and provisioning perspective (i.e., if Kubernetes considers these Pods as actually taking up resources or not), but anecdottally, it has seemed like Kubernetes counts them as real and will not allow me to provision more pods until I manually delete them. 

I was actually just about to open an issue on this very topic.

**Comment by jacobtomlinson** [comment]
I've also seen this. The only seems to happen when you leave a notebook running and it gets culled, the workers then go into a completed state. Completed containers so not take up resource.
