### ISSUE TITLE
Anyone at FOSS4G NA?

### ISSUE THREAD

**Issue by jflasher** [pangeo-data/pangeo#253]
Hi all, per @rsignell-usgs suggestion, putting a note up here to ask if anyone is at FOSS4G and would like to meet up?

**Comment by mrocklin** [comment]
I wish I was!

**Comment by jhamman** [comment]
@jflasher - did you manage to find any Pangeo folks FOSS4G? (I did not attend either)

**Comment by jflasher** [comment]
Sadly, I did not!

**Comment by jhamman** [comment]
Bummer, well keep us posted when you're off to similar events.
