### ISSUE TITLE
NEW Pangeo Software Engineer Position at NCAR

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#275]
Dear Pangeo Colleagues,

NCAR has just opened a new position to support the Pangeo collaboration and NCAR-related Pangeo efforts.  This position is for a Software Engineer I, and ideally suited for new undergraduates in Computer Science or related fields.  The link to the job posting is here:

https://ucar.silkroad.com/epostings/index.cfm?fuseaction=app.jobinfo&jobid=218374&version=1#.Ww8pffLBubc.gmail

If you know of anyone who would be a good fit, please encourage them to apply!

**Comment by rsignell-usgs** [comment]
@kmpaul,  must work in Boulder, no chance to work remotely, right?

**Comment by kmpaul** [comment]
Hey, @rsignell-usgs!  I don't think that we entirely rule out working remotely.  However, I do believe that for a position like this, we would want them to work locally, if possible.

**Comment by rabernat** [comment]
@kmpaul -- this is really fantastic news! Kudos to you and your NCAR colleagues for making this happen. I think that a full time engineer on Pangeo will really help us push things forward and tackle some big challenges. Please let me know (offline if you wish) to whom within NCAR leadership I can write an email to express my support and gratitude for this decision.

Your job description sounds great. I'll do my best to help get the word out about this opportunity.

**Comment by rabernat** [comment]
My [tweet](https://twitter.com/rabernat/status/1002190150049419264) on this position got quite a bit of traction!

![image](https://user-images.githubusercontent.com/1197350/41074505-7e946314-69d6-11e8-8190-63d43ab02862.png)

I hope we attract some great applications. We should also be proactive in reaching out to people who we think would be suited to this position to encourage them to apply.

**Comment by mrocklin** [comment]
> I don't think that we entirely rule out working remotely. However, I do believe that for a position like this, we would want them to work locally, if possible.

@kmpaul can you expand on this?  I'm reading this as "if a good candidate with remote restrictions would apply they would be at a disadvantage, but still possible".  Is that correct?  Is there a residency requirement?  Must they be US citizens or based in the US?

**Comment by kmpaul** [comment]
@mrocklin Yeah, I can expand on this, but only anecdotally.  

In the past, we have never had a policy of requiring that a person work locally.  However, the only people that I know who have received jobs at NCAR with a remote situation are PhD scientists and consultants/contractors.  This position is for an entry-level Software Engineer I, and I think that people would feel very uncomfortable with someone with little experience starting at NCAR remotely.

As for US citizen status, there is no requirement that they be a US citizen.  I do believe that there is a requirement, though, that the work is actually performed within the US.

All that said, since the NCAR job posting, we have received close to 80 job applications.  I feel pretty confident that the hiring committee will have a number of good choices of people willing to move to Boulder.

**Comment by mrocklin** [comment]
That helps.  Thanks for the detailed information @kmpaul !

**Comment by kmpaul** [comment]
You're welcome!
