### ISSUE TITLE
Pangeo + Binder

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#283]
I'm developing some pangeo tutorial content that I'd like to be able to run on either pangeo.pydata.org or mybinder.org. I have a few questions though:

1. Is it possible on the current version of binder to access the `dask-distributed` dashboard? I suspect not since, as far as I can tell, `nbserverproxy` is not configured on the binder jupyterhub instance. I'd be happy using a `LocalCluster` on binder if I could access the dashboard.

2. Down the road, it might be nice to bring dask-kubernetes into the mix. What is the road map for this? There are helm charts for each so would think there could be a pangeo-binder chart that enables both at some point?

cc @mrocklin, @yuvipanda, @choldgraf

**Comment by choldgraf** [comment]
Not sure if this answers your question totally, but you *can* use nbserverproxy within Binder. For example, the [r binder repositoriy](https://github.com/binder-examples/r) uses nbserverproxy to serve RStudio. It looks like [nbserverproxy is installed whenever and R buildpack is triggered](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/r.py#L192) so maybe you could do the same with a postBuild script?

**Comment by rsignell-usgs** [comment]
@jhamman, Here's an example: https://github.com/oschuett/appmode/blob/master/binder/postBuild

**Comment by mrocklin** [comment]
See item 2 here:
http://dask-kubernetes.readthedocs.io/en/latest/#configuration

Although these configuration names have changed a bit in master.  You might
want to look at these two links:

   -


   -

   https://github.com/dask/distributed/blob/93c6c1126806566db90e9cd57cbe1e1e4c22e40d/distributed/distributed.yaml#L70


   -

   http://dask.pydata.org/en/latest/configuration.html

**Comment by mrocklin** [comment]
Note also that the [dask-examples](https://github.com/dask/dask-examples) repository does everything necessary to support Dask LocalCluster on Binder

**Comment by jhamman** [comment]
@mrocklin - thanks. I noticed that yesterday. 

As an update on this issue, I'm testing out a pangeo-binder configuration now running on GCP.

- I've deployed binder with a custom pod hook for dask kubernetes
- I have a sample repository that includes a postBuild and `.dask` config: https://github.com/jhamman/xarray_tutorial
- It can be tried out here: [![Binder](http://35.225.89.152/badge.svg)](http://35.225.89.152/v2/gh/jhamman/xarray_tutorial/master)

**Comment by mrocklin** [comment]
My *guess* is that Kubernetes populates those automatically if the pod has roles to do these sorts of things.  I don't know though.  So are you trying to integrate the Binder service into the existing Pangeo deployment?  FWIW I think that this would be a useful idea.  It would be a nice way to remove us from the software configurability process.

**Comment by jhamman** [comment]
> So are you trying to integrate the Binder service into the existing Pangeo deployment? FWIW I think that this would be a useful idea.

Yes and no. Right now. I have a second cluster running on GCP where I've deployed binderhub and am more or less replicating the pangeo parts of our JupyterHub in the binderhub configs. The binderhub seems to be working just fine. Just a few kinks to work out on the dask-kubernetes part.

> It would be a nice way to remove us from the software configurability process.

Yes, exactly. I am also interested in using this for our use cases / examples. 

----

One other thing I need to figure out is how to tell the dask-workers what image to use. That shouldn't be too hard but for now I'm just using the pangeo worker.

**Comment by mrocklin** [comment]
I wonder if we can reuse the same notebook image, but with different
commands.  I wouldn't be surprised if the image were present in some
environment variable.

**Comment by jhamman** [comment]
@choldgraf - do you have ideas on how to point dask-distributed to the same docker image that the notebook image is running on? Basically, I just need to tell dask the name of the container that is used to run the notebook. I'm currently using binder's GCR option but could switch to dockerhub if that would smooth things out. 

@mrocklin - in dask-kubernetes, we point to a dockerhub image. Is that the only protocol we have available for accessing docker images?

**Comment by mrocklin** [comment]
We point to an image name and tag.  I believe that the local docker can
look at a set of repositories for images.  I believe that this works much
like conda channels.

So we don't give dockerhub any special attention.  This is configured
within the cluster itself.

**Comment by tjcrone** [comment]
Maybe I'm not fully understanding the problem here. The worker image/tag is specified in the worker-template.yaml file. Dask-kubernetes goes to this file because an environment variable is set in the notebook Dockerfile.

**Comment by tjcrone** [comment]
Users can easily point dask-kubernetes to a different worker image by modifying this file. What the user cannot easily do yet, to the best of my knowledge, is choose the notebook image.

**Comment by jhamman** [comment]
@tjcrone - binderhub builds a new image on the fly. I'm just trying to populate the worker template with the name of that image.

I have had a few lightbulb moments in the last few minutes on how this all works. Kubernetes supports GCR just like dockerhub so I just need the image name in some format like: 

```
gcr.io/my_project/image:tag
```
or more concretely:
```
gcr.io/pangeo/pangeo-binderjhamman-2dxarray-5ftutorial-b413c9:e63bd01866fc3099476895166b0350faae1f6b74
```

So my current crux remains. How do I get that image name during the binder deploy process?

**Comment by tjcrone** [comment]
I'm going to try to run through this with my own GCP cluster, and I will let you know what I find out. I tried binderhub on Azure, and because Azure does not support RBAC, it didn't work.

**Comment by tjcrone** [comment]
@jhamman, perhaps another way of doing it would be to prebuild your notebook/worker image and push it to Dockerhub or GCR, and then point to that in your Binder script? And then you could hard code that into the worker-template.yaml? If I remember correctly, you mentioned that Binderhub lets you point to an image rather than use a Dockerfile? This should be way faster for users as well.

**Comment by tjcrone** [comment]
Usually Dockerfiles start with a base image using the FROM directive. You could just place your preferred docker image, that you pushed up to dockerhub, as the only line in your Dockerfile (FROM) because you prebuilt your image with everything needed to run your examples. For version control, you can separate your Dockerfiles from the examples themselves. Lots of ways of doing this.

**Comment by jhamman** [comment]
I've made some recent progress setting up a pangeo/binder thing. I currently need some help working through the (dask)kubernetes permissions from inside my notebook session.

link to live deployment: [![Binder](http://35.185.197.178/badge.svg)](http://35.185.197.178/v2/gh/jhamman/xarray_tutorial/master)

In this environment, we have:
- a worker template file with the image name equal to that of the notebook image
- a handful of environment variables set (mostly dask stuff)

When I run:

```Python
from dask.distributed import Client
from dask_kubernetes import KubeCluster
cluster = KubeCluster.from_yaml('./worker-template.yaml')
```

I get the following error:

```Python-traceback
---------------------------------------------------------------------------
ConfigException                           Traceback (most recent call last)
/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in __init__(self, pod_template, name, namespace, n_workers, host, port, env, **kwargs)
    169         try:
--> 170             kubernetes.config.load_incluster_config()
    171         except kubernetes.config.ConfigException:

/srv/conda/lib/python3.6/site-packages/kubernetes/config/incluster_config.py in load_incluster_config()
     92     InClusterConfigLoader(token_filename=SERVICE_TOKEN_FILENAME,
---> 93                           cert_filename=SERVICE_CERT_FILENAME).load_and_set()

/srv/conda/lib/python3.6/site-packages/kubernetes/config/incluster_config.py in load_and_set(self)
     44     def load_and_set(self):
---> 45         self._load_config()
     46         self._set_config()

/srv/conda/lib/python3.6/site-packages/kubernetes/config/incluster_config.py in _load_config(self)
     61         if not os.path.isfile(self._token_filename):
---> 62             raise ConfigException("Service token file does not exists.")
     63 

ConfigException: Service token file does not exists.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-1594e1b0625c> in <module>()
      1 from dask.distributed import Client
      2 from dask_kubernetes import KubeCluster
----> 3 cluster = KubeCluster.from_yaml('./worker-template.yaml')
      4 cluster

/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in from_yaml(cls, yaml_path, **kwargs)
    265         with open(yaml_path) as f:
    266             d = yaml.safe_load(f)
--> 267             return cls.from_dict(d, **kwargs)
    268 
    269     @property

/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in from_dict(cls, pod_spec, **kwargs)
    230         KubeCluster.from_yaml
    231         """
--> 232         return cls(make_pod_from_dict(pod_spec), **kwargs)
    233 
    234     @classmethod

/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in __init__(self, pod_template, name, namespace, n_workers, host, port, env, **kwargs)
    170             kubernetes.config.load_incluster_config()
    171         except kubernetes.config.ConfigException:
--> 172             kubernetes.config.load_kube_config()
    173 
    174         self.core_api = kubernetes.client.CoreV1Api()

/srv/conda/lib/python3.6/site-packages/kubernetes/config/kube_config.py in load_kube_config(config_file, context, client_configuration, persist_config)
    468     loader = _get_kube_config_loader_for_yaml_file(
    469         config_file, active_context=context,
--> 470         config_persister=config_persister)
    471     if client_configuration is None:
    472         config = type.__call__(Configuration)

/srv/conda/lib/python3.6/site-packages/kubernetes/config/kube_config.py in _get_kube_config_loader_for_yaml_file(filename, **kwargs)
    425 
    426 def _get_kube_config_loader_for_yaml_file(filename, **kwargs):
--> 427     with open(filename) as f:
    428         return KubeConfigLoader(
    429             config_dict=yaml.load(f),

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.kube/config'
```

So I can tell I'm missing some Kubernetes configuration components. I am looking for pointers on:

- how we pass the information about the kubernetes cluster to notebook images in pangeo
- how this should be done in the binder context

A few other links for completeness:
- repo for example above: https://github.com/jhamman/xarray_tutorial
- repo for binder deployment: https://github.com/jhamman/pangeo_binder

cc @tjcrone, @jacobtomlinson, @betatim, @choldgraf, and @yuvipanda

**Comment by betatim** [comment]
The idea of pushing your image to dockerhub and then putting that name into your worker template sounds like a good idea. Even though you already have your solution.

We recently created some examples of how to use `repo2docker` to build your repo's image as part of your CI and then push it to dockerhub. The original motivation was to have tests that check your repo still works with Binder, but might be useful for this usecase as well.

**Comment by jhamman** [comment]
Thanks @betatim. Right, at this time I'm pushing the image to GCR but could swap out with dockerhub later on. The sticking point at the moment is initializing the dask kubernetes cluster within a binder notebook.

**Comment by mrocklin** [comment]
Is this resolved?

**Comment by jhamman** [comment]
Yes, it sure is! Closing with the following references:

- http://binder.pangeo.io/
- https://pangeo-binder.readthedocs.io/en/latest/
- https://github.com/pangeo-data/pangeo-binder
