### ISSUE TITLE
feedback on sphinx site

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#29]
I have a skeleton of a sphinx site set up here:
https://pangeo-data.github.io/pangeo/

Right now the CSS is not working...a subdirectory issue I think. Once that is resolved, we can use this issue to give feedback and discuss how we actually want the site to look.

**Comment by rabernat** [comment]
CSS issue is fixed.

**Comment by jhamman** [comment]
Should we add a tab on the https://pangeo-data.github.io site that points to this documentation? What else do we want to have in the documentation before we publicize it?
