### ISSUE TITLE
Frictionless data packages

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#296]
I’m sitting with @daniek at the earthcube meeting. 

I’m learning that some earthcube projects are using open source data packaging format called “frictionless” to distribute datasets. It would be great if we could easily read these from Pangeo. 

https://frictionlessdata.io/software/

Cc @ashepherd

**Comment by martindurant** [comment]
In case anyone is interested, Intake does off the concept of data packages also: https://intake.readthedocs.io/en/latest/data-packages.html
