### ISSUE TITLE
integrate intake data catalog into sphinx site

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#301]
We would like to automatically list the datasets on the intake catalog on our new website:
http://pangeo-data.org/data.html

This should be pretty straightforward...we just have to parse the `catalog.yaml` file.

xref #39

**Comment by martindurant** [comment]
Just noticed this because of the stale notification.
Given that Intake already parses such yaml files, generating any list would be easy. What didyou have in mind, @rabernat ?
