### ISSUE TITLE
Setup call to present Python framework for CDS at ECMWF

### ISSUE THREAD

**Issue by StephanSiemen** [pangeo-data/pangeo#302]
ECMWF to setup call to 
- Give overview of Copernicus Climate Store (CDS)
- Present ideas behind CDS toolbox and use of xarray and development of xarray_grib
- Present Metview-Python framework and use of xarray

**Comment by jhamman** [comment]
Either day works for me.

**Comment by jacobtomlinson** [comment]
I'm afraid I can't do either but @niallrobinson may be able to.

**Comment by StephanSiemen** [comment]
Unfortunately, the earliest we can do is the 20th :-( I hope to catch tomorrow a member of the CDS team to put some suggestions to you. Keep you posted ...

**Comment by rabernat** [comment]
Ok, what about 10:00 US EST, 16:00 Eurotime, on June 20?

**Comment by rabernat** [comment]
@StephanSiemen you have not responded to my latest time proposal (which is in 20 minutes). Is this going forward or not?

**Comment by StephanSiemen** [comment]
Hi @rabernat,
sorry only just saw your last two messages. Only back in office today and not sure where the updates went ... :-( **So no call today!** Sorry.

We discussed earlier today the CDS call, and our suggestion for the call is next Wednesday 27th at 16:00 BST (10:00 EST). Does this sound okay to all?

**Comment by StephanSiemen** [comment]
Unfortunately, we have to move this call to **Tuesday the 3 July 16:00 BST (10:00 EST)**. Sorry for the short notice.

**Comment by rabernat** [comment]
Ok, I can confirm that the July 3 time works for me. Others?

**Comment by mrocklin** [comment]
I should be around then

**Comment by fmaussion** [comment]
I'm happy to join - not sure if I can contribute much but I can be a silent (and curious ;) listener

**Comment by jhamman** [comment]
I should be able to join then too. ☕️ will be required.

**Comment by StephanSiemen** [comment]
Thank you all for confirming the date. 

On a different note, ECMWF is also organising a follow-up workshop, to the one we hosted last year, on Python frameworks in EarthSystem Sciences. Hope to see many of you there:
  https://www.ecmwf.int/en/learning/workshops/2018-workshop-developing-python-frameworks-earth-system-sciences

**Comment by StephanSiemen** [comment]
We set up a call on Bluejeans (Meeting ID 224 857 675) for later. To join please visit the meeting URL:   

    https://bluejeans.com/224857675 

Or dial one of the following numbers:
+1.408.317.9254 (USA)
+32.3.808.4256 (Belgium (Antwerp))
+33.4.84.80.12.56 (France (Southeast France))
+33.1.8626.0562 (Paris, France)
+49.69.255.114411 (Germany (Frankfurt, German))
+49.32.221.091256 (Germany (National, German))
+39.05.104.20256 (Italy (Bologna))
+47.2.160.1825 (Norway (Oslo))
+46.40.66.88256 (Sweden (Malmo))
+44.203.608.5256 (UK (London))

**Comment by rabernat** [comment]
I have logged in to the bluejeans meeting.

**Comment by fmaussion** [comment]
There was a mistake in the time announced by @StephanSiemen above: 16:00 BST is 11:00 EST, not 10:00 ...

**Comment by mrocklin** [comment]
OK, folks will reconvene then

**Comment by StephanSiemen** [comment]
Was nice talking to you all today! sorry for the confusion on the starting date :-(

I close this issue and we can open others when required ...
