### ISSUE TITLE
Hello from Seoul National University.

### ISSUE THREAD

**Issue by kwangwoog** [pangeo-data/pangeo#303]
Hi all,

My name is Kwangwoog, Jung.

I am candidate of Ph.D in School of Earth and Environmental Science, Seoul National University 

and my major is physical oceanography.

My research topic is acceleration of numerical ocean modelling with GPU computing. 

I am also technical architect and engineer of big IT company in republic of KOREA.

I have interest in application of informational technology like HPC, GPU, cloud, bigdata into geoscience and numerical modelling.

I want to have good relation with members of this comunity and share member's idea. 

I will be very happy if I can contribute something to this comunity.

My email address: next7885@snu.ac.kr

Best regards.

**Comment by rsignell-usgs** [comment]
@kwangwoog, good to see you here!   I read with great interest your discussion paper on [running ocean models on the commercial cloud using enhanced networking](https://www.geosci-model-dev-discuss.net/gmd-2017-270/), where you get the same performance as your HPC cluster with InfiniBand.  

Has your group had any experience with cloud-optimized data storage (e.g. zarr or other)?

**Comment by kwangwoog** [comment]
@rsignell, nice meet you here! and thanks for inviting me and reading my research paper.
I also vey happy to join pangeo and wanna contribute something to this community.
I have some experience in big data projects but no experince like zarr.
But I will research and find something to related topic like cloud-optimized data storage.
Best regards.
