### ISSUE TITLE
Draft Program for 2018 Developers workshop

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#306]
@rabernat and I are using this issue to jot down a draft program for the 2018 developers workshop in Boulder (Aug 13 - 15).

#### Monday August 13, 2018
*Science applications*

- All day - Talks from scientists using Pangeo and more.

#### Tuesday August 14, 2018
*Technical Architecture*

- Morning - talks from technical developers. Ask UNIDATA folks interested in cloud optimized data stores to join.
- Afternoon - breakout sessions to discuss technical development horizons. 

#### Wednesday August 15, 2018
*No program. Hack!*

**Comment by rabernat** [comment]
Looks good Joe!

We overlap on Tuesday and Wednesday with the North America Hail Workshop: https://www.mmm.ucar.edu/north-american-hail-workshop
The rationale for having science talks on Monday is to allow some of those folks (e.g. @chiaral) to attend the Pangeo meeting.

xref #199

**Comment by auraoupa** [comment]
Hi developpers and users of Pangeo !
@adeajayi-kunle and I are working with @lesommer (resp. as PHD student and Engineer) in Grenoble and are coming to the workshop at Boulder. Our first objective with Pangeo would be to efficiently implement some spatial filtering that can be applied on our highest resolution simulation NATL60.
I was wondering : is there any vital prerequisite for this workshop for us to work on before coming ?
Thanks,
See you next month !
Aurélie Albert

**Comment by jgerardsimcock** [comment]
Is there any plan to have a jupyterhub developer at the workshop?

**Comment by jhamman** [comment]
The agenda and attendee list is posted here: https://medium.com/pangeo/the-2018-pangeo-developers-workshop-1be359dac33c
