### ISSUE TITLE
blog posts wanted

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#311]
Now that we have launched the [new website](http://pangeo-data.org), and [Medium blog](https://medium.com/pangeo), it would be great to start adding more blog posts about what we are up to. I recently wrote one called [A Step-by-Step Guide to Building a Big Data Portal](https://medium.com/pangeo/step-by-step-guide-to-building-a-big-data-portal-e262af1c2977).

Some examples of posts I would like to see are:
- How is your organization using Pangeo? (e.g. UK Met office - @jacobtomlinson, @niallrobinson; USGS - @rsignell-usgs; OOI - @tjcrone; NCAR - @jhamman, @kmpaul; or *anyone else who is motivated to share*)
- Technical posts on xarray / dask / kubernetes / cloud storage
- Big ideas or visions for the future of Pangeo

If you are interested in doing even a short blog post, we would be very grateful. Just create an account on medium and let me know your username; I'll add you to the http://medium.com/pangeo publication.

**Comment by jhamman** [comment]
I have a technical blog post written describing Pangeo on HPC. Focusing mainly on the dask-jobqueue developments. I will probably wait to publish that until the upcoming dask/distributed/jobqueue release is made.

**Comment by rabernat** [comment]
Anyone besides Joe interested in writing a blog post?

**Comment by niallrobinson** [comment]
We certainly are (sorry we've been quiet)

**Comment by niallrobinson** [comment]
@rabernat email sent about an article a wrote

**Comment by mrocklin** [comment]
I'm inclined to write a short blogpost about activity other communities and domains.  

Quick question, does Medium support markdown?  A google search yielded some old requests for the feature, but nothing definitive.

**Comment by rabernat** [comment]
That's great Matt! @jhamman successfully imported our old blog, which was written in markdown. Perhaps he can explain how that was done.

@niallrobinson has one in the pipeline that we should probably publish first. Niall, I replied to your email request for feedback on that...can you let us know the status?
