### ISSUE TITLE
Jupyter Notebook in Cheyenne

### ISSUE THREAD

**Issue by edougherty32** [pangeo-data/pangeo#314]
Hi everyone, 

I know this has been touched upon [before](https://github.com/pangeo-data/pangeo/issues/108) but I was hoping for a more explicit set of steps to use Pangeo and Dask in Jupyter Notebooks on Cheyenne. I followed instructions given [here](http://pangeo-data.org/setup_guides/hpc.html#) for Pangeo set-up on Cheyenne and that works fine for me. The issue I run into is when I open Jupyter Notebooks (Python version 2, because version 3 just crashes, as previously mentioned) through Cheyenne and try: 

`from dask_jobqueue import PBSCluster` as mentioned [here](http://pangeo-data.org/setup_guides/hpc.html#)

I receive the following error message:

`ImportError: No module named dask_jobqueue`

Here is the following set of steps I took to get to this point (in my user space on Cheyenne):

`source activate pangeo
`
` qsub -I -l select=1:ncpus=4 -l walltime=03:00:00 -q regular`

`source activate pangeo`

`module load python jupyter `

`start-notebook `

From there I follow instructions to launch Jupyter Notebook. 

My questions: why isn't dask being imported, though the pangeo virtual environment is active? Do I need to install the kernel before doing this? I.e., 

`python -m ipykernel install - ...`

Thanks!

**Comment by jhamman** [comment]
@edougherty32 - thanks for submitting an issue and for sticking with this. I think the main problem I see is that you are calling `module load python jupyter`. This modifies a bunch of stuff in your environment. The other thing that you probably want to change is to replace `start-notebook` with `jupyter lab --no-browser --ip=`hostname` --port=8877`.

**Comment by edougherty32** [comment]
Thanks, @jhamman , that seemed to work! However, I am still running into issues importing certain modules, including matplotlib, cartopy, and netCDF4. Do I need to pip install those modules specifically into the pangeo environment in order to work with those modules in Pangeo? Thanks again!

**Comment by jhamman** [comment]
Yes, from within your pangeo environment, you can do things like:

```
source activate pangeo
...
(pangeo) $ conda install -c conda-forge netcdf4 matplotlib cartopy ...
```

**Comment by edougherty32** [comment]
Great, thanks @jhamman!
