### ISSUE TITLE
No Dask Cluster Workers on Cheyenne

### ISSUE THREAD

**Issue by edougherty32** [pangeo-data/pangeo#315]
Hi all, 

I am having trouble implementing Dask on Cheyenne. I followed instructions from this [site](http://pangeo-data.org/setup_guides/hpc.html) under "Deploy Option 1: Jupyter + Dask Jobqueue". Specifically, when I run the code in this section, below "Launch Dask with job-queue" and type:

`cluster`
I get the following message:
`VBox(children=(HTML(value='<h2>PBSCluster</h2>'), HBox(children=(HTML(value='\n<div>\n  <style scoped>\n    .d…`

typing:

`client`

results in the following message:
```
Client
Scheduler: tcp://10.148.9.33:57475
Dashboard: http://10.148.9.33:40536/status
Cluster

Workers: 0
Cores: 0
Memory: 0 B
```
Somehow it seems that there are no clusters or memory when I try to use dask_jobqueue on Cheyenne. I initially had the problem that when entering

`cluster`

I got an error message that said:

`ImportError: No ipywidget. `

So I conda installed that module and that resolved the import error. 

Does anyone have suggestions as to why using dask_jobqueue does not result in any workers, cores, or memory? Thanks!

**Comment by jhamman** [comment]
@edougherty32 - when you run `cluster.start_workers(10)`, dask_jobqueue submits a bunch of PBS jobs using `qsub` scripts. You can check on the status of these jobs on the command line using `qstat`. The time it takes to get workers through the queue will depend on how busy the queue is.

**Comment by edougherty32** [comment]
Thanks @jhamman! In the case where workers aren't loaded, does it time out if the queue is too busy?

**Comment by jhamman** [comment]
No, without any workers, dask will just wait until workers come online. In my experience, this usually just takes a few minutes but could take longer depending on how busy the system is.

**Comment by edougherty32** [comment]
Thanks @jhamman!

**Comment by jhamman** [comment]
@edoddridge - @rabernat has a good point. If you wouldn't mind summarizing the few nuggets that you think are missing from our HPC docs, I'd be happy to make the appropriate changes.

**Comment by edougherty32** [comment]
Sure, thing @jhamman! Here are a couple things that could be added to the HPC docs:

When deploying dask-jobqueue:
- Wait for a few minutes for Dask workers to appear (it will take shorter or longer, depending on how busy the queue is)
- Check their status by `qstat -u USERNAME`
- Can also type `client` in Jupyter Notebook to see the status of the workers
- Once all the workers appear, dask-queue is in operation

To install additional Python packages:
 `Source activate pangeo`
`conda install -c conda-forge netcdf4 matplotlib cartopy...`

Thanks for being willing to update the docs!

**Comment by filippo82** [comment]
Hi all,

I also get 

```
VBox(children=(HTML(value='<h2>PBSCluster</h2>'), HBox(children=(HTML(value='\n<div>\n <style scoped>\n .d…
```
when typing cluster. That doesn't seem correct. Do you know why that happens?

Thank you.

**Comment by mrocklin** [comment]
It's a sign that `ipywidgets` isn't installed correctly.  I also get this often when I use JupyterLab.  There is probably some JuptyerLab + ipywidgets documentation that explains how to get past this.  if you find a good link that solves your problems could I ask you to report it here?

**Comment by filippo82** [comment]
Hi @mrocklin! So, the solution is/should be [here](https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension). It now works for me. I had to run this `command`:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
However, when I did it, JupyterLab was still open and in the documentation (in the link) it states that `If you install this extension while JupyterLab is running, you will need to refresh the page or restart JupyterLab before the changes take effect`. Then I closed JupyterLab (also closed the interactive job on the cluster) and did a `jupyter lab clean` just to be sure (stated in the link too). Attached here you can see the widget currently working.

![LSFCluster](https://user-images.githubusercontent.com/5595364/64039136-3f3d7c00-cb5a-11e9-9389-894204e22551.png)

Cheers!

P.S. Just in case, this is the environment.yml file I used:
```
name: dask_on_euler
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  - jupyterlab
  - dask
  - dask-jobqueue
  - bokeh
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - jupyter-server-proxy
  - nodejs
  - pip:
    - dask_labextension
```
