### ISSUE TITLE
what about conda-pack for distributing environments to workers

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#316]
I just learned about conda-pack via twitter:
https://conda.github.io/conda-pack/

> conda-pack is a command line tool for creating relocatable conda environments. This is useful for deploying code in a consistent environment, potentially in a location where python/conda isn’t already installed.

Maybe this could solve our problems with notebook / worker environment consistency (e.g. pangeo-data/helm-chart#39). Could we make dask-kubernetes package the environment from which it was launched on-the-fly and then install it on all of the workers using conda-pack?

That way we would only need a very generic docker image for the worker.

cc @mrocklin, @jcrist

**Comment by mrocklin** [comment]
Yes, something like this is possible, though we would need an efficient mechanism to distribute the environment.  Our notebook environment is currently something like 4GB.  At 100MB/s this will take 40s to transfer after a worker is started.  If we want to start up many at the same time (say we go from zero to 20 workers) then this will take a long while before any activity happens.

There was a short twitter conversation about this: https://twitter.com/mrocklin/status/1007230795038232578

**Comment by mrocklin** [comment]
So yes, this is something that could happen, but it would require some design and effort to make efficient and user-friendly.  That being said, it's in scope for Anaconda devs to work on under the NSF funding, so we can pursue this if it's a good direction.

**Comment by jcrist** [comment]
> Our notebook environment is currently something like 4GB

As a data point, I tried building and packing just the worker environment from https://github.com/pangeo-data/helm-chart/blob/master/docker-images/worker/Dockerfile, and that came in at 246 MB. This took ~50s to package.

**Comment by mrocklin** [comment]
This is both because the worker environments are smaller and because I've
been considering the uncompressed size (although this might not be correct).
