### ISSUE TITLE
Accessing NetCDF files from object store using http byte range requests

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#324]
Just in case it's of interest to Pangeo folks, I discovered that you can use NetCDF-Java's ToolsUI to explore NetCDF files in object storage.  For example, you can browse the National Water Model datasets being updated on AWS as part of the NOAA Big Data Project by simply opening URLs like this:
https://noaa-nwm-pds.s3.amazonaws.com/nwm.20180623/forcing_short_range/nwm.t00z.short_range.forcing.f001.conus.nc
![2018-06-23_0-23-38](https://user-images.githubusercontent.com/1872600/41976199-7f71d3e2-79ea-11e8-8b52-465c19ee38cf.png)

This works because of https://www.unidata.ucar.edu/software/thredds/v4.6/netcdf-java/javadoc/ucar/unidata/io/http/HTTPRandomAccessFile.html

**Comment by martindurant** [comment]
If only that functionality were in the C/python library! The file-like class looks a lot like [dask's](https://github.com/dask/dask/blob/master/dask/bytes/http.py#L70).

**Comment by dopplershift** [comment]
The closest you can get is download the full file into an in-memory buffer, which netcdf-c can read from.

**Comment by martindurant** [comment]
@dopplershift , to be sure: pangeo has had some success using gcsfs-fuse to "view" remote files as if they were local, for netcdf to be able to read them.
