### ISSUE TITLE
Raise your hand if you'll be attending the AGU Fall Meeting in New Orleans

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#33]
I'd like to coordinate a Pangeo happy hour during the AGU fall meeting. I'm thinking of Wednesday evening following ["New Approaches to Analyze Big Geoscientific Data Sets"](https://agu.confex.com/agu/fm17/meetingapp.cgi/Session/26340) session. Please give a 👍  if you are going to be at AGU and are interested in a happy hour. Feel free to use this issue to bring up other relevant AGU topics (e.g. talks, meetings, etc.).

**Comment by niallrobinson** [comment]
>  Feel free to use this issue to bring up other relevant AGU topics (e.g. talks, meetings, etc.).
I'm doing a [talk this afternoon](https://agu.confex.com/agu/fm17/meetingapp.cgi/Paper/240197) which is covering Dask+Iris for distributed analysis in the cloud. I've come all the way for the UK Met Office (!) - it would be nice to get to know you guys while I'm here and hear more about the pangeo project in general.

**Comment by jgerardsimcock** [comment]
Did we get a confirmed time as to when/where we'll be meeting for the happy hour?

**Comment by jhamman** [comment]
> Did we get a confirmed time as to when/where we'll be meeting for the happy hour?

We're going to try [Capdeville](https://www.cnola.com) starting at 5:30 PM.

ping @jgerardsimcock, @mrocklin, @brian-rose, @spencerahill, @NicWayand, @colingannon, @mcgibbon, @brews, @frode, @darothen, @niallrobinson , and others.

Also, come see @mrocklin's poster at 10:45 this morning.

**Comment by spencerahill** [comment]
Shoot, double booked myself.  Sorry I can't make it!  Hopefully will run into some of you otherwise by the end of the week.

**Comment by darothen-cc** [comment]
Thanks so much for organizing @jhamman. Unfortunately I had to cancel my AGU trip at the last minute... looking forward to seeing people at AMS, though!
