### ISSUE TITLE
Cannot start server on pangeo.pydata.org

### ISSUE THREAD

**Issue by JiaweiZhuang** [pangeo-data/pangeo#330]
I've been having trouble with pangeo.pydata.org since yesterday. 

This loading page hangs for much longer than it used to be (> 5 min):

<img width="443" alt="screen shot 2018-07-04 at 7 01 48 pm" src="https://user-images.githubusercontent.com/25473287/42295905-38c3b428-7fbd-11e8-972b-fb3a1a32597f.png">

Then finally leads to this error:
<img width="504" alt="screen shot 2018-07-04 at 7 04 43 pm" src="https://user-images.githubusercontent.com/25473287/42295916-4f4ec5f2-7fbd-11e8-93ee-8ce11cb7b7f3.png">

Not sure if this is related to #287.

**Comment by martindurant** [comment]
Agreed, seeing this too. Looking at kuberenetes, the server pod is up and jupyter is running, don't know why the hub proxy isn't passing through. The hub pod is recording TimeoutError and nothing more informative. I don't see anything specific amiss.

**Comment by rabernat** [comment]
I just took my usual steps to fix this. First I ran
```
$ helm history
```
to get the current installed helm chart version. This is what I saw
```
REVISION	UPDATED                 	STATUS         	CHART                	DESCRIPTION      
1       	Fri May 18 21:33:46 2018	SUPERSEDED     	pangeo-v0.1.1-a14d55b	Install complete 
2       	Sat May 19 18:17:32 2018	SUPERSEDED     	pangeo-v0.1.1        	Upgrade complete 
3       	Sat May 19 18:44:24 2018	SUPERSEDED     	pangeo-v0.1.1        	Upgrade complete 
4       	Sat May 19 18:53:27 2018	SUPERSEDED     	pangeo-v0.1.1        	Upgrade complete 
5       	Sat May 19 18:57:31 2018	SUPERSEDED     	pangeo-v0.1.1-a14d55b	Rollback to 1    
6       	Wed May 23 08:28:40 2018	PENDING_UPGRADE	pangeo-v0.1.1        	Preparing upgrade
7       	Wed May 23 08:34:03 2018	PENDING_UPGRADE	pangeo-v0.1.1        	Preparing upgrade
8       	Wed May 23 08:39:43 2018	SUPERSEDED     	pangeo-v0.1.1        	Upgrade complete 
9       	Wed May 23 08:46:09 2018	SUPERSEDED     	pangeo-v0.1.1-a14d55b	Rollback to 1    
10      	Wed Jun  6 10:48:05 2018	SUPERSEDED     	pangeo-v0.1.1-a14d55b	Upgrade complete 
11      	Wed Jun 13 16:27:58 2018	SUPERSEDED     	pangeo-v0.1.1        	Upgrade complete 
12      	Wed Jun 13 20:13:31 2018	SUPERSEDED     	pangeo-v0.1.1        	Upgrade complete 
13      	Sun Jun 17 22:56:11 2018	SUPERSEDED     	pangeo-v0.1.1-85dc5c9	Upgrade complete 
14      	Tue Jun 26 19:00:14 2018	SUPERSEDED     	pangeo-v0.1.1-85dc5c9	Upgrade complete 
15      	Tue Jun 26 19:01:09 2018	SUPERSEDED     	pangeo-v0.1.1-85dc5c9	Upgrade complete 
16      	Tue Jun 26 19:02:50 2018	SUPERSEDED     	pangeo-v0.1.1-85dc5c9	Upgrade complete 
17      	Thu Jun 28 08:50:44 2018	SUPERSEDED     	pangeo-v0.1.1-85dc5c9	Upgrade complete 
18      	Sat Jun 30 14:55:46 2018	DEPLOYED       	pangeo-v0.1.1-85dc5c9	Upgrade complete ```
This told em that the current deployed version is `0.1.1-85dc5c9`.

Then I ran my usual command to restart the cluster
```
helm upgrade --force --recreate-pods jupyter pangeo/pangeo --version=0.1.1-85dc5c9 -f actual-secret-config.yaml  -f jupyter-config.yaml
```

This appears to have resolved the issue for me.

Is anyone else still having problems.

**Comment by tjcrone** [comment]
@rabernat, this fixed the situation for me. Thank you!

So I can help solve this next time, what repo/branch/commit jupyter-config.yaml are you using?

**Comment by rabernat** [comment]
My `jupyter-config.yaml` is exactly what is stored in this repo:
https://github.com/pangeo-data/pangeo/blob/master/gce/jupyter-config.yaml

Anyone else with sufficient credentials to restart the service should not hesitate to try this in the future.
