### ISSUE TITLE
Who's at Scipy?

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#335]
I'll be at Scipy this week. I'm looking forward to seeing/meeting some of you. A few Pangeo things are happening.

- Tomorrow morning (Wednesday) at 11:30a, I will be giving an overview talk on the Pangeo effort, [link](https://scipy2018.scipy.org/ehome/index.php?eventid=299527&tabid=721463&cid=2264594&sessionid=21618394&sessionchoice=1&)
- Tomorrow afternoon (Wednesday) at 1:00p, I will be hosting, with @mrocklin, a Pangeo BOF. [link](https://scipy2018.scipy.org/ehome/index.php?eventid=299527&tabid=721463&cid=2264594&sessionid=23409892&sessionchoice=1&)

Perhaps a trip to a local watering hole will be necessary on Wednesday evening as well. 

cc @ocefpaf, @rsignell-usgs, @mrocklin, @dopplershift, @pelson, @choldgraf, @SylvainCorlay, @philippjfr

**Comment by ocefpaf** [comment]
@jhamman are you organizing a BoF or something? I guess there are still slots available for those.

**Comment by philippjfr** [comment]
Unfortunately I'll be missing this years SciPy but @jbednar and @jlstevens will be in attendance.

**Comment by martindurant** [comment]
I am here, attending the conference probably Wednesday, Friday and Saturday.

**Comment by jhamman** [comment]
@ocefpaf - yes, tomorrow afternoon at 1p we have a Pangeo BOF planned. Plan is to facilitate short/informal presentations and conversation around Pangeo's current efforts.

**Comment by mrocklin** [comment]
If would be great if people here would come and present for a few minutes
on their current work, what works well, what current pain points are, etc..

**Comment by jbednar** [comment]
I'd love to come, but I'm running a BoF next door at the same time.  Maybe @jlstevens could spend some of his time in each.

**Comment by choldgraf** [comment]
Me! Arriving in 4 hours :-)

**Comment by dopplershift** [comment]
I’m here though Sunday.

**Comment by shoyer** [comment]
I'm arriving late tonight and will be at SciPy through Sunday afternoon.

I'm giving a 3 minute update on xarray at the SciPy tools session on Wednesday, and booked the afternoon break on Friday (3-3:30) for xarray at the open source table.

**Comment by rsignell-usgs** [comment]
I just arrived and I'm here through Sunday.  I'll attend the BOF tomorrow, and I'm looking forward to trying out S3NetCDF and TileDB during the sprints this weekend.

**Comment by jlstevens** [comment]
> Maybe @jlstevens could spend some of his time in each.

Sure!

**Comment by dopplershift** [comment]
@shoyer Definitely interested in that topic.

**Comment by SylvainCorlay** [comment]
Hi all,

Unfortunately I will only come in on Thursday morning so I will miss the
PanGeo talk.

Looking forward to seeing everyone!

Cheers,

Sylvain

**Comment by jacobtomlinson** [comment]
We had some Pangeo stickers made! We'll bring them to the meeting in August!

**Comment by niallrobinson** [comment]
Spot the sticker!

![20180716_150300](https://user-images.githubusercontent.com/2979205/42762967-a24925e0-8909-11e8-901a-cc5d38afecdb.jpg)

**Comment by rsignell-usgs** [comment]
Nice recorded [Scipy 2018 talk on Pangeo](https://www.youtube.com/watch?v=2rgD5AJsAbE) by @jhamman
