### ISSUE TITLE
verde: processing and gridding spatial data using Green's functions

### ISSUE THREAD

**Issue by shoyer** [pangeo-data/pangeo#336]
I just saw a SciPy lightning talk from @leouieda on verde:
https://www.fatiando.org/verde
https://github.com/fatiando/verde

It looks like a promising project that could be relevant to other Pangeo users. It outputs gridded datasets using xarray and they are considering integrating with dask for parallel computation.

Copied from their docs page:

![image](https://user-images.githubusercontent.com/1217238/42664040-44df05ae-85fe-11e8-91ce-fdfcd505eecb.png)

## About

Verde is a Python library for processing spatial data (bathymetry, geophysics surveys, etc) and interpolating it on regular grids (i.e., gridding).

Most gridding methods in Verde use a Green’s functions approach. A linear model is estimated based on the input data and then used to predict data on a regular grid (or in a scatter, a profile, as derivatives). The models are Green’s functions from (mostly) elastic deformation theory. This approach is very similar to machine learning so we implement gridder classes that are similar to scikit-learn regression classes. The API is not 100% compatible but it should look familiar to those with some scikit-learn experience.

Advantages of using Green’s functions include:

- Easily apply weights to data points. This is a linear least-squares problem.
- Perform model selection using established machine learning techniques, like k-fold or holdout cross-validation.
- The estimated model can be easily stored for later use, like spherical-harmonic coefficients are used in gravimetry.

## Project goals
Provide a machine-learning inspired interface for Green’s functions gridding of spatial data
- Integration with the Scipy stack: numpy, pandas (for xyz data), and xarray (for grids)
- Include functions for common processing and data preparation tasks, like blocked means and medians
- Support for gridding scalar and vector data (like wind speed or GPS velocities)
- Support for both Cartesian and geographic coordinates

**Comment by leouieda** [comment]
@shoyer I'm looking forward to incorporating more dask into the project and trying it out on a pangeo instance
