### ISSUE TITLE
Custom deployment to GCP: Failed to start your server.

### ISSUE THREAD

**Issue by samanvp** [pangeo-data/pangeo#337]
I followed [guideline](http://pangeo-data.org/setup_guides/cloud.html) to bring up a custom deployment to GCP. Everything goes as expected (BTW, thanks for clear and detailed steps) until I authenticate and try to "Start my Server". It shows the `Your server is starting up. You will be redirected automatically when it's ready for you.` for a few minutes and then fails with this error message:

> 500 : Internal Server Error
> Failed to start your server. Please contact admin.
> You can try restarting your server from the home page.

In GCP Console I see the following error:
```
Error: ImagePullBackOff
Failed to pull image "pangeo/notebook:ce2f7f5": rpc error: code = Unknown desc = Error response from daemon: manifest for pangeo/notebook:ce2f7f5 not found
Error: ErrImagePull	Failed
pulling image "pangeo/notebook:ce2f7f5"
```

I am wondering what might be causing this?

Thanks for your help.

**Comment by jgerardsimcock** [comment]
[Docker hub tags for pangeo](https://hub.docker.com/r/pangeo/notebook/tags/) don't show that commit. What about deploying from a different tag?

**Comment by samanvp** [comment]
I found it:
In [Upgrade Cluster](http://pangeo-data.org/setup_guides/cloud.html#upgrade-cluster) section one can update the helm chart version. For some reason [some the versions](https://pangeo-data.github.io/helm-chart/) are missing the corresponding [Docker hub tags for pangeo](https://hub.docker.com/r/pangeo/notebook/tags/). 

Make sure select a version that also has a tag.

**Comment by kaipak** [comment]
I am also running into issues with the latest Helm chart releases and had to revert to earlier versions. I see that a new release just came out (v0.1.1-2d5c8b4) and so far, that seems to start up without issue.
