### ISSUE TITLE
dask worker name is now 'jovyan

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#338]
My dask worker pod names used to start with `dask-rsignell-usgs`, but now they start with `dask-jovyan`:
```
$ kubectl get pods -n esip-dev | more
NAME                          READY     STATUS      RESTARTS   AGE
dask-jovyan-12c9d5d2-e92jll   0/1       Completed   0          50m
dask-jovyan-12c9d5d2-ezdntk   0/1       Completed   0          50m
dask-jovyan-7028fc06-72jz44   0/1       Completed   0          4h
dask-jovyan-7028fc06-7cqrtz   0/1       Completed   0          4h
dask-jovyan-7028fc06-7lp9md   0/1       Completed   0          4h
dask-jovyan-7028fc06-7xrxbd   0/1       Completed   0          4h
dask-jovyan-c4d7dec8-alj87z   1/1       Running     0          4m
dask-jovyan-c4d7dec8-axbt2v   1/1       Running     0          4m
hub-6888d66557-r69zq          1/1       Running     0          1h
jupyter-rsignell-2dusgs       1/1       Running     0          6m
proxy-749c488cd4-gpg6f        1/1       Running     0          1h
```
I guess this happened when I updated the helm chart at some point.  I'm currently at:
```
esip-dev-pangeo         57              Wed Jul 18 17:32:44 2018        DEPLOYED        pangeo-v0.1.1-ce2f7f5        esip-dev
```
What is confusing is that in the container, I see environment variables that would seem to specify the dask worker name with my juptyerhub_user name. 
```
jovyan@jupyter-rsignell-2dusgs:~$ env | grep USER
DASK_KUBERNETES_WORKER_NAME=dask-{JUPYTERHUB_USER}-{uuid}
NB_USER=jovyan
DASKERNETES_WORKER_NAME=dask-{JUPYTERHUB_USER}-{uuid}
JUPYTERHUB_USER=rsignell-usgs
```
Any ideas?

**Comment by mrocklin** [comment]
The dask-specific environment varibles are somewhat old.  Dask went through
a breaking change with configuration in 0.18.0.  See
http://matthewrocklin.com/blog/work/2018/06/14/dask-0.18.0

Full configuration docs: http://dask.pydata.org/en/latest/configuration.html

Dask-kubernetes specific:
http://dask-kubernetes.readthedocs.io/en/latest/#configuration

**Comment by rabernat** [comment]
Helm chart `0.1.1-2bd2369`, which I built today, has some issues (e.g. https://github.com/pangeo-data/helm-chart/issues/48#issuecomment-406005232). I would not recommend running it.

How are you deploying? I recommend sticking with `0.1.1-85dc5c9` for now until these issues have been resolved.

**Comment by rsignell-usgs** [comment]
@mrocklin , awesome.   I edited my `~/.config/dask/kubernetes.yaml` to contain these lines:
```
kubernetes:
  name: "dask-{JUPYTERHUB_USER}-{uuid}"
```
and now I've got:
```
(IOOS3) rsignell@gamone:~/github/pangeo/aws> kubectl get pods -n esip-dev 

NAME                                 READY     STATUS      RESTARTS   AGE
dask-rsignell-usgs-eae38138-er6t9b   1/1       Running     0          1m
```

@rabernat, I'm upgrading using:
```
 helm upgrade esip-dev-pangeo pangeo/pangeo -f jupyter-config.yaml -f secret-config.yaml --version=v0.1.1-ce2f7f5
```

**Comment by jacobtomlinson** [comment]
This was originally being set by an environment variable in dask-kubernetes when it was called daskernetes (`DASKERNETES_WORKER_NAME: "dask-{JUPYTERHUB_USER}-{uuid}"`).

Some changes went in a while back to get it to use the dask config instead. Hence the breaking change. You may want to check your `jupyter-config.yaml` and remove `DASKERNETES_WORKER_NAME` if it's still in there, just to be tidy 😄.
