### ISSUE TITLE
CMIP6 Model Analysis Workshop

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#339]
https://cmip6workshop19.sciencesconf.org/

> CMIP6 MODEL ANALYSIS WORKSHOP
>
> 25-28 March 2019 
>(starting 1 pm Monday March 25 and ending 5 pm Thursday March 28) 
Barcelona Supercomputing Center (BSC), Barcelona (Spain)
The workshop is jointly organized by the WCRP Working Group on Coupled Modelling (WGCM) CMIP Panel and the European Commission Horizon 2020 project PRIMAVERA (PRocess-based climate sIMulation: AdVances in high-resolution modelling and European climate Risk Assessment) and EUCP (European Climate Prediction system)
>
> Following the format of the WCRP CMIP5 model analysis workshop held in 2012, the workshop focus will be on:
>
> - Multi-model CMIP6 analyses and evaluation that take advantage of the large suite of CMIP6 experiments
> -Efforts to connect model development and analysis to identify Earth system model improvements that help reduce systematic biases and/or increase the realism of models
> - Methods for multi-model analysis
> -Climate change impacts
> The workshop will be structured around the three scientific questions:
>
> 1. How does the Earth system respond to forcing?
> 2. What are the origins and consequences of systematic model biases?
> 3. How can we assess future climate change given climate variability, predictability and uncertainty in scenarios.

Abstract submission opens: 15 September 2018
Abstract submission deadline: 15 November 2018
Abstract / Participation acceptance: 15 December 2018

It would be great to have some pangeo presence at this workshop

**Comment by jacobtomlinson** [comment]
This is geographically close to us and we are involved in PRIMAVERA (and CMIP6). So I expect there will be a group of Met Office folk going. 

I'll explore whether we can get some Met Office Pangeo representation.

**Comment by kmpaul** [comment]
Someone from NCAR will go to this.  I'd like to go myself, but I'm checking my calendar.

**Comment by jhamman** [comment]
Reopening as a reminder that the deadline for participation is Dec. 15.

**Comment by jhamman** [comment]
@kmpaul - do you have someone attending this?

**Comment by kmpaul** [comment]
I don't have anyone solidly lined up.  I was planning on going to this myself, but I've spoken with one of the workshop organizers who has told me that it might not be the best fit.  The impression that I get is that this is more scientifically focused, rather than engineering focused.  Do you want to go?
