### ISSUE TITLE
Dask on Cheyenne -- workers killed instantly

### ISSUE THREAD

**Issue by ksulia** [pangeo-data/pangeo#345]
Good morning!  I apologize if this topic has already been addressed, if so, please point me in the right direction!

I have a python code that I am attempting to run in parallel on Cheyenne (have been using pool previously, but still too slow on local machine).  I have followed the instructions on the Dask Cheyenne wiki page exactly (other than account-specific data), and have made it all the way to the end until getting the workers initiated. It seems that both JupyterLab (and notebook) and the Dask interface launch successfully (and am able to run the code in the notebook on 2 processes via pool), but the "add-one-worker.sh" fails (I believe that the workers that are maybe supposed to launch with the initial dask launch fail as well). A worker is initiated, and then is killed after a few seconds.  Attached is an example log file.

Any assistance, guidance, or tips would be appreciated!
[dask-workers.txt](https://github.com/pangeo-data/pangeo/files/2246142/dask-workers.txt)

**Comment by jhamman** [comment]
@ksulia - I'm glad to hear your giving dask a go on Cheyenne. Are you following these instructions: http://pangeo-data.org/setup_guides/hpc.html

The dask-jobqueue approach is likely the best (most stable/common) choice on Cheyenne right now.

**Comment by ksulia** [comment]
@jhamman -- Thank you!  The dask-jobqueue option worked perfectly.

**Comment by jhamman** [comment]
Glad to hear it @ksulia. Okay to close this issue?

**Comment by ksulia** [comment]
@jhamman Yes thank you!
