### ISSUE TITLE
Jupyter Community Workshop Proposal

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#347]
Project Jupyter has an [open call](https://blog.jupyter.org/jupyter-community-workshops-cbd34ac82549) for community workshops. The deadline has been [extended](https://blog.jupyter.org/deadline-extension-jupyter-community-workshops-9ff760d4e66c) through August 6.

> Bloomberg is a long-time partner and supporter of Project Jupyter. Earlier this year Bloomberg announced funding of $120,000 to enable Project Jupyter to host a series of Jupyter Workshops in 2018. These workshops will bring together small groups, approximately 12 to 24 people,) of Jupyter community members and core contributors for high-impact strategic work and community engagement on focused topics.

Individual awards seem to be targeting the $10k-20k range. If anyone is interested in putting together a proposal for a Pangeo-Jupyter meeting, I'd be happy to contribute.

**Comment by rsignell-usgs** [comment]
The [Jupyter Community Workshop for HPC](https://blog.jupyter.org/jupyter-community-workshop-jupyter-for-scientific-user-facilities-and-high-performance-computing-3afa4a990086) seems like worth having a Pangean attend, no, perhaps describing the work on Cheyenne?

**Comment by kmpaul** [comment]
@rsignell-usgs Yes!  I think we need to be there.  I'm trying to get the sysadmins who actually did the work here at NCAR to go.
