### ISSUE TITLE
Custom User Notebook Images on Login

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#348]
Has anyone used the [wrapspawner](https://github.com/jupyterhub/wrapspawner) with jupyterhub? I wonder if this could be leveraged to allow users to choose the single-user image during the login process.

**Comment by tjcrone** [comment]
I changed the title of this issue because I'm not sure it properly described the issue. I think that giving users the ability to choose an image on login should be pretty high priority, and the wrapspawner *might* provide this capability. Has anyone tried it?

**Comment by jacobtomlinson** [comment]
I seem to remember this has been added to `KubeSpawner` a while back. I was waiting for it to make its way upstream before putting some effort it, this may have happened now.

@yuvipanda do you know if this has happened yet?

**Comment by guillaumeeb** [comment]
Using it on an HPC Jupyterhub setup here.

As long as KubeSpawner has a configuration option for specifying single-user image, which [it obviously has](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#module-kubespawner.spawner), WrapSpawner will allow you to specify several images for the user to chose from. 

It is really simple to use, just a few lines in the config file. For pangeo, this could look as this (not sure what docker image is currently used):
```python
c.ProfilesSpawner.profiles = [
   ('Ocean analysis environment', 'ocean-env', 'kubespawner.spawner.KubeSpawner',
      dict(image_spec='pangeo/pangeo-singleuser:latest')),
   ('Satellite image analysis', 'image-env', 'kubespawner.spawner.KubeSpawner',
      dict(image_spec='pangeo/pangeo-singleuser-image:latest'))
   ]
```


However, user won't be able to chose any single-user image, just chose from a predefined list.

**Comment by jacobtomlinson** [comment]
This has been added to KubeSpawner already and you can configure it like this:

```
c.KubeSpawner.profile_list = [{
            'display_name': 'Informatics Lab - Pangeo Notebook v0.4.0',
            'kubespawner_override': {'singleuser_image_spec': 'informaticslab/pangeo-notebook:0.4.0',}
            },{
            'display_name': 'Informatics Lab - Pangeo Notebook v0.3.11',
            'kubespawner_override': {'singleuser_image_spec': 'informaticslab/pangeo-notebook:0.3.11',}
            }]
```

However we are waiting for z2jh 0.7 for it to make it downstream.

**Comment by jhamman** [comment]
Are we really blocked by a full z2jh release? We can use a development version, can't we?

**Comment by jacobtomlinson** [comment]
There seems to have been a bunch of breaking changes and I haven't managed to successfully use the development versions without causing myself headaches.

Perhaps @yuvipanda can comment?

**Comment by yuvipanda** [comment]
Can this be closed now?

**Comment by jhamman** [comment]
@yuvipanda - I don't think so. We know this is possible with KubeSpawner but as far as I know, no one has tried just yet. I know @rabernat is quite interested in seeing this happen so let's leave this open.
