### ISSUE TITLE
access to TACC wrangler

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#35]
I would like to grant those interested access to our allocation on TACC wrangler.

If you already have XSEDE account, just tell me your username.

If not, you need to [create and XSEDE account](https://portal.xsede.org/?p_p_id=58&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&saveLastPath=0&_58_struts_action=%2Flogin%2Fcreate_account).

cc @mrocklin, @jhamman

**Comment by mrocklin** [comment]
I just created an account with the mrocklin username.

**Comment by jhamman** [comment]
Same here. Username is *jhamman*.

**Comment by rabernat** [comment]
I have requested accounts for both of you.

**Comment by mrocklin** [comment]
@rabernat would it be possible to add @pitrou to the wrangler allocation as well?  @pitrou handles most of Dask's networking infrastructure.  He's a good guy to have around when complex problems arise.

**Comment by rabernat** [comment]
Sure! @pitrou would just need to tell me his XSEDE username.

Have you or Joe actually received your access yet?

**Comment by mrocklin** [comment]
Officially yes.  I haven't done anything with it yet though.

**Comment by pitrou** [comment]
Ok, my XSEDE username is `pitrou`.

**Comment by rabernat** [comment]
Done

**Comment by jhamman** [comment]
@rabernat - I have access. Setup an account but nothing more just yet.
