### ISSUE TITLE
Plotting POP (ocean model) output

### ISSUE THREAD

**Issue by mnlevy1981** [pangeo-data/pangeo#351]
I've created a gist that walks through the issue I'm having:

https://gist.github.com/mnlevy1981/ec33c5aa74c27804d5e0a5ac045885b6

To summarize, if I use `xarray` to read a POP history file and then run `DataArray.plot()`, Greenland shows up at the top of the plot because of POP's displaced pole grid. If I use `DataArray.plot.pcolormesh()` then I think `xarray` tries to interpolate across missing values and the resulting plot is a mess. If I use `cartopy`, then I get a big seam of missing values down the middle of the plot because I don't know how to specify that `TLONG` is periodic (there isn't data at `TLONG=0 deg` or `TLONG=360 deg`).

Best case would be if someone could help me figure out why `pcolormesh()` makes such a terrible plot when I specify `x` and `y`, because then I wouldn't even need to import cartopy... though it would probably be good to know how to get rid of the seam in cartopy in case I find myself using that package in the future.

I just noticed that in the markdown sections of the linked gist, I refered to `lat` and `lon` as dimensions rather than `nlat` and `nlon`... hopefully that's not too confusing.

**Comment by ahuang11** [comment]
`How do I tell pcolormesh() that the data is periodic in x?`

You can fix the seam running down the middle with `cartopy.util.add_cyclic_point` https://scitools.org.uk/cartopy/docs/v0.15/cartopy/util/util.html

See https://gist.github.com/darothen/c7560d8d19ffca90024c1f2df4927599 for an example.

**Comment by rabernat** [comment]
Hi @mnlevy1981 -- thanks for reaching out to the pangeo community. We are happy to help you get this problem! It sounds like @ahuang11 may have a solution?

If not, I would really recommend you re-post the same question on the xarray issue tracker, as it is fundamentally an xarray issue:
https://github.com/pydata/xarray/issues

You will have more success there if you can simplify your problem to a **short** code snippet that can easily be cut / pasted by another developer, along with a link to a downloadable file. If others can reproduce your problem easily, they will be more able to help.

**Comment by mnlevy1981** [comment]
@ahuang11 Thanks for pointing out `add_cyclic_point` (I didn't think to use "cyclic" instead of "periodic" in my search terms!) -- unfortunately, it looks like it doesn't play nicely with 2D coordinates?

```
data = ds['SSH'].isel(time=0)
coord = ds.coords['TLONG']
cyclic_data, cyclic_coord = add_cyclic_point(data, coord)
```

leads to

```
ValueError: The coordinate must be 1-dimensional.
```

@rabernat Cool, I'll spend a little more time converting the gist to a slimmed down version in a repository (including a small dataset) and repost to the xarray issue page.

**Comment by ahuang11** [comment]
Maybe relevant resources for 2D coordinates?
https://github.com/SciTools/cartopy/issues/398
http://nbviewer.jupyter.org/gist/pelson/6219116

**Comment by mnlevy1981** [comment]
It took a little bit of playing in cartopy, but rather than trying to force the data to be treated as cyclic, I was able to use the `central_longitude` option of the transformation to move the seam to the edge of plot:

https://github.com/mnlevy1981/cartopy-issue/blob/master/cartopy-example.ipynb

I wouldn't be surprised if I need `central_longitude` to be a different value for the 1 degree resolution POP grid, but `219` seems to do the trick for the 3 degree resolution. Thanks for all the suggestions, I appreciate it!

(Also, my original issue of the initial plot not showing up was due to the missing `%matplotlib inline` magic. Oops.)

**Comment by AJueling** [comment]
If anyone comes across this in the future, here is a small function that adds a cyclic point to 2D POP data as well as the coordinates TLAT and TLONG (works fine for both the dipole 1 degree grid and the tripole 1/10 degree grid):
```
def add_cyclic_POP(da):
    """ add a cyclis point to a 2D POP output field to remove missing data line in cartopy """
    assert 'TLAT' in da.coords
    assert 'TLONG' in da.coords
    lats = np.zeros((len(da.nlat),len(da.nlon)+1))
    lons = np.zeros((len(da.nlat),len(da.nlon)+1))
    data = np.zeros((len(da.nlat),len(da.nlon)+1))
    lats[:,:-1] = da.TLAT
    lons[:,:-1] = da.TLONG
    data[:,:-1] = da.data
    lats[:,-1]  = da.TLAT[:,0]
    lons[:,-1]  = da.TLONG[:,0]
    data[:,-1]  = da.data[:,0]
    dims = ['nlat','nlon']
    new_da = xr.DataArray(data=data, dims=dims, coords={'TLAT':(dims,lats), 'TLONG':(dims,lons)})
    return new_da
```
