### ISSUE TITLE
storage-benchmark updates

### ISSUE THREAD

**Issue by kaipak** [pangeo-data/pangeo#353]
Apologies for lack of updates recently as I've been a bit nomadic since the start of summer. After completing my master's program at Columbia, I moved back to good old Portland, Oregon, went travelling a bit, and spent a lot of time settling back into family life and finding a job. A few weeks ago, I was finally able to put in a significant amount of time into this project.

Some of you may recall back on issue #247 that storage-benchmarks had produced some pretty good results.  Unfortunately, there were some challenges that needed to be hammered out before continuing, as it was proving to be difficult to get reproducible results on a consistent basis:

 ## Issues
1. pangeo.pydata.org has a fair bit of traffic on it and getting required resources to run the benchmarks was proving to be problematic. One of the parameters the benchmarks cycles through is number of Dask workers. During peak usage, it could get quite difficult to get clusters larger than 40 nodes. This resulted in benchmarks waiting and waiting before finally timing out and failing.
2. Resource saving settings on pangeo.pydata.org including 20 minute timeout for Jupyter pods.
3.  Airspeed Velocity shortcomings. On the surface, ASV looks like a great framework to create these benchmarks. It has built-in git commit tracking, automated reports, and a sophisticated set of options for managing results. Unfortunately, there is also some rigidity in ASV that makes it not well suited for gathering IO statistics, and somewhat difficult to coerce it into doing so. Also, ASV records averaged runs and doesn't provide an out-of-the-box way of getting individual results. This is likely not a big deal for producing informal reports, but if we wanted to see error bars, standard deviations, spreads, and other more nuanced statistical data, we'd need to get to individual results.

## Solutions
1. I created my own GCP Pangeo instance and altered several of the settings so that the environment would be more conducive long-running, resource intensive runs. A lot of problems went away just with this move! I have been given access to an AWS account and will be creating a `storage-benchmarks` cluster on there as well. 
2. Very long running benchmarks. We're doing runs on reading/writing terabytes of data so some of the benchmarks can take many minutes if not hours to run. Originally, I thought it would be better to try to combine benchmarks so as to reduce amount of time deploying Dask clusters. This ended up being much more frustrating than anticipated since one problem could mess up an entire run. To combat this, I went much more modular so that each benchmark is its own file and can be run individually. Instead of having gcp_dask and running through all possible backend permutations (netCDF on FUSE, Zarr on GCSFS, Zarr on FUSE, etc.), each separate benchmark will only do one thing (gcp_kubernetes_zarr_read). While I'm losing a bit on having to set up Dask clusters with each run, I gain being able to more consistently produce results. I also found that as long as the Kubernetes cluster is already auto-scaled, getting a Dask cluster of the requested size actually doesn't take that long at all.
3. Hacking ASV. It wasn't really behaving in the way I wanted it to, so I decided to write a Python script to act as a kind of orchestrator for `storage-benchmarks`. `run_benchmarks.py` allows you to kick off jobs using regex and specifying the number of runs that you want. e.g., 
    ```
    $ python run_benchmarks.py -b gcp*read -n 10
    ```
    Will run all GCP read tests 10 times. The script will then scrape the JSON file ASV outputs, and   tidy up the data into a CSV file.  I basically abused the parameters option in ASV to coerce it into outputting individual runs. And now, I can build a history of benchmark runs in tabular form rather than having separate JSON files tied to git commits.

## Next Steps
I've merged all these changes into the main repository for `storage-benchmarks` and everything looks pretty good thus far. I still need to rewrite the Pandas reports to account for all these changes, but since I'm dealing with tabular output now, this shouldn't be a huge issue. Next, I plan on continuing to modularize the other existing tests.

## Questions for you folks
What other tests should I be looking at now? We more or less have the following covered. All read tests are done on some ocean simulation data we have available at Columbia (LLC4320). I am also running tests on random Xarray/Dask datasets.

- netCDF/(POSIX|FUSE) on workstation, kubernetes, HPC
- Zarr on GCSFS/(POSIX|FUSE) on workstation, kubernetes, HPC
- HDS on workstation, kubernetes, HPC. This needs some work but we have some base code in there.

I am working on AWS as I mentioned above. Also, I've been keeping TileDB in the back of my mind as well. You can also check out the README and docs we have on the [repo](https://github.com/pangeo-data/storage-benchmarks).

**Comment by rsignell-usgs** [comment]
@kaipak, the problems you encountered on `pangeo.pydata.org` should no longer exist as cluster autoscaling was (finally) successfully enabled on September 10.   You should have no problems requesting 50 or 100 workers.   Can you confirm?
