### ISSUE TITLE
Brainstorming notes for JupyterLab

### ISSUE THREAD

**Issue by yuvipanda** [pangeo-data/pangeo#355]
# JupyterLab extension ideas

## New file renderers

- multi-dim: we're probably only going to look at metadata, not necessarily full data
    * netCDF
        - lets look at ncview
        - GRID: used for meshes
    * hdf5
    - GRIB, lots of different extensions, sort of a zoo.
- geotiff
    -  ipyleaflet may already do some nice auto-tiling
    -  do native JS viewers exist?  Something may already exist for Cloud Optimized GeoTIFF (COG)
- geojson/shapefile

## Extensions

* ncview server
* gist uploader
- these might have to depend on python nb server extensions
- cluster management
    - ability to launch dask clusters from notebook level GUI
    - awareness of cluster
- Dask's dashboard panes in JupyterLab panes
- 

## Dashboarding

-  Plot.ly Dash and Bokeh Server are nice, but the transition from jupyter notebooks to live server is jarring.  Also design makes other designers unhappy.

## Catalogging

-  Example exists with THREDDS server
-  Left-panel extension exists wit
-  ![](https://raw.githubusercontent.com/eWaterCycle/jupyterlab_thredds/master/jupyterlab_thredds.gif)
-  Examples of catalogs
    -  ingrib?
    -  intake
    -  Thredds (shown above)

**Comment by martindurant** [comment]
Intake is getting an ipywidgets browser GUI here: https://github.com/ContinuumIO/intake/pull/130

**Comment by ashwinvis** [comment]
:+1: for netCDF (relevant https://github.com/jupyterlab/jupyterlab/issues/4184) and HDF5.

For dask, there seems to be an abandoned project: https://github.com/dask/dask-labextension
