### ISSUE TITLE
Data hosting at google cloud for a potential new use case.

### ISSUE THREAD

**Issue by jianwuwang** [pangeo-data/pangeo#365]
I'm working a NASA project on parallel [MODIS atmospheric data](https://modis-atmosphere.gsfc.nasa.gov/) Level 2 -> Level 3 aggregation. We believe Pangeo is the best framework for our project. After talking to some Pangeo folks at [GeoDaRRS workshop](https://www2.cisl.ucar.edu/events/workshops/geodarrs-workshop/2018/geoscience-digital-data-resource-and-repository-service-geodarrs-workshop), I'm told I could apply for data hosting at Google cloud so I can access them directly at http://pangeo.pydata.org/hub/home. The data we will process are in HDF format. Depending on available space can be given, we are interested in uploading one-month (around 400 GB) to one-year (around 4TB) MODIS level 2 data. If everything goes well, we are happy to share our implementation as a use case at Pangeo website. Thanks.

**Comment by jianwuwang** [comment]
Any updates on it are appreciated. Hope it will not be discarded.

**Comment by rabernat** [comment]
Hi @jianwuwang, sorry we neglected this message.

This sounds like an excellent use of pangeo. Do you remember whom you spoke with at GeoDaRRS?

**Comment by jianwuwang** [comment]
@rabernat , thanks for picking up the thread. I talked to Joseph Hamman, Niall Robinson and Kevin Paul at the workshop. They referred me to this approach for the application.

**Comment by jhamman** [comment]
@jianwuwang - thanks for sticking around. I apologize for missing this after the GeoDaRRS workshop. I'm perfectly fine with pangeo providing some storage space for this MODIS dataset. Now some questions for you?

- Have you had a chance to read the cloud data section on pangeo's website: http://pangeo.io/data.html#data-in-the-cloud? This would be a good place to start when thinking about how you want to store your data in cloud object storage.
- On data volume, I would say that it is probably worth starting with ~1month (400GB) and scaling up from there. If things look promising or you can't proceed without more data, then we can discuss a larger amount. Sound good?
- Finally, can you expand on the type of data processing you are likely to be doing? There is growing interest in the community to look at pangeo as a platform for analyzing remote sensing data. You may want to take a look at this blog post describing a project we're just kicking off: https://medium.com/pangeo/nasa-access-c3515a44f31b

**Comment by jianwuwang** [comment]
@jhamman - Thanks for your reply and help. Here are my answers to your questions. Any feedback is welcome. 

- I have read the web page and agree different data formats will cause huge performance differences. We are happy to try new data formats such as Zarr and see how much faster it can be for our project tasks.
- Yes. Starting with one month is perfectly fine to me. 
- Congratulations on the ACCESS project. We are happy to expand our efforts to other data processing tasks after data aggregation part is working.

**Comment by jhamman** [comment]
@jianwuwang - great. I suggest you play around with Zarr for a bit and when you're ready to move some data to GCS, let us know and we'll setup the transfer credentials.

**Comment by jianwuwang** [comment]
@jhamman , thanks a lot. Will contact when we are ready. We have a related issue. The MODIS data uses HDF4 format, not HDF5. So we couldn't use h5py library. We have been using [pyhdf](https://hdfeos.org/software/pyhdf.php) and [netCDF](http://unidata.github.io/netcdf4-python/). Just saw [pynio](https://github.com/NCAR/pynio) project. Any suggestion on which library is a better choice for the dataset is really appreciated.

**Comment by jhamman** [comment]
Pynio and xarray may work for you for reading hdf. I think I'd probably start there. If that doesn't work, I'd think about using building a quick converter from pyhdf to zarr. This may or may not use xarray as an intermediary.

**Comment by jianwuwang** [comment]
Thanks for the information. We will give a try.
