### ISSUE TITLE
Update the description of this repo

### ISSUE THREAD

**Issue by niallrobinson** [pangeo-data/pangeo#369]
Could we change this 
![image](https://user-images.githubusercontent.com/2979205/44473993-80d34700-a629-11e8-826f-cf72ba36ba94.png)
to read something like:

A place to discuss and track issues related to the Pangeo project, as well as the project [website](http://pangeo.io/).

I found it unclear that this is where you go to PR the website, and I don't think I can PR that change.

**Comment by rabernat** [comment]
Done

**Comment by niallrobinson** [comment]
💥 that was quick - thanks!
