### ISSUE TITLE
Document using dask-distributed on Geyser/Caldera Systems

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#37]
With Cheyenne's prolonged outage, I have been working on Geyser using a local cluster with a fair bit of success. I'll just share the workflow here so others can move forward in the short term. 

1. log on to yellowstone
   ```$ ssh yellowstone.ucar.edu```
2. go to your notebook directory, for me that was:
    ```$ cd ~/projects/pangeo/notebooks```
3. launch a notebook server on a geyser node:
    ```execgy notebook```
4. follow the instructions for creating an ssh tunnel, something like:
    ```ssh -N -l user_name -L 8888:geyserXX-ib:8888 yellowstone.ucar.edu```
5. Open a notebook and connect to a dask distributed "local cluster" using:
    ```Python
    from distributed import LocalCluster, Client
    client = Client(LocalCluster(processes=True, n_workers=10, threads_per_worker=2))
    client
    ```

cc @rabernat - this could be useful to you.
cc @mrocklin  - any thoughts on how this should perform. Seems to be working well for me.

**Comment by rabernat** [comment]
What is happens when you run `execgy notebook`? Is this a built-in command on yellowstone? I am familiar with `execgy` itself, but I didn't know it had a notebook option.

**Comment by jhamman** [comment]
Interesting. CISL must have changed things a bit. They now [say](https://www2.cisl.ucar.edu/resources/computational-systems/yellowstone/software/python/jupyter):

- Start an interactive session on Geyser or Caldera, or ensure that your work meets the guidelines for interactive use of Yellowstone's login nodes.
- Load the python and all-python-libs modules.
- Run the start-notebook command.

*It looks like `notebook` has become `start-notebook`...*

---

My workflow described above uses the old notebook command. I modified the launch script to use jupyter lab: `/glade/u/home/jhamman/notebook`.

You should be able to do `execgy /glade/u/home/jhamman/notebook`.

**Comment by jhamman** [comment]
ping @kmpaul
