### ISSUE TITLE
Advice on merging/zarring big lagged ensemble datasets

### ISSUE THREAD

**Issue by niallrobinson** [pangeo-data/pangeo#370]
@rprudden is trying to load multiple netcdf chunks, construct them into a high dimensional object and then restore them as a zarr but she and I are finding it hard. I seem to remember that @chiaral was talking about similar challenges. I thought I should introduce you, and find a place to share approaches

**Comment by niallrobinson** [comment]
I've attached some code which loads a hindcast set and calculates the anomaly, just as food for thought. The messy stuff is hidden away in "tools.py" (@chiaral this was the example I was talking about in CO)

https://gist.github.com/niallrobinson/ea1063b610f5047e602fb22bfde516c9

**Comment by chiaral** [comment]
This is great! 

So far I started with a netcdf SubX dataset only (GEOS_v2_p1), and I created one zarr file per year (I kind of did it on purpose to test if opening many zarr files was very slow, in my case it wasn't, or maybe I have low expectations!). 

Indeed the issue with Start time and Lead time (which i think correspond to your forecast_reference_time and forecast_period_time) it's the big headache. Storing data with S and L is better and more compact, whereas using T generates a sparse matrix. But the broadcasting of the "truth" to a S and L shaped dataset seems a waste of memory too.

So yeah, don't have an answer. But very interested in this. I will share my progress here!

**Comment by niallrobinson** [comment]
> But the broadcasting of the "truth" to a S and L shaped dataset seems a waste of memory too.

The way I did that was Very Hard...all the messiness is hidden in the tools.py. I'd just like a nice generalizable way to do that, then we can talk about efficiency!

**Comment by niallrobinson** [comment]
I'm also going to invoke @dpeterk and @pelson who are core iris devs incase they're interested in being github ghosts for some of this discussion

**Comment by RPrudden** [comment]
I'll hopefully take another look at this next week.

What I'm aiming for is a single zarr containing all the MOGREPS-UK data for one variable, for a single year. This would be 4 runs per day, each with 12 ensemble members and 37 lead times. So far, I've only managed to create the zarr for a single month - trying to convert any more than this seemed to break the distributed cluster. 

> Storing data with S and L is better and more compact, whereas using T generates a sparse matrix

This has also come up for me with ensemble members. For some reason, the names of the ensemble members are different depending on the start time - the 03 and 15 runs use {0,1,2,3...}, whereas the 09 and 21 runs use {0,12,13,14...}. I'm inclined to rename the ensemble members rather than use a sparse dataset, but it doesn't feel like a great solution.

**Comment by chiaral** [comment]
I think we will need to test a few examples to see what is more efficient. 

based on my tho very low experience, I think that storing them in a compact form it's more efficient, but then we have to match L+S to T. 

> This has also come up for me with ensemble members. For some reason, the names of the ensemble members are different depending on the start time - the 03 and 15 runs use {0,1,2,3...}, whereas the 09 and 21 runs use {0,12,13,14...}. I'm inclined to rename the ensemble members rather than use a sparse dataset, but it doesn't feel like a great solution.

I would rename the ensemble members. Maybe you can do it with a preprocessing function in open_mfdataset (if you using that)?

> The way I did that was Very Hard...all the messiness is hidden in the tools.py. I'd just like a nice generalizable way to do that, then we can talk about efficiency!

I right now have data with lat,lon,M,L,S and I think I am onto something (but will it be efficient for long time period? I smell memory issues):


Dataset:
```
<xarray.Dataset>
Dimensions:  (L: 45, M: 4, S: 146, lat: 181, lon: 360)
Coordinates:
  * L        (L) float64 0.0 24.0 48.0 72.0 96.0 120.0 144.0 168.0 192.0 ...
  * M        (M) int64 1 2 3 4
  * lat      (lat) float64 -90.0 -89.0 -88.0 -87.0 -86.0 -85.0 -84.0 -83.0 ...
  * lon      (lon) float64 0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 ...
  * S        (S) datetime64[ns] 1999-01-01T12:00:00 1999-01-06T12:00:00 ...
Data variables:
    pr       (M, S, L, lat, lon) float32 dask.array<shape=(4, 146, 45, 181, 360), chunksize=(1, 146, 45, 181, 360)>
```

select US portion
```
dd = dslist2.sel(lat=slice(25,50), lon=slice(230,300)).mean(dim='M').mean(dim=['lat','lon'])
```

I have to transform my L in a Timedelta - I should have done it when I created the zarr files
Also, it took me a while to figure out that in this case I need to use pd.Timedelta and not datetime.timedelta [https://github.com/pandas-dev/pandas/issues/16448](https://github.com/pandas-dev/pandas/issues/16448)

And I broadcast S and L
```
S2d, L2d = xr.broadcast(dd['S'], 
                        xr.DataArray(np.array([pd.Timedelta(ii, 'h') for ii in dd.L.values]), dims=['L']))

T2d = (S2d+L2d)

dd['T2d']=T2d
```

```
<xarray.Dataset>
Dimensions:  (L: 45, S: 146)
Coordinates:
  * L        (L) float64 0.0 24.0 48.0 72.0 96.0 120.0 144.0 168.0 192.0 ...
  * S        (S) datetime64[ns] 1999-01-01T12:00:00 1999-01-06T12:00:00 ...
Data variables:
    pr       (S, L) float32 dask.array<shape=(146, 45), chunksize=(146, 45)>
    T2d      (S, L) datetime64[ns] 1999-01-01T12:00:00 1999-01-02T12:00:00 ...
```

Then I group by T2d
```
dd['pr1']=xr.full_like(dd['pr'],1) # just to make sure I am grouping correctly

dd.groupby('T2d').sum().pr1.plot()
```

![image](https://user-images.githubusercontent.com/8453445/44595961-a92d8380-a798-11e8-9181-04a6a460443b.png)


seems to work (these are daily data with (kind of) pentad (it's an irregular grid) starts)

But I am SURE it can be done more efficiently. And still have to do the opposite step...

**Comment by chiaral** [comment]
Actually - that plot doesn't help in understanding whether the grouping is, but if I look at the groups:

```
dd.groupby('T2d').groups

numpy.datetime64('1999-01-01T12:00:00.000000000'): [0],
 numpy.datetime64('1999-01-02T12:00:00.000000000'): [1],
 numpy.datetime64('1999-01-03T12:00:00.000000000'): [2],
 numpy.datetime64('1999-01-04T12:00:00.000000000'): [3],
 numpy.datetime64('1999-01-05T12:00:00.000000000'): [4],
 numpy.datetime64('1999-01-06T12:00:00.000000000'): [5, 45],
 numpy.datetime64('1999-01-07T12:00:00.000000000'): [6, 46],
 numpy.datetime64('1999-01-08T12:00:00.000000000'): [7, 47],
 numpy.datetime64('1999-01-09T12:00:00.000000000'): [8, 48],
 numpy.datetime64('1999-01-10T12:00:00.000000000'): [9, 49],
 numpy.datetime64('1999-01-11T12:00:00.000000000'): [10, 50, 90],
 numpy.datetime64('1999-01-12T12:00:00.000000000'): [11, 51, 91],
 numpy.datetime64('1999-01-13T12:00:00.000000000'): [12, 52, 92],
 numpy.datetime64('1999-01-14T12:00:00.000000000'): [13, 53, 93],
 numpy.datetime64('1999-01-15T12:00:00.000000000'): [14, 54, 94],
 numpy.datetime64('1999-01-16T12:00:00.000000000'): [15, 55, 95, 135],
 numpy.datetime64('1999-01-17T12:00:00.000000000'): [16, 56, 96, 136],
 numpy.datetime64('1999-01-18T12:00:00.000000000'): [17, 57, 97, 137],
 numpy.datetime64('1999-01-19T12:00:00.000000000'): [18, 58, 98, 138],
 numpy.datetime64('1999-01-20T12:00:00.000000000'): [19, 59, 99, 139],
....
```
it's, *I think*, what I want. 
Still figuring out!

**Comment by chiaral** [comment]
Ok! I made some progress!

Here a [gist with 2 ways to map T to (L,S)](https://gist.github.com/chiaral/9b0e282c040ae2e94b817848b2a56d7f). One not super efficient, another one that is pure magic (thanks to @rabernat for some input on this!)

Let me know what you think.

Next on the list is calculating climatologies, with some type of harmonic fitting, as discussed in [this paper](https://journals.ametsoc.org/doi/pdf/10.1175/JAMC-D-17-0299.1).

**Comment by chiaral** [comment]
I should add, that the stack/swap_dims/swap_back/unstack procedure works of course when you have data with (L,S,lat,lon) dimensions as well. you simply do not stack those coordinates.

**Comment by niallrobinson** [comment]
I'm going to try and do what I did previously by copying lines of code from what you did @chiaral I want to get a better feel for Iris vs Xarray here (my xarray experience is pretty limited so far).

>  For some reason, the names of the ensemble members are different depending on the start time - the 03 and 15 runs use {0,1,2,3...}, whereas the 09 and 21 runs use {0,12,13,14...}.

is this because they're lagged ensembles or something? the 0th is unpurturbed. I don't think this is just a metadata screwup - we should find out why they're numbered like that

**Comment by rabernat** [comment]
The key code which allows you to "broadcast" the truth data to S, L space is this
```python
stacked = ddslice.stack(all_points=['S', 'L'])
swapped = stacked.swap_dims({'all_points': 'T2d'})
swapped['truth'] = ddtruth.pr.sel(time=swapped.T2d)
swappedback = swapped.swap_dims({'T2d': 'all_points'})
broadcasted_data = swappedback.unstack('all_points')
```

I would consider this "advanced xarray." this sort of workflow is not very well documented or widely understood.

**Comment by pelson** [comment]
> is this because they're lagged ensembles or something? the 0th is unpurturbed. I don't think this is just a metadata screwup - we should find out why they're numbered like that

For operational reasons we can't run all of our ensembles all of the time. 03 and 15 are the "full" runs (with all ensembles), where 09 and 21 are the "quick" runs (only half of the ensembles).

For the same reason, I believe the "quick" run stops much sooner than the "full" run in terms of time too. I don't know the exact numbers off the top of my head, but for example the "full" might run for T+360 (15 days) whereas the "quick" might only go out to T+120 (5 days).

There is no way around this, you will definitely need semantics for defining "no data exists here". Ideally those semantics will be extensible too, so that we can say *why* there is no data ("the model fell over" / "the model doesn't cover this range")
