### ISSUE TITLE
Any MPAS users out there?

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#371]
I have a few colleagues here at NCAR who are working on MPAS and have an interest in using the Pangeo software stack.  Are there any other MPAS users out there that I can talk with about using Xarray / Dask with MPAS grids?

**Comment by jhamman** [comment]
I know this package uses xarray and dask extensively: https://github.com/MPAS-Dev/MPAS-Analysis

cc @pwolfram

**Comment by pwolfram** [comment]
We have found that Xarray / Dask is best for prototyping and have ended up using more and more netCDF tools, e.g., ncks, nco, etc for the production analysis.  @xylar, who is the primary developer of MPAS-Analysis, can speak more to these details.

**Comment by rabernat** [comment]
> We have found that Xarray / Dask is best for prototyping and have ended up using more and more netCDF tools, e.g., ncks, nco, etc for the production analysis.

😢

**Comment by ktyle** [comment]
Is the NetCDF Operators (nco) python package worth exploring?  I've installed it on our systems, but am not aware of any use cases which leverages the capabilities presumably provided.

**Comment by pwolfram** [comment]
@ktyle, can you please explain more?  If I understand correctly, newer versions of nco have become parallel on node, but in terms of cross-node computation I don't believe it can compete with Dask.  This just hasn't been our immediate use case.

**Comment by xylar** [comment]
> We have found that Xarray / Dask is best for prototyping and have ended up using more and more netCDF tools, e.g., ncks, nco, etc for the production analysis.

We find that complex computations across a large number of files with xarray are too slow to be useful.  We end up using NCO either to compute climatologies or to strip out specific variables of interest. In either case, we end up with a single file.  Once we do that, xarray is very useful for loading a single file.  For now at least, we're still finding xarray to be much more reliable for problems where all data fits in memory.

**Comment by ktyle** [comment]
@pwolfram Looks like none other than @jhamman set up the PyNCO library, so maybe Joe could comment on how it can work its way into the Pangeo ecosystem.  https://pynco.readthedocs.io/en/latest/

**Comment by rabernat** [comment]
> We find that complex computations across a large number of files with xarray are too slow to be useful. We end up using NCO either to compute climatologies or to strip out specific variables of interest.

Within Pangeo, we would be very interested in tackling this problem. Our process for the last year has basically been to identify such cases, reduce them to specific minimal examples, and pursue fixes upstream in dask and xarray. This had lead to some major performance improvements.

Can you provide us with an example of a failing calculation you are trying to do + data? We can copy the data to Cheyenne or google cloud so we can all have a look at the underlying issue.

**Comment by xylar** [comment]
> Can you provide us with an example of a failing calculation you are trying to do + data? We can copy the data to Cheyenne or google cloud so we can all have a look at the underlying issue.

I appreciate the offer to look at this.  The MPAS-Ocean data sets we work with are quite large (even for relatively low resolution simulations) and I'm not sure at this point which results I'd be able to share more broadly.  I'll look into it and see what I can provide, though this is not likely to be something I have time for in the immediate future.

**Comment by rabernat** [comment]
Xylar and Phil: I feel your pain. You have a job you need to get done, and you are doing what you have to do with the tools as they are today.

From the perspective of Pangeo, this provides a unique and important opportunity to figure out what is wrong with our stack. Your use case is ostensibly exactly what Pangeo is trying to optimize. So the news that you had to go back to the legacy tools is concerning. This is something that our project needs to address.

The open source process tends to work best when users report the problems they are having to the upstream developers. In this case, there doesn't appear to be [any record](https://github.com/search?q=author%3Axylar+repo%3Apydata%2Fxarray&type=Issues) in the xarray issue tracker describing the problem that caused you to abandon xarray for your production workflow. This is important information. (Apologies if I missed the relevant issue.) 

> The MPAS-Ocean data sets we work with are quite large

Pangeo is all about big data! We have no problem absorbing datasets up to 10 TB. Although issues can usually be diagnosed with much smaller examples.

Within the constraints of your busy schedules and existing commitments, we would really appreciate a bug report whenever you can find the time.
