### ISSUE TITLE
Synergy with Geospatial Big Data Platform (GBDX)  

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo#372]
For those interested in satellite imagery, DigitalGlobe has a Jupyter Notebook interface for analyzing imagery directly from their catalogs:
https://notebooks.geobigdata.io 

They are using similar technologies to the pangeo.pydata.org (such as parallelism with Dask), but also have some great features, such as a interactive catalog browser that can load imagery into the notebook automatically:

![widget-browser](https://user-images.githubusercontent.com/3924836/44613048-fb839a00-a7c2-11e8-8d70-77cff0f39e5a.jpg)

I recommend checking it out with their free account (related to desirable JupyterLab extensions for Pangeo -  #26). You can explore the interface for free, but access to commercial imagery, persistent storage, and greater computing power comes at a high cost!

And here is an interesting blog post describing some of the technology under the hood:
http://blog.digitalglobe.com/developers/cloud-optimized-geotiffs-and-the-path-to-accessible-satellite-imagery-analytics/

**Comment by grizonnetm** [comment]
Pour info j'ai suivi un tutorial d'1/2 journée en aout 2017 sur GBDX. Je dois encore avoir des notes sur le sujet...

Si tu veux d'autres exemples de ce type de plateforme il y a aussi le MEP Proba-V développé par VITO:

[https://proba-v-mep.esa.int/notebooks](https://proba-v-mep.esa.int/notebooks)
