### ISSUE TITLE
GFS data on S3

### ISSUE THREAD

**Issue by willirath** [pangeo-data/pangeo#375]
There seems to be an experimental version of GFS data hosted on AWS:

https://gist.github.com/jedsundwall/e85bfca46f4b2ee5a985ec793c30725a

Did anyone use this before?

**Comment by rabernat** [comment]
Cc @chiaral

**Comment by willirath** [comment]
Short update: PyNIO and `cfgrib` both can't seem to handle file streams, because they pass the object to be read from to a low-level C function that expects a path.  I'm able to access the files with Dasks `s3fs` and `pupygrib` though:

```python
import s3fs
import pupygrib

fs = s3fs.S3FileSystem(anon=True)

with fs.open('noaa-gfs-pds/VREL/9950 sigmavalue SGMA/20180910/0000/003', 'rb') as f:
    msg, = pupygrib.read(f)

print(sorted(msg[0].fieldnames))
```
```
['discipline', 'editionNumber', 'identifier', 'totalLength']
```

**Comment by martindurant** [comment]
Note that Intake now has a [cache-on-first-access](https://www.anaconda.com/blog/developer-blog/intake-caching-data-on-first-read-makes-future-analysis-faster/) mechanism that can be applied to formats where the reader absolutely needs a local file. That is not the same thing as accessing the data in-place on the remote service, but worth mentioning.

**Comment by willirath** [comment]
Thanks for the pointer!

**Comment by willirath** [comment]
No, I did not. My comment above (with pupygrib) was the closest I got.


Am 8. Dezember 2018 18:23:04 schrieb Nic Wayand <notifications@github.com>:
