### ISSUE TITLE
ESA Conference : Big Data from Space 2019 - February - Munich

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#376]
Some of you may be aware of [this conf](https://www.bigdatafromspace2019.org), I remember seeing UK Met Office folks in Toulouse last year presenting their JADE platform (one of the best talk of 2017 edition, seriously).

It would be good to have some Pangeo talks this year, deadline for submission is mid-october. I may propose some paper around dask-jobqueue and its usage at CNES, not sure yet. I will be happy to give an introduction on Pangeo, but it would probably be better to have a complete talk?

**Comment by guillaumeeb** [comment]
So I will probably attend this conference and propose a paper. Two choices depending of other people here:
- I remain focused on CNES side, and give a talk about our use cases at CNES arount Jupyter/Dask/Dask-jobqueue.
- If nobody else is doint it, I can divide the paper in half, presenting Pangeo initiative in more details and then talking about its use at CNES.

@jacobtomlinson will you go there? Any other might be there?

**Comment by rabernat** [comment]
Just chiming in to say that I really hope someone can say something about Pangeo at this confierence. @guillaumeeb, I would be happy to share our existing pangeo slides.

What does a "paper" mean at a conference like this? Is it peer reviewed?

**Comment by jacobtomlinson** [comment]
It is unlikely that I will go personally as I'm expecting a newborn any day now and so will aim to keep international travel to a minimum for a while. However there may well be attendance from the Met Office. @niallrobinson do you know who went before (was it Jeremy?) and do you think we will send anyone this time (maybe @tam203)?

I agree that someone should definitely present Pangeo there.

**Comment by guillaumeeb** [comment]
@rabernat I would be happy to have your slides and to say something about Pangeo.

The 4 pages paper here is peer-reviewed by the Program Committee, usually some technical experts or managers from ESA or other national space agencies like CNES (see https://www.bigdatafromspace2019.org/QuickEventWebsitePortal/2019-conference-on-big-data-from-space-bids19/bids-2019/ExtraContent/ContentSubPage?page=6&subPage=2).

**Comment by guillaumeeb** [comment]
ping @rabernat and @jhamman (and maybe others)? Would you share Pangeo slide and eventual papers/proposals that you may have? I will need to begin writting something soon.

**Comment by jhamman** [comment]
@guillaumeeb - Here's a few materials for you:

- Presentation I gave at scipy:
  - abstract: https://www.dropbox.com/s/7uqlloamvlja2m2/Pangeo_scipy_abstract.docx?dl=0
  - slides: https://www.dropbox.com/s/8ita8j611brwbyy/Pangeo_Unidata_users.key?dl=0
- Presentation I gave at EGU: 
  - abstract: https://www.dropbox.com/s/fui0uwvq2r77txx/2018_EGU_Abstract_Hamman_Pangeo.docx?dl=0
  - slides: https://www.dropbox.com/s/cbfpg23vv1skz7u/pangeo_egu_presentation.pptx?dl=0

Let me know if you have any questions.

**Comment by guillaumeeb** [comment]
Thanks, that's perfect!

**Comment by guillaumeeb** [comment]
For those interested, I've begun the paper redaction here: https://github.com/guillaumeeb/bids2019. There is only the outline of the paper for now, but do not hesitate to tell me if you think I've forgotten or missed something.

I will update this issue when I got a close to final submission version.

cc @apatlpo who was interested in this.

**Comment by guillaumeeb** [comment]
First complete draft version available [here](https://github.com/guillaumeeb/bids2019/blob/master/pangeo-cnes.pdf]).

Any idea, comment, remark, correction, typo fix, english correction is welcomed, directly on the tex file or reading the PDF.

**Comment by guillaumeeb** [comment]
Submission deadline is on monday. This will not be the final paper, only the peer reviewed one, but reviews from people here would still be welcomed 🙂. I know this is not easy to find time for this.

I'm especially targeting @rabernat and @jhamman if possible.

**Comment by rabernat** [comment]
@guillaumeeb  see https://github.com/guillaumeeb/bids2019/pull/1

Thanks for putting this together!

**Comment by guillaumeeb** [comment]
Paper submitted, thanks all for your reviews. I'm pretty confident it will be accepted as Pangeo is gaining traction day after day.

**Comment by apatlpo** [comment]
thanks a lot Guillaume !
