### ISSUE TITLE
dask workers dying mysteriously on wrangler

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#38]
I have a new notebook I'm trying to use on wrangler:
https://github.com/pangeo-data/pangeo/blob/master/notebooks/test_cm2-6_wrangler.ipynb

Wrangler seems fantastic due to the speed of the flash storage. It can also use this flash storage to spill to disk, which can be convenient (and is necessary for this use case).

However, I'm encountering some weird dask behavior. The calculation and the failures are described in the notebook.

@mrocklin, as soon as you get access to wrangler, I think you might enjoy playing around with it. It's an amazing system. If you want to take a look at this problem I'm having, I would be very grateful.

**Comment by mrocklin** [comment]
OK.  I probably won't time to play with this today.  However if you have more information about the problem I may be able to diagnose it.

Is the flash storage a network drive or locally attached?  I am suspicious of Dask spilling to disk well on any system without locally attached storage.

**Comment by rabernat** [comment]
It is a network drive. But it is super fancy.
https://portal.tacc.utexas.edu/user-guides/wrangler#architecture

**Comment by mrocklin** [comment]
When spilling to disk, Dask workers perform many small reads and writes.  This is generally a fail case for network file systems.  It has less to do with throughput or latency and more to do with implementing consistency across a distributed system, which is hard.  Maybe this system's capabilities are enough for common spill-to-disk usage.  I certainly hope so, but if you're seeing hardware failures when spilling to disk then this would be my first guess.

Alternatively, maybe it's not spilling to disk at all, and it's just exceeding it's memory allocation and so being killed by the job scheduler.  You might want to verify that the `--memory-limit` value is conservative relative to the available memory that you've been given.

**Comment by rabernat** [comment]
Definitely spilling to disk. I can see this in the dashboard.

**Comment by mrocklin** [comment]
Do you happen to have access to the worker logs?

**Comment by rabernat** [comment]
[worker.57476.out.txt](https://github.com/pangeo-data/pangeo/files/1476285/worker.57476.out.txt)

**Comment by mrocklin** [comment]
I was hoping to see a clear out-of-memory error but didn't see anything.  I hope to have some time to take a look at this tomorrow.
