### ISSUE TITLE
Zarr/GCS potential optimisation to reduce latency

### ISSUE THREAD

**Issue by alimanfoo** [pangeo-data/pangeo#381]
In discussion of a separate issue (#196) it came up that gcsfs currently makes 2 HTTP requests each time a cloud object is retrieved, the first to obtain the size and download URL (media link), the second to retrieve the actual bytes. Looking at the [source code for the google cloud Python client library](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/storage/google/cloud/storage/blob.py#L425), it appears that it should be possible to build the download URL from a template, and the size is not required, hence it should be possible to retrieve the data in a single HTTP request. This could eliminate significant latency, especially when using with zarr arrays where chunks are relatively small. 

I thought I would raise here for initial discussion about the best way forward, although this issue affects potentially the zarr and/or gcsfs projects. We could pursue an optimisation within gcsfs. We could also look again at @rabernat's PR with a GCS mapping using the google cloud Python client library (https://github.com/zarr-developers/zarr/pull/252). Some performance comparison on a relevant dataset to confirm the issue would also be useful.

**Comment by alimanfoo** [comment]
Basically it looks like if you add ``?alt=media`` to the object URL and [make a GET request](https://cloud.google.com/storage/docs/json_api/v1/objects/get), you get the object data in the response.

**Comment by martindurant** [comment]
I should point out that the second request is only made if the file information is not already cached. I suppose that this is indeed the case when we are explicitly trying to avoid "contains" calls.

**Comment by martindurant** [comment]
Try https://github.com/dask/gcsfs/pull/111 ?

**Comment by alimanfoo** [comment]
Many thanks Martin, I'll give it a go asap.

**Comment by alimanfoo** [comment]
For interest, on my local machine, retrieving a very small object directly
using the google cloud storage client library takes ~300ms.

Using GCSMap from @martindurant's new gcsfs branch also takes ~300ms, down
from >700ms using the release version.

I also tried GCSStore from @rabernat's zarr PR
https://github.com/zarr-developers/zarr/pull/252 which currently takes
~450ms and profiling shows some extra network communication, however with a
small amount of hacking this too can be brought down to ~300ms.



-- 
If I do not respond to an email within a few days, please feel free to
resend your email and/or contact me by other means.

Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health
Big Data Institute
Li Ka Shing Centre for Health Information and Discovery
Old Road Campus
Headington
Oxford
OX3 7LF
United Kingdom
Phone: +44 (0)1865 743596 or +44 (0)7866 541624
Email: alimanfoo@googlemail.com
Web: http://a <http://purl.org/net/aliman>limanfoo.github.io/
Twitter: @alimanfoo <https://twitter.com/alimanfoo>

**Comment by martindurant** [comment]
I think we can call this fixed.

**Comment by rabernat** [comment]
So should we consolidate all our GCS metadata now?!?

**Comment by alimanfoo** [comment]
@rabernat if you are happy with the revised format for the consolidated metadata (https://github.com/zarr-developers/zarr/pull/268#issuecomment-435621394) then I think we can merge that PR, and you could go ahead with consolidating GCS metadata. I think @martindurant also plans to add support for consolidated metadata in intake, so opening a dataset with consolidated metadata would be transparent for pangeo users.

**Comment by martindurant** [comment]
Yes, it will be an argument in Intake, but someone still has to make the effort to run consolidate on datasets. It's particularly worthwhile with those that have many metadata files at the moment.
