### ISSUE TITLE
NEW!!!  Second NCAR Software Engineer I Position OPEN

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#385]
As a sign of NCAR's commitment to the Pangeo project, we have opened a search for a SECOND Software Engineer I!  To see the job posting, [click here](https://ucar.silkroad.com/epostings/?fuseaction=app.jobinfo&jobid=218435&version=1#.W5aNTU6PqEw.email).  Note that this position is _in addition to_ the first NCAR Pangeo SE I job posting, previously announced in Issue #275.

**A word of advice...**
Our previous posting was so popular that we received more than 50 applications in the first 2 weeks!  With such a high application rate for just 1 position, I highly recommend that all applicants take a close look at the _required_ and _desired_ skills mentioned in the job posting above and tailor your resume to emphasize your fit.  Make your resume stand out!

**Comment by jhamman** [comment]
This closed a few weeks ago so closing now.
