### ISSUE TITLE
Weekly checkin meeting?

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#391]
Do we want to have a short weekly checkin meeting to synchronize work and issues happening around Pangeo development?  This might help to align efforts and also form a stronger social base.

**Comment by guillaumeeb** [comment]
That definitly sounds good to me! 

For example I'm currently experiencing cloud deployment when I find free time, but I'm not convinced I use and update the correct procedure, see #378. It seems there is some activity on this with helm chart or jupyterhub guide. And there's also an experiment with terraform and maybe other tools mentioned by @jacobtomlinson.

I'm also trying to work on a basic satellite image processing example with Dask and Xarray, there may be some existing material around here...

**Comment by rabernat** [comment]
Thanks for suggesting this Matt. It's a good idea. My schedule is very tight this semester, but I will try to make it as much as possible.

My preferred time would be Wednesday morning.

FYI @jhamman is currently on vacation.

**Comment by jhamman** [comment]
+1 on this idea. Wednesday mornings would work for me (or probably any other morning). Just keep in mind that I'm on Pacific Time so preferably nothing earlier than 8 PT.

**Comment by jacobtomlinson** [comment]
8PT would be 15GMT so that's fine with me. I am about to disappear on paternity leave at some point in the next few weeks, so probably best to get at least one in before I go. 

I would suggest we aim to have one tomorrow?

**Comment by guillaumeeb** [comment]
Wednesdays are not ideal for me, I have to leave work at 17:20, sot 15:20 UTC due to too many paternity leaves already taken 🙂. I would prefer tuesday or thursday where 15UTC is generally fine for me.

Not available tomorrow, sorry for that, but it's certainly fine to do that without me, just keep everyone posted of the discussions!

**Comment by kmpaul** [comment]
Wednesday mornings usually work well for me, so I'll put my vote in for that.

**Comment by mrocklin** [comment]
I suggest that we meet regularly at 8am Wednesday mornings.  

I apologize that this doesn't work well for you @guillaumeeb .  It was unlikely that we would find a time that worked well for everyone.

**Comment by mrocklin** [comment]
Sorry, 8am US Pacific, 9am US Mountain, 11am US Eastern, 15:00 UTC

**Comment by jacobtomlinson** [comment]
Sounds good to me. Are we checking in at https://appear.in/pangeo

**Comment by guillaumeeb** [comment]
> I apologize that this doesn't work well for you @guillaumeeb . It was unlikely that we would find a time that worked well for everyone.

Yes this is always difficult. I can try to do the first 20 minutes or even 30 if I can, if you don't mind me quitting suddenly in the middle of the conversation?

**Comment by jacobtomlinson** [comment]
Weekly is quite a short interval and there is only so much that can happen in that period, so I would be surprised if the meeting lasts longer than 20 mins anyway. As we've not spoken for a bit I imagine the first one or two will be longer, but I think it will settle down after that.

**Comment by mrocklin** [comment]
Reminder that we're having a weekly group meeting tomorrow.  I'll recommend the following structure:

1.  Quick reports from people on things that they've been working on, if they've been doing pangeo related work recently

    Example: "This week I worked on science case X.  I ran into performance issues with dask array due to small chunk sizes and am still working through these.  I think I can maybe solve this with Y, but would welcome feedback after meeting if anyone has suggestions" or "Nothing from me this week.  Busy with other work"

2.  Status check on some of the larger efforts that we want to track over longer time period

    Example: "How are we doing on refactoring pangeo.pydata.org, governance, X, Y, and Z"

3.  General discussion on coordinating near-term work.  I'm going to suggest that we try to limit discussion to things that should happen near-term, and save other discussions for less frequent but longer meetings.  

    Example: "Has anyone submitted to conference X?  I think that we should send someone." or "I would like to start working on a tutorial, does anyone have any good resources or is intersted in helping?"

    Anti-Examples: "Building cloud-friendly data storage formats is critical to our field." or "We really need to find someone to hire that has X skillset"

I would be *very* happy for someone else to provide counter-proposals here.  But I figure that some structure to start is better than no structure, even if we tear it down quickly.

**Comment by mrocklin** [comment]
Lets meet at https://appear.in/pangeo at 11am US Eastern, 15:00 UTC

**Comment by rabernat** [comment]
Sounds perfect Matt. Thanks for taking the initiative to organize this.

**Comment by guillaumeeb** [comment]
As I probably won't be able to attend, here are my list of open points that could benefit from this discussion:

1. Quick report
    -  Working on deploying a Pangeo infrastructure on GCE, with or without @dsludwig terraform script. All steps well understood and OK.
    - I will probably need some help for correctly starting KubeCluster soon (it does not seem to work yet), but I will reach to some of you when I've dug a little more.
 2. Larger effort
    - Cooperation CNES/NASA with Pangeo, probably on SWOT: there are some discussion of cooperation possibilities around data analytics between CNES and NASA's JPL, I'd like to introduce Pangeo there. @rabernat do you still have a contact?
    - French cooperation between CNES/Ifremer on SWOT to begin soon, using Pangeo on HPC, maybe Cloud later on.
    - http://www.spaceclimateobservatory.org/ CNES initiative. Only starting, but it would be good to fit Pangeo in it, I'm working on it internally.
    - Pangeo on a European cloud provider (Cloud act problem for GCE, Azure or AWS): OVH or T-Systems (OTC), but much less work from them yet on providing K8S clusters it seems, any thoughts?
3. Coordinating near-term work
    - It would be good to synchronize on what we want to do for the cloud setup guide and in relation with #373 and terraform. 
    - Open work on Dask ClusterManager new component https://github.com/dask/distributed/issues/2235.
    - Who is the new NCAR Pangeo SE?
    - Pangeo for image processing: working on a dask-examples notebook for that, but would appreciate some inputs if someone has already worked on this.
    - ESA Big Data from Space (#376): will work on it soon, inputs welcomed. 

All those points can be discussed somewhere else if anybody wants to.

**Comment by rabernat** [comment]
Notes: https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU/edit?usp=sharing

**Comment by guillaumeeb** [comment]
Thanks for the notes! A few things that interest me:
- >NASA Pangeo award should be kicking in any day now  

  Could you elaborate on this this? What are Pangeo relations with NASA?
- https://github.com/dbuscombe-usgs/cdi_dl_workshop: nice !
- >Scott Henderson GeoTIFF example
  
  I imagine this is on satellite Data? Could I get this one?
- CI/CD: I'm happy to help as a guinea pig or for documentation on this, keeping on testing pangeo clusters deployment.
- >Split pangeo.pydata.org to many smaller domain
  
  Would it make sense to have one for satellite imagery/radar?

**Comment by mrocklin** [comment]
> Thanks for the notes! A few things that interest me:

Sorry we couldn't find a time that worked for everyone.  I would be happy to meet with you any time one-on-one @guillaumeeb if you're interested.  I suspect that other people would also love to get to know you.

>> NASA Pangeo award should be kicking in any day now

> Could you elaborate on this this? What are Pangeo relations with NASA?

The University of Washington, NCAR, and Anaconda have a joint grant from NASA ACCESS.  @jhamman can probably point you to the proposal.  It is about cloud infrastructure to handle satellite imagery.

> CI/CD: I'm happy to help as a guinea pig or for documentation on this, keeping on testing pangeo clusters deployment.

@dsludwig is heading this up.  I think that he plans to write up a bit of documentation early this week and then have a few people try it out.  If you're interested I'm sure he'd love to interact with you.  You're an easy first user :)

>> Split pangeo.pydata.org to many smaller domain

> Would it make sense to have one for satellite imagery/radar?

Definitely

**Comment by jhamman** [comment]
@guillaumeeb - we'll have a full announcement on the NASA ACCESS award soon. The basic idea is to start tuning parts of pangeo for remote sensing datasets. @scottyhq is about to publish a blog post on some preliminary/related work.

**Comment by guillaumeeb** [comment]
>  I would be happy to meet with you any time one-on-one @guillaumeeb if you're interested. I suspect that other people would also love to get to know you.

Thanks for that, we could try to find some time to do this and speak about Pangeo and Dask. 

@jhamman Thanks for the clarifications here, hope I can talk to some people at NASA to possibly work in coordination. Perhaps on deploying remote-sensing.pangeo.pydata.org?

And I've found [Scott Henderson GeoTiff example](https://github.com/scottyhq/pangeo-example-landsat-2018/blob/master/PangeoSprintLandsat-Simple.ipynb), and at the same time I've read the [Pangeo Developers Workshop outcome](https://medium.com/pangeo/the-2018-pangeo-developers-workshop-1be359dac33c) which was really interesting and speaking about NASA.

**Comment by mrocklin** [comment]
> Thanks for that, we could try to find some time to do this and speak about Pangeo and Dask.

I'm free tomorrow 8-10:30am US East, 12:00-14:30 UTC if that works for you.  Also very free next week.

You might also want to chat with @dsludwig at some point about setting up a cloud deployment using his CI system.  I suspect that you could be a very good first user / dev.

**Comment by niallrobinson** [comment]
hi everyone - I think we've got a pangeo meeting in a few mins. I'm going to sit this one out if that's ok. @jacobtomlinson is off now (!) the only thing I would mention in @rabernat - are you still up for doing this paper - conversation can continue on gitter though

**Comment by kmpaul** [comment]
Unfortunately, I will have to miss this meeting, too.  However, @andersy005 will be there in my place.

**Comment by jhamman** [comment]
@guillaumeeb - you had asked for some more information on the NASA Pangeo project. Take a look at this blog post: https://medium.com/pangeo/nasa-access-c3515a44f31b. I'd be happy to talk more about it if you'd like.

**Comment by guillaumeeb** [comment]
Thanks @jhamman! Really exiting and something CNES will definitly be interested in.

**Comment by jhamman** [comment]
@guillaumeeb - let's stay in touch on the subject. Maybe we can identify a few places where our development agenda overlaps with CNES and we can actively collaborate.
