### ISSUE TITLE
Trustworthy Data Repositories - CoreTrustSeal Cohort Opportunity

### ISSUE THREAD

**Issue by RPrudden** [pangeo-data/pangeo#393]
Just wanted to share this email that was sent to the AGU mailing list. They are offering certification for Earth and environmental science datasets. It might be worth considering for open datasets in the Pangeo ecosystem.

> All,
> 
>  
> 
> (apologies for cross-posting)
> 
>  
> 
> If you represent a repository that stores Earth, space, or environmental science related data and would be interested in the CoreTrustSeal certification, consider adding your name to the cohort described below and participating in the webinars for preparing your certification submission package. 
> 
> Feel free to share this with your communities.   There is no risk nor requirement to be included in the cohort.  Completion of a certification submission package is not required, though we hope this opportunity will make it easier and more likely for success. 
> 
>  
> 
> From Rebecca Koskela, 
> 
>  
> 
> A cohort of data repositories is being assembled to apply for  CoreTrustSeal certification as part of the American Geophysical Union Coalition Enabling FAIR Data Project. CoreTrustSeal certification demonstrates to a repository’s users and funders that they have been evaluated by an independent authority and endorsed for their trustworthiness.
> 
>  
> 
> We are planning a series of webinars in the first part of October to provide more information on CoreTrustSeal and the certification process. The webinars will be recorded and made available for those unable to attend.
> 
>  
> 
> If you are interested in becoming a member of this cohort, please send email to Rebecca Koskela (rkoskela@unm.edu).  Also, please pass this on to anyone you think would be interested in joining the cohort.
> 
> 
> Regards,
> 
> Rebecca
> 
>  
> 
> For more information: 
> 
> CoreTrustSeal certification: https://www.coretrustseal.org/
> 
> Enabling FAIR Data Project: http://www.copdess.org/enabling-fair-data-project/

**Comment by rabernat** [comment]
This is a cool idea. Thanks @RPrudden!

One challenge here is that pangeo is not an "official" repository of any datasets. We have mirrored several in order to make them more cloud-friendly. But our ultimate goal is to persuade the data providers to share their data this way from the beginning.
