### ISSUE TITLE
NASA RFI: SMD Strategic Plan for Scientific Data and Computing

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#400]
NASA is requesting community input for its strategic plan for scientific data and computing. I plan to submit a short Pangeo related white paper related to this call. If you are interested in participating in this, please speak up below.

------- 

REQUEST FOR INFORMATION FOR

INPUTS TO THE SCIENCE MISSION DIRECTORATE STRATEGIC PLAN FOR SCIENTIFIC DATA AND COMPUTING

Solicitation Number: NNH18ZDA017L

Release Date: September 18, 2018

Response Date: 11:59 PM Eastern Time October 19, 2018

The NASA Science Mission Directorate requests information, comments and suggestions to assist in the development of a Strategic Plan for Scientific Data and Computing. This notice is published to solicit input from all stakeholders, including but not limited to members of scientific community, academic institutions, other agencies, the private sector, professional societies, advocacy groups, the general public, and international collaborators. The objective of the Strategic Plan for Scientific Data and Computing is to articulate a whole-of-SMD 5-year strategy that has four overall goals:

- Improve discovery and access for all SMD data for immediate benefit to science data users and to improve the overall user experience
- Identify large-scale and cross-disciplinary/division science users and use cases to inform future science data system capabilities
- Enable strong theory programs that are firmly based on NASA’s observations
- Modernize science data and computing systems to improve efficiency and enable new technology and analysis techniques for scientific discovery and commercial use

The Strategic Plan for Scientific Data and Computing is intended to span the range of activities within the Science Mission Directorate, including opportunities for cross-disciplinary science investigations. Respondents are therefore encouraged to think broadly about future capabilities and needs, and we encourage members of all fields of NASA science, engineering, industry, and academia to respond to this RFI in order to ensure a range of views. 

NASA will use your response to aid in programmatic decisions about future investments for data and computing, including partnerships with private sector and philanthropic organizations. This RFI is not to be construed as a commitment by the Government nor will the Government pay for information solicited. No proposals will be awarded funding as a result of this RFI.

This RFI is open to responses from all parties including commercial entities, international organizations, academia, NASA Centers, and other government agencies. The full text of the RFI and response instructions can be found on NSPIRES at:  https://nspires.nasaprs.com/external/solicitations/summary!init.do?solId={B896B39A-F430-1916-2247-B791CE3D5FBF}&path=open. Responses will be accepted only if submitted via NSPIRES. Responses provided by email, mail or other means will not be accepted.

 Questions concerning this RFI may be addressed to Kevin Murphy, Science Mission Directorate, NASA, Washington, DC 20546; Email: hq-smd-data-computing-rfi@mail.nasa.gov and Ellen Gertsen, Science Mission Directorate, NASA, Washington, DC 20546; Email: hq-smd-data-computing-rfi@mail.nasa.gov.

**Comment by rabernat** [comment]
I definitely want to take part.

**Comment by jhamman** [comment]
The deadline on this has been bumped to Nov. 2. @scottyhq and I are starting on a document here: https://docs.google.com/document/d/154Xw-wKXtCqe0RCrDZOJpIobrvIkPLDgd19fhb5HcXY/edit?usp=sharing

If you contribute to this doc, please add your name to the title page.

**Comment by rabernat** [comment]
Hi @jhamman and @scottyhq. I added a section to the RFI on physical oceanography. Besides that, I'm very pleased with what you wrote and happy to be listed as an author. Please finalize and submit whenever you're ready.
