### ISSUE TITLE
use NFS for cloud home directories

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#401]
In the current pangeo.pydata.org, we use 10GB persistent volumes for each user. This adds up with hundreds of users, and most of this space is unused.

A more flexible choice would be to have a central file server for the cluster and use NFS to mount user home directories. At the developers meeting, @yuvipanda mentioned that this was already available in zero2jupyterhub-k8s (or maybe I misunderstood). As the refactoring of pangeo.pydata.org moves along (#373), we should assess how much effort it would be to use this approach. 

cc @dsludwig, @jacobtomlinson

**Comment by rabernat** [comment]
Also related to #272.

**Comment by jacobtomlinson** [comment]
This is definitely on my wish list. We are restricted by the fact that AWS don't have NFS as a service available in London. But that doesn't stop you from doing this on Google Cloud.

It would also open up the ability to mount the user home directory on all the dask workers in `dask-kubernetes`. Which would be nice!

**Comment by yuvipanda** [comment]
Both EFS and Google Cloud filestore expose themselves as NFS. So they match our criteria of cloud services that expose a standard interface. So using either for storage seems fine.

Z2jh does make it easy to mount NFS on each pods, and we should make it!

**Comment by yuvipanda** [comment]
Yes! For Google cloud,

1. Create a Filestore instance https://cloud.google.com/filestore/
2. Configure z2jh to use it https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/421

You might have to switch to a nodepool with Ubuntu base images rather than the default COS ones for it to work. You should also decide what to do with the current home directories you have.

**Comment by jacobtomlinson** [comment]
> We definitely would not want to use a vendor-specific service.

There is no avoiding this. But all cloud providers should have a service which presents generic NFS. We have a "how to get kubernetes on GCE" step of the instructions and we just need to extend that. Once that is done everything else should be the same.

**Comment by rabernat** [comment]
How are usernames handled in this case? Is each user still called `jovyan`? If so, how does NFS map the users personal space?

**Comment by yuvipanda** [comment]
The NFS directories would be created under /some-path/<username>, while inside the container it'll still seem to be /home/jovyan. See https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/config/prod.yaml#L15 for an example - specifically the `{username}` template expansion.

**Comment by yuvipanda** [comment]
I'd love to take this on for pangeo. 

Plan would require:

1. Set some downtime
2. Create an Google Cloud Filestore
3. Copy user home directories from individual disks to Filestore
4. Switch over hub to use filestore as homedirs
5. End downtime

I'd love for someone to help co-ordinate steps 1 and 5. I'll set up plan for 2 and possibly scripts for 3 and 4. This will be generally useful for z2jh as well.

**Comment by jhamman** [comment]
@yuvipanda - Hopefully you can coordinate with @dsludwig on this one. He's been developing Pangeo's hubploy and CI/CD infrastructure. Personally, I'd like to see us start working on a demo deployment (eg. hub.pangeo.io or demo.pangeo.io). Perhaps that is a good candidate for rapid development to occur in the short term and a replacement for pangeo.pydata.org in the longer term.

**Comment by yuvipanda** [comment]
@jhamman starting from new is going to be the easiest thing to do! Switching pangeo.pydata.org is gonna save you a ton of money in the short term though.

@dsludwig lmk how I can help!

**Comment by mrocklin** [comment]
@yuvipanda I think that we're probably going to be ok just removing the
pangeo.pydata.org deployment once the smaller domain-specific ones are up.
My hope is that some of our previous pain around managing user workspaces
goes away.  Probably not all of it though.

**Comment by jreadey** [comment]
Is it possible to have a per-user quota on the amount of NFS storage used?
The current EBS approach is wasteful since most users are using a small fraction of the volume, but on the other hand it prevents any one user from using up gobs of storage.

**Comment by yuvipanda** [comment]
@jreadey unfortunately there isn't, outside of monitoring usage and cutting it off / notifying whenever that gets too big. However, in practice it hasn't happened in the hubs I've run - but will be different for different use cases.

**Comment by jhamman** [comment]
@yuvipanda did this in https://github.com/pangeo-data/dev.pangeo.io-deploy/pull/28.
