### ISSUE TITLE
Welcome Anderson Banihirwe!

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#410]
I want to formally announce that Anderson Banihirwe (@andersy005) has joined the NCAR Pangeo team as of today!  

Anderson recently graduated from the University of Arkansas at Little Rock, in May 2018.  He spent a summer internship working for Quansight, and before graduating, Anderson was a 2017 SIParCS summer intern here at the NCAR Computational & Information Systems Laboratory.  

Please welcome Anderson to the Pangeo Community!

**Comment by mrocklin** [comment]
Welcome @andersy005 !

**Comment by jhamman** [comment]
Yes, welcome @andersy005 - glad your joining both the NCAR and Pangeo teams!

**Comment by andersy005** [comment]
Thank you for the introduction, @kmpaul! Thank you, @mrocklin, @jhamman for the warm welcome! I'm really glad to be part of this team. I hope to contribute to Pangeo project's future and success. I am looking forward to working with each and every one of you
