### ISSUE TITLE
Hanging Jupyter cell, Websocket problem: Fix or inform user of possible network problem

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#412]
When trying to access pangeo.pydata.org, or my own pangeo deployment from my corporate network, any notebook cell hangs when trying to execute it.

After wrongly raising some issue [here](https://github.com/dask/dask-kubernetes/issues/103), @mrocklin point me to the web socket problem. I also found some exchange in https://gitter.im/pangeo-data/Lobby about this:
@SimonKrughoff was having the same problem as me:
>I can log in, but any import hangs.

@rabernat pointed to network problems:
> what you are describing sometimes happens on restrictedly configured networks, something related to proxying

and @mrocklin confirmed:
>Yeah, that's the lack of websockets, Which many corporate networks restrict

What could we do about that?

@rabernat says:
>I really wish that Jupyter could detect this and let the user know

After some quick testing, this seems to be the case with former Jupyter notebook
![image](https://user-images.githubusercontent.com/17138587/46338123-a17ebb80-c62f-11e8-90fc-b290f40f47f8.png)

But not in Jupyterlab. Should we raise an issue upstream? Maybe @yuvipanda has something to say about this?

Should we document this potential problem somewhere, in pangeo.io docs or directly in Jupyterlab readme?

**Comment by guillaumeeb** [comment]
Interestingly enough, I can use notebooks on mybinder with dask-examples from my corporate network.

Main difference I see is the use of https instead of http. I don't think we've got more authorisation or goind to mybinder.org over pangeo.pydata.org.

**Comment by guillaumeeb** [comment]
Correction on the above about Jupyterlab not detecting this case, it just did, after a lot of time, don't know why...

![image](https://user-images.githubusercontent.com/17138587/46346167-70aa8080-c647-11e8-93b4-3b64c18571da.png)

**Comment by guillaumeeb** [comment]
Redeploying my pangeo cluster with HTTPS did solve the issue! 🎉 

As @rabernat said in https://github.com/pangeo-data/pangeo/issues/404#issuecomment-425979814, we need to modify jupyter_config.yaml, but also don't forget github oauth callback that needs to point to https instead of http.

**Comment by SimonKrughoff** [comment]
@guillaumeeb Thanks for looking into this.  I'll pass this on to my network people, but it sounds like the thing to do is to redeploy `pangeo.pydata.org` on https.

**Comment by yuvipanda** [comment]
I think opening an issue in github.com/jupyterlab/jupyterlab is appropriate. Glad switching to HTTPS fixed it!

**Comment by guillaumeeb** [comment]
Closing in favor of #482.
