### ISSUE TITLE
Questions on setting up polar.pangeo.io

### ISSUE THREAD

**Issue by NicWayand** [pangeo-data/pangeo#416]
Hello all, I have gotten a cluster running following the new guide at #402 (very helpful thank you!) and #373, but have two questions for further customizing it.

1) How to add notebooks: @jhamman pointed me to the `EXAMPLES_GIT_URL` env variable, but I am not sure where to change this. (I tried setting locally before deploying but it didn't grab it). I see its defined on the cluster, but not sure where this should be set/how to update an running cluster.

2) Best way to set domain name of polar.pangeo.io, and redirect(?) to the clusters external IP?

**Comment by jhamman** [comment]
@rabernat and I currently hold the keys to the dns settings so I can take care of (2). For 1, the examples path was once set in the docker image but I think with the refactor, we've moved away from this. @dsludwig can probably comment on how this should work now.

**Comment by guillaumeeb** [comment]
For (1), shouldn't you modify https://github.com/pangeo-data/pangeo/blob/master/gce/setup-guide/jupyter_config.yaml#L6 so that the env variable is taken into account in https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/prepare.sh?

I'm not sure if Docker images are rebuilt on cluster deployment?

**Comment by NicWayand** [comment]
Thanks @jhamman for setting up polar.pangeo.io! (note this is running on my trial GCP credits so won't do much right now).

@guillaumeeb yes that worked! And the docker images are apparently rebuilt when I redeploy after updating the `EXAMPLES_GIT_URL` variable.

**Comment by NicWayand** [comment]
How do I go about adding different packages to be available by default (without each user having to `conda install XXX`)?

Is the only way to [extent the current image ](https://zero-to-jupyterhub.readthedocs.io/en/stable/user-environment.html#customize-an-existing-docker-image)?

For example, I would like to automate:
```
conda install -c conda-forge proj4
conda install seaborn
conda install cartopy

pip install git+https://github.com/NicWayand/ESIO.git
```

**Comment by NicWayand** [comment]
Hi @dsludwig! Thanks for the suggestions. I am finally starting to understand the workflow, and am making some edits to the README.md [here](https://github.com/NicWayand/example.pangeo.io-deploy).

To be explicit (any maybe save others like me time), we are setting up the CircleCI to automate the deployment of the Helm, which will update each time someone make a commit. That is why [here](https://github.com/pangeo-data/example.pangeo.io-deploy) the instructions stop at step 2 (`/2_configure_kubernetes.sh`), where the existing [docs](https://github.com/arokem/pangeo/blob/more_setup_guide/docs/setup_guides/cloud.rst) keep going.

Where I am currently stuck is customizing the configuration files. In the  existing [docs](https://github.com/arokem/pangeo/blob/more_setup_guide/docs/setup_guides/cloud.rst) I set up two files ( `secret_config.yaml` and `jupyter_config.yaml`) that contained the config info used when deploying. When using CircleCI, I assume that the [staging.yaml](https://github.com/NicWayand/example.pangeo.io-deploy/blob/master/deployments/polar.pangeo.io/secrets/staging.yaml) file should be replaced with the contents of `secret_config.yaml`. But I am unsure where to put the config settings of  `jupyter_config.yaml`?

**Comment by dsludwig** [comment]
Yes, you should use a different image name (using your own project name). The CI script actually builds a custom image for you, based on the examples and environment that you have configured.

That image should be in a public-readable bucket (this is currently a constraint of hubploy, one of the automation pieces).

**Comment by NicWayand** [comment]
Thanks @dsludwig for all the help getting setup! The CircleCI is now successful and the [polar.pangeo.io](polar.pangeo.io) is now deployed.

However, when I start my server, I get a `CrashLoopBackOff` error when inspecting the GCP workload viewer. (`Back-off 1m20s restarting failed container=notebook pod=jupyter-nicwayand_staging(0b16b8d5-c8e3-11e8-a4d1-42010a8a00cb): CrashLoopBackOff`)

The log files of relevance are:
```
"/home/jovyan/binder/start: line 14: exec: start-singleuser.sh: not found
"cp: preserving times for '/home/jovyan': Operation not permitted
"JUPYTER_IMAGE_SPEC is not set
```
I when back to the default environmental.yml file, but same behavior. Any suggestions?

**Comment by NicWayand** [comment]
So I am pretty sure the above error is due to this [issue](https://github.com/jupyterhub/jupyterhub/issues/1083). But I am not sure where to add the below fix in the jupyter_config.yaml file? I tried [here](https://github.com/NicWayand/example.pangeo.io-deploy/blob/staging/deployments/polar.pangeo.io/config/staging.yaml#L42), but still get the same error. Can someone with more Jupyterhub config expertise help?

```
c.DockerSpawner.extra_create_kwargs = {
    "command": 'env PATH="/opt/conda/bin:$PATH" /usr/local/bin/start-singleuser.sh',
}
```

**Comment by jhamman** [comment]
@rabernat - I've added @NicWayand to our Google project allocation.

**Comment by NicWayand** [comment]
Thanks @rabernat and @jhamman! I will try to migrate the cluster over soon.

**Comment by NicWayand** [comment]
Closing as it's running now
