### ISSUE TITLE
Unable to access pangeo.pydata.org

### ISSUE THREAD

**Issue by jetesdal** [pangeo-data/pangeo#418]
I'm working with @rabernat and just joined the @pangeo-data organization on GitHub (Just joined @pangeo-data today following invitation by @rabernat). Currently, I am still unable to access pangeo.pydata.org. After I sign in with GitHub, I receive "403 : Forbidden" (see attached screenshot).
![screenshot 2018-10-03 16 17 16](https://user-images.githubusercontent.com/8991018/46437946-9066a500-c72a-11e8-9b55-5a63c332c1ab.png)

Is there anything I can do to grand access or does it take a while before I am registered?

**Comment by jhamman** [comment]
you need to set your organization affiliation to public: https://github.com/orgs/pangeo-data/people

**Comment by jetesdal** [comment]
OK got it. I'm able to access it now. Thanks!
