### ISSUE TITLE
login on pangeo plattform failed

### ISSUE THREAD

**Issue by Chiara7** [pangeo-data/pangeo#422]
Hello everyone, I tried to login on the pangeo plattform with my account as usual, but I just get the error
403 : Forbidden

when I renew the page I get the error:
400 : Bad Request
OAuth state missing from cookies

Does somebody know a reason, like an update or so, and if there is a certain time when it will work again? Thankyou very much

**Comment by rabernat** [comment]
Hi Chara--sorry for the glitch.

You should follow the instructions by Joe here: https://github.com/pangeo-data/pangeo/issues/404#issuecomment-426030386

In particular, you need to make your membership in the pangeo organization public.

**Comment by Chiara7** [comment]
Hi Ryan,
thank you very much for the link. I followed your instructions, my membership is now puplic and I have access again.
