### ISSUE TITLE
Add cartopy to the pangeo image

### ISSUE THREAD

**Issue by SimonKrughoff** [pangeo-data/pangeo#423]
I'm not sure what the formal way to request new packages is, but I would like to see [cartopy](https://scitools.org.uk/cartopy/docs/v0.16/) available from the standard kernel.

Is this the right forum for this request?

**Comment by SimonKrughoff** [comment]
I looked for mentions of `cartopy` in this repository and a readme suggests it should be available.  However, `import cartopy` in a notebook at pangeo.pydata.org results in a `ModuleNotFoundError`.  I would just install it in my `.local`, but it depends on Proj4 which needs to be compiled and I can't find a `gcc` in my environment.

**Comment by NicWayand** [comment]
As a temp solution, you should be able to open up a terminal on `pangeo.pydata.org` and run the below commands to get cartopy working. I will let others comment on the longterm solution.

```
conda install -c conda-forge proj4
conda install cartopy
```

**Comment by mrocklin** [comment]
@SimonKrughoff requests for adding packages to pangeo.pydata.org got to a point where we decided that we needed to split off and make several smaller deployments (see https://github.com/pangeo-data/pangeo/issues/373).  So I'm going to rephrase your request to the following:

>  I'd like to have an astro.pangeo.io deployment where I can control the full software stack for my users

@dsludwig has been working on infrastructure for this over at https://github.com/pangeo-data/example.pangeo.io-deploy and we're working to make it easier over time.  Would you be interested in going through this process with us?  We're looking for guinea pigs.

**Comment by SimonKrughoff** [comment]
Thanks both.  
@NicWayand that seemed to work!

@mrocklin we have a similar thing at https://github.com/lsst-sqre/jupyterlabdemo.  Maybe we could learn something from each other.

I don't have time right at the moment to be a guinea pig for a new deploy, but if it's useful for you, I could carve out some time in the relatively near future.

**Comment by mrocklin** [comment]
In https://github.com/pangeo-data/pangeo/issues/373#issuecomment-428201256 I propose that we just set things up for you and give you access to a github repository that has config files in it.  You would then be able to add `cartopy` to an environment.yml file and that would trigger various docker images to be built and deployments to be updated.  

I suspect that this will probably be pretty lightweight.  I think that @dsludwig is planning to set this up in the next few days.

**Comment by SimonKrughoff** [comment]
@mrocklin sounds great.  Thanks.
