### ISSUE TITLE
403 Forbidden, Requesting Access

### ISSUE THREAD

**Issue by peterbwewusa** [pangeo-data/pangeo#424]
Would like to access Jupyter Hub, for my research in a data science lab.

**Comment by andersy005** [comment]
@peterbwewusa, sorry about that. 

You should follow the instructions here #404 (comment)

> we have just changed access to pangeo.pydata.org to whitelist based on organization. Your affiliation with the pangeo-data organization needs to be public for this to work.

In particular, you will need to make your membership in the pangeo Github organization public.

**Comment by rabernat** [comment]
Is this resolved?

**Comment by peterbwewusa** [comment]
I set my email address to public, and I know my repositories are set to
public because I selected the free plan. But I am still receiving the 403
Forbidden error message, it is possible I misunderstood your instructions

**Comment by andersy005** [comment]
@peterbwewusa, it appears that you've not added yourself to this list: https://github.com/pangeo-data/pangeo/blob/master/docs/data/people.yml yet. You need to add your information to this list, and then submit a pull request to the pangeo repo for changes to take effect.

Once the pull request is merged by one of the admins, you will need to make your affiliation with pangeo Github organization public by going to this page and searching your username and changing your organization visibility to `public`.

![image](https://user-images.githubusercontent.com/13301940/47382248-0ec9bd80-d6bf-11e8-93cd-30154c0ec82a.png)

Let me know if you have any questions regarding this procedure

**Comment by rabernat** [comment]
@andersy005 - I think you might be confusing the membership on the website with the github org membership. These are currently two separate and unrelated lists. (I agree this is confusing!)

I have just added @peterbwewusa to the github org. That's what he needs to access pangeo.pydata.org.

**Comment by andersy005** [comment]
@rabernat, thank you for taking care of this, and for the clarification.  Indeed I've been confusing the two processes. ( I've always assumed that there was an automatic process in place that parses the `people.yml` file whenever it is updated, and updates github org members list). I just found that @jhamman' PR (https://github.com/pangeo-data/pangeo/pull/407) about this, never got merged. 

@peterbwewusa, I am sorry for the confusion.

**Comment by peterbwewusa** [comment]
@andersy005 @rabernat Thank you both for addressing my issue, but it seems I am still receiving the same error, should I carryout the process given by @andersy005 or is this something I will need to wait for before access is granted?

**Comment by andersy005** [comment]
@peterbwewusa, all you have to do now is make your affiliation public as illustrated in that image I attached in one my previous comments.

**Comment by jhamman** [comment]
@peterbwewusa - you have a pending invitation to join the pangeo-data organization. Once you accept that, you'll need to set your affiliation to public. It appears you accepted the invitation yet though.

**Comment by peterbwewusa** [comment]
Thank you all for your assistance, my issue is now resolved. 
@jhamman @andersy005 @rabernat
