### ISSUE TITLE
reduce the size of environment for documentation build

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#426]
In order to build the docs right now, travis needs to install hundreds of MB of conda packages:
https://travis-ci.org/pangeo-data/pangeo/builds/439793032#L1810

This is due to the following line in .travis.yml:
```
conda create -q -n docs-environment -c conda-forge -c intake python=$TRAVIS_PYTHON_VERSION intake intake-xarray
```

Apparently these are the dependencies that come with intake. Installing intake is necessary because of this code:
https://github.com/pangeo-data/pangeo/blob/b60e932f7307c4d484337d4da1e3842037362d51/docs/conf.py#L276-L277

which parses the intake catalog.

Is there a way we could reduce the size of the dependencies to make for smaller builds?

Related to #425 

cc @martindurant, @dsludwig

**Comment by dsludwig** [comment]
Adding `nomkl` should help reduce downloads by around 200 MB.

**Comment by jhamman** [comment]
I'm guessing xarray package is partially to blame: https://github.com/conda-forge/xarray-feedstock/issues/5. We will likely fix this in the next major release.
