### ISSUE TITLE
Membership to pangeo-data github

### ISSUE THREAD

**Issue by jameshawkes** [pangeo-data/pangeo#435]
Hi, would it be possible to become a member of the pangeo-data github organization so that I may try a demo of Pangeo on JupyterHub?

I am affiliated with ECMWF and researching possible solutions to cloud analytics of our data.

Thanks.

**Comment by scottyhq** [comment]
Hi @jameshawkes, you should be able to do this with Pangeo-Binder:
https://github.com/pangeo-data/cookiecutter-pangeo-binder 

Also see this step-by-step workflow for guidance:
https://github.com/pangeo-data/cookiecutter-pangeo-binder/issues/6 

Let us know how it goes!

**Comment by jhamman** [comment]
@jameshawkes - we can also add you to Pangeo github organization. You'll need to set your affiliation to public.
