### ISSUE TITLE
True divide issue on dask

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo#438]
I am trying to divide two arrays with different data types, an operation that goes through perfectly on my local machine. However, on the pangeo deployment `pangeo.pydata.org` I get the error : 

TypeError: ufunc true_divide cannot use operands with types dtype('float32') and dtype('<m8[ns]')

What should I do? Does the dask version on pangeo need to be upgraded?

*Input*
print(flux.data)
print('~~~~~~~~~')
print((time_ax.data))
​
flux.data/time_ax.data

*Output*
[ 0.09220999  0.1693505   0.23929575 ... 42.786396   42.772877
 42.84485   ]
~~~~~~~~~

[                 0    432000000000000    864000000000000 ...
 619920000000000000 620352000000000000 620784000000000000]

*Error:* 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-568e7007e413> in <module>()
      3 print((time_ax.data))
      4 
----> 5 flux.data/time_ax.data

TypeError: ufunc true_divide cannot use operands with types dtype('float32') and dtype('<m8[ns]')

**Comment by andersy005** [comment]
@dhruvbalwada, what dask version are you using on your local machine? You can get it with `dask.__version__`, and how about the one on pangeo too? 

Can you also provide a reproducible example (sample code)?

**Comment by rabernat** [comment]
In newer versions of numpy, it looks like you have to explicitly cast your datetime to a compatible type using `.astype`. See, for example, [this line](https://github.com/xgcm/xrft/blob/master/xrft/xrft.py#L263) in xrft.

For reference, this has nothing to do with dask, or pangeo. This is purely a numpy question.
