### ISSUE TITLE
Store notebooks on GCS

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#44]
If we get further into using Google compute engine for computation we'll need some place to store and manage notebooks.  When googling around for this I found https://github.com/danielfrg/s3contents which seems to imply that we can teach Jupyter notebooks to manage notebooks in storage systems like S3 or GCS, which might be convenient.

cc @danielfrg

**Comment by danielfrg** [comment]
Not sure what the context is but s3contents should work for a s3 jupyter notebook/lab storage backend.

gcs should be easy to add but harder to test unfortunately, I will give it a try

**Comment by mrocklin** [comment]
[gcsfs](http://gcsfs.readthedocs.io/en/latest/) is around, if that helps.  If I were to do this I would write the `s3contents` project in terms of a generic interface, test against, s3, and then hope that everything else that matched that interface worked as well.
