### ISSUE TITLE
Dev deployment of pangeo jupyterhubs

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#441]
We are now creating many pangeos. This is great! But unlike when we all shared a single JupyterHub, we don't have a centralized place to test out new functionality. 

This has come up in conversation with @yuvipanda in #401 and @rsignell-usgs in #145 (among other places).

My thought is that a dev/demo cluster would be of use to those of us actively developing/testing generic pangeo topics. It may also help us centralize our development whilst democratizing our deployments. 

Thoughts from concerned parties (@dsludwig, @yuvipanda, @mrocklin, @rsignell-usgs, @rabernat)?

**Comment by rsignell-usgs** [comment]
I would love to test out some hopefully-improved "base" environments for pangeo somewhere.  The current "base" pangeo environment is quite fragile, with a [pool of five channels to pull from and numerous pinned package versions](https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/Dockerfile#L13-L17).   

Instead, the environment can use conda-forge except for a few specific packages (e.g. intake, holoviews), which removes the need for pinning.  We have a version with the [same packages as the current pangeo.pydata.org](https://github.com/rsignell-usgs/helm-chart/blob/forge/docker-images/notebook/Dockerfile#L12-L66), and a version with [pyviz included](https://github.com/rsignell-usgs/helm-chart/blob/conda_pyviz/docker-images/notebook/Dockerfile#L12-L69)

These containers end up being about 0.5GB larger than the existing containers (3GB->3.5GB):
```
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
rsignell/pangeo-gcs-notebook-geoviews    2018-10-22          aa5ac36bbc7c        14 hours ago        3.497 GB
rsignell/pangeo-gcs-notebook             2018-10-22          3f849ba56d19        17 hours ago        3.39 GB
pangeo/notebook                          ede11f6             70ce76c45be3        4 weeks ago         2.944 GB
```

**Comment by rsignell-usgs** [comment]
Would one approach be for @dsludwig (or someone) to create a `dev.pangeo.io` and then folks submit  PRs to the `Dockerfile`/ `environment.yaml` and associated config to try different experiments?

**Comment by dsludwig** [comment]
A new dev instance setup here: https://github.com/pangeo-data/dev.pangeo.io-deploy
The branch `develop` deploys to `dev.pangeo.io, `staging` deploys to `staging.pangeo.io` and `prod` deploys to `hub.pangeo.io`.

**Comment by mrocklin** [comment]
@rsignell-usgs you have write privileges to that repository

**Comment by jhamman** [comment]
This is done so I'm going to close.
