### ISSUE TITLE
Request membership to pangeo-data

### ISSUE THREAD

**Issue by adityarn** [pangeo-data/pangeo#442]
Hello,

I would like to explore the pangeo tools for my research on the Southern Ocean.

I don't currently understand how the JupyterHub membership works. Is it free and open access for now? Can I use the cloud computing pangeo deployments for my scientific analysis?

**Comment by rabernat** [comment]
Welcome! I have just added you to the pangeo-members group. https://github.com/orgs/pangeo-data/teams/pangeo-members/members Once you make your affiliation public, you can access http://pangeo.pydata.org.

You are welcome to experiment. This service will probably change a lot soon. For oceanography in particular, we will soon launch ocean.pangeo.io.

**Comment by adityarn** [comment]
Thank you @rabernat ! I've really enjoyed using all the other tools, such as dask and xarray. Looking forward to the next iterations. Will be sharing my ipython notebooks soon too.

**Comment by adityarn** [comment]
I just checked, it seems like I have not been added. Could you please look into this again? Thanks!

**Comment by jhamman** [comment]
There is a pending invitation for your user name in the system. Please check again.
