### ISSUE TITLE
choose notebook resource options at login

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#445]
I suddenly find myself in need of a GPU node.

This makes me realize that it would be great if we could select some pod resource options from a pangeo cluster. Other options I would like to control would be number of CPUs and amount of memory. I imagine a dropdown menu with several different predefined machine types next to the "start my server" button.

This seems like a jupyterhub / kubspawner question. I tried searching for relevant docs / issues but couldn't find anything.

Maybe @yuvipanda or @choldgraf can point us in the right direction?

**Comment by rabernat** [comment]
Never mind, I found it! `profile_list`

https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html?highlight=profile_list

Closing in favor of #87.

**Comment by choldgraf** [comment]
@rabernat any ideas on where we could put this to be more discoverable?
