### ISSUE TITLE
How does one set up a Pangeo cloud deployment today?

### ISSUE THREAD

**Issue by raphaeldussin** [pangeo-data/pangeo#448]
@dsludwig could you point me to this?
thanks!

**Comment by dsludwig** [comment]
The instructions can be found here: https://github.com/pangeo-data/example.pangeo.io-deploy

**Comment by rabernat** [comment]
@raphaeldussin - I recommend using the environment I created for the ecco tutorial:
https://github.com/rabernat/pangeo_ecco_examples/tree/master/binder
as a starting point for the ocean.pangeo.io environment.

**Comment by raphaeldussin** [comment]
@rabernat @dsludwig first roadblock : 

Running 1_create_cluster.sh fails with : 

ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=The user does not have access to service account "default". Ask a project owner to grant you the iam.serviceAccountUser role on the service account.

**Comment by rabernat** [comment]
These are the roles you `raphael.dussin@gmail.com` had before:
- Kubernetes Engine Admin
- Security Reviewer
- Service Account Admin
- Storage Admin
- Viewer

I just added
- Service Account User

Let's see if it works?

**Comment by rabernat** [comment]
@raphaeldussin  - let me know once you have a deploy repo (like https://github.com/pangeo-data/astro.pangeo.io-deploy) for the new cluster and I will leave you some more specific ideas there.

**Comment by raphaeldussin** [comment]
it's building VMs now, will check in when it's all set (or at next roadblock)

**Comment by raphaeldussin** [comment]
creating the cluster crashes after a while : 

`MacBookPro:~/LDEO/PANGEO/pangeo/gce/setup-guide ./1_create_cluster.sh
pangeo-181919
Updated property [core/project].
WARNING: Starting in 1.12, new clusters will have basic authentication disabled by default. Basic authentication can be enabled (or disabled) manually using the `--[no-]enable-basic-auth` flag.
WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-certificate` flag.
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
WARNING: Starting in Kubernetes v1.10, new clusters will no longer get compute-rw and storage-ro scopes added to what is specified in --scopes (though the latter will remain included in the default --scopes). To use these scopes, add them explicitly to --scopes. To use the new behavior, set container/new_scopes_behavior property (gcloud config set container/new_scopes_behavior true).
Creating cluster ocean-pangeo-io-cluster in us-central1...done.
Timed out waiting for operation <Operation
 clusterConditions: []
 name: u'operation-1541431776601-2e2a5a97'
 nodepoolConditions: []
 operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
 selfLink: u'https://container.googleapis.com/v1/projects/464800473488/locations/us-central1/operations/operation-1541431776601-2e2a5a97'
 startTime: u'2018-11-05T15:29:36.601378732Z'
 status: StatusValueValuesEnum(RUNNING, 2)
 targetLink: u'https://container.googleapis.com/v1/projects/464800473488/locations/us-central1/clusters/ocean-pangeo-io-cluster'
 zone: u'us-central1'>
ERROR: (gcloud.container.clusters.create) Operation [<Operation
 clusterConditions: []
 name: u'operation-1541431776601-2e2a5a97'
 nodepoolConditions: []
 operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
 selfLink: u'https://container.googleapis.com/v1/projects/464800473488/locations/us-central1/operations/operation-1541431776601-2e2a5a97'
 startTime: u'2018-11-05T15:29:36.601378732Z'
 status: StatusValueValuesEnum(RUNNING, 2)
 targetLink: u'https://container.googleapis.com/v1/projects/464800473488/locations/us-central1/clusters/ocean-pangeo-io-cluster'
 zone: u'us-central1'>] is still running`

**Comment by rabernat** [comment]
Indeed I am seeing to failed clusters on the status page
https://console.cloud.google.com/kubernetes/list?project=pangeo-181919
![image](https://user-images.githubusercontent.com/1197350/48019236-ee5b2380-e100-11e8-80d8-98eaea6fecef.png)

When I click "status details" I see
> All cluster resources were brought up, but the cluster API is reporting that: component "kube-apiserver" from endpoint "gke-cd3cd901e5253f85ba56-8f6a" is unhealthy.

What could be going on here?

**Comment by raphaeldussin** [comment]
should I try to delete those clusters and start again ?

**Comment by rabernat** [comment]
Need advice from @dsludwig here...

**Comment by dsludwig** [comment]
When I've seen that in the past, it's been an intermittent error. Since it's been like that for a while, I'd suggest cleaning up and trying again.

**Comment by raphaeldussin** [comment]
cluster is up and running, starting deployment and hitting expected roadblock : 

> MacBookPro:~/LDEO/PANGEO/example.pangeo.io-deploy gcloud iam service-accounts keys create gcrkey --iam-account=raphael.dussin@gmail.com
ERROR: (gcloud.iam.service-accounts.keys.create) PERMISSION_DENIED: Permission iam.serviceAccountKeys.create is required to perform this operation on service account projects/-/serviceAccounts/raphael.dussin@gmail.com.

**Comment by jhamman** [comment]
I think @dsludwig has a service account setup that we can all share. If that works for this case, we should update the docs to account for this option.

**Comment by raphaeldussin** [comment]
any idea what that account might be ?

**Comment by raphaeldussin** [comment]
@dsludwig we can talk offline (rdussin @ ldeo . columbia . edu)

**Comment by raphaeldussin** [comment]
@dsludwig @rabernat the circleCI job worked. 2 questions however : 

1. How does one set up the loadbalancerIP ?
2. where do we add the jupyterhub configuration ?

**Comment by jhamman** [comment]
pinging @dsludwig and @NicWayand for some input here.

**Comment by NicWayand** [comment]
You can get the loadbalancerIP from within the GCP console by looking at the autohttps workloads for your ocean (filter by "ocean") cluster. @raphaeldussin I will direct message you the screen shot and IP.

**Comment by dsludwig** [comment]
I determine the load balancer IP from the proxy-public IP address, e.g.: [a search in Google Cloud](https://console.cloud.google.com/kubernetes/discovery?project=pangeo-181919&service_list_tablesize=50&service_list_tablequery=%255B%257B_22k_22_3A_22is_system_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22false_5C_22_22_2C_22s_22_3Atrue%257D_2C%257B_22k_22_3A_22metadata%252FclusterReference%252Fname_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22ocean-pangeo-io-cluster_5C_22_22_2C_22s_22_3Atrue%257D_2C%257B_22k_22_3A_22metadata%252Fname_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22proxy-public_5C_22_22%257D%255D)

I think @NicWayand's suggestion would also work.

You can put jupyterhub configuration in the "common.yaml" or "staging.yaml" files in the `config` directory, e.g. https://github.com/pangeo-data/example.pangeo.io-deploy/blob/staging/deployments/example.pangeo.io/config/common.yaml

**Comment by rabernat** [comment]
At some point we will need to make a DNS entry for ocean.pangeo.io no? @jhamman how have you been handling the DSN provisioning for the other clusters?

**Comment by jhamman** [comment]
I've been doing all these myself. Takes about 20 seconds at this point.
