### ISSUE TITLE
Formal benchmarks

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#45]
At this point we have several different platforms working and a few different use cases. It’s time to start thinking about organizing benchmarks more formally. We need to define

- What we want to measure? Just runtime, or more fine-grained detail?
- What parameters to vary? (n_workers, n_threads, etc.)
- How to automate this? (Shell script, airspeedvelocity, etc.)

Thoughts?

**Comment by mrocklin** [comment]
I'm interested in this, but I suspect that it is not on the critical path right now.  The impression I've gotten is that we should focus more on attracting users than on performance.

**Comment by rabernat** [comment]
Recruiting more users is definitely important. I would like to improve the docs a bit before we really push on that.
