### ISSUE TITLE
Request pangeo membership

### ISSUE THREAD

**Issue by h4gen** [pangeo-data/pangeo#451]
Hi everyone!

First, let me thank you for the amazing work you are doing here. What you guys build up here is what I always head in mind when I thought of modern data science. I am currently getting hands on with the whole kubernetes/jupyterhub topic and would like to peek into your running cluster in the meantime. Therefore it would be nice if you could add me to your org. Thank you very much!

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation a\nd set your affiliation to public for this to take effect.

**Comment by h4gen** [comment]
@jhamman Sorry to bug you but I got no invitation :(
