### ISSUE TITLE
Request membership to pangeo-data

### ISSUE THREAD

**Issue by giswqs** [pangeo-data/pangeo#452]
Hello pangeo team,

Thank you for developing the amazing pangeo framework! I have been reading many posts about pangeo on Medium (e.g., [1](https://medium.com/pangeo/cloud-native-geoprocessing-of-earth-observation-satellite-data-with-pangeo-997692d91ca2), [2](https://medium.com/pangeo/nasa-access-c3515a44f31b), [3](https://medium.com/pangeo/pangeo-meets-binder-2ea923feb34f)), and I am really excited about this new platform. I use Google Earth Engine (GEE) intensively for my research. However, GEE is could not directly handle data stored on the clouds other than its own data catalog. The capability of pengeo for cloud native geoprocessing is exciting! Therefore, I would like to request membership to pangeo-data and try out this new platform. I would be more than happy to provide feedback for potential improvement of the platform. Many thanks!

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation a\nd set your affiliation to public for this to take effect.
