### ISSUE TITLE
Request membership to pangeo data

### ISSUE THREAD

**Issue by valentina-s** [pangeo-data/pangeo#456]
Hello pangeo-team,

I am giving a presentation to acoustic oceanographers on the power of jupyter notebooks, so I want to use pangeo to demonstrate some examples of handling big datasets in the cloud.

Thanks a lot!

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation a\nd set your affiliation to public for this to take effect.
