### ISSUE TITLE
Request for Access to PanGeo JupyterHub Instance

### ISSUE THREAD

**Issue by synflyn28** [pangeo-data/pangeo#457]
All,

I am a developer/contractor at NOAA's National Centers for Environmental Information and I would like a Pangeo JupyterHub account in order to keep up with technologies like xarray and data processing techniques for remote sensing data. Thanks!

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation a\nd set your affiliation to public for this to take effect.
