### ISSUE TITLE
Request access to Pangeo Jupyter hub

### ISSUE THREAD

**Issue by asiddi24** [pangeo-data/pangeo#459]
Hi ! 
I am a grad student working in Physical oceanography just starting out my research. I am trying to explore the ECCO V4r3 for my research and am interested in accessing the data-set via the cloud deployment. Can you kindly provide access to me for doing so ? It'd be of great help.
Thanks !

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation a\nd set your affiliation to public for this to take effect.
