### ISSUE TITLE
Request access to Pangeo JupyterHub

### ISSUE THREAD

**Issue by jwagemann** [pangeo-data/pangeo#461]
Hi,
I am a PhD candidate working on Big data technologies for meteorological and climate data. I am interested in trying out Pangeo and potentially deploy it on a Amazon Web Service. I would like to set up a use case with ECMWF / Copernicus data, ERA5/ERA-Interim and Seasonal forecast data in concrete terms.
Would be great if you could grant me access to the JupyterHub instance.
Thanks!

**Comment by mrocklin** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!
