### ISSUE TITLE
Geoinformatics postdoc opportunity at USGS

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#462]
@Pangeans, there is a [Geoinformatics Postdoc Opportunity at USGS](https://geology.usgs.gov/postdoc/opps/2019/17-18%20Signell.htm) to explore applications and challenges of Pangeo on USGS workflows.   

The announcement doesn't explicitly say Pangeo (as that was removed by the editors) but that's definitely what we were thinking when we wrote the announcement!

Note that position this is limited to folks who have received their PhDs within the last 5 years and are either: "U.S. citizens; a person who owes allegiance to the U.S.; or a person who is lawfully admitted for permanent residence and is seeking U.S. citizenship".

Please spread the word!

**Comment by jhamman** [comment]
@rsignell-usgs - is this position still open?

**Comment by rsignell-usgs** [comment]
Because of the US Government Shutdown, postdoc applications have been extended to Feb 19:
https://www.usajobs.gov/GetJob/ViewDetails/515821600
