### ISSUE TITLE
Access to the pangeo JupyterHub

### ISSUE THREAD

**Issue by derpyninja** [pangeo-data/pangeo#465]
Hi!
I am a student at the Vienna University of Technology and besides affiliated with the Research Group for Climate and Environmental Remote sensing. I would love to give [your data analysis platform](http://pangeo.pydata.org/hub/login) a try. 
Cheers, 
Felix

**Comment by rabernat** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!
