### ISSUE TITLE
Proccessing thousands of GRIB files on Cheyenne via dask and xarray

### ISSUE THREAD

**Issue by edougherty32** [pangeo-data/pangeo#466]
Hi, 

I am attempting to open and analyze thousands of GRIB files (downloaded from [here](https://data.eol.ucar.edu/dataset/21.093), with the extension ".h")  of Stage-IV rainfall data (~4.75 km resolution) over ~10 years on Cheyenne using Pangeo and dask. 

I launch Pangeo and dask as specified [here](http://pangeo.io/setup_guides/hpc.html) (under Deploy Option 1) and read in the Grib files the following way:

```
import pygrib
import threading

pcp_list = []

for c, item in enumerate(date_list_fflood_sub):  
    print(c)
    for name in glob.glob('/glade/scratch/doughert/stage_iv/**/ST4.**.01h'):
        if item in name:
            match = xr.open_dataset(name, engine = 'pynio', lock=threading.Lock())
            pcp= match['A_PCP_GDS5_SFC_acc1h']
            pcpnan = pcp.where((centroid_lon_sub[c]-5 <= pcp.g5_lon_1) & 
                               (pcp.g5_lon_1 <= centroid_lon_sub[c]+5)
                             & (centroid_lat_sub[c]-5 <= pcp.g5_lat_0) &  
                               (pcp.g5_lat_0 <= centroid_lat_sub[c]+5), 
                                drop=False)
            pcp_list.append(pcpnan)
```

This code opens the Stage IV rainfall data when it matches a date of a flood and pulls the relevant precipitation data, turns all values beyond the flood domain into NaN's, then appends to a list. 

The issue I have is that I can run this portion of the code, but anything beyond this, and my code stops running, with the following message on the command line:

`qsub: job 3361059.chadmin1 completed`

This is despite the code only running for 1 h, which is far less than the 6 h of walltime I specify in my initial qsub and when I launch dask-jobqueue. This suggests a memory error to me, though I am not sure what specifically is the issue. 

Does anyone have suggestions as to why this might occur and how to resolve this issue?

**Comment by rsignell-usgs** [comment]
On our local HPC, interactive jobs are limited to one hour.   Could it be that even though you requested 6 hours, they cut you off after 1 hour?

**Comment by edougherty32** [comment]
@rsignell-usgs That is good idea, but I have run interactive jobs on Cheyenne before that last up to 8 hours. They allow [interactive jobs](https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/submitting-jobs-pbs#scripts) up to 12 hours.

**Comment by jhamman** [comment]
@edougherty32 -

I think the default wall time on cheyenne is now 1 hour.  So if you are just using `qinteractive` that could be one problem.

Another comment. Xarray has recently gained a new grib backend (cfgrib). I wouldn't be surprised if this works much better than pynio. Its on xarray's master branch but you may think about giving it a try.

**Comment by edougherty32** [comment]
@jhamman 

I am using qsub command to specify the walltime for my interactive job, so I don't think that is the issue necessarily. 

That's great to know–thanks! I'll check that out.

**Comment by ahuang11** [comment]
Maybe you could create a list of all the files you want to read in first:

fi_list = []
```
for c, item in enumerate(date_list_fflood_sub):  
    print(c)
    for name in glob.glob('/glade/scratch/doughert/stage_iv/**/ST4.**.01h'):
        if item in name:
              fi_list.append(item)
```
Then do a

`ds = xr.open_mfdataset(fi_list, engine='pynio')`

**Comment by edougherty32** [comment]
Good idea, @ahuang11! However, I was able to get this working, by setting 

`autoclose=True`

in the xr.open_dataset argument. This seemed to resolve the issue.
