### ISSUE TITLE
Pangeo tutorial at AGU 2018 Fall Meeting

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#468]
@rabernat and I are hosting a Pangeo tutorial at AGU this year. The full announcement is here: https://medium.com/pangeo/pangeo-agu-workshop-d9565667ad48. Registration fee can be waived if you sign up via this link. Please distribute broadly!

**Comment by rsignell-usgs** [comment]
@jhamman  and @rabernat, I was considering signing up because I'd be interested to see how it's taught and what the response of the attendees is like, but didn't want to take the place of a potential pangean-to-be.   Thoughts?

**Comment by jhamman** [comment]
My understanding is that we'll have up to 100 seats. At this point, I'd be surprised if we fill to capacity.

**Comment by rsignell-usgs** [comment]
I was unable to sign up for the workshop today via [the workshop web page](https://fallmeeting.agu.org/2018/scientific-workshops/) (seems you can no longer modify your registration), but I was able to call and sign up over the phone:
Phone: 703-449-6418 (International) or 866-470-7778 (within the United States)

**Comment by ktyle** [comment]
One of our grad students signed up via the Medium link but was not sure how to proceed from there. Should he just call the registration telephone # and mention the fee waiver link?

**Comment by jhamman** [comment]
Hi @ktyle - he should be registered now. We sent the list off a few days ago. We'll try to get an email out to participants later this week.
