### ISSUE TITLE
Access to pangeo JupyterHub

### ISSUE THREAD

**Issue by MHee** [pangeo-data/pangeo#472]
Hi,
I am a Staff Scientist with [Ocean Networks Canada](http://www.oceannetworks.ca/data-tools) and am very interested in promoting the use of the pangeo ecosystem for the effective use of our large ocean data archive.

I would like to have access to the pangeo JupyterHub, to test and demo possible workflows with our data.

Hope to meet you at AGU.

Cheers,
Martin

**Comment by rabernat** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!
