### ISSUE TITLE
Request access to Pangeo

### ISSUE THREAD

**Issue by jo-chemla** [pangeo-data/pangeo#473]
Hi,
I am CTO of Iconem, a startup dedicated to building 3D models of endangered archaeological sites, monuments and cities - Middle East (Mosul, Palmyra, ...), Southeast Asia (Cambodia, India, ...), North Africa (Egypt, Sudan, ...)... I am interested in trying out Pangeo especially for the mapping of city-scale areas damaged by conflict as we are doing with UNESCO (Mosul, Aleppo, Damascus, Kabul, ...). Extracting layers of information such as buildings contours, roads and infrastructure, and comparing with data captured at different dates, from our orthos/pointclouds directly on a JupyterHub instance would be great.
Thanks a lot!

**Comment by rabernat** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!
