### ISSUE TITLE
weekly checkin meeting 2018-11-13 4p UTC (11a EST, 8a PST)

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#474]
We will have our usual checkin meeting tomorrow morning at http://appear.in/pangeo

Some of the topics issues on the agenda for tomorrow:

- updates on new Pangeo Jupyterhub deployments
- Pangeo Tutorial at AGU
- Pangeo Intake Catalogs

Notes from past meetings: http://pangeo.io/meeting-notes.html

**Comment by arokem** [comment]
Hi folks. I was really hoping to join tomorrow, but that time is really hard for me to make, so it looks like it's not happening this time. I don't have much to report anyway -- still need to follow up on #399, but haven't had the bandwidth in the last couple of weeks to work on it.
