### ISSUE TITLE
Coordination between administrators of example.pangeo.io deployments

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#476]
In today's weekly checkin (#474), we discussed how it may be useful to better connect the people running pangeo JupyterHubs to share experiences and to identify possible developments that would benefit all deployments.

Just to list current deployments and who is working on them:

- example.pangeo.io: @dsludwig and @rsignell-usgs 
- hydroshare.pangeo.io: @bartnijssen and @jhamman 
- polar.pangeo.io: @NicWayand 
- astro.pangeo.io: @SimonKrughoff and @wtbarnes 
- atmos.pangeo.io:  @charlesbluca and @biasuttimic
- neuro.pangeo.io: @arokem
- ocean.pangeo.io: @raphaeldussin

Each of these deployments are at varying levels of operation and completeness but there is a growing knowledge base that would be good to consolidate.

For example, @NicWayand and @dsludwig are the only two (to my knowledge) that have set one of these up from scratch. @raphaeldussin is about to embark on this himself. 

Other issues that are on the near term horizon include:

- porting to AWS (@amanda-tan and @apawloski)
- shared file systems via NFS mounts (@yuvipanda)

I want to make sure we're all seeing these developments and sharing information/documentation as best as possible.

**Comment by NicWayand** [comment]
Thanks Joe for connecting here!

One question I have been meaning to ask that may be relevant to others here is:

How do you set the README.md file (or any file) to be already open by default (so the user doesn't have to click on it)?

**Comment by apawloski** [comment]
I've been building out automation for the AWS resources below the helm layer (VPC, IAM, EC2, EKS). https://github.com/Element84/pangeo-deployment

This also has scripts for deploying jupyterhub, but while it deploys, I suspect I need better configuration information before that layer works. My goal is to keep that consistent with the other pangeo deployments (i.e. everything after the base infrastructure will be the same.)

**Comment by jhamman** [comment]
I'm going to keep this open. I'd still like to move atmos/astro/polar over to pangeo-cloud-federation.

**Comment by rabernat** [comment]
👍 

I just deleted the old ocean cluster.

atmos, astro, and polar should all move to the same gke cluster.

**Comment by jhamman** [comment]
For atmos/astro, would it make sense to port their notebook images to pangeo-stacks and then just add those images to hub.pangeo.io? I'm getting the feeling that those hubs aren't being used much.
