### ISSUE TITLE
Timing of weekly checkin meeting

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#477]
We currently have a recurring checkin meeting scheduled for 4p UTC (8a PST). This time seems to be difficult for folk on the US west coast to make. In our meeting this morning, I brought up the idea of alternating times for this meeting so we can get the west coasters to attend. That idea was generally accepted. So I'm proposing changing our meeting time on alternating weeks with an early meeting one week for our European colleagues and a late meeting for our west coast colleagues the next. 

For those of you that would generally attend these meetings, please fill out the following two forms. We'll stick with Wednesday:

Early Meeting: http://whenisgood.net/pangeo-early
Late Meeting: http://whenisgood.net/pangeo-late

I'm specifically hoping @arokem, @amanda-tan, and @NicWayand can join more regularly.

**Comment by mrocklin** [comment]
cc'ing folks in European time zones cc @niallrobinson @guillaumeeb @jacobtomlinson

**Comment by NicWayand** [comment]
I fully agree (usually fielding airborne Cheerios at 8am PST...). Voted for times.

**Comment by guillaumeeb** [comment]
That's perfectly fine for me!

**Comment by jacobtomlinson** [comment]
Fine with me!

**Comment by jhamman** [comment]
Just reviewed the results from the poll.

- The early meeting will stay at 4p UTC (8a PT, 11a ET).
- The late meeting will move to 8p UTC (12p PT, 3p ET).

For this week, we'll stick with the early time slot and start the late meeting the following Wednesday (Nov 28).
