### ISSUE TITLE
Request access to Pangeo

### ISSUE THREAD

**Issue by abkfenris** [pangeo-data/pangeo#480]
Hi,

I'm a developer for the Gulf of Maine Research Institute. We're trying to figure out what we might want to do for a more structured computing system, and I'd love to have access to Pangeo to demo an option.

Thanks,
-Alex

**Comment by rabernat** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!

Note that there are lots of oceanographers here. We are currently in the process of setting up ocean.pangeo.io (see #448).

**Comment by abkfenris** [comment]
Awesome, thanks. I've been lurking and watching the process of ocean.pangeo.io. 

I'm hoping I can get some folks from the lab to go to the AGU workshop.
