### ISSUE TITLE
Move all *.pangeo.io to HTTPS

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#482]
I didn't find a dedicated issue to this, and this have been quite a problem for me in several occasions. Maybe it's a french thing to have corporate proxies that messes up with websocket, but I've often trouble to make a proper Pangeo demo due to this, see #412.

I'm not sure in which state we are on this issue. From my point of view, this is a somehow easy fix, but it may be hard to generalize to all separate platforms. Maybe we could start on dev.pangeo.io and binder.pangeo.io?

Sorry if this is clearly identified in another place.

**Comment by guillaumeeb** [comment]
See also #404.

**Comment by jhamman** [comment]
dev.pangeo.io already uses https. For binder, we were blocked due to some kubernetes version issues but this may be sorted out now: https://github.com/pangeo-data/pangeo-binder/issues/11

**Comment by guillaumeeb** [comment]
Ok that's great, sorry I haven't tried dev.pangeo.io yet.

Can we keep this open at least until binder.pangeo.io uses https?

Another point, is https configuration documented somewhere for building new pangeo clusters?

**Comment by jhamman** [comment]
@guillaumeeb - I think this detail falls under zero to jupyterhub. @dsludwig setup the dev.pangeo.io deployment using letsencrypt: https://github.com/pangeo-data/example.pangeo.io-deploy/blob/7fa7a2438d0ac5b06aab392a59164a31a337bbc5/deployments/example.pangeo.io/config/staging.yaml#L3-L7

**Comment by guillaumeeb** [comment]
Thanks @jhamman, this is perfect and totally sufficient if this is in example.pangeo.io-deploy repo config file! 

Sorry again, should have looked at it first.

**Comment by jhamman** [comment]
I think we can close this now. The new hubs and the binder deployment are all on https now.
