### ISSUE TITLE
Request for access to Pangeo JupyterHub

### ISSUE THREAD

**Issue by zaneselvans** [pangeo-data/pangeo#483]
Hello! I'm a developer working on an open platform for US energy and electricity data, to provide access to climate advocates, journalists, academic researchers, and others acting in the public interest. It's over here: https://github.com/catalyst-cooperative/pudl

We have accumulated ~100GB of data at this point, and it's getting to be too much for people to easily shuffle around, and it's not reasonable to expect all users to install our data processing pipeline and run it on their local machines, so we're exploring ways to make it easily accessible in a computationally useful context, and something like JupyterHub + a bunch of pre-installed data seems pretty much perfect... and then today I came across Pangeo, which is exactly that. I'd like to get a little more familiar with the deployment and using the platform before we try and do it on our own.

**Comment by rabernat** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!

Your project sounds fascinating. This is exactly the type of application we envision for Pangeo. Please have a look and then feel free to open new issues to discuss the specifics of your use case.

Also note that pangeo.pydata.org is getting a bit stale. We are planning to shut it down soon and replace it with something more specialized (see #373).
