### ISSUE TITLE
Pangeo happenings at the 2018 AGU Fall Meeting

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#484]
Hi everyone, the 2018 AGU Fall Meeting in Washington, D.C. is just a few weeks away. In this issue, I plan to help coordinate some Pangeo community happenings. I'll keep updating these lists as more details become available. Feel free to suggest edits.

### Pangeo Workshop / Tutorial

@rabernat and I are hosting a Pangeo tutorial at AGU this year. The full announcement is here: https://medium.com/pangeo/pangeo-agu-workshop-d9565667ad48. Registration fee can be waived if you sign up via this link. Please distribute broadly!

Time: Wednesday, 12 December 8:00 a.m.-12:20 p.m.

See also #211 

### Dinner and/or Happy Hour

I'm proposing happy hour and/or dinner on Tuesday December 11, 2018. Exact time and location TBD. 

### AGU at EarthCube Booth
We are signed up for a few 30 minute demos of Pangeo at the Earth Cube booth. Current times are:
- Tuesday December 11, 2018: 11a
- Thursday December 13, 2018: 2p

### Talks and Posters
I spent a few minutes grabbing Pangeo-like talks/posters from the program. It may be worth moving this list to a blog post right before the meeting. Please feel free to comment below if I missed your talk.

- WS22 Pangeo: Scalable Geoscience Tools in Python—Xarray, Dask, and Jupyter
  - Wednesday, 12 December 2018  08:00 - 12:20 Grand Hyatt - Independence FGHI
- IN54A-05 Pangeo: Community tools for analysis of Earth Science Data in the Cloud
  - Anthony A Arendt1, Joseph Hamman2, Matthew Rocklin3, Amanda Tan2, Dennis Robert Fatland4, Jonah Joughin5, Ethan D Gutmann6, Landung Setiawan7 and Scott T Henderson8, (1)Applied Physics Laboratory University of Washington, Seattle, WA, United States, (2)University of Washington, Seattle, WA, United States, (3)Anaconda, Inc., Austin, TX, United States, (4)Unversity of Washington, Seattle, WA, United States, (5)Applied Physics Laboratory University of Washington, Seattle, United States, (6)National Center for Atmospheric Research, Boulder, CO, United States, (7)University of Washington, Applied Physics Lab, Seattle, WA, United States, (8)University of Washington Seattle Campus, Seattle, WA, United States
  - Friday, 14 December 2018  17:00 - 17:15 Walter E Washington Convention Center - 209A-C
- IN53A-03 Pangeo and Binder: Scalable, shareable and reproducible scientific computing environments for the geosciences
  - Joseph Hamman, University of Washington, Seattle, WA, United States, Ryan Abernathey, Lamont -Doherty Earth Observatory, Palisades, NY, United States, Chris Holdgraph, University of California, Berkeley, Berkeley Institute for Data Science, Berkeley, CA, United States, Yuvi Panda, University of California, Berkeley, Berkeley Institute for Data Science, Berkeley, CO, United States and Matthew Rocklin, Anaconda, Inc., Austin, TX, United States
  - Friday, 14 December 2018  14:10 - 14:25 Walter E Washington Convention Center - 209A-C
- IN54A-06 Ocean Modeling Simulation, Analysis and Visualization in the Cloud
  - Richard P Signell, USGS Coastal and Marine Science Center Woods Hole, Woods Hole, MA, United States
  - Friday, 14 December 2018  17:15 - 17:30 Walter E Washington Convention Center - 209A-C
- IN52A-08 What Interdisciplinary Research, Heterogeneous Data, and Netflix have in common: Leveraging Open Data and the Cloud to Increase Data Access and Use with Ephemeral Archives of Convenience
  - Daniel Pilone1, Nate Pauzenga1, Drew Daniel1, Nelson Marehalau1, Matthew O'Brien1 and Andrew Pawloski2, (1)Element 84, Inc., Alexandria, VA, United States, (2)Element 84, Inc., Alexandria, United States
  - Friday, 14 December 2018  12:05 - 12:20 Walter E Washington Convention Center - 209A-C
- ED51C-0684 Environmental Data-Driven Inquiry and Exploration (Project EDDIE): Successes and challenges using large online datasets to build quantitative reasoning
  - Dax Christian Soule, CUNY Queens College, Flushing, NY, United States, Timothy J Crone, Lamont -Doherty Earth Observatory, Palisades, NY, United States, Catherine O'Reilly, Illinois State University, Department of Geography-Geology, Normal, IL, United States, Cailin Huyck Orr, Carleton College, Northfield, MN, United States and Friedrich Knuth, University of Washington Seattle Campus, Seattle, United States
  - Friday, 14 December 2018  08:00 - 12:20 Walter E Washington Convention Center - Hall A-C (Poster Hall)
- IN51B-0584 Scalable, cloud-based WRF simulations and analysis with community climate and reanalysis datasets
  - Luke Madaus, Jupiter, Earth and Ocean Systems, Boulder, CO, United States, Joshua Hacker, Jupiter, Boulder, CO, United States and John Exby, Jupiter, Boulder, United States
  - Friday, 14 December 2018  08:00 - 12:20 Walter E Washington Convention Center - Hall A-C (Poster Hall)
- IN33A-06 Beyond netCDF: Cloud Native Climate Data with Zarr and XArray
  - Ryan P Abernathey, Lamont -Doherty Earth Observatory of Columbia University, Palisades, NY, United States
  - Wednesday, 12 December 2018  14:55 - 15:10 Walter E Washington Convention Center - 209A-C
- IN41F-0892 A tale of two clusters: Working with lots of weather radar data bridging research and operations.
  - Scott M Collis1, Giri Prakash2, Robert Clyde Jackson1, Jitendra Kumar3, Zachary Sherman4 and Bhargavi Krishna2, (1)Argonne National Laboratory, Argonne, IL, United States, (2)Oak Ridge National Laboratory, Oak Ridge, TN, United States, (3)ORNL, Climate Change Science Institute, Environmental Science Division, Oak Ridge, TN, United States, (4)Argonne National Laboratory, Argonne, United States
  - Thursday, 13 December 2018  08:00 - 12:20 Walter E Washington Convention Center - Hall A-C (Poster Hall)
- IN41F-0899 Community Data Management Systems for CMIP6
  - Denis Nadeau, Dean Norman Williams, Charles Doutriaux and Tanya J Reshel, Lawrence Livermore National Laboratory, Livermore, CA, United States
  - Thursday, 13 December 2018  08:00 - 12:20 Walter E Washington Convention Center - Hall A-C (Poster Hall)
- NS53A-0548 Xarray-simlab: a Python package to build, customize and run computational models interactively
  - Benoit Bovy, Université de Liège, Liege, Belgium and Jean Braun, Universite Joseph Fourier, Grenoble, France
  - Friday, 14 December 2018  10:45 - 10:50 Marriott Marquis - Marquis 12-13
  - Friday, 14 December 2018  13:40 - 18:00 Walter E Washington Convention Center - Hall A-C (Poster Hall)
- NS53A-0544 Taking Geostationary Lightning Mapper data to the community with Python
  - Eric C Bruning, Texas Tech University, Lubbock, TX, United States, Julien Chastang, University Corporation for Atmospheric Research, Boulder, CO, United States and Tom Yoksas, UCAR, Unidata, Boulder, CO, United States
  - Friday, 14 December 2018  08:25 - 08:30 Marriott Marquis - Marquis 12-13
  - Friday, 14 December 2018  13:40 - 18:00 Walter E Washington Convention Center - Hall A-C (Poster Hall)
- NS53A-0561 Obsplus: A Pandas-Centric ObsPy Expansion Pack
  - Derrick JA Chambers, Centers for Disease Control and Prevention, Spoakne, WA, United States
  - Friday, 14 December 2018  08:05 - 08:10 Marriott Marquis - Marquis 12-13
  - Friday, 14 December 2018  13:40 - 18:00 Walter E Washington Convention Center - Hall A-C (Poster Hall)
- IN54A-07 Accessing data stored in Amazon S3 via the Hyrax OPeNDAP server
  - James H R Gallagher, Nathan Potter and David W Fulker, OPeNDAP, Inc., Butte, MT, United States
  - Friday, 14 December 2018  17:30 - 17:45 Walter E Washington Convention Center - 209A-C
- ED53E-0762 Out of RAM? Practical First Steps for Accelerating Research
  - Amanda Tan, University of Washington, Seattle, WA, United States, Catherine Kuhn, University of Washington Seattle Campus, School of Environmental and Forestry Sciences, Seattle, WA, United States and Dennis Robert Fatland, Unversity of Washington, Seattle, WA, United States
  - Friday, 14 December 2018  13:40 - 18:00 Walter E Washington Convention Center - Hall A-C (Poster Hall)

**Comment by rabernat** [comment]
Thanks Joe! This is a great list!

I would slightly favor a get-together on Wednesday, but Tuesday works for me too.

**Comment by NicWayand** [comment]
Tuesday and Wednesday evening both work for me for :beers:!

**Comment by rsignell-usgs** [comment]
I'm placing my vote for Pangeo dinner Tuesday night, as on Wednesday night I'd like to attend (and hopefully present) at Ignite@AGU at Busboys and Poets , co-hosted by NASA’s Applied Sciences Program and ESIP:   https://www.esipfed.org/igniteagu2018

**Comment by rabernat** [comment]
Given @rsignell-usgs's constraints, let's go with Tuesday night for Pangeo get-together.

Any suggestions for a venue?

**Comment by rsignell-usgs** [comment]
https://www.yelp.com/search?find_desc=good+for+groups&find_loc=convention+center%2C+dc&ns=1

**Comment by rabernat** [comment]
Rich, if you have time, it would be awesome if you would just pick a spot and make a reservation for ~20 people. Joe and I will cover as much of the tab as possible from the Pangeo workshop stipend $ we are getting. Keep in mind that @lheagy's OSS forum is 18:15 - 19:15 on Tuesday, and many of us plan to attend that. So our dinner should be after.

**Comment by rsignell-usgs** [comment]
Okay, I propose The Capital Burger, right across from the Convention Center at 7:30. 
Has a decent [4 stars on yelp](https://www.yelp.com/biz/the-capital-burger-washington-5 and noise level is listed as "average").  Can't book a table bigger than 15 without a contract for a minimum spend of $30 so let's get a head count:

If you plan to attend, can you just give a thumbs up here?

**Comment by rabernat** [comment]
Thanks so much for taking this on! Really appreciate your help.

**Comment by gidden** [comment]
Hi all, hey @jhamman - I inadvertently started a parallel effort on the [xarray listserv](https://groups.google.com/forum/#!topic/xarray/4QCxp7rIeac) for happy hour/dinner. I'm suggesting we all coalesce here. Looking forward to seeing some faces I know, as well as new ones!

**Comment by tjcrone** [comment]
cc @hpmarshall
