### ISSUE TITLE
Request for access to Pangeo JupyterHub

### ISSUE THREAD

**Issue by gmaze** [pangeo-data/pangeo#485]
Hi all,
I'm a physical oceanographer at Ifremer/LOPS, could I have access to the JupyterHub please ?
I'm currently developing [pyXpcm](https://github.com/obidam/pyxpcm), a machine learning library to mine collection of oceanic profiles and consuming xarray objects. I'd like to test it on the xarray/dask cluster through the hub.
Thanks !
Guillaume

**Comment by rabernat** [comment]
Welcome Guillaume!

You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.


Your project sounds fascinating. This is exactly the type of application we envision for Pangeo. Please have a look and then feel free to open new issues to discuss the specifics of your use case. @NickMortimer of CSIRO has been playing around with cloud storage of ARGO data. You may wish to touch base with him.

Also note that pangeo.pydata.org is getting a bit stale. We are planning to shut it down soon and replace it with something more specialized (see #373).

**Comment by NickMortimer** [comment]
Great I also have funding for a pangeo/hackathon in Hobart in May would be great to work together. Intact I’m in Hobart sail on Friday morning would be great to catch up and talk

Nick

Sent from my iPhone

On 19 Nov 2018, at 9:51 am, Ryan Abernathey <notifications@github.com<mailto:notifications@github.com>> wrote:


Welcome Guillaume!

You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Your project sounds fascinating. This is exactly the type of application we envision for Pangeo. Please have a look and then feel free to open new issues to discuss the specifics of your use case. @NickMortimer<https://github.com/NickMortimer> of CSIRO has been playing around with cloud storage of ARGO data. You may wish to touch base with him.

Also note that pangeo.pydata.org<http://pangeo.pydata.org> is getting a bit stale. We are planning to shut it down soon and replace it with something more specialized (see #373<https://github.com/pangeo-data/pangeo/issues/373>).
