### ISSUE TITLE
Request for access to Pangeo JupyterHub 

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [pangeo-data/pangeo#486]
I would like to request access to JupyterHub as part of the  GCP / ESGF / pangeo collaborative efforts from the NOAA GFDL end. Thanks,

**Comment by rabernat** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!

Your project sounds fascinating. This is exactly the type of application we envision for Pangeo. Please have a look and then feel free to open new issues to discuss the specifics of your use case.

Also note that pangeo.pydata.org is getting a bit stale. We are planning to shut it down soon and replace it with something more specialized (see #373).
