### ISSUE TITLE
Request for access to Pangeo JupyterHub

### ISSUE THREAD

**Issue by spencermathews** [pangeo-data/pangeo#487]
Hello, I'm a graduate student at UC Davis working on scalable hyperspectral data analysis. Pangeo seem a potentially interesting project and I'd like to experiment with your deployment.

Thanks,
S

**Comment by rabernat** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!
