### ISSUE TITLE
Please add me to the organisation

### ISSUE THREAD

**Issue by alexgleith** [pangeo-data/pangeo#488]
I'm working on a similar project, the Open Data Cube, and I'd like to be able to use your sandbox from time to time if possible. Please!

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

We're really hoping to engage more with the ODC community (see also #96), particularly in the area of analysis of remote sensing data. So please keep in touch.
