### ISSUE TITLE
Weekly meeting calendar - late weeks does not repeat

### ISSUE THREAD

**Issue by jacobtomlinson** [pangeo-data/pangeo#491]
I noticed on the [weekly checkin](http://pangeo.io/meeting-notes.html) page that the early meetings have been set to repeat weekly but the late meetings haven't.

I'm guessing this is a mistake. Can someone update it? 

cc @jhamman

**Comment by jhamman** [comment]
@jacobtomlinson - I think I've fixed this. Can you check?
