### ISSUE TITLE
Clarify the new *.pangeo.io deployments usage

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#494]
As mentioned in https://github.com/pangeo-data/pangeo-binder/pull/19, I'm a bit lost between all the new Pangeo deployments available. As proposed by @jhamman, this would be helpful if the deployments and their goal/usage was available somewhere (who can modify it, who can use it, resources quota, how to use...).

This is mainly for the generic deployments:

- dev.pangeo.io
- example.pangeo.io
- binder.pangeo.io
- staging.binder.pangeo.io
- the dying pangeo.pydata.org

But we could also point to thematic deployments, which is related to #476.

**Comment by jhamman** [comment]
Hi @guillaumeeb - thanks for the cross post.

I think we can break things down into three categories. 

1. Domain specific JupyterHubs such as atmos.pangeo.io, hydroshare.pangeo.io, polar.pangeo.io and astro.pangeo.io. These are being designed specifically for domain use cases and communities and are being managed, in most cases, by folks outside of the core Pangeo developers. 
1. Test and development hubs such as dev.pangeo.io, staging.pangeo.io, hub.pangeo.io, and example.pangeo.io. These are meant to be used for testing and development. A few months ago, we had one cluster (pangeo.pydata.org) and we were routinely having trouble balancing testing out new features while maintaining a production deployment. Anyone can use these for development purposes. We may also use hub.pangeo.io for tutorials at some point. 
1. binder.pangeo.io and staging.binder.pangeo.io are BinderHub deployments. The staging namespace of course is our development iteration and allows us to test things in the wild. Anyone can use these and I'd personally be excited if others had reason to work on these as well.

Question: does something like this belong on the pangeo website? If so, how do you suggest we describe the landscape here.

**Comment by guillaumeeb** [comment]
Thanks @jhamman! I (re ?) discover hub.pangeo.io. Does all these environments share the same resources quota on GCE?

I'm not sure if this belong to pangeo website, the question may be: is this stable enough to appear there? Anyway, I definitly think this should appear somewhere (outside from the issue tracker), and I currently don't see any other place than pangeo website. Maybe just updating the http://pangeo.io/deployments.html page would be good enough? I don't know, I like the layout you provided above, and having some paragraph describing how to use the various testings hubs would be nice.

**Comment by jhamman** [comment]
> Do all these environments share the same resources quota on GCE?

Not necessarily. The binder deployments are on the same kubernetes cluster and dev/staging/hub.pangeo.io are on the same cluster. Of course, we do have project wide quotas as well but I don't think that is what you were referring too. 

I'd be happy to see someone work on the deployments page in the pangeo docs to represent this conversation by the way.

**Comment by rabernat** [comment]
> I'd be happy to see someone work on the deployments page in the pangeo docs to represent this conversation by the way.

👍 would really appreciate if someone would tackle this
