### ISSUE TITLE
Request For Access To Pangeo JupyterHub <http://pangeo.pydata.org/hub/login>

### ISSUE THREAD

**Issue by saviokay** [pangeo-data/pangeo#496]
Hello, I'm a Graduate Research Assistant at UMBC working on Big Data Related Flexible Aggregation and Distribution of MODIS Atmospheric Products based on Climate Analytics. 
Pangeo as a project has intrigued my interest and would like to explore the possibilties with regards to my project. 

Also I'm not sure if this is pertinent to the issue, but I have made a pull request by adding my credential to the 'people.yml' file. 
Pull Request #495 

Regards,
Savio Kay

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public for this to take effect.

Welcome!
