### ISSUE TITLE
Request for access to Pangeo JupyterHub

### ISSUE THREAD

**Issue by acwu1** [pangeo-data/pangeo#499]
Good afternoon, I'm an engineer at NASA working on big data Earth Science and I was wondering if I could obtain access to the Pangeo JupyterHub to experiment with the system.

**Comment by mrocklin** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public on [the members page](https://github.com/orgs/pangeo-data/people) for this to take effect.

Welcome!
