### ISSUE TITLE
pangeo jupyterhub access

### ISSUE THREAD

**Issue by cr458** [pangeo-data/pangeo#500]
Hi, I'm a postdoctoral researcher in geophysics at LANL and would like to have acess to pangeo to test and potentially demonstrate some workflows with seismic data. Thanks!

**Comment by mrocklin** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public on [the members page](https://github.com/orgs/pangeo-data/people) for this to take effect.

Welcome!
