### ISSUE TITLE
advice on Zarr structure for large reanalysis dataset

### ISSUE THREAD

**Issue by leroygr** [pangeo-data/pangeo#502]
Hi all,

## Context
I'm planning to store a set of single level variables (time x latitude x longitude) of ERA5 in a Zarr dataset, with full globe coverage, hourly time resolution for a period of at least 20-30 years. This corresponds to a total size of about 2.5-3TB.

## Requirements

I chose Zarr because the final goal is to put the data on S3 and be able to analyse the data efficiently using Dask and Xarray. The primary use is for querying time series at single points for long periods (> 20). But I would also perform some monthly/yearly statistics (e.g, mean, std,...) for some areas so I need to chunk the data in an efficient way, though giving a preference for time series access.

There are some flexibility I want/need with the Zarr dataset:

- encode and store the arrays following CF conventions (as it is in the original netCDF) for automated decoding by Xarray
- prepend/append new data to the existing dataset. E.g., now only data back to 2008 are available, but I'll have to add data prior to 2008 when it will be released. I will also need to add the new data generated every month
- have the possibility to add/remove any variable without the need of removing/overwriting other arrays, e.g., from the same group.

## Tested strategy

I chose to define only one Zarr file

**Chunking**

As I request the original data as netCDF in monthly chunks, the dimensions are the following: `time: 744, latitude: 721, longitude: 1440`.

Given the typical queries I would do on the dataset, I semi-arbitrarily define the chunks with the following shape: `time:744, latitude: 100, longitude: 100`. I didn't tested (yet) the performances but sounds like a good compromise for fast time series access while keeping reasonable chunk size on lat&lon for mapping purposes.

**Test 1 :** Using Xarray interface

I first tested the `xarray.Dataset.to_zarr` interface as it complies with the encoding and CF conventions I would like to use for serializing the variables to Zarr. It is also the simplest, but is still in experimental phase. I quickly found out that it would not fit my case:

- it stores all variables in the dataset to the same Zarr group
- we can't modify the arrays in the group without overwriting the entire group
- we can't append/prepend data to existing arrays using the `to_zarr` interface

**Test 2:** Using Dask+Zarr

I quickly ended up with the following idea, that seem to suit my needs:

- Use Zarr directly to open the Zarr dataset, create the groups
- To avoid the need of appending to existing arrays and to allow flexible addition/deletion of variables, I would define a group for each `{year}/{month}/{variable}/{variable}` (for 3d variables). 2d variables would go in `{constant}/{variable}/{variable}`

For example,

```
>>> root.tree()
/
 └── 2015
     └── 01
          └── time
                ├── time (744) int32
          └── sp
                ├── sp (744, 721, 1440) int32
          └── u10
                ├── u10 (744, 721, 1440) int32
 └── constant
     └── latitude
          └── latitude (721) int32
     └── longitude
          └── longitude (1440) int32
     └── z
          └── z (721, 1440) int32
```

It is more or less a similar structure I would use for building such database with netCDF and directories.

I would then serialize each of my variable separately to Zarr using CF conventions similarly to Xarray (potentially re-using some core functionalities). Dask would be used to store the variables & also to query the Zarr arrays along the appropriate dimensions to finally build a Xarray Dataset (corresponding to time series or lat/lon slices).

However, I have no idea on the query performances for the intended use (mainly time series). With this structure, there will be several groups and I'm not sure on how efficient would be the queries along the time dimension.

## Questions

I basically need a bit of advices on how to structure this dataset for the intended purpose. Would you have any recommendation/experience with similar cases? 

The big questions are:

- 1 Zarr file? A Zarr file per year/month/...?
- Array chunks size. Is the one suggested appropriate?
- If 1 Zarr file, how to structure the data in it? All variables in root? A group per year/month/variable?
- What are the appropriate libraries for doing such processing with the required flexibility? Xarray alone? Dask + Zarr? 

I hope this is the right place for raising such questions.

Thanks a lot.

Greg

**Comment by alimanfoo** [comment]
Hi Greg, I'm not very familiar with the domain so can't offer much advice, but FWIW your chunk size sounds reasonable (744 x 100 x 100 =~ 7 million; if dtype is float then chunks would be around 28M uncompressed size?).

Also if you break up your arrays into multiple groups, but want to then run analyses across data from multiple groups, you can use something like [dask stack or concatenate](http://docs.dask.org/en/latest/array-stack.html). Performance should end up being pretty much the same as if the data were all in a single array.

Hth.

**Comment by tam203** [comment]
Hi,

I'll be keen to hear how you get on. I'm looking at a parallel case for our weather forecasts.  Hear at the UK Met Office we are pushing 7 TB (1/2M NetCDF files) a day up to AWS. This forms a rolling 24 hour rolling archive of weather forecasts. 

Files come in 2 (lat x lon), 3 (hight x lat x lon) or 4 (realisation X height X lat X long) but I wish to concatenate along 'forecast reference time' and 'forecast time step' to create several high order (forecast reference time X forecast time step X realisation X height X lat X long) rolling time window Zarr files.

The approach I'm taking is processing the files in parallel (on lambda) as they come re-shaping the data in each file in to appropriate chunks (the chunk policy must ensure each chunk will only ever come from one file else there is a concurrency issue) and writing (through Zarr) to S3. This will happen in parallel, 1/2 M files a day usually arriving in batches.

In series I update the Zarr metadata (mainly the shape) such that these new chunks will now be found. There are few other  metadata items (such as the zarr arrays used for the dimensions) that also need updating if you want to import the data in xarray (and all the CF attributes etc)

This method allows for appending, in series, but does not allow for pre-pending or (as occurs in our rolling 24 hour case) truncating from the beginning. In our situation, because we will delete the chunks we just get an ever growing amount of null/missing data at the beginning of the array with the end grown away from the beginning at the same rate.

This issue zarr-developers/zarr/#267 offers an (in my opinion) exciting solution to this but does require a change to the Zarr spec and so needs a compelling case. Please lend your weight if you feel it would help.

**Comment by leroygr** [comment]
Thanks for your answers @alimanfoo & @tam203. I'm implementing the second strategy and I'll do some tests in the coming weeks and give a feedback here on performances.

Additional comments are of course welcome.

**Comment by darothen** [comment]
@leroygr I'd also be interested in hearing more as you progress on this project. I'm beginning to do more or less the exact same exercise with some colleagues. As we spin-up, I'd be interested in reaching out and chatting more via video conference with you. I believe that @kmpaul will also be interested as the NCAR folks are studying very similar use cases at the moment.

**Comment by mrocklin** [comment]
My recommendation in situations like this is to schedule a 30 minute
meeting a week or two in the future.  This makes sure that some engagement
happens, and gives people a target to shoot for when doing experiments
(it's fun to share results).

**Comment by ktyle** [comment]
I'm interested too. We have a customized set of CFSR and ERA-Interim reanalyses in-house and (besides integrating them into the Pangeo data-sphere) are looking at Zarr. Additionally I have another large dataset on XSEDE/Wrangler and am looking at storing it as Zarr files using object storage.

**Comment by leroygr** [comment]
@mrocklin : I'm fully open for sharing experience and for scheduling a 30 minute meeting! I hope to get some results in the coming days but it depends on priorities that can change. I suggest to raise my hand when I have something out of my tests, so we can plan a meeting.

**Comment by leroygr** [comment]
Hi all,

Here is some feedback of my first tests.

## Zarr structure
After some local tests, I found the following file structure to be the most appropriate so far:

- 3D variables stored in groups containing exactly 1 month of data (always), with group key being `yyyy/mm`. Each month also contains the `time` coordinate
- 2D variables are stored in the `constant` group. This group contains `latitude` and `longitude` coordinates
- chunking is `time: 744, latitude: 100, longitude: 100`


```
>>> root.tree()
/
 └── yyyy
     └── mm
          └── time (744) int32
          └── sp (744, 721, 1440) int32
          └── u10 (744, 721, 1440) int32
 └── constant
     └── latitude (721) float32
     └── longitude (1440) float32
     └── z (721, 1440) int32
```
## Conversion from netCDF to Zarr
Original data are using CF-compliant encoding to store the data as integer using `scale_factor` and `add_offset`  for all variables except `latitude` and `longitude`. `time` is using `units` and `calendar`.

I wrote my own functions to write the data to Zarr per monthly chunks, keeping the original encoding. It uses the same philosophy as xarray and puts encoding information in the variable attributes, e.g.:

```python
>>> root.get('2008/01/sp').attrs.asdict()
{'_ARRAY_DIMENSIONS': ['time', 'latitude', 'longitude'],
 'add_offset': 100203.21171251507,
 'long_name': 'Surface pressure',
 'scale_factor': 0.10782496986251201,
 'standard_name': 'surface_air_pressure',
 'units': 'Pa'}
```

Global attributes are also stored at root level:

```
>>> root.attrs.asdict()
{'dimensions': ['time', 'latitude', 'longitude'],
 'dx': 0.25,
 'dy': 0.25,
 'epsg': 4326,
 'last_update': '2018-12-11 12:17:15+00:00',
 'model': 'IFS CY41R2',
 'name': 'ERA5',
 'source': 'ECMWF',
 'timefreq': '1h',
 'xmax': 180,
 'xmin': -180,
 'ymax': 90,
 'ymin': -90}
```

### Some tests on S3 

To test and develop my time series query functions, I pushed a sample file on **S3** containing **two years of hourly data** with a few variables but for a **limited area** (`5 latitude x 5 longitude`).

I tried to structure the functions to paralellize the code with Dask to accelerate the query. The idea is to get a dataframe for a specific point, period and variables. A high-level view of the steps :

For each variable, loop on each monthly chunk and:
1. open zarr array 
2. convert zarr array to `xarray.DataArray` with corresponding attributes
3. slice `DataArray` at the point, decode the values using `xarray.conventions.decode_cf_variable` (after slicing to do it only on subset), and compute
4. Then, all `DataArray` are concatenated along time dimension

To save time, the coordinate arrays (time, latitude longitude) are note loaded from the file but inferred from:
- from the global attributes for `latitude` and `longitude`
- from the group name for `time`

You can see [the code in notebook](https://gist.github.com/leroygr/dde77e7c7baf77ac80a5b64e2d2d542e).

I got the data I wanted in a relatively short timeframe: 30 seconds. Obviously, I assume that if the same code is run on an EC2 instance in the same region (not tested), it will be much faster than querying over the internet.

However, I'm not sure that I'm properly dividing my problem to use Dask in an efficient way (I'm new to Dask). When I check the Dask graph, it seems that half of the time is spent on deserializing the "open_zarr_array" delayed function.

Could someone tell me if I'm doing this properly in the [example notebook](https://gist.github.com/leroygr/dde77e7c7baf77ac80a5b64e2d2d542e)?

Also, how could I paralellize the process further by also do some delay operations when I loop on the variables?

Thanks a lot for your feedback :-).

**Comment by darothen** [comment]
@leroygr did you happen to see #507? We're holding a teleconference focusing on establishing a technical working group focused on data management... your experience here would be super helpful! We're planning chatting in  http://appear.in/pangeo at 1PM EDT on Thursday, December 20.
