### ISSUE TITLE
Connecting with CDAT/ESGF

### ISSUE THREAD

**Issue by doutriaux1** [pangeo-data/pangeo#506]
Just saw @rabernat talk at ESGF. We should work together to make CDAT/CDMS comoatible with pangeo (mv2xarray and xarray2mv functions?), same for VCS and viz tools.
Some initial links here more to come when ESGF presentation will be ready

https://cdat.llnl.gov
https://cdat.llnl.gov/tutorials.html
https://cdms.readthedocs.io/en/latest/
https://cdat.llnl.gov/documentation/utilities/utilities.html
https://cdat-vcs.readthedocs.io/en/latest/

**Comment by doutriaux1** [comment]
@dnadeau4 feel free to chime here

**Comment by doutriaux1** [comment]
@rabernat looking forward to this. Without brainstorming too much I think a first scenario would be the ability for xarray users to take advantage of cdms2 regridding capabilities. Probably plot use cases with vcs' easy mapping tools would be another good one. `genutil` and `cdutil` packages are probably good candidates for test cases. (see utilities link above)

**Comment by rabernat** [comment]
Are there the regridding functions you are referring to?
https://cdms.readthedocs.io/en/latest/manual/cdms_1.html#regridding

If so, are you talking about the cdms2 native regridder or the SCRIP regridder?

**Comment by doutriaux1** [comment]
yes. cdms does a LOT of magic behind the scene to make this happen so effortless

**Comment by doutriaux1** [comment]
cdms includes 3 regidder, our native "area-weighted" one, libcf regirdder, and esmf regirdder, there's also hooks to get in scrip weight files.
All 3 regridder are completely transparent to the user, essentially zero knowledge about grids is required if the data is CF compliant.

**Comment by dnadeau4** [comment]
@doutriaux1 I saw @rabernat today here at AGU.  Let's wait until next week to discuss this.  We will be more free.

**Comment by rabernat** [comment]
Just following up on this discussion.

What are come concrete first steps we could take to improve compatibility. I would start with the low-hanging fruit. Does the something like the following workflow work today?
```python
ds = xr.open_zarr(some_zarr_store)
da = ds['variable_name]
# does the next line trigger eager loading of dask arrays?
cdms = da.to_cdms2() 
# is the next line lazy?
cdms_regrid = cdms.regrid() # obvious some arguments are needed?
da_regrid = xr.DataArray.from_cdsms2(cdms_regrid)
```

It would be very useful to have someone try this and see where the pain points are.

**Comment by dnadeau4** [comment]
@rabernat here is a better example with cdms regrid directly.
https://github.com/CDAT/cdms/blob/master/tests/test_EsmfRegridPeriodictyRegional.py

**Comment by doutriaux1** [comment]
@dnadeau4 it's becoming increasingly obvious we really need these jupyter notebooks on cdms regridding.

**Comment by rabernat** [comment]
Wow this is really fantastic! I will take some time to digest these examples and get back to you with my thoughts for follow up.

> ESMF uses (xyz) and CMIP6 is (zyx) so it get a little confusing to transpose all the time. I am close to a solution.

This is one of the main reasons we love xarray...it handles these issues in such a way that the user never has to think about dimension order. See the [xesmf](https://xesmf.readthedocs.io/en/latest/) package for an implementation of regridding with xarray.


> I fixed your Julia issue in binder as well, you can find it here.
Wow, so cool! Thanks! You have solved this issue: https://github.com/conda-forge/julia-feedstock/issues/60. I encourage you to share your solution on that thread. In the meantime, I will update my ocean binder.

**Comment by doutriaux1** [comment]
@rabernat let's re-open this. ok?
