### ISSUE TITLE
Data Management Technical Working Group

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#507]
I realize that this might be premature, but there seems to be a lot of interest and activity around data management activities related to Pangeo, notably mentioned in #503 and contained references.  It seems to me that the creation of the Technical Working Group on Data Management should be something the new Steering Council should consider creating.

Other than me, I would say that @darothen would be interested in being a part of this group.  I'll let others chime in if they would want to participate, too.

**Comment by darothen** [comment]
To add to the conversation, we're currently planning a technical call with folks interested in discussing migrating very large datasets to zarr and ultimately onto some sort of commercial cloud service - anyone is welcome to attend, and we have a [Doodle poll](https://doodle.com/poll/7v348ipa6ub5zhis) to coordinate a time that works well (@kmpaul please add your availability!) If it's alright with everyone, we may want to discuss this working group on that call and get at least some sort of initial effort off the ground.

**Comment by darothen** [comment]
Turns out we have an optimal time on **Thursday, Dec 20** at **1-2PM EST**. The group will meet in the lobby at https://appear.in/pangeo; I'll reserve a Zoom conference room to have as a back-up, but we'll post here if things change.

I'll reply-all via e-mail to the folks who completed the Doodle Poll so that you have independent confirmation and a Calendar invite.

**Comment by alando46** [comment]
@darothen I'm a little late to the party on this one (looks like the doodle is closed) but if possible, I'd like to join and listen in on the dataset migration conversation.

**Comment by leroygr** [comment]
Hi all, as mentioned in #502 I can't join the meeting on Thursday. However, I'm really interested to join this group. Thanks.

**Comment by darothen** [comment]
@leroygr and @alando46 I'll make sure we take minutes and post them here; if you end up being available, you're more than welcome to join!

**Comment by Thomas-Moore-Creative** [comment]
@kmpaul et al.  Also late to this party and might not be able to join (TAS time-zone) but keen to follow the outcomes.

**Comment by kmpaul** [comment]
@Thomas-Moore-Creative Understood about the time-zones!  It's kind of impossible to get both Europe, US and TAS on the same calls.  We can talk separately, if you'd like.  I'll keep you posted.

**Comment by alimanfoo** [comment]
Just to say I'm very interested to follow these conversations and learn about the technical directions this community takes (so I can borrow lots of good practice for our genomics work!). Unfortunately I can't join the call tomorrow, but look forward to keeping in touch.

**Comment by rabernat** [comment]
I have put up an example notebook of how I produce zarr datasets with some detailed commentary:
https://gist.github.com/rabernat/4ae286464f55a75e30b55f529195aff0

Hopefully this will be useful for today's discussion.

Also, here is a copy of the slides on zarr I gave at AGU. These might be a useful reference:
https://speakerdeck.com/rabernat/cloud-native-climate-data-with-zarr-and-xarray

**Comment by darothen** [comment]
If you're a last minute joiner and don't have the Zoom link, please use this: https://zoom.us/j/5944845886

Because this is my private room I'll remove it from this comment after the meeting.

**Comment by darothen** [comment]
The original agenda, notes, and minutes from our meeting is [available here on Google Docs](https://docs.google.com/document/d/1roo5PWAHua_HkWQaupAxgqTy4vWBscY0pqsWj9phvdk/edit?usp=sharing). We also recorded the conversation for others to listen to at their leisure, I've hosted them [from my Dropbox](https://www.dropbox.com/sh/zw6njsxsn651mhj/AABBAZlkLQgTb9ZGQfNDkR_Za?dl=0) for now.

To ensure that everyone's perspectives are captured, we're going to host two additional calls: one focused on European working hours, and one focused on Australian. Here's a Doodle for the European one; @kmpaul and @jmunroe have offered to coordinate the Australian one: https://doodle.com/poll/bde5qwyts5vsxnfb

**Comment by darothen** [comment]
We'll have a discussion for Euro-time zone folks on **Friday, January 4** at **14:00-15:00 UTC**. @willirath and @leroygr were our only two participants, but anyone is welcome to join! Let's plan on using the https://appear.in/pangeo link; we don't necessarily need to video/audio record this meeting.

**Comment by darothen** [comment]
@willirath and @leroygr - something came up on my schedule and I can't make the proposed time anymore. Can you both e-mail me (daniel AT climacell DOT co) so we can find a new time?

**Comment by rabernat** [comment]
I have created a new repo to hold my ideas and experiments related to a pangeo datastore:
https://github.com/pangeo-data/pangeo-stac

**Comment by rabernat** [comment]
Would anyone 

I would like to transfer this issue to the new https://github.com/pangeo-data/pangeo-datastorerepository. Any objections?
--

**Comment by kmpaul** [comment]
None here.  Thanks!
