### ISSUE TITLE
Request access to Pangeo

### ISSUE THREAD

**Issue by rogema** [pangeo-data/pangeo#510]
Hi,

I am oceanographer and I would like to participate and experiment with PanGeo. I am mainly interested in using the AVISO SSH dataset and compute the associated monthly EKE. I would be happy to share the notebook to complete the pangeo ocean examples.

I am also wondering if it is possible to download post-processed data from the cloud. This should be only a couple of 2D fields.

Thanks!

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public on [the members page](https://github.com/orgs/pangeo-data/people) for this to take effect.

Downloading small datasets from the Pangeo Jupyterhubs is fairly straight forward. Feel free to ask for pointers once you get to that point.

Welcome!
