### ISSUE TITLE
Pangeo cloud deployment : static deployment vs CircleCI CI/CD

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#511]
I think it is not clear currently how should be done Pangeo cloud deployments. We should take the time to settle down and clarify this.

There are currently two ways of doing things:

- Following the [setup guide](http://pangeo.io/setup_guides/cloud.html), and so using https://github.com/pangeo-data/helm-chart
- Duplicating and following intstructions in https://github.com/pangeo-data/example.pangeo.io-deploy

We had a discussion on gitter a few days ago, here are @rabernat conclusions:

> 1) The "pangeo" helm chart is stale: https://github.com/pangeo-data/helm-chart
> all these deployments are essentially defining a new chart called pangeo-deploy, which does not depend on the original chart: https://github.com/pangeo-data/dev.pangeo.io-deploy/tree/staging/pangeo-deploy
> I would propose we break out pangeo-deploy into a standalone helm chart and repo and then make it a submodule for these different deployments
> 2) I don't think it makes sense to have all these different deployment repos!

and before that: 
> I think now it's just time to circle back a bit and sort out what are the important / durable pieces

Note that Pangeo helm-chart is still used in https://github.com/pangeo-data/example.pangeo.io-deploy/blob/staging/pangeo-deploy/requirements.yaml, but not in dev.pangeo.io-deploy.

My current opinion is that both ways are usefull. I like to have the hability to deploy a Pangeo platform just relying on cloud commands, K8S and Helm, and not other fancy github related CI tools. But I have to admit that these tools are great and really helpful when updating configuration a lot. We've got to make sure that the two solutions are not diverging (like the helm chart thing).

If we keep the helm chart and setup guide, we should at least update some parts of it (I noticed Jupyterhub image version, the problem with the pangeo jupyterhub home pageo not correctly displaying, there are probably other things to update).

**Comment by guillaumeeb** [comment]
ping @jacobtomlinson who was really active on the Helm chart repo. Don't you think we should maintain it? Do you use it for Met Office deployment?

**Comment by jacobtomlinson** [comment]
Sorry I totally missed the ping from @guillaumeeb. Yes I strongly think we should keep it and base as much as we can from it like the hubploy deployments. We use it actively here.

**Comment by rabernat** [comment]
In https://github.com/pangeo-data/dev.pangeo.io-deploy/issues/32, we are discussing consolidating all of the pangeo-google-cloud managed hubs into one single repository. That would be a good opportunity to update the helm chart / CI approaches and update all these clusters with the latest best practices / packages / etc.

I think this is a very important task. I can volunteer to help oversee some of the progress, but it would be great if someone with more kubernetes / helm knowledge could be involved in the technical steps.

**Comment by guillaumeeb** [comment]
Great, we're all on the same page then.

I began looking more deeply into https://github.com/pangeo-data/helm-chart, and started proposing some PR to update it. I'm still a Kubernetes rookie, but I'd like to learn more, so I'm volunteering again helping maintain the helm-chart repo. I just hope I will find enough time to do so, 2019 started hard!

**Comment by jacobtomlinson** [comment]
In this case I would be keen for @guillaumeeb to drive the work forwards and to draw me, @yuvipanda and others in to assist where necessary.

**Comment by jhamman** [comment]
We should use https://github.com/yuvipanda/hubploy/issues/9 to describe the path to using the pangeo helm chart in hubploy.

At some point, we may want to document, within Pangeo, how to setup and use hubploy managed jupyter hubs. I don't think we're far enough down that path to write up those docs yet. 

In an effort to keep  sprawling meta-issues to a minimum, @guillaumeeb - do you think we can close this one?

**Comment by guillaumeeb** [comment]
Sure, I think we've answered my initial questions, and established some strategy to solve the problem, so that's perfect for me!
