### ISSUE TITLE
PASC 2019 Pangeo Minisymposium

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#512]
Last Friday (Dec 7, 2018), @niallrobinson, @allibco, and I expressed interest in organizing a Pangeo Minisymposium at [PASC'19](https://pasc19.pasc-conference.org/).  According to the [PASC'19 Guidelines for Minisymposia](https://pasc19.pasc-conference.org/submission/guidelines-for-minisymposia/), a "minisymposium" is a themed 2-hour slot comprising of 4 30-minute talks.  We proposed, as part of the *Climate and Weather* Science Domain, the following minisymposium:

> **Title:** The Pangeo Platform for Interactive Data Analysis
> 
> **Abstract:**
> The Pangeo community is an international community committed to fostering collaboration around the open source scientific Python ecosystem for ocean / atmosphere / land / climate science, supporting the development with domain-specific geoscience packages, and improving the scalability of these tools to handle petabyte-scale datasets on HPC and cloud platforms.  The Pangeo ecosystem of Python packages include Dask, Xarray, Iris, and Jupyter, and developing interoperability around these packages has lead to significant advancements in the last year in the areas of Xarray- and Iris-compatible data cataloging and discovery software, Jupyter Notebook dashboarding, cloud-friendly data formats for analysis, hybrid HPC-cloud technologies and environments, just to name a few.  In this session, we cover some of the recent advancements made by the Pangeo community.

A full minisymposium proposal, according to the guidelines, "should include an extended abstract along with proposed speakers and titles for four 30-minute presentation slots (typically, these slots are 25-minute talks with 5 minutes for questions). The minisymposium organizer is permitted to give one of the four presentations her/himself. If desired, the fourth 30-minute slot could be a panel discussion or open discussion forum. Please note that no other formats are possible."  **The full proposal is due January 11.**

Allison Baker (my colleague here at NCAR, @allibco) was told by the PASC organizers that if we get 8 speakers lined up, then we might be able to have a "double minisymposium."

So, I'm posting this issue to solicit interest from the Pangeo community in being a speaker.   (I believe that @niallrobinson has an interest in being a speaker, but I will let him chime in to confirm.  :smile:)

**Comment by mrocklin** [comment]
I or some other non-Pangeo Dask person may also go to this conference as part of a separate Python HPC minisymposium.

**Comment by kmpaul** [comment]
@guillaumeeb There seems to be interest in the French Pangeo meeting (#493), and maybe one of you would be willing to give a talk at PASC in June?

**Comment by kmpaul** [comment]
A proposal has gone in for this minisymposium.  I currently have me, @niallrobinson, and @mrocklin on the agenda, with the 4th slot reserved for discussion and hack-a-thon topic gathering.

**Comment by guillaumeeb** [comment]
Oh sorry for my late answer here. This looks really interesting, let me know how it goes or if you need something from me. I will have a look at my agenda and see if I can make it there, at least to finaly meet you guys!

**Comment by mrocklin** [comment]
If there is an opportunity later in this process to change around speakers I would be more than happy to give my speaking slot to @guillaumeeb .  It would be nice to have more people representing the project publicly.

**Comment by kmpaul** [comment]
I'm positive we can find replacement speakers or modifications to the agenda later, but it would be wondering @guillaumeeb for you to come, regardless.  (And, I agree, it would be great to meet you in person!)

**Comment by kmpaul** [comment]
I'd like to reopen this issue and ask if anybody would be interested in coming to PASC this June to participate in a Pangeo-related hackathon...?  I am officially drumming up interest.

@guillaumeeb It would be great to see you there!

**Comment by guillaumeeb** [comment]
Is it possible to attend for one day? What are the fees?

**Comment by kmpaul** [comment]
I don't know if it's possible to register for 1 day.  All I know is here:

https://pasc19.pasc-conference.org/registration/attendance/

Early registration fee is 400 CHF.
