### ISSUE TITLE
ECAS Call for Proposals

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#513]
@lila from Google sent this to me.  I thought I'd cross-post it here.

I wanted to let you know about a new NSF program focused on innovative uses for cloud in the sciences.  Its funded by NSF, and run by Internet2, called ECAS:  Exploring Clouds for Acceleration of Science).  The CFP is out at: https://www.internet2.edu/blogs/detail/16949

It looked like an interesting program and I thought that some people here might be interested in applying.

**Comment by robfatland** [comment]
I've been dragging my feet on this but I thought I would try to write something *light* (as in modest funding ask) around data publication and serverless compute-based API access. If anyone is interested in this or other cloud-centric responses I'd be happy to hear.
