### ISSUE TITLE
BiDS 2019 : Paper enhancement by the 15th of january

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#514]
The Pangeo talk for [BiDS](https://www.bigdatafromspace2019.org) (see #376 ) has been accepted! However, this was not a formality as I thought it would be, we've encountered a tough second reviewer (see below). I will try to work on an update, schedule is tight, any suggestions/improvement would be appreciated.

For a reminder, paper is available here: https://github.com/guillaumeeb/bids2019.

> ----------------------- REVIEW 1 ---------------------
> PAPER: 17
> TITLE: The Pangeo Big Data Ecosystem and its use at CNES
> AUTHORS: Guillaume Eynard-Bontemps, Ryan Abernathey, Joseph Hamman and Aurélien Ponte
> 
> Suitability for Big Data from Space conference: 4 (good)
> Originality: 4 (good)
> Technical quality: 3 (fair)
> Readability: 4 (good)
> Bibliography: 3 (fair)
> Overall evaluation: 2 (accept)
> 
> ----------- Overall evaluation -----------
> The authors present an open source toolset for Big Data processing using Python. It is based on Juypter fo interactive computing and analysis via the web browser, Dask for parallel computing and Xarray for the data model. The abstract is clear and the subject is relevant for this BiDS conference. As the proposed toolset seems somehow overlapping with the existing Orfeo Toolbox (OTB, also developed by CNES), it is surprising that no reference to OTB is given. The authors should comment on the existing overlap, difference, pro's and con's of each of the packages and, in particular, on the reason why this new initiative was started.
> 
> Some more technical details on the implementation would be welcome. The figures 1,3, and 4 are hardly readable and should be improved.
> 
> 
> ----------------------- REVIEW 2 ---------------------
> PAPER: 17
> TITLE: The Pangeo Big Data Ecosystem and its use at CNES
> AUTHORS: Guillaume Eynard-Bontemps, Ryan Abernathey, Joseph Hamman and Aurélien Ponte
> 
> Suitability for Big Data from Space conference: 2 (poor)
> Originality: 2 (poor)
> Technical quality: 2 (poor)
> Readability: 4 (good)
> Bibliography: 3 (fair)
> Overall evaluation: -1 (weak reject)
> 
> ----------- Overall evaluation -----------
> The abstract introduces Pangeo, a tool aiming at giving scalable support to scientific data analysis, which boils down to support for n-D arrays. 
> 
> Interestingly, interoperability is not considered by the authors, and Pangeo does not seem to support the relevant open standards, such as OGC WCS. This certainly is a drawback in practice. 
> 
> The technology stack lists a shopping basket of tools plugged together (and that has been done elsewhere), but does not explain the specific innovation - for example, how can the generic Dask library help with the specific data structures of xarray? Can it only do the trivial, "embarrassingly" parallel operations or can it also efficiently parallelize data fusion, such as SciDB and rasdaman and others? How? Despite the title of Section 2.3 this does not become clear.
> 
> Talking of that, relating to the state of the art is missing completely.
> 
> There is a gap between the python interface and the "one click" request described - how is that accomplished? What about security when python code from the Internet is executed blindly on a server? How powerful is the single-click interface? Etc.
> 
> Benchmark results, best comparing to other systems, would have been helpful.
> 
> Finally, a neutral comment: There is the well-known portal Pangea, it seems not very advantageous to choose a name that is so close phonetically and in spelling.

**Comment by apatlpo** [comment]
Hum, I am not sure I can be of much help to you Guillaume, sorry.
Here follows what I've got for you.

- Reviewer 1:

Orfeo seems "limited" to remote sensing data. Pangeo's potential reaches a much broader community.
You may be able to state this more explicitly in the introduction.

Does Orfeo handles distributed computations?

It seems to be written in C++ which, if it is true, would strongly limits uptake by scientists (which remains to a large extent python or matlab users).
I do not believe any C++ or java library can become a community tool in geosciences.

- Reviewer 2:

Interoperability, OGC WCS, SciDB, rasdaman?

Both reviewers comment on how pangeo relates to the state of the art. 
It seems to be a good comment to me and that it probably should be addressed at least partly (maybe by comparing with one or two existing librairies), again though I won't be able to help you with this.

Benchmarks would indeed be interesting but can't you mention that the project is still young and under-development.

**Comment by willirath** [comment]
Im addition to the concrete and very important questions in R1 (techical details
of the implementation) and R2 (inter-operability, technical details of the "once
click" solution), I think both reviews (and especially R2) give some hints at
what Pangeo's in for upon entering the big-data geospatial community.

Most of the points in R1 seem to trace back to the misunderstanding that
Pangeo is a well-defined _tool_ or _package_ that is backed by a well-defined
institution.  And the very negative attitude of R2 on the other hand should not
be mistaken for plain gate-keeping.  It's important to understand that this
criticism comes from a world where the majority of solutions are provided by
enterprises that are in direct competition with each other. (A competition that
is evaluated along the lines of "being the fastest DB for", or "being the most
efficient solution of" ...)

Pangeo, however, neither is a tool or package nor does it seek to enter the race
for, e.g., the next on-premise remote-sensing data base.  It's about enabling
scientists, and about building a community.  The fact that the paper did not
manage to clarify this is what should guide the update (as opposed to simply
answering the questions raised by R1 and R2).  Hence, I suggest to shift the
focus away from the specific platforms to even more  highlight the impact Pangeo
and the community-driven approach has for scientists at CNES and in other
institutions.

**Comment by fmaussion** [comment]
Interesting reviews! And tough ones indeed.

From R2:

> The technology stack lists a shopping basket of tools plugged together (and that has been done elsewhere), but does not explain the specific innovation

Do you know what R2 refers to?

**Comment by willirath** [comment]
See https://github.com/guillaumeeb/bids2019/pull/5 which tries to account for some of the misunderstandings I was referring to in https://github.com/pangeo-data/pangeo/issues/514#issuecomment-447815766.

**Comment by guillaumeeb** [comment]
Thanks everyone for the feedback. To be clear, R1 comment on OTB, and a good part of R2 review seems not really relevant to me. 

But @willirath is probably right, this is just another world point of view, and we should try to make ourselves explicit about what we propose here. I personnaly have great trouble understanding the OGC world of often abstract standards, especially when talking about data analysis tooling. The most helpful standard here to me would be for the file format (Zarr for example). All the OGC standard seems defined from a consumer --> services provider perspective, which is kind of what @willirath  underlines.

@fmaussion I'm not sure of what R2 refers to: the Jupyter + Dask + Xarray Pangeo core packages? I'm not sure what has been done elsewhere, and where...

**Comment by guillaumeeb** [comment]
@rabernat, while reviewing the paper, I thought that you might be interested in a blog post on "Why we use Pangeo at CNES", based on the second part of this paper. What do you think?

**Comment by guillaumeeb** [comment]
Thanks everyone who contributed to this. Conference went very well. Put the slides on https://github.com/pangeo-data/pangeo-presentations/wiki/Slides. 

@rabernat let me know if your interested in the blog post mentionned above on Pangeo use at CNES.

**Comment by rabernat** [comment]
> let me know if your interested in the blog post mentionned above on Pangeo use at CNES

Yes yes yes!

Our blog is at https://medium.com/pangeo. Let me know your Medium usename and I will add you to our authors list.

**Comment by guillaumeeb** [comment]
I signed in using my gmail account, I think you have that email! LMK if you need something else. Don't expect a post before april though...

**Comment by rabernat** [comment]
Ok I have added you as an author. Please get your post started whenever you're ready. We'll be happy to provide feedback before publishing.
