### ISSUE TITLE
Request access to Pangeo

### ISSUE THREAD

**Issue by jianwuwang** [pangeo-data/pangeo#516]
I'm a researcher at UMBC (https://userpages.umbc.edu/~jianwu/) and have been on PanGeo based data processing. Please grant my request at https://github.com/pangeo-data/pangeo/pull/515. Thanks.

**Comment by jhamman** [comment]
You've been invited to the Pangeo-data GitHub organization. You'll need to accept the invitation and set your affiliation to public on [the members page](https://github.com/orgs/pangeo-data/people) for this to take effect.

Welcome!
