### ISSUE TITLE
Interest in NSF CyberTraining Proposal?

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#518]
Is there any interest in writing a proposal to the [NSF Training-based Workforce Development for Advanced Cyberinfrastructure (CyberTraining) (NSF 19-524)](https://www.nsf.gov/publications/pub_summ.jsp?WT.z_pims_id=505342&ods_key=nsf19524) solicitation?

We have some interest here at NCAR in writing something to develop a series of Pangeo training workshops.  But I think we need a few other people from the community who would be interested in pursuing this with us.

**Comment by ktyle** [comment]
I'd be interested!

**Comment by kmpaul** [comment]
The full submission deadline for this proposal would be Feb 6, 2019.  So, I would suggest that anybody who is interested fill out this [poll](https://doodle.com/poll/3i8x5mcg7wqsf9xf) to indicate when we could meet to discuss in the next 2 weeks (excluding the holidays, of course).

**Comment by kmpaul** [comment]
CC: @jhamman @matt-long

**Comment by kmpaul** [comment]
CC: @brian-rose

**Comment by brian-rose** [comment]
Yes, interested! Thanks. I don't know if having me and @ktyle together on something like this would be too many (UAlbany) cooks, but there is potential for some good synergies there.

**Comment by ktyle** [comment]
@brian-rose the nature of my fully state-funded position makes it better if we (UAlbany) had one easily RF-fundable PI.

**Comment by brian-rose** [comment]
@kmpaul is this still on the table? If there was a meeting that followed the doodle poll, I somehow missed it.

**Comment by kmpaul** [comment]
No you didn't miss anything.  There was no meeting, but I'll put together a new poll and see if we can find a new time now that it is the new year.

**Comment by kmpaul** [comment]
Okay.  Here's a [new poll](https://doodle.com/poll/dpkkm5yz29ker8qz).  I'm sorry about the last one.  I know time is slipping by here, but I've been really distracted lately.  If none of these times works out, I'm not sure we will have time to throw something together...and with the shutdown current in place, we can't even call the program officers to get advice.  So, we're on our own.

**Comment by jhamman** [comment]
Closing as the deadline passed. I don't think any of us submitted to this RFP.
