### ISSUE TITLE
Towards Federated Pangeo?

### ISSUE THREAD

**Issue by willirath** [pangeo-data/pangeo#519]
Are there any existing efforts / implementations of a federated Pangeo cluster?  (By which I mean based on a Dask cluster spanning workers from, e.g., different data centres, seeing different file systems, etc.)

Tests with a set of VMs and data on local disks not accessible from the respective other machines are promising in that the Dask side was just working via [worker resources](http://distributed.dask.org/en/latest/resources.html).  There seem to be some rough edges on the Xarray side, though (it's not trivial to make sure all IO really only happens on the cluster and not on the frontend Python process).

**Comment by jacobtomlinson** [comment]
We have done some work on this by running Pangeo across a federated Kubernetes cluster. However this introduces a lot of latency between data centres.

We would be keen to explore improving dask and distributed to give it more awareness of locality and placement.
