### ISSUE TITLE
No output/error files during python batch run on Cheyenne using dask

### ISSUE THREAD

**Issue by ksulia** [pangeo-data/pangeo#520]
Hello!  

I have been attempting to submit a batch job to Cheyenne (rather than using Jupyter) so that I do not have to worry about notebook disconnection during run.  I believe I have gotten to the point where the python job runs successfully (though have not run out to completion yet), but I cannot seem to get the basic output files to produce OR the dask-worker.[oe] files to produce during the run. They DO show up after the job is killed or completes, but this makes it difficult to monitor the progress of the code (and kill early if needed).  

Here is the batch script I use to submit:

```
  #!/bin/bash
  #PBS -N pangeo
  #PBS -q economy 
  #PBS -A UALB0018
  #PBS -l select=1:ncpus=1:mpiprocs=1:mem=109GB
  #PBS -l walltime="00:15:00"
  #PBS -o /glade/u/home/sulia/IPAS_Aug2018/IPAS_array/pangeo.o
  #PBS -e /glade/u/home/sulia/IPAS_Aug2018/IPAS_array/pangeo.e  

  #module purge
  #export LD_LIBRARY_PATH="source activate pangeo"
  cd /glade/u/home/sulia/IPAS_Aug2018/IPAS_array/
  source activate pangeo
  python Agg_Main_phiarray_Dec2018.py
```

and this is how I get the workers online in the "Agg_Main_phiarray_Dec2018.py" script :

```
dir1 = '/glade/u/home/sulia/IPAS_Aug2018/IPAS_array/'
cluster=PBSCluster(cores=8,queue='economy', project='UALB0018', walltime='12:00:00',memory="6GB",local_directory=dir1)
client = Client(cluster)
cluster.adapt(minimum=3, maximum=100)
```

I also allow time buffers for the workers to get online before the rest of the code is executed, so there are no timeout issues.  The code submits, and runs, and I (most times) output is produced, but again, not until the job is not longer running.

Any suggestions?

Thank you!
Kara

**Comment by rabernat** [comment]
I think you want to tell python to use unbuffered output. Otherwise you won't see anything in the logs until the job ends.

```
python -u Agg_Main_phiarray_Dec2018.py
```

https://docs.python.org/3/using/cmdline.html#cmdoption-u

**Comment by willirath** [comment]
With PBS, the job stdout and stderr often are only copied to their final 
destinations at the end of jobs.  You probably have to use something 
like qcat or qpeek to monitor the logs while the job is running.
