### ISSUE TITLE
Announcing initial release of intake-cmip: An intake plugin for CMIP data sets 

### ISSUE THREAD

**Issue by andersy005** [pangeo-data/pangeo#522]
I am very excited to announce that we now have an intake plugin for loading CMIP data sets (https://github.com/NCAR/intake-cmip). 

## Features

- Intake-cmip contains just one DataSource class (for CMIP5 data ) for the time being, although it could have several related source (i.e. data source for the upcoming CMIP6). 

- For users with access to NCAR's GLADE, intake-cmip ships with a database for CMIP5 datasets available on GLADE. 

```python
source = intake.open_cmip5(database='glade', model="CanESM2", experiment="rcp85",
                           frequency="mon", realm="atmos", ensemble="r2i1p1",
                           varname="Tair")
dset = source.to_xarray()
```

- In general, the user is able to generate their own database and then point intake-cmip to this database when loading the dataset. 

```python 
from intake_cmip.database import create_cmip5_database
import tempfile
CMIP5_TEST_DIR = tempfile.mkdtemp()
DB_DIR = tempfile.mkdtemp()

create_cmip5_database(CMIP5_TEST_DIR, DB_DIR)

# Specify path to database file
db_file_path = f"{DB_DIR}/cmip5.csv"
```
```python
source = intake.open_cmip5(database=db_file_path, model="CanESM2", experiment="rcp85",
                           frequency="mon", realm="atmos", ensemble="r2i1p1",
                           varname="Tair")
dset = source.to_xarray()
```

See [documentation](https://intake-cmip.readthedocs.io/en/latest/) for more. 

Feedback, requests/suggestions for new features, and/or improvements to include in future versions are welcome and appreciated!

**Comment by rabernat** [comment]
This is extremely cool! Have you showed it to @martindurant (creator of intake)?

**Comment by martindurant** [comment]
Indeed: https://github.com/ContinuumIO/intake/pull/223 :)

**Comment by andersy005** [comment]
@jhamman, 
> After going through this process, do you have thoughts on what it would take to do this sort of thing for the full ESMF CMIP archive in-situ (where files would likely be replace with OPENDAP URLs)?

My key takeaway was that the trickiest part is generating and maintaining the database of available files. Once you have the database of files, everything is straightforward. So, It is possible that it wouldn't be that complicated to replace file paths with OPENDAP URLs, then you would be good to go. I could be wrong ( since my experience with OPENDAP is very limited). Nonetheless, I think it is worth trying OPENDAP URLs out. 

I should point out that intake-cmip relies heavily on [CMIP Data Reference Syntax (DRS)](https://cmip.llnl.gov/cmip5/docs/cmip5_data_reference_syntax_v1-00_clean.pdf). This allows us to make some assumptions regarding the directory structure. As a result, intake-cmip is able to infer necessary (metadata) attributes information (such as `model`, `frequency`, `experiment`, etc..) for each file without having to know what is inside the file. How to extract necessary attributes information from an OPENDAP URL is something I don't know how to do (again due to my limited experience with opendap :) ). 

I would be interested in trying this out if you could point me to an OPENDAP server with CMIP archive. 

Any additional thoughts/comments @kmpaul, @matt-long?

**Comment by rabernat** [comment]
[Siphon](https://github.com/Unidata/siphon) makes it very easy to crawl any [THREDDS catalog](https://www.unidata.ucar.edu/software/thredds/current/tds/catalog/), the standard way to expose the holdings of an opendap server.

This notebook gives an example of how to do this on a NOAA ESRL THREDDS server:
https://github.com/rabernat/pangeo_esgf_demo/blob/master/narr_noaa_thredds.ipynb
(unfortunately it doesn't work right now due to the NOAA shutdown)

Something similar should definitely be possible on an ESGF OpenDAP node. I would recommend adding this capability to intake-cmip.

ping @dopplershift, a siphon developer.

**Comment by martindurant** [comment]
@rabernat , do you think there's merit in building an Intake-Siphon translation layer, since Siphon already has something like a catalogue concept (from thredds) internally and a way to generate opendap/netcdf datasets?

**Comment by andersy005** [comment]
@rabernat, thank you for pointing me in the right direction. I've been playing around with Siphon this weekend. It seems very powerful. I concur with @martindurant's idea of an intake-siphon package plugin.  I set up a dev repository [here](https://github.com/NCAR/intake-siphon) for the time being. @rabernat, @martindurant, @dopplershift, @jhamman  I've made all of you collaborators on this repository. Feel free to chime in.

**Comment by danielballan** [comment]
Hi all -- I too have been building an intake driver that performs searches against a database, and @martindurant brought my attention to a useful pattern we might share. My driver builds a Catalog on the fly to encapsulate the results of a search. For example, this usage of yours from the top of this issue:

```py
source = intake.open_cmip5(database='glade', model="CanESM2", experiment="rcp85",
                           frequency="mon", realm="atmos", ensemble="r2i1p1",
                           varname="Tair")
```

fully specifies one `DataSource`. For a looser search, such as

```py
intake.open_cmip5(database='glade', model="CanESM2")
```

it may be useful to return a dynamically-built `Catalog`, containing all the matches as entries. (Because a `Catalog` "is a" `DataSource`, this a consistent / type-stable return value.) A very coarse search may produce a very large Catalog, and I have been contributing changes to intake -- especially the server and Remote Catalog -- avoid greedily transferring Entries.

A sketch of my use case is in [this notebook](https://github.com/danielballan/intake-bluesky/blob/master/demo.ipynb).

**Comment by martindurant** [comment]
```
> intake.open_cmip5(database='glade', model="CanESM2")
```
I would imagine maybe having an `open_cmip_cat` or `open_cmip_search` where you specify as much as is appropriate, the class takes care of doing the search, and the entries that it creates are all CMIP datasets.


@andersy005, thanks for being so swift in setting something up for siphon!

**Comment by hot007** [comment]
Hi all,
I may have missed what you're doing here in depth, but my understanding is that Siphon indexes the THREDDS server you point it at, meaning you will probably only be seeing a subset of the total CMIP archive at any given ESGF node. As the ESGF/CMIP data is distributed, it might make sense to query an index node to find the OPeNDAP URLs of data anywhere (not only local)?
e.g. https://www.earthsystemcog.org/projects/cog/esgf_search_restful_api
Having a local copy of the index speeds things up substantially but is not strictly necessary. 
I can't speak for Intake and whether that's feasible, just a general observation about searching for CMIP data/URLs.
-Claire

**Comment by andersy005** [comment]
Just thought I would add this here as a future reference for interested parties:

**NOTE:** As of March 2019, continued development of `intake-cmip` will be taking place as part of the `intake-esm` project: https://github.com/NCAR/intake-esm.

**Comment by martindurant** [comment]
Please add intake-esm to https://intake.readthedocs.io/en/latest/plugin-directory.html , and remove intake-cmip if appropriate.

**Comment by andersy005** [comment]
@martindurant, I addressed this in https://github.com/intake/intake/pull/283
