### ISSUE TITLE
closing down pangeo.pydata.org

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#524]
@pangeo-data/pangeo-members - **We are closing down pangeo.pydata.org on January 11.**

### Where to go
If you've missed #373, we've been refactoring pangeo.pydata.org into multiple topical JupyterHubs. We currently have a number of topical deployments that you may want to know about:

- ocean.pangeo.io: https://github.com/raphaeldussin/example.pangeo.io-deploy
- atmos.pangeo.io: https://github.com/pangeo-data/atmos.pangeo.io-deploy
- polar.pangeo.io: https://github.com/NicWayand/polar.pangeo.io-deploy
- astro.pangeo.io: https://github.com/pangeo-data/astro.pangeo.io-deploy

Others in the works:
- hydroshare.pangeo.io
- neuro.pangeo.io

Of course, there is also https://binder.pangeo.io if you are just looking for a way to run notebooks using Pangeo.

### Getting your data/notebooks off pangeo.pydata.org
If you have data/notebooks on this JupyterHub that you may want to keep, @rsignell-usgs suggested this little snippet:

```bash
find . -type f -name '*.ipynb' -print | grep -v '.ipynb_check' > list_of_notebooks
tar -cvf backup.tar -T list_of_notebooks
gzip backup.tar
# download the backup.tar using jupyterlab interface
```

xref: #373

**Comment by jhamman** [comment]
> What about hub.pangeo.io

We're currently using this deployment (and dev.pangeo.io) for testing and development. Things have been slow there recently but its fair game for general use.

**Comment by mrocklin** [comment]
FYI @aterrel Pangeo is no longer using this domain
