### ISSUE TITLE
Access to pangeo

### ISSUE THREAD

**Issue by sdanbury** [pangeo-data/pangeo#526]
Hello!

I just came across pangeo via this YouTube video: https://www.youtube.com/watch?v=iRHJYXu5qx8.

Is it possible to get access please?

Thanks

**Comment by scottyhq** [comment]
Hi @sdanbury you should get an email from github to confirm membership.

There are now a few domain-specific deployments:
http://pangeo.io/deployments.html 

In theory once you are a member you have access to this deployment (but I think it might be broken currently!):
https://hub.pangeo.io 

In the meantime, consider using binder to if you are just wanting to prototype and familiarize with the interface. Here are the most recent demos:
https://github.com/pangeo-data/pangeo-tutorial-agu-2018
