### ISSUE TITLE
Access to Pangeo JupyterHub Insta

### ISSUE THREAD

**Issue by KateSnow** [pangeo-data/pangeo#528]
Hi,

I am a Research Data Management Specialist at the National Computation Infrastructure, Australia and we are interested in potentially promoting pangeo and providing a deployment here for our climate science user-base. 

If possible, would I be able to get access to the pangeo JupyterHub to test possible workflow use-cases and asses it against the data we host at NCI?

Thanks!

Kind regards,
Kate.

Dr Kate Snow
Research Data Management Specialist
National Computational Infrastructure (NCI)
The Australian National University
143 Ward Road
Acton, ACT, 2601

**Comment by jmunroe** [comment]
Hi Kate,

Have you heard about CSIRO Data Science Community of Practice? (
https://research.csiro.au/dfp/get-involved-in-the-csiro-data-science-community-of-practice-in-2019/).
There is a group of us pushing for Pangeo adoption in Australia. In
particular, I'll highlight

   - May 8-10th:  Sessions and workshops in Canberra, Australia in concert
   with the Collaborative Conference on Computational and Data Intensive
   Science, 2019 (C3DIS 2019)

which will have a Pangeo focus.

James


JAMES MUNROE   |   ASSOCIATE PROFESSOR

Department of Physics and Physical Oceanography
Memorial University of Newfoundland
230 Elizabeth Avenue
St. John’s, Newfoundland, Canada   A1C 5S7
Chemistry and Physics Building   |   Room C 4060
T  709 864 7362   |   M  709 771 0450

www.physics.mun.ca

**Comment by mrocklin** [comment]
Welcome @KateSnow .  I've extended you an invitation to join the Pangeo-data github org.  

I'm a bit behind on the current state of things, but I *think* that this should given you sufficient privileges to log into most of our deployments.

**Comment by scottyhq** [comment]
Hi @KateSnow 

You should have gotten a membership confirmation email from github.

In theory once you are a member you have access to this deployment (but I think it might be broken currently!):
https://hub.pangeo.io 

There are now a few domain-specific deployments that might interest you
http://pangeo.io/deployments.html 

Also, consider using binder to if you are just wanting to prototype and familiarize with the interface. Here are the most recent demos:
https://github.com/pangeo-data/pangeo-tutorial-agu-2018
