### ISSUE TITLE
conference opportunity: FOSS4G-NA (San Diego, Apr 16-18)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#529]
The FREE AND OPEN SOURCE SOFTWARE FOR GEOSPATIAL conference is a community that Pangeo might want to engage with:
https://2019.foss4g-na.org/

There are lots of GIS, COG, STAC type things at this conference. Maybe @scottyhq would be interested in submitting a talk about Pangeo?

Submission deadline is Jan. 16:
https://www.papercall.io/fossa4gna2019

**Comment by scottyhq** [comment]
Good idea! I'm free the week of FOSS-4G (April 15-19 San Diego) and could go represent pangeo. Anyone else going? Want to be a coauthor? Let me know. There is an option for a 20 minute talk or 1-hour workshop.

**Comment by jhamman** [comment]
@scottyhq submitted an abstract for this (and I think it was accepted). Thanks @rabernat for posting.
