### ISSUE TITLE
conference opportunity: SciPy (Austin, TX, July 8-14)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#530]
I think we should definitely make a strong Pangeo showing at SciPy this year.

https://www.scipy2019.scipy.org/

Talk and poster submission deadline is Feb. 10:
https://www.scipy2019.scipy.org/talk-poster-presentations

Let's brainstorm what sort of things we are excited to share with the SciPy community.

**Comment by jhamman** [comment]
A few references from last year:

- We proposed a Xarray/Dask tutorial that was not accepted. Abstract and discussion are included in this issue: https://github.com/pydata/xarray/issues/1882
- I gave an overview presentation on Pangeo: [link](https://scipy2018.scipy.org/ehome/index.php?eventid=299527&tabid=712461&cid=2233540&sessionid=21618394&sessionchoice=1&)
- We held a Pangeo BoF ([link](https://scipy2018.scipy.org/ehome/index.php?eventid=299527&tabid=721463&cid=2264594&sessionid=23409892&sessionchoice=1&)) and Dask BoF ([link](https://scipy2018.scipy.org/ehome/index.php?eventid=299527&tabid=721463&cid=2264594&sessionid=23401072&sessionchoice=1&))

I think a revised version of the tutorial would be a great. I'm also keen to see a strong Pangeo showing at the sprints which I unfortunately missed last year.

**Comment by kmpaul** [comment]
I am thinking of sending my software engineers to SciPy this year, with the primary goal of having them involved in the sprints.  However, I'm sure they would be happy to help out with tutorials, too.

**Comment by jhamman** [comment]
FWIW, I submitted a proposal for a Pangeo BoF today.

**Comment by jsignell** [comment]
It looks like there will be a pyviz tutorial.
