### ISSUE TITLE
First meeting of the machine learning working group

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/pangeo#532]
cc @rabernat @jhamman @mrocklin @arokem @shoyer 

Today, we spent some time in the weekly check-in meeting  (#527 ) discussing how pangeo can support machine learning workflows. Overall, there is a lot of interest, and we just barely cracked the surface. To further discuss, we agreed to start a machine learning working group, and I think we should set up a video-call within the next couple of weeks. If you would like to participate, **please fill in your availability on this doodle poll: https://doodle.com/poll/5f6x8dinmu5eetmn**

I was not able to find github user names for everyone on today's call. Would someone be able to @ the people I missed (eg. Alando, Jim)?

As an agenda, we could build off the topics we mentioned today:

- Example workflows for climate ML - jupyter vs command line
- Data preprocessing and data loading
- Data structures (e.g. labeled arrays for deep learning, interoperability of numpy-like libraries)
- Infrastructure - GPUs, data storage
- Automation and reproducibility: 
   - hyper-parameter tuning
   - workflow engines: snakemake, pachyderm
   - experiment loggers: sacred

As @mrocklin brought up, I think we should figure which of these items are general enough to lie within the scope of pangeo. Having a list of existing or envisioned machine learning workflows would help us do this. It seems that Anaconda+NASA has compiled a nice set of tutorials in the [EarthML](http://earthml.pyviz.org/index.html) project. For my part, I recently gave an [ML tutorial](https://github.com/nbren12/2018-11-06-python-in-geosciences) using binder.pangeo.io that went really smoothly.

What else do you all think we should discuss?

**Comment by alando46** [comment]
I like the idea of starting off with the workflows. It seems like it could be useful to try and coalesce on a common-ground workflow that is the ideal balance between flexibility/extendability and simplicity. Through that lens, we could also discuss what fits into the Pangeo scope.

Thoughts?

Looking forward to getting started.

**Comment by raspstephan** [comment]
Hi everyone. 
I would also be interested in joining this (replied to the doodle already). I am working an a similar topic as Noah and am also struggling with large data amounts in my ML and analysis workflow for which I already use xarray. Maybe I can contribute some insights from a practitioner's perspective.

**Comment by gmaze** [comment]
Hi all,
I'm also very interested into this.
I primarily use ocean observations (in situ and satellite through xarray, eg: github.com/obidam/pyxpcm)
I found that a critical step is into the data preprocessing and loading, as it requires slow "stacking" of multiple dimensions and possibly interpolation along at least one of the dimension of the arrays.

**Comment by jhamman** [comment]
@nbren12 - was a date/time settled on here?

**Comment by RPrudden** [comment]
I'm also very interested, and will make the next meeting if I can.

**Comment by jhamman** [comment]
I've updated my availability. I can be available on the morning of the 25th.

**Comment by nbren12** [comment]
@jhamman  Great! Sounds like we should go with that date.

Ok everyone. It looks like the best date for us to meet is [Jan 25 from 10:00 AM to 11:00 AM (PST)](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=1&day=25&hour=18&min=0&sec=0&p1=234&p2=179). I will follow up with details about the video conference.

I am sorry that @gmaze and Rachel cannot make that time. Hopefully, you can attend future calls.

**Comment by nbren12** [comment]
Thanks for letting me know Ryan. Even with that in mind, I still think Jan 25 is the best day given everyone's availability. 

Unfortunately, I think we are stuck in a local minimum for now. An alternative would by June 24th at 9am (PST), but then @shoyer, @alando46 , and @rabernat  couldn't attend.

**Comment by nbren12** [comment]
Okay.  I think we should finalize the date for  [Jan 25 from 10:00 AM to 11:00 AM (PST)](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2019&month=1&day=25&hour=18&min=0&sec=0&p1=234&p2=179). Does that sounds okay? If so, thumbs up this post.

**Comment by rabernat** [comment]
@duncanwp is very interested in participating!

**Comment by djgagne** [comment]
I will be joining in as well.

**Comment by ktyle** [comment]
I would like to join in too!

**Comment by nbren12** [comment]
Great! I'm glad there is so much interest. 

@rabernat or @jhamman  How do you recommend setting up the video conference?

**Comment by jhamman** [comment]
@nbren12 - for groups less than 12, https://appear.in/pangeo has been working well. For larger groups, it seems Zoom has been our best option. I think we're likely on the edge there so I'd favor a zoom call. Can you set that up?

**Comment by nbren12** [comment]
I think I have zoom through UW.

**Comment by nbren12** [comment]
Actually, the UW zoom accounts have this limitation: "Your Zoom Basic plan has a 40-minute time limit on meetings with 3 or more participants." I emailed IT to see if they can upgrade me to an unlimited account.

**Comment by djgagne** [comment]
NCAR has access Google Meet, which seems to scale pretty well for moderate sized meetings. Joe or I could set up a calendar event with a Google Meet link if that works for everyone?

**Comment by TomAugspurger** [comment]
@djgagne could you send an invite to me at taugspurger@anaconda.com? Thanks!

**Comment by chiaral** [comment]
Hello, can I get an invite too? thanks!

**Comment by gmaze** [comment]
It is funny that I can't attend this meeting because I'll be giving a lecture on Machine Learning for Physical Oceanographer !
Anyway, just keep the group commenting on this issue updated with your discussions and hopefully I'll be able to attend the next call.
Cheers
gm

**Comment by darothen** [comment]
Not to add to the clutter but I can lend my Zoom Pro room and delegate someone as a host for the event if it would be helpful. There's already excellent representation in the quorum of participants so I don't want to add any noise.

**Comment by gmaze** [comment]
well, well, thanks to time zones I can make it 
can I get an invite too ?
g

**Comment by djgagne** [comment]
If anyone else wants an invite to the calendar event, can you please post your email address in the request? It would save me some time trying to search for it.

**Comment by leifdenby** [comment]
I'd like to join too, leifdenby@gmail.com. Thanks

**Comment by duncanwp** [comment]
I'm at duncan.parris@gmail.com - thanks

**Comment by pbranson** [comment]
pbranson@gmail.com

Not sure I will make it (2am in my time zone!), but keen to listen - is it going to recorded?
________________________________

**Comment by RPrudden** [comment]
It's out of work hours for me, but I'll sit in if I can.

**Comment by svadams** [comment]
Hi There,

I work with @RPrudden at the Met Office on ML and use Pangeo so I would like an invite please! Can you send it to  sam@samantha-adams.me.uk please! Many Thanks.

**Comment by djgagne** [comment]
I can record the meeting with Google Meet and post a link to the video afterward.

**Comment by svadams** [comment]
Thanks @djgagne that will be a good fallback if we can't manage to dial in!

**Comment by alando46** [comment]
@djgagne alando.ballantyne@gmail.com

**Comment by nbren12** [comment]
I started an agenda for this meeting. Here is a link to an editable document: https://paper.dropbox.com/doc/2019-01-25-MLWG-Meeting-Agenda--AWTjaFKdo001mQ7j0RoyDx~pAQ-sRO8369Z07syVGRaSi0GT

Since we have so many people in attendance, I don't think we will be able to discuss everyone's use-case in depth. Instead, it would be great if a few people (e.g. @RPrudden @djgagne @raspstephan @gmaze ) could describe their use-cases ahead of time on the agenda document. I think this could help guide our discussion to cover the full range of use-cases and avoid repetition. I summarized my own project as an example that you can copy. Please feel free to change the format while remaining concise.

**Comment by djgagne** [comment]
The video of the meeting can be viewed at https://drive.google.com/file/d/1PWqUyyk6Kc3rfMLHQG27jtHP66XblZ74/view?usp=sharing.

**Comment by nbren12** [comment]
Thanks @djgagne for setting up the call and taking that video!

**Comment by nbren12** [comment]
I'm going to close this issue, since the meeting already happened.
