### ISSUE TITLE
Pangeo GCP Account Cleanup

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#533]
Looking at our active kubernetes clusters, I see a few deployments that I'm curious if we are using:

- dev-ocean-pangeo-io-cluster
- pangeo-test-rabernat

@rabernat and @raphaeldussin - I think these belong to you. Are you still using these?

**Comment by raphaeldussin** [comment]
@jhamman yes! it's my test cluster

**Comment by jhamman** [comment]
Along the same thread, we have three buckets in our GCS storage domain that I'm unfamiliar with. They are: 

- gs://artifacts.pangeo-181919.appspot.com
- gs://pangeo-181919_cloudbuild
- gs://us.artifacts.pangeo-181919.appspot.com

Does anyone have any ideas what these might be and if we need to keep them around?

@yuvipanda and @dsludwig -  some of the timestamps indicate these were setup in the fall when you were working on hubploy/nfs things. Any ideas?
