### ISSUE TITLE
Virtual Hubploy Dev Meeting Next Week

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#535]
@yuvipanda and I are trying to setup a virtual meeting next week to coordinate recent and future [HubPloy](https://hubploy.readthedocs.io/en/latest/) development efforts. We're roughly thinking of an agenda including these items:

1. Overview of current functionality, docs, and use cases
1. Decide on scope of hubploy - in and out
1. Enumerate use cases we wanna support - multi-cloud, image building + deployment, repo2docker, any perf goals
1. Make a roadmap with these leading to 1.0, which I wanna get out before end of Feb (and have cycles for)

I'd would really like @dsludwig, @amanda-tan, @apawloski, and @raphaeldussin to be able to make this meeting but anyone is welcome to join if the topic interests you. Please fill out this poll to voice your interest and availability: https://doodle.com/poll/784qp5ufmkmqhzag

also cc @lheagy

**Comment by jhamman** [comment]
Locking in the time at Tuesday, January 22⋅1:00 – 2:00pm PT.  We'll meet here: https://appear.in/pangeo

**Comment by andersy005** [comment]
@jhamman, I am interested in participating, but I can't make the meeting due to time conflict. Any chance meeting notes will be available after the meeting?

**Comment by jhamman** [comment]
@andersy005 - yes, we'll take notes.

**Comment by andersy005** [comment]
Great! Thanks

**Comment by jhamman** [comment]
Thanks all who joined. The meeting notes are here: https://docs.google.com/document/d/1GejmF82L7yNMem1sv5-ZsA25KMuUHgvSe5E736LJRSg/edit?usp=sharing

**Comment by yuvipanda** [comment]
I filed the following issues in hubploy:

- https://github.com/yuvipanda/hubploy/issues/8
- https://github.com/yuvipanda/hubploy/issues/9
- https://github.com/yuvipanda/hubploy/issues/10
- https://github.com/yuvipanda/hubploy/issues/11

And this in example.pangeo.io-deploy

- https://github.com/pangeo-data/example.pangeo.io-deploy/issues/7

There should also be an issue in this repo about moving all the hub configs to one repo, but I'd love for @jhamman or @dsludwig to create that!

I think I got everything? Thanks everyone for coming, and thanks for organizing, @jhamman!

**Comment by jhamman** [comment]
Thanks @yuvipanda - I'm going to close this and we'll start working through the hubploy issues.
