### ISSUE TITLE
Error when upgrading cluster

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#538]
Running step 4 in [this part](http://pangeo.io/setup_guides/cloud.html) of the setup guide

```
setup-guide (master)$./4_upgrade_helm.sh 
Error: failed to download "pangeo/pangeo" (hint: running `helm repo update` may help)
```

Following that hint doesn't help. I seem to remember seeing this before and that it had a rather simple fix, though I can't remember what it was... Searching around, I found that this was also raised in https://github.com/pangeo-data/pangeo/issues/366, but I can't see a solution to this there either. 

Any ideas?

**Comment by jhamman** [comment]
@arokem - how's your cluster coming along?

**Comment by arokem** [comment]
It's up! Based on the documentation in #402, which seems to work now. 

This issue is addressed in https://github.com/pangeo-data/pangeo/commit/6743a960a2a8fdc9657e849d501e4238bce29853, so I think I can close this one.

**Comment by jhamman** [comment]
Great. Nice work @arokem!
