### ISSUE TITLE
Documentation available both on pangeo.io and ReadTheDocs

### ISSUE THREAD

**Issue by lesteve** [pangeo-data/pangeo#548]
When working on #547, I realised that the documentation was available in two separate places, namely pangeo.io and ReadTheDocs, which caused slight confusion. @guillaumeeb asked me to create an issue and cc @rabernat so here it is!

For example, if you look carefully at https://pangeo.io/setup_guides/cloud.html vs https://pangeo.readthedocs.io/en/latest/setup_guides/cloud.html, there are slight discrepancies between the two.

**Comment by rabernat** [comment]
Wow I did not even realize that our docs were on readthedocs. That’s weird!

**Comment by guillaumeeb** [comment]
I really have no idea of where this is or has been set up, I really don't know. of these things...  Any idea @rabernat? Does it come from doctr configuration?

**Comment by jhamman** [comment]
It looks like I am an admin on the pangeo readthedocs account. Should I tear it down. The builds have been failing for some time...

**Comment by jhamman** [comment]
I've removed the readthedocs version of the website for now.
