### ISSUE TITLE
sustainable model for custom binderhub running on GCP?

### ISSUE THREAD

**Issue by mbobra** [pangeo-data/pangeo#551]
Hello! @jmason86 and I put together a [Jupyter-book](https://helioml.github.io/HelioML) powered by a Binderhub running on GCP. The Jupyter-book is meant help students in heliophysics understand machine learning. Right now we have $5k of research credits from Google, but we'll run out of it quickly. Does anyone have ideas on how we can keep our book running? I thought I would ask here since Pangeo also runs a custom Binderhub. I would appreciate some advice!

**Comment by jhamman** [comment]
@mbobra, you bring up a challenging topic. From my perspective, we are currently using the pangeo binderhub to share progress on the Pangeo project in real time. We are also working off research credits from Google and as such, we will eventually (next year sometime) be forced to confront the sustainability of Pangeo services like binderhub. 

I find it useful to clearly state that what we are running right now is a prototype. As such, some of the protoypte services may not move on to a sustainable state.

Ultimately, we want to help inform the process by which research groups, institutions, and distributed projects like Pangeo fund the use of cloud resources. These are open questions and we're probably just scratching the surface. For now, the cloud providers seem to be eager to provide research credits, how we transition to the next stage is yet to be seen.

**Comment by mbobra** [comment]
@jhamman Thanks for your response, I appreciate it. I think it might be nice for the research community to outline their vision for the next stage as well as potential solutions to get there. I'm happy to help draft this kind of thing if anyone at Pangeo is interested. For now I'll close the issue, so that it's not hanging around forever.
