### ISSUE TITLE
Delineation and purpose of domain-specific pangeo subgroups

### ISSUE THREAD

**Issue by poplarShift** [pangeo-data/pangeo#552]
Hi all,

what is not clear from how pangeo is currently presented is where the domain-specific deployments/communities/repos are supposed to head. Are they just temporary subgroups to develop specific aspects of pangeo and to draw in people with particular backgrounds, or are they eventually going to be different deployments?

I'm asking because I've been wondering about how to delinate the polar from the other Earth system science communities/repos/deployments. For example, as an oceanographer working in the Arctic, I would find it quite natural to e.g. develop uses cases etc in the ocean section. Yet it is my impression from numerous conferences, probably due to historical reasons and geopolitics, that (particularly Arctic) researchers mingle/work much more with other Arctic researchers than the people from their respective fields, regardless of the regional focus, and much more so than in other fields. To me, Polar Science and Oceanography/Meteorology/Astronomy are just incommensurable categories. (For instance, do glaciers go into hydrology or polar? Does sea ice go into polar, where it currently "is", or into the ocean?)

I would hate to cement these largely historical divides, but all that being said, I appreciate every effort to get more people into the cloud and big-data style thinking.

**Comment by rabernat** [comment]
Hi Achim,

Thanks for raising a good question for discussion. First of all, keep in mind that this project is very young, and we are basically just making it all up as we go along. Indeed a major goal is to increase collaboration across disciplines. Our thinking in terms of the cloud deployments is that people are more likely to feel welcome if they see a hub listed for "their" discipline. It's also based on our early experience with pangeo.pydata.org, which was our original "all in one" environment. It was hard to balance all of the different use cases in a single cluster.

However, this could definitely backfire if, as you say, we create artificial and unnecessary divides between disciplines.

In the end, these hubs are not going to be that different. They are basically just different DNS pointers to what is essentially the same cluster.

I'd be keen to hear your thoughts on alternative approaches. Should we just have one big cluster?

**Comment by poplarShift** [comment]
Thanks, once again good points - and sorry for my slow response. 

My impression was that different deployments were needed for different software requirements and this was the reason for different deployments? In terms of showcasing the various disciplines, I think one big repository with different subcategories may be enough to not spread the attention too thin and to facilitate exchanges between the disciplines.

And of course I realise pangeo is very young and this issue might not be a concern for many at this stage. Just wanted to learn more about the issue and voice my concerns.
