### ISSUE TITLE
NCAR Seeks Input on next-generation supercomputing system by March 1

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#554]
From the NCAR/CISL Bulletin:

> NCAR’s Computational and Information Systems Laboratory (CISL) is seeking users’ input as part of the process of procuring a system to follow the Cheyenne cluster currently in production in the NCAR-Wyoming Supercomputing Center. Users’ input will help ensure procurement of a system that best meets the community’s future needs.
> 
> Users are asked to provide their input by completing this survey by March 1: [User Survey for CISL's Next HPC Procurement](https://goo.gl/forms/nrhEnnYh36cUJErt2). The survey includes questions about users’ experience with the Cheyenne environment and priorities for the next-generation environment, which is expected to be in production by mid-2021.
>
> Two of the three sections of the survey can be completed in about 10 minutes. Users are welcome and encouraged to respond to some open-ended questions in the third section if they can take the time.

This is a good opportunity for Pangeans to influence NCAR's next computing environment.

**Comment by guillaumeeb** [comment]
Answered as a non Cheyenne user :)
