### ISSUE TITLE
Pangeo needs better tag lines

### ISSUE THREAD

**Issue by djhoese** [pangeo-data/pangeo#557]
I have now had multiple conversations and answered questions multiple times when public speaking about "so what is pangeo?" or "I looked at their website but couldn't tell what they did" or "So what package do I install?" (I know this is addressed on the packages page). I think it would help if the Pangeo home page (http://pangeo.io/) had a top section equivalent to "What we do". This is different from "Our goals" in that it is a simple sentence or two of:

> We provide instructions, support, and community for people wanting to do open reproducible science.

Or something like that. Thoughts?

**Comment by rabernat** [comment]
This is a great suggestion David.

PR welcome!

**Comment by amanda-tan** [comment]
This would be really good to clarify. 

In the About Us page it says this:
Pangeo is first and foremost a community of people working collaboratively to develop software and infrastructure to enable Big Data geoscience research.

The Earthcube funded proposal labels Pangeo as "Pangeo: An Open Source Big Data Climate Science Platform"

The first sounds like Pangeo is really a community and software and tools are an _outcome_ of the community effort. 

The second sounds like Pangeo is a computing platform. 

Without context, it is easy to get confused. I would love to get feedback on what an elevator pitch should be.

**Comment by amanda-tan** [comment]
@rabernat  Can we reopen this issue? It was brought up _**again**_ in the latest Pangeo Summer Meeting and I feel that even after the edits in March, people are still confused.

**Comment by djhoese** [comment]
I'm curious if the people who are confused knew of Pangeo *before* the changes to the home page's description or if they are relatively new to the community. Maybe there needs to be an emphasis when presenting on Pangeo at conferences that it is a community, not a python package. As long as people are listening I think that can help set the frame of thinking for the rest of the talk.

I also think it is a little unexpected for people seeing a presentation at a conference to be about a community rather than research results or a software tool/package.

**Comment by rabernat** [comment]
I am happy to reopen the issue. But it would be good to clarify why we are doing this. We should try to clarify 
- who is our audience here?
- what outcome do we hope to achieve from improving our messaging?
- what are some examples of similarly complex, multi-faceted projects that we feel are more successful than Pangeo at achieving these outcomes?

For example, how would you answer “What is Jupyter?” In 5 words?

**Comment by amanda-tan** [comment]
What actually spurred me to rethink this is that there are only 5 abstracts with the word "Pangeo" submitted to the AGU Fall Meeting this year - and they are all by people intimately involved with Pangeo. And while I realize that the AGU Fall meeting is not the best proxy for user base, it is probably one of the easiest avenue for any new research to be submitted. 

So to @rabernat 's question about the audience, I think we need to start looking beyond folks at NCAR and those who develop xarray or dask or Jupyter. Pangeo's sustainability depends heavily on being able to reach the wider, higher level research community and not just developers. Obviously this depends more on education and outreach than a singular mission statement but even those who work with Pangeo outreach are often confused about how to articulate exactly what Pangeo is.

The outcome that we should aim for is that when someone lands on pangeo.io or googles "What is Pangeo?", they _know_ what is it within a minute. They can envision using it for their own research just by clicking around the website. I would suggest paring down what we have right now on the website to a  two-sentence description that encapsulates the core idea of Pangeo e.g. **The Pangeo Project aims to build and enable a community committed to open, reproducible, and scalable science. The Pangeo computing platform is a synthesis of open-source, scientific Python tools accessible through a Jupyter environment. **

**Comment by rabernat** [comment]
Thanks @amanda-tan for continuing to brainstorm on this important topic. I like your definition of the "Pangeo computing platform," but I have some hesitation about other points you made.

I would not recommend measuring our success by the number of AGU abstracts about Pangeo. How many AGU abstracts have the word "numpy" in them? Or "Jupyter"? It is normal that the abstracts about Pangeo are submitted by the Pangeo core contributors. It is not common practice to refer to software tools and infrastructure in scientific papers, let alone conference abstracts.

> I think we need to start looking beyond folks at NCAR and those who develop xarray or dask or Jupyter. Pangeo's sustainability depends heavily on being able to reach the wider, higher level research community and not just developers.

I resist this characterization of our user base. Python, xarray, dask, Jupyter are growing rapidly at an international level. I don't particularly care whether people think they are "using" Pangeo or not. The boundary between Pangeo and just general scientific python is amorphous and impossible to define precisely. Our goal is to cultivate and support this ecosystem, not to absorb everyone into our platform.

**Comment by rabernat** [comment]
This issue was moved to https://discourse.pangeo.io/t/pangeo-needs-better-tag-lines/44
