### ISSUE TITLE
Pangeo Demo for OpenMod at NREL in October? 

### ISSUE THREAD

**Issue by zaneselvans** [pangeo-data/pangeo#561]
The first North American Open Energy Modeling ([OpenMod](https://www.openmod-initiative.org/)) workshop is being organized for the end of September at NREL in Golden, CO (see [this forum thread](https://forum.openmod-initiative.org/t/north-america-openmod-workshop-series/1325/10)). These are the folks who would be making use of the energy modeling Pangeo deployment that I started discussing in #489. I'm wondering if anyone from Pangeo (maybe at NCAR/UCAR, @jhamman?) would be interested in attending and giving a workshop demonstrating how Pangeo could be put to use in this domain? Hopefully by that point we will actually have some of the energy system specific data sources loaded into the catalog, but even if not, it would be great to get folks more familiar with the platform and usage model. I asked folks on the OpenMod email list if they would be interested in using such a platform for energy system modeling and there were some enthusiastic replies.

**Comment by jhamman** [comment]
Hi @zaneselvans - sorry I missed this (until now). Hopefully you found someone to attend the workshop already (unfortunately I'm most likely unavailable). I did want to make sure you saw the announcement for the Pangeo Summer Community Meeting (#347). Maybe you or someone from Catalyst Cooperative can make it to Seattle for that?
