### ISSUE TITLE
Materials for presentations

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#563]
Good news! I am giving a talk at [BRAIN Initiative PI meeting](https://www.braininitiative.org/events/pimeeting/) about our use of Pangeo in a neuroscience collaboration (and also presenting a poster). 

I am wondering whether we should start a repo/repos for presentation materials. I tend to use reveal.js for talks, and latex for posters, so my talk slides and posters are version-control friendly, and could each be a repo (under pangeo-data? under my own account with a link from a central location?) but I realize that there may be multiple formats that people use for these kinds of things.

**Comment by scottyhq** [comment]
Awesome! I think this is a great idea, I just created a new repo under pangeo-data:
https://github.com/pangeo-data/pangeo-presentations 

Feel free to add pull-requests to link to version controlled content, or directly edit the wiki page with links to content:

https://github.com/pangeo-data/pangeo-presentations/wiki/Videos

**Comment by arokem** [comment]
How do you feel about adding in other repos as sub-modules? I would like to put up my talk on a gh-pages website, so would need an entire repo for it, but would also be pushing it here. Looks like a sub-module might work for that.

**Comment by arokem** [comment]
Well, I went ahead with https://github.com/pangeo-data/pangeo-presentations/pull/1, so we can discuss the submodule issue there.
