### ISSUE TITLE
NOAA Emerging Technologies Workshop

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#565]
https://nosc.noaa.gov/emerging-tech-workshop.php

> The National Atmospheric and Oceanic Administration (NOAA) Emerging Technologies Workshop (ETW), is a two-day, public event showcasing the latest innovations designed to collect, analyze, and/or synthesize environmental data. First held in 2016, the event aims to identify new technology with the potential to advance NOAA’s capabilities to monitor, assess, and predict the environment. The workshop features presentations and technical posters highlighting projects funded by NOAA and external stakeholders, representing academia, private industry, and other federal government agencies

![poster](https://nosc.noaa.gov/images/Poster_area-20190225.jpg)

Could be a good opportunity to drum up support for Pangeo. Anyone interested in attending?

**Comment by aradhakrishnanGFDL** [comment]
Hi @rabernat- Balaji also brought this up. If there is an opportunity for us to help with this workshop/demo, we'd (GFDL) be interested. Please let me know. Thanks,

**Comment by rabernat** [comment]
Basically we need a volunteer to submit a talk to this. I can't make it personally, as it conflicts with [another conference](https://www.ametsoc.org/index.cfm/ams/meetings-events/ams-meetings/22nd-conference-on-atmospheric-and-oceanic-fluid-dynamics/22nd-conference-on-atmospheric-and-oceanic-fluid-dynamics-call-for-papers/).

What would be best would be a general talk on Pangeo and its potential value to NOAA, along the lines of the [talk I gave](https://speakerdeck.com/rabernat/pangeo-at-esgf-f2f) at the ESGF F2F.

@aradhakrishnanGFDL - If you or anyone else would like to take the lead here, we will be happy to support you with slides and resources for a demo. Nobody "owns" Pangeo, and anyone reading this is qualified to present on behalf of the project.

**Comment by aradhakrishnanGFDL** [comment]
Hi @rabernat- Thanks. We will be happy to help. There may be a couple of GFDL-ers to help out with this. I will check the abstract guidelines, get some approvals and circle back with you by email.

**Comment by aradhakrishnanGFDL** [comment]
Hi @rabernat. Just letting you know that I am looking into this-- meeting with some GFDL colleagues tomorrow. I will keep you posted ASAP since the abstract submission deadline is March 15. Thanks .
