### ISSUE TITLE
Pangeo presence at EGU2019

### ISSUE THREAD

**Issue by DPeterK** [pangeo-data/pangeo#566]
Hi all, I've a poster confirmed at EGU this year presenting construction and processing of big nD datasets using Iris on the Informatics Lab Pangeo. I was wondering if there will be any other Pangeo community presence there? We could try and put together an informal meet-up (I suspect it's now rather too late for anything more formal) if it's more than just me representing Pangeo at EGU this year!

**Comment by jhamman** [comment]
Hi @DPeterK - I was at EGU last year but won't be able to make it this year. I think @fmaussion, @Chilipp, and @benbovy all came our for 🍻 last year. Perhaps they will be there again this year?

**Comment by DPeterK** [comment]
EGU is done! It was a good assembly, but my reflection on the Pangeo front is there's very little knowledge of it over here in Europe. I think we need to go on a publicity drive! What I saw was a lot of people inventing something that looks a bit like Pangeo, but much more limited – it's either hosted on a private cloud, or doesn't scale, or just hasn't been designed with the long view in mind.

There were a few people and organisations who were interested though - particularly KNMI, the Royal Dutch Meteorological Agency. They've produced a system that's already quite like Pangeo, so I'm going to engage with them and see if I can help them out with what they've currently got and see if we can also get them onboard with Pangeo!

**Comment by kmpaul** [comment]
@DPeterK That is very interesting feedback.  I and @niallrobinson and @mrocklin will be at PASC this June giving a minisymposium focused on Pangeo.  I am hoping to have a mini-hackathon while we are at PASC, and it seems like that might be a good way to interact more closely with interested individuals and possible build contacts with some of the organizations you mentions (KNMI).
