### ISSUE TITLE
What could be the next generation HPC cluster design, private cloud hybridation?

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#572]
Hi Pangeans!

I'm currently thinking about the design for the next generation of computing cluster at CNES, due to 2021. What I want is to take the best of two worlds: standard HPC architecture and Cloud technology.

So the current idea is to have an infrastructure which can host both a job queueing system (PBS, LSF or Slurm) and an OpenStack or Kubernetes cluster. This infrastructure should comply with HPC needs, so Infiniband connection and high performance storage (GPFS/Lustre). At CNES our workload is pretty data centric, even when using classical HPC interface, so the compute nodes are kind of "commodity harware" and can easily be shared between HPC and a private cloud.

In order to deploy that, I currently see two solutions:

- My first idea was to handle deployment with classical tools: Xcat or alike (Cobbler/ansible) for automatic node deployment, one group of compute nodes is dedicated to the HPC side whereas the other is deployed for the private Cloud. Private cloud can talk to HPC. Balancing between worlds can be done by redeploying nodes in a few hours, but needs low level administration so you won't do that every day.
- Second idea came for further reading [here](https://kubernetes.io/blog/2017/08/kubernetes-meets-high-performance/) or [there](https://fr.slideshare.net/luckyfengyong/when-hpc-meet-mldl-manage-hpc-data-center-with-kubernetes): all the infrastructure is deployed with Kubernetes, and part of Kubernetes resources are used for deploying a job queueing system managed cluster. This looks really elegant, much more dynamic, but may be more tricky to handle, especially with specialized fabric like Infiniband or hardware such as GPUs.

So I'm curious of what the community think of this, and if people have already tried things like that. I'm sure people at NCAR do think about that (#554), and others too. My current interrogations are specifically:

- Kubernetes or Open Stack?
- How to handle Infiniband in Kubernetes?
- Are there job queuing system already compliant, I've seen that Univa and IBM with LSF already work on this?
- Is there a solution close to this already existing, again thinking on IBM Spectrum suite here, even if I'm more an open source technology guy?

cc @kmpaul @jhamman @willirath @jacobtomlinson and probably others.

**Comment by jacobtomlinson** [comment]
cc @niallrobinson

**Comment by guillaumeeb** [comment]
Uping this thread a bit, I'd really like to have some insights from @kmpaul or other NCAR fellows. Or any other computing center thinking about this. If other Pangeans have some clue on who might give some answers to my reflexion, this would be quite welcome!

**Comment by kmpaul** [comment]
Hey, @guillaumeeb!  Sorry for the delay.

One thing that has come up in our discussions around our next supercomputer purchase here at NCAR is the need for reliability.  User surveys have indicated to us that 95% uptime (~2 days a month) is not enough.  Scheduled downtimes for system maintenance are actually a big annoyance for some of our users, who are quite vocal about the inconvenience.  So, unscheduled downtimes are even worse.

Usually, we try to purchase a machine that is roughly 3x faster than the last machine.  In one of the planning meetings, the idea was floated that maybe we could trade some performance for an "always up" machine, virtualizing everything.  Maybe we only deliver 2x performance, but then "some part" of the machine would always be up and usable.

In this scenario, you could dynamically balance which nodes were part of the Kubernetes cluster and which were part of the traditional HPC cluster...though (with current technology?) maybe only with the help of sysadmins.  That would also give you a platform on which to experiment with HPC on Kubernetes, such as developing tooling that works with Kubernetes to act like a traditional job scheduler...which would lead (hopefully) to full adoption of Kubernetes.

On paper, I like what Univa is doing, building on top of Kubernetes for their entire HPC stack, but I've never used it, I don't know who does, and I worry about the cost.  From the NCAR perspective, I feel like we are too small to invent our own wheel, like maybe LLNL or NERSC might do.  So, as is usually our situation, we tend to get into the game late, after the technology is tried and tested.  Personally, I have my eyes on (kube-batch)[https://github.com/kubernetes-sigs/kube-batch].

**Comment by guillaumeeb** [comment]
Thanks very much @kmpaul for the answer. We've got a little better uptime (10 hours planned downtime a month), but this is still a concern for "operational" users. So having some part of the machine always up is also something we are thinking about. The main concern being the storage component, cost of complete replication is really high.

I don't mind using the help of sysadmins for balancing, we're way smaller than you are, so probably a little more agile, I do sysadmins stuff on our cluster! 

And I will keep an eye on kube-batch.
