### ISSUE TITLE
Weekly checkin meeting 2019-03-20 20:00 GMT (1p PT, 4p ET)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#576]
Today we will have our _late_ weekly checkin meeting. Video Conference Link: https://appear.in/pangeo

As we decided in #570, please try to add agenda items to the agenda BEFORE the meeting starts so we can be sure to cover the topics that are important to everyone.

https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU

The items I have added so far are:
- Recent progress on unifying Pangeo cloud datastore (Ryan)
   - https://github.com/pangeo-data/pangeo-datastore
   - Master catalog + sub catalogs
   - Running CI on catalog
- Education Working Group
   - https://github.com/pangeo-data/pangeo/issues/575
   - https://github.com/pangeo-data/education-material

Due to my child-care constraints, I will have to leave after 30 minutes, you you should certainly carry on without me.

**Comment by mrocklin** [comment]
For Pacific time there is a discrepancy in time in the title.  If we're meeting at 20:00 GMT then this is 1pm Pacific time

**Comment by rabernat** [comment]
Thanks for catching this Matt. As a climate scientist, time zones are the bane of my existence.

**Comment by mrocklin** [comment]
Try fiannce
