### ISSUE TITLE
Weekly checkin meeting 2019-03-27 16:00 GMT (9am PT, 12pm EST)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#578]
I'm looking forward to our weekly checkin meeting tomorrow.  https://appear.in/pangeo

On the agenda so far:

- Demo of new CMIP6 examples binder and discussion of the potential role of Pangeo within CMIP / ESGF  - https://github.com/pangeo-data/pangeo_cmip6_examples 
- Discussion from Julia Wagerman (@jwagemann) about possible applications of Pangeo at ECMWF

Please add any other agenda items to the [google doc](https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU/edit#) _before_ the meting starts.

**Comment by naomi-henderson** [comment]
The 12 person quota for appear.in is full. Who is still trying to connect?
