### ISSUE TITLE
no access to pangeo

### ISSUE THREAD

**Issue by chiara7** [pangeo-data/pangeo#580]
Hello everyone,
since a couple of days I cannot login on my pangeo-account, https://ocean.pangeo.io/hub/user/chiara7/ just gives me a '504 Gateway Time-out' error. Is this a general issue at the moment or is it just me? Thank you for any help,
Chiara

**Comment by rabernat** [comment]
@raphaeldussin can you please look into this asap?

**Comment by raphaeldussin** [comment]
@chiara7 I can see a server running. Do you want me to kill it and try again?

**Comment by chiara7** [comment]
yes, please. Kill the server and I try again. Thankyou

**Comment by raphaeldussin** [comment]
so the nice way through the GUI is not working so I'm gonna kill the pods directly

**Comment by raphaeldussin** [comment]
give it another try and keep me posted

**Comment by chiara7** [comment]
It works. I could login. Great!
Do you have any idea what went wrong? So that I can prevent it from happening again?

**Comment by raphaeldussin** [comment]
awesome! Unfortunately no idea what went wrong, your jupyterhub instance was already destroyed but somehow the hub was stuck in a state where your hub was like a schrodinger's cat. I stopped the hub and it worked.

**Comment by chiara7** [comment]
ok, thank you for explaining what you did :)

**Comment by raphaeldussin** [comment]
@chiara7 I'm going to migrate the ocean.pangeo.io cluster, can you log out?
