### ISSUE TITLE
ESIP Pangeo 403

### ISSUE THREAD

**Issue by acannistra** [pangeo-data/pangeo#581]
cc: @rsignell-usgs @amanda-tan 

After two weeks of successfully using the Pangeo installation up at `pangeo.esipfed.org`, I'm now getting a 403 error when I sign in. (This started about a week ago, but I've been traveling and am just now mentioning it). Any idea why?

There may perhaps be a correlation with a change I made in `.profile` (I wanted a `pip install` to happen on login)? 

Looking forward to your assistance.

**Comment by amanda-tan** [comment]
It's 403 for me as well, @jhamman I can't access this cluster, so can you assist?

**Comment by rsignell-usgs** [comment]
Sorry gang, this was my fault.  A week ago or so I restricted the usage to a single whitelisted github organization
https://github.com/orgs/cdi-workshops/people
You should find invites there.
