### ISSUE TITLE
Something wrong with pangeo.io DNS?

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#582]
I can't seem to connect to our learning2learn.pangeo.io instance for the last hour or so. I can't see anything wrong our end, so I am wondering whether there is something afoot with the DNS redirect?

**Comment by jhamman** [comment]
I'm was able to access the hub's front page. I don't think I have perms to log in so I get an error during the auth step.

**Comment by arokem** [comment]
Looks like it was a temporary thing. Works now.

@jhamman: It's weird that you ran into issues . I think that must be because you are not a public member of the GitHub org. I will amend that :-)
