### ISSUE TITLE
Access to Pangeo 

### ISSUE THREAD

**Issue by hot007** [pangeo-data/pangeo#583]
Hi there,

I really ought to create an account so I can use Pangeo myself instead of just watching the chatter here. Could you please invite me to the git space? I'm a support scientist in climate modelling and projections at CSIRO, Australia; and yes, I will be at C3DIS and the subsequent hackathon ;-) Just wanting to get prepared now so I can have useful questions next month!

cheers
Claire

**Comment by mrocklin** [comment]
Welcome @hot007 !  We're glad to have you.

I've sent you an invitation to the pangeo-data organization on  GitHub .  You'll also need to go to https://github.com/orgs/pangeo-data/people and change your visibility status from Private to Public.

**Comment by hot007** [comment]
Thank you very much :)
