### ISSUE TITLE
OpenShift Deployment of Pangeo

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#587]
The USGS has approved OpenShift for use on AWS but we are struggling to get Pangeo going on OpenShift.   

On the [ZeroToJupyterHub Documentation for OpenShift](https://zero-to-jupyterhub.readthedocs.io/en/latest/redhat/step-zero-openshift.html) it suggests using the [JuypterHub for OpenShift project](https://github.com/jupyter-on-openshift/jupyterhub-quickstart/blob/develop/README.md) but that project does not use Helm.  In fact, there it says:

> OpenShift, being a Kubernetes distribution, you can use the JupyterHub deployment method for Kubernetes created by the Jupyter project team. That deployment method relies on using Helm templates to manage deployment. The use of Helm, and that Kubernetes is a platform for IT operations, means it isn't as easy to deploy by end users as it could be. This repository aims to provide a much easier way of deploying JupyterHub to OpenShift which makes better use of OpenShift specific features, including OpenShift templates, and Source-to-Image (S2I) builders. The result is a method for deploying JupyterHub to OpenShift which doesn't require any special admin privileges to the underlying Kubernetes cluster, or OpenShift. As long as a user has the necessary quotas for memory, CPU and persistent storage, they can deploy JupyterHub themselves.

I'm guessing this non-Helm approach might be a problematic for deploying Pangeo, right?

**Comment by guillaumeeb** [comment]
I'm curious, why USGS prefers using OpenShift instead of EKS?

And to give some answer (but I'm not a Kubernetes/Helm expert), Pangeo deployment currently relies entirely on Helm. Pangeo helm chart extends Jupyterhub one, and mainly add some RBAC rules to allow Dask starting new Pods on the underlying Kubernetes cluster.

I guess this means you require some admin priviledges to define this RBAC rules, and I don't know how this translates to Openshift features...

**Comment by rsignell-usgs** [comment]
@guillaumeeb , indeed, it seems we are asking for trouble (or at least a lot of extra work) if we don't stick with Helm.  I will investigate the issues with the USGS Cloud Hosted Solutions team.

**Comment by jduncan-rva** [comment]
> I'm curious, why USGS prefers using OpenShift instead of EKS?
> 
> And to give some answer (but I'm not a Kubernetes/Helm expert), Pangeo deployment currently relies entirely on Helm. Pangeo helm chart extends Jupyterhub one, and mainly add some RBAC rules to allow Dask starting new Pods on the underlying Kubernetes cluster.
> 
> I guess this means you require some admin priviledges to define this RBAC rules, and I don't know how this translates to Openshift features...

The same RBAC is used in OpenShift as any other kubernetes distribution. I'm happy to help debug this if you can offer up some more information about the error(s) you're running into? 

Helm charts work fine on OpenShift. It's likely just an issue around how the images are built that is tripping up OpenShift's default security profiles.

**Comment by rsignell-usgs** [comment]
Over on the [Pangeo gitter](https://gitter.im/pangeo-data/Lobby?at=5cb4da8e93fb4a7dc234fc31), @yuvipanda said:

> Probably [the issues with jupyterhub helm chart were] around runAsUser and the crazy rbac that our nginx ingress requires.  These are all fixable, and I think if the regulatory environment can't be changed, we should be able to get the chart working it's just work that needs to happen, and requires some understanding of openshift's opinionated decisions, why they were made, and how to adapt ourselves to that. 

I have a meeting later today with the USGS developer who tried to get this going, and hopefully he can join the conversation here and report his issues.

**Comment by rsignell-usgs** [comment]
@samuel-co, can you please post the problems you encountered trying to get the JupyterHub helm chart going?

**Comment by samuel-co** [comment]
Haven't yet tried to run the Pangeo helm chart on OpenShift, only jupyterhub has been attempted.

Using Openshift 3.9.68, with Helm 2.13.1. Prior to attempting to install jupyterhub Helm was confirmed to be working, as per [this blog post](https://blog.openshift.com/getting-started-helm-openshift/) we could deploy the test nodejs helm chart.

Next, attempting to install jupyterhub v0.7.0 (as later versions require Kubernetes >= v1.11.0 and were using v1.9.1). The tiller project on openshift was granted admin access to the pangeo project. Initial install attempts all timed out with `Error: timed out waiting for the condition`.

When running with a  timeout of 6000, the chart was able to successfully deploy the proxy pod, however the hub pod continuously failed to deploy with the following error:

```
Error creating: pods "hub-7bcbccbb89-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000270000, 1000279999]]
```

That is the main error I'm concerned with. Some initial research indicated granting kubernetes-system increased permissions could solve this, however when I attempted a reinstall I ran into the following error, regardless of the timeout set.
`Error: watch closed before UntilWithoutRetry timeout`

I haven't had a chance to dig into that latest error yet. Let me know what other info might help to debug.

**Comment by jduncan-rva** [comment]
The error is that the pod is trying to use UID 1000 (I noticed it in the python script for Pangeo)
`1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser`

OpenShift's default behavior is to allow a randomized UID from the following range:
` must be in the ranges: [1000270000, 1000279999]]`

The fix for that error is to either:
1) roll a new image that aligns with OpenShift's default behavior - https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html#openshift-specific-guidelines
2) Modify the default security context constraint to allow arbitrary UIDs to be inherited from the container image metadata - https://docs.openshift.com/container-platform/3.9/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile

Let me know if you have any questions.

**Comment by rsignell-usgs** [comment]
Just to follow up on this, we ended up deploying on AWS using EKS.
