### ISSUE TITLE
Autoscaling on GCE

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#59]
To manage costs it would be useful to use autoscaling clusters on GCE.  This is especially valuable for dask workers, whose usage will be highly variable.  However, I'm somewhat concerned that user's juypter pods may be relocated up while scaling down.  I'm curious if it's possible to use multiple node groups to do this, and to have certain pods prefer certain node groups.

**Comment by mrocklin** [comment]
cc @yuvipanda (low priority)

**Comment by rabernat** [comment]
I just had a chat with @lila (Karan Bhatia of Google). He mentioned that they already have an autoscaling dask cluster running on GCP. It would be good to sync up with the google folks to find out what they are up to.

**Comment by mrocklin** [comment]
Agreed.

In the mean time @lila do you happen to have any information about what you
all are up to?

**Comment by mrocklin** [comment]
Back to the topic at hand.  @yuvipanda can you make some suggestions about how to encourage jupyter pods to end up on one node-pool and dask-workers to end up on another?

**Comment by yuvipanda** [comment]
Yes! You can use node-pools and nodeSelectors!

You can create two nodepools - one based on permanent nodes for notebook pods, and one based on preemptible ones for dask workers. Then you can use nodeSelectors (`hub.nodeSelector`, `proxy.nodeSelector` and `singleuser.nodeSelector`) to pin the jupyter related pods to one nodepool, and the dask workers to the other pool. If you don't pin the dask workers, they'll take up space on all pools - which might or might not be something you want. Soon https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/ will be widely available and might be something you wanna use for dask workers.

https://cloud.google.com/kubernetes-engine/docs/concepts/preemptible-vm has more info as well.

**Comment by jreadey** [comment]
Has anyone considered Google Cloud Functions for dask workers?  The advantage here would be that you can launch cloud functions much faster than spinning up additional servers and the cost is billed in 100ms increments.

**Comment by mrocklin** [comment]
My concern would be that different workers wouldn't have network access to
find each other.  If this was the case then we would only be able to
perform the very basic parallel computations.

**Comment by mrocklin** [comment]
Do you know if this is the case?  Is it possible to use these sorts of
features (or AWS Lambda) in a space where different long-running functions
can communicate with each other?  My assumption to this has always been
"no", but I haven't investigated deeply.

**Comment by jreadey** [comment]
No, I don't think so either.   The max runtime for a GCF is 9 minutes, it would not even be possible to keep them around for a long-running job.

I was imagining GCF as one-shot workers.  I.e. they would execute there function return the result and terminate.

Don't know if this would fit in with the Dask.Distributed framework though.  Maybe as leaf nodes?

**Comment by mrocklin** [comment]
The 9 minute time isn't a big obstacle.  Dask workers can come and go.  The
lack of inter-worker communication is.  People often use Dask when they do
more complex computations, such as arise in our case from multi-dimensional
arrays.

**Comment by jreadey** [comment]
Yep, that would be a problem for that use case.

Autoscaling has the limitation in that it can take several minutes for the new instances to come online.

**Comment by yuvipanda** [comment]
Azure Container Instances or AWS Fargate are probably better fits for dask
workers, and they can work with the same kubernetes API (via the Virtual
Kubelet project).

**Comment by rabernat** [comment]
Has this been resolved?

**Comment by mrocklin** [comment]
Yes
