### ISSUE TITLE
  Plug Pangeo into EU Cloud provider and Data and Information Access Services (DIAS)

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo#594]
Hi everyone,

It's been a while now that I want to try out Pangeo on european Cloud providers. Just did not find the time and (small) funding yet.

Yesterday, I organized an event on how to handle Data in the Cloud, and we had several talks about the DIAS. I briefly mentioned them on a gitter conversation a few months ago : it's basically 5 different organizations (Sobloo, Mundi, Onda, Creodias, Wekeo), funded by European Union, providing high level services (catalog, web UI, datasets ...) to access EO data. These DIAS are built on European cloud provider services (OVH, T-Systems, Orange ...). This is tightly linked to #588, as DIAS propose Sentinel, Landsat, Copernicus Marine Services and other datasets for free (see for example https://sobloo.eu/data/global-data-offer or https://www.onda-dias.eu/cms/fr/data/catalogue/). Sometimes in some optimized format. You don't pay the data, only the infrastructure and services you build to make use of it. However, I'm not sure you can have object store S3 access to the data for free...

Currently none of the presented DIAS has a service such as Google Earth Engine or Digital globe GBDX, and I think Pangeo could provide this (Maybe Mundi DIAS is looking at this). I discussed briefly with some of them, and they are really interested in trying things out. I see this as an opportunity to test European cloud, with scientific data already there! I'm not sure how this will evolve, it's just the start. I just wanted to know if this sounds interesting to the Pangeo community, and if some people are interested in taking part of it, or if people have already done it?

**Comment by rabernat** [comment]
This sounds like a great opportunity @guillaumeeb! Thanks for taking the initiative on this!

Maybe this is something for the agenda at the upcoming Euro Pangeo meeting?

**Comment by guillaumeeb** [comment]
This has been added to the agenda. But if someone has somethign to say on this before the meeting, do not hesitate!

**Comment by guillaumeeb** [comment]
Just for information @fbriol and I have just started working with Wekeo DIAS. This probably won't be easy on this institutional DIAS because they aren't backed up by any real public cloud offering. I'll try to keep talking with other players to see if there are opportunities, and I'll keep pangean folks posted if we make any advance.
