### ISSUE TITLE
Move my Pangeo-Azure fork into pangeo-data

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#597]
Hi Folks. I am interested in moving [my Azure-focused fork](https://github.com/daxsoule/pangeo) of Pangeo deployment scripts into the pangeo-data organization, and perhaps rename it something like pangeo-azure. Does this seem like something that would be worth doing? Or would it be better for me to branch pangeo into an azure branch? Not sure what the best way of doing this would be, and I'm open to ideas. The reason I would like to do this is because I think it would make sense for all of my Azure-related work on Pangeo to be brought back into the fold. We can organize it in a way such that deployment scripts for the different clouds are organized the same way. Any thoughts, feelings, or ideas would be greatly appreciated. Thanks!

**Comment by rabernat** [comment]
Tim, the latest deployment repo is here:
https://github.com/pangeo-data/pangeo-cloud-federation/

This has evolved quite a bit from the early days. We are doing continuous deployment of multiple clusters to both AWS and Google Cloud via a single repo. It would be great to add Azure to the mix!

**Comment by jhamman** [comment]
@tjcrone - do you have a feeling for what is different from your Azure deployment and the current pangeo helm chart?

I'll second @rabernat's comment about moving to pangeo-cloud-federation. This will require a bit of work but it should be manageable.

**Comment by tjcrone** [comment]
@jhamman, finally getting around to making this happen. I am following the steps here: https://github.com/ooicloud/pangeo-cloud-federation#configure-this-repository, but I am unable to unlock the secrets files. I'm guessing I need the shared key? And would that be the key just for the dev deployment? Or is there a single key for the repo? Sortof expecting the latter, but maybe not. Any help would be greatly appreciated!

**Comment by tjcrone** [comment]
@rabernat, do you have any ideas here? Dax and I are looking to make a bunch of progress on this over the weekend, but the decryption issue is blocking. Without decrypted secrets files, is not possible to see the the structure of the encrypted files, and so we have no way of knowing how to modify them to work with Azure. Would be great to get an OOI Pangeo deployment up on Azure! Any help would be greatly appreciated!

cc: @scottyhq, @yuvipanda, @rsignell-usgs

**Comment by scottyhq** [comment]
Hi @tjcrone, I think it would be great to add Azure to the mix! The caveat is that yes, all deployments in pangeo cloud federation are sharing secrets with the repo admin. See https://github.com/pangeo-data/pangeo-cloud-federation/issues/285. That said, if you create an account on https://keybase.io I will send you the git crypt key so that you can get going.

**Comment by tjcrone** [comment]
Thanks Scott! I will create an account and contact you with my info. I have read https://github.com/pangeo-data/pangeo-cloud-federation/issues/285, and I think this should work fine at this stage, but I wonder if it might make sense to have different keys for different directories/deployments in the repo? Not sure if git-crypt allows this, but if it does, this might be a good way to move forward. Also, as you suggest we plan to fork and deploy separately during the debug phase on Azure, but as it stands, we have no idea what the three required secrets file look like without the key. Would it make sense to decrypt the secrets files in the dev deployment and push them in plain text (with actual secrets replaced with random garbage)? Or alternatively, we could make a "template" directory/deployment that serves this purpose, with garbage secrets decrypted, so that potential users can see what the files look like and how to deploy separately on a fork? Then PR when the time comes to merge with Pangeo proper? Just a few possible ideas for compartmentalizing to some extent.

**Comment by scottyhq** [comment]
Agreed it would be best to have per-deployment encryption. It would be really awesome though to show how this common repo and CI can deploy to all 3 clouds, so definitely put it in there as soon as you can!

Good idea to just have plain text mock-ups of the secrets files to guide other deployments! Not sure why we didn't do that from the beginning. Here they are on my branch for now: https://github.com/scottyhq/pangeo-cloud-federation/blob/secrets-examples/docs/readme-secrets.md

**Comment by tjcrone** [comment]
Thanks Scott! This should give me what I need to get this going in my fork. When I have it working, I will issue a pull request and we can have all three majors functioning!
