### ISSUE TITLE
NCAR NCL Team Looking to Hire!!!

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#598]
Dear Pangeons,

The NCAR NCL Team is looking to hire 2 Software Engineers at level II and/or III.  The position announcement can be found here:

https://ucar.silkroad.com/epostings/index.cfm?fuseaction=app.jobinfo&jobid=218645&company_id=15947&version=1&source=ONLINE&JobOwner=992772&startflag=1

As you may be aware, NCAR is looking to transition [NCL to Python](https://www.ncl.ucar.edu/Document/Pivot_to_Python/) (in what they are calling NCL's "Pivot to Python"), and as part of this transition, the NCL team is trying to determine how best to fit NCL into the Pangeo ecosystem (i.e., dask and xarray).  This means that development experience with xarray and/or dask is _greatly_ valued, in addition to required experience with C and Fortran (as the bulk of the existing NCL codebase is in C and Fortran).

Please spread the word about these job openings!  It would be great to see some experienced Pangeons apply!

**Comment by JiaweiZhuang** [comment]
> UCAR/NCAR will sponsor a work visa to fill this position.

👍👍👍
