### ISSUE TITLE
Network bandwidth

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#6]
I'm getting about 1GB of bandwidth (simultaneous read and write) on Cheyenne.

I'm using the following code:

```python
from dask.distributed import Client
client = Client(scheduler_file='scheduler.json')

import dask.array as da
x = da.random.random((100000, 100000), chunks=(5000, 5000)).persist()

y = (x + x.T).persist()   # either of these will stress bandwidth
z = y.rechunk((100000, 250)).persist()   # either of these will stress bandwidth
```

I then measure bandwidth by looking at the dashboard for a single worker.  We see peaks around 1GB/s and one full CPU being used (presumably the Tornado event loop thread).

![image](https://user-images.githubusercontent.com/306380/30123302-89915c6c-92ff-11e7-8b08-664ebfd650d9.png)

I suspect that this is below what we should expect on Cheyenne's network for TCP over IB (cc @davidedelvento for confirmation).

I suspect that this is due to Tornado's byte handling.

**Comment by davidedelvento** [comment]
How many nodes? I assume 2. 
How many processes per node talking concurrently? What is message size? 

The theoretical bw is 25 GB/s bidirectional per link (TCP can use only one link, IIRC, and depending on where you are in the topology of the fabric you may have more or fewer links connecting the nodes). Also, you can see something approaching this number only for large message size with low overhead protocols (certainly not with TCP on top of IP over IB). 

Yet, 1GB/s seems low, but too high to let me suspect you are using ethernet (Cheyenne batch nodes have 1Gbit Ethernet).

**Comment by mrocklin** [comment]
This is eight nodes, all transferring several 200MB chunks between each other several times concurrently.  The numbers above are looking at the bandwidth coming out of one machine.

We're not making any attempt to be nearby in the network topology.

Do you happen to have a reference on why TCP is high overhead?  Have you seen other distributed applications using TCP go faster than this?

**Comment by davidedelvento** [comment]
TCP is really not used for HPC, so no, I have not examples that I can point you to.

TCP is high overhead for just the way it is designed, mostly because of two reasons:
* the additional ACK packages (which need to take bw+latency and need to be processed by either the CPU or the network card, taking time to do so) and 
* because of all the congestion control logic which is great when you have an unknown link between two random points (i.e. on the internet). But when you have a known link certainly (or most likely) not oversubscribed, as you do in HPC, all of that it's just overhead. 

My favorite reference for everything networking (besides IB), it's Tanenbaum's book.

**Comment by sjperkins** [comment]
I followed this issue with interest from http://matthewrocklin.com/blog/work/2017/09/18/pangeo-1

My domain is radio astronomy (https://github.com/ska-sa/) and to sustain high data rates we've developed UDP transfer protocols (See https://github.com/ska-sa/spead2) for instance. spead2 is lossy since losing some portion of the signal is accepatble.

Do either of you have any thoughts on the use of reliable UDP protocols in HPC environments? Off the top of my head I'm aware of the following:

- https://en.wikipedia.org/wiki/UDP-based_Data_Transfer_Protocol
- https://github.com/real-logic/aeron
- https://www.chromium.org/quic

I suspect use of any of the above protocols within tornado might be non-trivial, but I'd appreciate your thoughts on the matter.

/cc @bmerry

**Comment by davidedelvento** [comment]
In HPC environments as I see them, they network is InfiniBand (IB) not Ethernet. I'm not familiar with UDT (or any of the other UDP-based protocols you mentioned) but it is certainly possible. For non-network-sensitive applications, it's common to use an IP-over-IB protocol, and then on top of IP you can stack whatever else you'd like. Most commonly TCP, but I'm pretty sure you can use UDP and therefore anything else such as the ones you mentioned. It should not be a huge amount of work.

However, if one **really** cares about network performance, I think they should use IB. Using IB directly is a huge pain, hence my suggestions (elsewhere, not in this issue discussion) to use MPI. Any HPC environment will have at least a decent (probably a good, often more than one) MPI implementation, with transfer performance pretty close to the hw limits. Building mpi4py against that implementation is often trivial, and I expect will provide the best performance you can hope to get without spending a **huge** amount of time into nitty-gritty details of the particular interconnect you are running on.

**Comment by bmerry** [comment]
A colleague of Simon's here. For radio astronomy there are two main reasons for using UDP:
1. You're streaming observations of a physical system. If you drop a packet, you can't pause the universe while you wait for retransmission.
2. The stuff with really high bandwidth:compute rations is done on FPGAs, and it's not practical to give them a high-performance TCP stack (or often even enough memory for a TCP window).

Neither applies to a "standard" HPC batch-processing environment. The third reason I'm aware of for using UDP is that TCP wasn't designed for such high bandwidths (UDT is an example) - but nor has the UDP stack in the Linux kernel. Even with jumbo frames, we've found UDP with the kernel stack tops out around 25Gb/s = 3GB/s in spead2's synthetic benchmarks.

We use 40Gb Ethernet, which we can saturate on a single thread using IB libraries to send/receive UDP packets. While I gather IB hardware is good for reducing latency, a big part of the value in IB is in the software stack which allows direct transmission from user-space to user-space without involving the kernel, and sometimes without even involving the other side's CPU. It is also (as @davidedelvento points out) a massive pain to code, and I agree with him that MPI is likely to be easier to use and better supported in HPC environments.

**Comment by mrocklin** [comment]
cc @pitrou here is a screenshot of a single worker machine's bandwidth (as measured by `psutil.net_io_counters()` when using your `large_buffers_2` branch.

![image](https://user-images.githubusercontent.com/306380/32457846-7158eb46-c2f8-11e7-8fcc-56f3b4cec326.png)

**Comment by mrocklin** [comment]
The computation is as above

```python
x = da.random.random((100000, 100000), chunks=(5000, 5000)).persist()

y = (x + x.T).persist()   # either of these will stress bandwidth
z = y.rechunk((100000, 250)).persist()   # either of these will stress bandwidth
```

**Comment by mrocklin** [comment]
I also moved an 8GB array between two machines in around 20s.  This is 400MB/s for a single connection.

**Comment by pitrou** [comment]
@mrocklin that sounds concerning. Can you try with the original Tornado to check if there's no external cause for the slowdown?

**Comment by pitrou** [comment]
@mrocklin, also, are you using Python 3?

**Comment by mrocklin** [comment]
Yes in both cases.  Sorry I haven't yet tried latest release to see if something else has happened.  It is unlikely that I will get to this today.

**Comment by pitrou** [comment]
Is there any workload that I may try on a single 4-8GB 4-core machine to reproduce what you are seeing?

**Comment by davidedelvento** [comment]
Folks,
We're seeing some failures on Cheyenne which might be related to the IB fabric not being in perfect shape, so I suggest you hold off making conclusions about performance settings at this time. Try again in a day or two when we will have the issue sorted out.

**Comment by mrocklin** [comment]
> Is there any workload that I may try on a single 4-8GB 4-core machine to reproduce what you are seeing?

You could always try the communication-heavy dask.array workloads above (with reduced array sizes).

**Comment by pitrou** [comment]
@mrocklin, ok, I've made the following benchmark script, which consumes ~4GB RAM:
https://gist.github.com/pitrou/9b4f470b78360eca4478b067639be681

I get the following results on my machine (Ubuntu 16.04, 4 CPU cores, 8 GB RAM):
* with TCP comms and Tornado git `master`: 4.5 s.
* with TCP comms and my `zerocopywrite` branch (*): 4.0 s.
* with inproc comms: 2.5 s.

YMMV, so I would be glad to have your results. You can also vary the parameters at the start of the script.

(*) This is https://github.com/tornadoweb/tornado/pull/2169; the `large_buffers_2` branch you used is obsolete, sorry

**Comment by mrocklin** [comment]
On a similar machine (Ubuntu 16.04, 4 CPU cors, 16GB RAM)

- master: 5.4s +- 0.1
- zerocopywrite: 4.5s +- 0.2
- inproc: 2.9s

**Comment by mrocklin** [comment]
@davidedelvento thank you for the warning.  I'll try again in a day or two.

**Comment by pitrou** [comment]
Update with an additional result:
* with TCP comms and `IOStream.read_into()` (see https://github.com/tornadoweb/tornado/pull/2193) in addition to `zerocopywrite`: 3.5 s.

**Comment by mrocklin** [comment]
Under Tornado master (5fcfb4277514ff82e2d3b17a24a26ed505b8d453) and latest dask release (dask/dask: 0.16.0 and dask/distributed 1.20.0) we get the following results when doing a rechunking operation

![image](https://user-images.githubusercontent.com/306380/33023956-b7416446-cdd7-11e7-8541-4d5988505058.png)

**Comment by pitrou** [comment]
Hmm... It seems a bit difficult to take away something from this.
* Total runtime is about 10-15 seconds in both cases? is that right?
* CPU usage is very spiky in the latest measurement, with two different patterns. Occasional 2000% CPU spikes (might this be an unrelated system task kicking in?), and period 100% CPU spikes every 500 ms. or so (is this due to some periodic task we introduced recently?)
* Network bandwidth seems to oscillate a lot as well
* In the former measurement, memory growth seems about 3 GB, while only 1.5 GB in the case the latter
* Not sure if the number of open file descriptors really has anything to do with this

**Comment by mrocklin** [comment]
The spiky behavior is, I think, an artifact.  Resolving it in https://github.com/dask/distributed/pull/1573

Will post again when I have cleaner plots

**Comment by mrocklin** [comment]
Here, this is much cleaner:

![image](https://user-images.githubusercontent.com/306380/33026263-09fda7b6-cdde-11e7-93ec-4be552aa04d8.png)

**Comment by pitrou** [comment]
Based on the bandwidth graph, it seems we're transmitting more data than we used to? (1.5-2 GB/s. during 15 s., as opposed to 1-1.5 GB/s. during 8 s.)

**Comment by mrocklin** [comment]
Yes, I would agree with that assessment.

**Comment by mrocklin** [comment]
Hrm, here is the same computation run under tornado 4.5.2

![image](https://user-images.githubusercontent.com/306380/33026809-4837b34a-cddf-11e7-8711-579584a1da57.png)

**Comment by pitrou** [comment]
So it seems like something else had changed since the first measurement on Sep 6th? Either in our rechunking algorithm, the cluster itself, its configuration, or...?

**Comment by pitrou** [comment]
That said, it's reassuring for the communications side: it means we're saving some runtime and CPU with the new buffering algorithm inside Tornado, though it seems memory consumption has increased a bit?

**Comment by mrocklin** [comment]
I suspect that I just had another dataset in memory when I ran the experiment.  I wouldn't read too much into the increased baseline.

From my perspective these plots show surprisingly little change in bandwidth between 4.5.2 and master.

**Comment by pitrou** [comment]
Well, bandwidth is around 1.4 GB/s. on v4.5.2 vs. 1.8 GB/s. on master. That's not bad considering we have other bottlenecks in such a functional benchmark. Another way to express it: to ship around a given number of bytes, we needed 22 s. but now we only need 16 s.

As for aggregate CPU consumption, it's a bit harder to tell, but average CPU usage seems around 120% in both cases, again despite the 25% reduction in runtime with git master.

**Comment by mrocklin** [comment]
Ah you're right, the total runtime is more precise way of looking at these plots :)

**Comment by pitrou** [comment]
For the sake of clarity, "before" is with Tornado git master?

**Comment by mrocklin** [comment]
Correct

**Comment by pitrou** [comment]
So, the runtime seems to have shrunk from ~16 s. to ~12 s., and there seems to be a slight decrease in memory consumption (though there might be external factors impacting the latter).

**Comment by rabernat** [comment]
Can this be closed?
