### ISSUE TITLE
Persistent web server

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#618]
Many people have asked questions about supporting services alongside our currenty notebook workflow.  This might be the desire to have an OpenDAP server, host dashboards, plots, and so on.

I suspect that if we put up a single web server that people would find a variety of uses for it.  My guess is that this could be organized as follows:

-  A git repository that followed the repo2binder specification, and contained a Python application that ran a Tornado web server (tornado seems to be common among our technology stack of Jupyter/Dask/Bokeh).
-  Hooks into hubploy or some other CI service that would build and deploy this repository into Kubernetes, which would then serve it at `server.pangeo.io` or something similar.  Presumably we would avoid state in the server so that Kubernetes could restart it as necessary.

People would then add routes to the web server as they wanted to try out their favorite service.  For example someone might add an `/intake` route that people could navigate to to play with Intake's UI.  

(also, sorry to propose work without having the intention to follow through.  This came up in today's meeting)

@jacobtomlinson you might have thoughts on this?  I suspect that you all have done similar things.

**Comment by rsignell-usgs** [comment]
I'm definitely interested in this.    We would like to try using pangeo to improve backend processing for an existing web service (the [GDP](https://cida.usgs.gov/gdp/)) that crunches large amounts of geospatial ndarray data.

**Comment by jacobtomlinson** [comment]
Yes this is interesting. I think Jupyter Hub already has a facility for this kind of thing. We could build on that.

https://jupyterhub.readthedocs.io/en/stable/reference/services.html#services
