### ISSUE TITLE
Near term pangeo.pydata.org goals

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#62]
Thank you all for your work and involvement over the last couple weeks.  http://pangeo.pydata.org is up and running, I encourage you to try it out.

There is still plenty of work to do.  However now is probably a good time to take a step back and figure out where we want to take this near and mid term so that we can prioritize effort appropriately.

What do we want to do with this?  Are people around for a video conversation about this?  I'm particularly free Tuesday afternoon and all day Friday.

cc @yuvipanda @rabernat @jhamman @jacobtomlinson (feel free to ping others, I've tried to ping a small number of people who will know others that may or may not want to be involved with work short term on this)

**Comment by yuvipanda** [comment]
am happy to do either!

**Comment by jhamman** [comment]
@mrocklin - thanks for all the hard work getting things to this stage. I'm free Tuesday except between  1:30-2:30 PST.

A few things to put out there in the near term:
  - Finish develop branches in gcsfs, distributed, zarr, and xarray
  - move more data to GCS
  - develop a community effort to evaluate FUSE, Zarr, and HSDS
  - Science use cases
  - Write some blogs highlighting where we're at with the HPC and Cloud systems

**Comment by rabernat** [comment]
Matt, thanks for leading the charge on this. I can't do Tuesday as I'm still at this NSF workshop. Friday is maybe possible.

Your suggestion of a meeting has somewhat preempted my forthcoming proposal of a pangeo-wide telecon. We are approaching the six-month milestone for the NSF award, and I think an all-hands-meeting is in order. I would prefer to do that next week, as this one is consumed with conferences.

**Comment by rabernat** [comment]
To clarify my comment above...

Matt, did you have in mind a video call just related to pangeo.pydata.org (and related cloud deployment issues)? Or were you thinking of a broader scope, related to the entire project (as Joe's list suggests).

If it's the former, then please proceed with Friday (or Tuesday without me).

If it's the later, then I'm happy to take the reins for scheduling and agenda-setting. I was planning to organize such a meeting anyway already.

**Comment by mrocklin** [comment]
I was proposing the former, a meeting just about pangeo.pydata.org.  I think that this is something on which a number of groups outside of the original collaboration are interested in pushing forward. 
 I'd like to provide some ideas on how they can achieve that.  

@rabernat I suspect that your group will be one of the first user groups for the cloud system.  I'm inclined to wait until Friday so that you can participate.  There is plenty of cleanup to do before then.  People might also take this pause as an opportunity to raise issues that we can maybe prioritize during such a meeting.  I have a few things in my head that I'll endeavor to write down.

**Comment by rabernat** [comment]
Ok: in that case, any time after 10am EST works for me.

**Comment by mrocklin** [comment]
@jacobtomlinson @mkjpryor-stfc do either of you have any interest in participating in this?  I'm not sure what your desire to work on this stuff near-term is.

**Comment by jhamman** [comment]
@mrocklin - did we settle on a time for this conversation? (My apologies for misreading the initial request)

**Comment by mrocklin** [comment]
Ah!  I had forgotten.  Doodle poll here: https://doodle.com/poll/xvkti9m2t3u4c5bz

**Comment by mrocklin** [comment]
I suggest that we meet at 3pm Eastern time 12pm Pacific time. 

UK Met folks if you all are around and interested let us know and we can try to adjust.  It would be great to have you.

**Comment by jacobtomlinson** [comment]
@mrocklin sorry for the delay in responding, been off sick!

My interest would be to get our own version set up and hosted ourselves, and contribute any things we feel would be good for our use case and bring it in line with functionality we have in our Jade platform. 

I can't make 3pm EST. Perhaps we should have a separate catch up next week.

**Comment by jmunroe** [comment]
Hi @mrocklin. If you're meeting at 3pm EST today, I'd like to join in the video conference if that is possible.

**Comment by yuvipanda** [comment]
Am happy to make it today too

**Comment by jhamman** [comment]
Do we have a location for this call? Zoom / Google, etc?

**Comment by rabernat** [comment]
What do people prefer? Zoom requires people to install stuff.

**Comment by rabernat** [comment]
We can meet here:
https://columbiauniversity.zoom.us/j/651740543

**Comment by mrocklin** [comment]
https://appear.in/pangeo

**Comment by rabernat** [comment]
@jmunroe: please join us!

**Comment by jmunroe** [comment]
Unfortunately, appear.in has a 4 person max without the Pro version.

**Comment by mrocklin** [comment]
Try again
