### ISSUE TITLE
Using a custom docker image

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#626]
I would like to construct my own docker image for my pangeo deployment. How do I go about doing that? Part of my problem is that I don't really understand the relationship between the helm chart and the docker image that is used on the pods. Are there any resources I should read to understand how these pieces fit together?

**Comment by jhamman** [comment]
@arokem: You'll need to override `jupyterhub.singleuser.image.{name,tag}`: https://github.com/pangeo-data/helm-chart/blob/dd3ec92a0e2db2ad45310b76e0963772e0e95a57/pangeo/values.yaml#L22-L23

This can be done in your `config.yaml`. More in the z2jh docs here: https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#choose-and-use-an-existing-docker-image

**Comment by arokem** [comment]
I see - I didn't understand that I could over-ride it! 

Just to be explicit, to see that I understand. If I add a section:

```
image:
    name: arokem/fancy_pants
    tag: fancy_tag
```

In the `jupyter_config.yaml` file (nested under `jupyterhub: singleuser:`), that would then over-ride the image that is used? 

Presumably it would be best to use `pangeo/base-notebook` as the image to inherit my image from, so that it has all the necessary components, on top of which I add my own stuff?

**Comment by jhamman** [comment]
You've got it. If you aren't going to use dask[-kubernetes], you can choose a different base image.

**Comment by arokem** [comment]
Great. Thanks!

**Comment by arokem** [comment]
For future reference. The following works to add (in this case) octave to the base image: 

```
from pangeo/base-notebook

USER root
RUN apt-get update && apt-get install -yq less sudo octave && apt-get clean
USER jovyan
```
