### ISSUE TITLE
Error in xarray-data.ipynb example

### ISSUE THREAD

**Issue by Boes-man** [pangeo-data/pangeo#631]
Hello, tried to run the example but it errored as per the attached. Thanks

![Screen Shot 2019-05-15 at 2 30 53 pm](https://user-images.githubusercontent.com/26314583/57748700-65abe880-771e-11e9-90db-2f2d9bb011df.png)

**Comment by jhamman** [comment]
@Boes-man - can you report which versions of xarray and zarr you are using?

You may just paste the output of `xarray.show_versions()`.

**Comment by Boes-man** [comment]
thanks @jhamman 

`INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-957.12.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.8
pandas: 0.23.2
numpy: 1.15.1
scipy: 1.1.0
netCDF4: 1.4.2
h5netcdf: 0.6.2
h5py: 2.8.0
Nio: None
zarr: 2.2.0
bottleneck: 1.2.1
cyordereddict: None
dask: 0.18.2
distributed: 1.22.1
matplotlib: 2.2.3
cartopy: 0.17.0
seaborn: None
setuptools: 39.2.0
pip: 18.1
conda: 4.5.4
pytest: 3.9.1
IPython: 6.4.0
sphinx: None`

**Comment by jhamman** [comment]
I think you just need to upgrade to the most recent versions of zarr and xarray.

**Comment by Boes-man** [comment]
I have not been able to fix. Thanks
