### ISSUE TITLE
Promoting the use of KubeCluster.adapt()

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#632]
I've noticed a pattern in dask cluster usage. 

- log into a pangeo jupyterhub/binder instance
- immediately run `KubeCluster.scale(40)`
- do some work
- go to lunch

What ends up happening is that the 40 worker dask cluster can stay alive for hours (or until the user is logged out of the Jupyter session due to inactivity) despite being done processing. Here's an example of one such dask nodes where a node has been idle for more than 30 minutes but isn't scaling down:

![image](https://user-images.githubusercontent.com/2443309/57813412-e1a92f00-7724-11e9-8465-e147c4a8bb70.png)

So I have a request. Can we start promoting the use of `KubeCluster.adapt()`? This will really help avoid these super long running dask worker jobs that are just waisting resources. 

cc @rabernat

**Comment by mrocklin** [comment]
cc @jcrist if you ever wanted a proto-user for dask-gateway, I think that Pangeo would be a good one.  

Pangeans, this is the sort of thing that would probably benefit from having central control.  Ideally we could make policies that said things like "switch any cluster that hasn't been active in the last 20 minutes to adaptive mode".

**Comment by mrocklin** [comment]
(not to distract from the main point, which is that yes, we should certainly use adapt)

**Comment by rabernat** [comment]
I agree with you Joe.

Here we are dealing with a non-expert (i.e. real!) user who logs into the cluster at 9am, starts a 40-worker cluster, and turns it off when they go home at the end of the day.

More generally, we have no systematic way of communicating with the cluster users. We need a mailing list, forum, etc. something that allows us to make these kind of suggestions.

**Comment by mrocklin** [comment]
Or default config settings?  We could probably put a very inactive adaptive
policy in place in config without most users realizing it ?

**Comment by arokem** [comment]
Is there an example notebook where `KubeCluster.adapt()` is used? Is it
simply a matter of adding a cell with a call (no inputs?) to that function
after the following?

```

from dask_kubernetes import KubeClustercluster =
KubeCluster(n_workers=10)cluster

```

**Comment by jhamman** [comment]
>cc @jcrist if you ever wanted a proto-user for dask-gateway, I think that Pangeo would be a good one.

I'm increasingly starting to believe this is going to be desired for centrally managed Pangeo deployments. @jcrist - I'd love to hear more about your plans with dask-gateway.

> Here we are dealing with a non-expert (i.e. real!) user who logs into the cluster at 9am, starts a 40-worker cluster, and turns it off when they go home at the end of the day.

Can we contact this person directly?

> More generally, we have no systematic way of communicating with the cluster users. We need a mailing list, forum, etc. something that allows us to make these kind of suggestions.

We should revisit the authentication conversation then. Is ORCID giving us sufficient information to contact individuals? I, for one, don't love having to look up users using ORCID but that is a separate conversation.

> Is there an example notebook where `KubeCluster.adapt()` is used?

@arokem - this will work:

```python
cluster = KubeCluster()
cluster.adapt(maximum=10)
```

**Comment by arokem** [comment]
Just to follow up on this: I think that a software library of tools that implements what is currently repeated in many of the example notebooks may be useful. This would also help nudge people towards certain best practices. For example, I wrote a small module: 

```
from dask.distributed import Client
from dask_kubernetes import KubeCluster

def init_cluster(n_workers=10):
    cluster = KubeCluster(n_workers=n_workers)
    cluster.adapt(maximum=n_workers)
    client = Client(cluster)
    return cluster, client
```

that users can import and call whenever they start working. 

Should we develop these things jointly? Does this kind of thing belong somewhere in existing libraries?
