### ISSUE TITLE
Pleiades deployment information

### ISSUE THREAD

**Issue by wtbarnes** [pangeo-data/pangeo#639]
I'm not sure if this is the right place to ask this so please let me know if I should be posting elsewhere.

On [pangeo.io](http://pangeo.io) under "Deployments," there is a listing for a deployment on the NASA Pleiades cluster. However, there's not much more information about how it is setup or who is/was responsible for maintaining it. I'd be very interested to talk to anyone affiliated with this deployment and to know whether it is still up and running.

I'm currently looking to get Dask up and running on Pleiades and would like to avoid reinventing the wheel wherever possible. Thanks!

**Comment by jhamman** [comment]
I think @rabernat was the one who has worked on Pleiades most. Ping!

**Comment by dshean** [comment]
I did some quick tests with Dask on Pleiades devel queue following Dask-jobqueue PBS examples (https://jobqueue.dask.org/en/latest/), but hit some errors (likely due PBS option syntax), and didn't have time to investigate further.  

In recent user feedback survey, I suggested to NAS support that it would be good to support this use case in the future, maybe with a small cluster of nodes dedicated for experimentation with efficient scaling, without long PBS job scheduler wait times.

Our group does a lot of work on Pleiades, and we need to migrate a subset of workflows to Dask.  It would be great to hear about other user experiences and discuss strategies.  Looping in @scottyhq, @ShashankBice, @friedrichknuth, @jmichellehu.

**Comment by scottyhq** [comment]
I’m also very interested in having this functionality on Pleiades! But unfortunately haven’t done any work to try it out. Looping in @kmpaul who could share some insights on setting things up on NCARs Cheyenne HPC.

**Comment by mrocklin** [comment]
Ideally @rabernat can share his configuration.  If not I'd be happy to sit down for 30 minutes with someone who has access and I suspect that we could get things running smoothly.  Ideally that person would then upload their configuration to https://jobqueue.dask.org/en/latest/configurations.html

**Comment by rabernat** [comment]
Yes I have a bunch of stuff I can share about Pleiades. 

Going forward I would like to think about how we can improve the way we document these things

**Comment by wtbarnes** [comment]
Wow thank you all for the great feedback! This is a significant component of my current project so I'm happy to sink a bit of time into documenting any configuration I come up with. I assumed that Dask jobqueue would do the job. 

@dshean I wondered if this would be a problem. Did you get a response from anyone at Ames RE: this kind of allocation? Presumably this is just a matter of creating a high-availability queue with a relatively short wall time.

@rabernat What is the best medium for sharing this? If you just have a collection of scripts, I'm happy to sort through them and turn them into more proper documentation on [https://jobqueue.dask.org/en/latest/configurations.html](https://jobqueue.dask.org/en/latest/configurations.html).

**Comment by rabernat** [comment]
> If you just have a collection of scripts, I'm happy to sort through them and turn them into more proper documentation on

It seems like there are two pieces to a Pangeo HPC setup:

1. The dask-jobqueue config, which should rightly live in the dask-jobqueue docs
1. How to launch a Jupyter notebook. **where should this live?**

Here is a script I use to launch a notebook on pleaides
```bash
#!/bin/bash
#PBS -N jupyter
#PBS -W group_list=g26209
#PBS -l select=1:ncpus=20:model=ivy
#PBS -l walltime=7:59:00
#PBS -j oe
#PBS -m abe

export LANG="en_US.utf8"
export LANGUAGE="en_US.utf8"
export LC_ALL="en_US.utf8"

# Setup Environment
module purge
source activate pangeo

jupyter lab --no-browser --ip=`hostname` --port=8877
```

Here is how I start a dask cluster
```python
from dask_jobqueue import PBSCluster

cluster = PBSCluster(processes=1, threads=10, memory="54GB",
                     interface="ib0",
                     group_list='g26209',
                     resource_spec='select=1:ncpus=20:mpiprocs=5:model=ivy',
                     walltime='06:00:00')
cluster.start_workers(8)
```

**Comment by mrocklin** [comment]
I think it's ok to include additional context information in the dask-jobqueue site description.

**Comment by kmpaul** [comment]
I'm coming to the party late, but thanks for the ping, @scottyhq!

@rabernat has the minimal Pangeo HPC description correct.  Unfortunately, on most HPC systems, this is the only way to go.  (I would say the only missing steps might be the SSH tunnelling, and possibly some initial setup if the compute nodes on the HPC machine are air-gapped.)  However, NERSC and NCAR both (now) have JupyterHub's running.  If enough people push this kind of job on Pleiades, I'm sure the admins can set up a JupyterHub.  @dshean, based on your own experiences, do you think this is a possibility?

**Comment by guillaumeeb** [comment]
For 
> How to launch a Jupyter notebook. where should this live?

This is currently in http://pangeo.io/setup_guides/hpc.html, I think it's a good place, isn't it?

An some comments on @rabernat's dask-jobqueue code:
* `resource_spec='select=1:ncpus=20:mpiprocs=5:model=ivy'` : this is probably not needed (should be generated automatically), else according to the conf it should be 10 ncpus, mpiprocs probably don't needed, and a memory request is missing.
* `cluster.start_workers(5)` : shouldb be `cluster.scale(5)`

**Comment by wtbarnes** [comment]
@rabernat Thanks for sharing this. Is there a reason you submit a job to start the notebook as opposed to just running it on a login node? Presumably all of the compute is offloaded to the workers by Dask anyway so it wouldn't be clogging up the login.

@kmpaul There is an ongoing effort to setup some sort of notebook interface on Pleiades, but I think it is complicated by all of the security that surrounds login credentials on NASA computing resources.

**Comment by rabernat** [comment]
Not all the compute is offloaded to dask. In my workflows, the notebook node has the highest memory requirements. That’s where all the data eventually land and where I do the “last mile” of my analysis. Running compute jobs on head nodes is not a good practice.

**Comment by dshean** [comment]
Hi all.  Great discussion and thanks for the template @rabernat.

To follow up on whether NAS would set up a customized solution for this application - I think the answer is yes, but we should coordinate on specifics.  Their support group is excellent, and they'll definitely need higher-level approval for something like this.  I'm guessing we could connect with managers, convince them this is worth exploring, and they could find a good solution given existing resources and constraints, especially if there were multiple users/groups on the request.  I don't have time to lead this right now, but can potentially follow up in June/July.

With that being said, I recommend people try @rabernat's approach with the devel queue for testing (https://www.nas.nasa.gov/hecc/support/kb/pleiades-devel-queue_290.html).  Jobs should start immediately, and you can request a relatively large block of nodes.  Just keep time limit under 2 hours.

**Comment by dshean** [comment]
For reference, I will often check out a single bro node for post-processing and interactive analysis.  The new `pbs_rfe` command is convenient for this: https://www.nas.nasa.gov/hecc/support/kb/reserving-a-dedicated-compute-node_556.html
```
#Notes for starting Jupyter Notebook server on Pleiades

#Remote
##Request a dedicated node for interactive use
pbs_rfe

##ssh to this node or use one of the pfe nodes (avoid heavy compute on shared pfe)
ssh pfe27
cd ~/src

##Initial setup: set a password
jupyter-notebook password

##Start the Jupyter notebook server
jupyter-notebook --no-browser --ip=$(hostname -i) --port=9999

#Local
#Copy and paste server IP
ip=''

##The -N here does not execute remote commands, just sets up forwarding
ssh -N -L 9999:${ip}:9999 pfe27

##Enter appropriate login credentials

##Open browser
open http://localhost:9999
```

**Comment by scottyhq** [comment]
Hi all, thanks for the great tips and examples! I'm going to ping @yuvipanda on this issue since he has recently put together some utilities that could be of use for running JupyterHub via Charliecloud -  [which is an option on Pleiades](https://www.nas.nasa.gov/hecc/support/kb/enabling-user-defined-software-stacks-with-charliecloud_558.html):

personally, i haven't used Charliecloud, but if someone wants to try this out on Pleiades, could be a great experiment!

here is a [description](https://groups.io/g/charliecloud/topic/jupyterhub_charliecloud/31832426?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,31832426) of the code and the corresponding repo: https://github.com/yuvipanda/jupyterhub-charliecloudspawner

**Comment by yuvipanda** [comment]
I would love for someone to test out charliecloud! It has great potential...

**Comment by rabernat** [comment]
> I recommend people try @rabernat's approach with the devel queue for testing

@dshean - I just tried this and realized you're limited to one job at a time. The way dask jobqueue works it to launch many simultaneous jobs. So it seems like dask jobqueue can't be used at scale with the devel queue.

Someone please correct me if I am wrong.

**Comment by dshean** [comment]
Ah.  Yes, one job per user on devel, but that one job can check out a block of nodes.

**Comment by wtbarnes** [comment]
For anyone interested in this, @dshean and I have created [pangeo-data/pangeo-for-hpc](https://github.com/pangeo-data/pangeo-for-hpc) for collecting various setup scripts, requirements files, etc. for getting setup on HPC systems. Our interest is Pleiades, but this could be a home for other setups as well (e.g. NCAR, NERSC)
