### ISSUE TITLE
update pangeo communication channels

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#64]
We currently have many inconsistent "membership" lists / communication channels

1. Issue discussions in this repo
1. The [pangeo google group](https://groups.google.com/forum/#!forum/pangeo)
1. The [people list](https://pangeo-data.github.io/people/) from pangeo-data.github.io
1. The pangeo-data [github organization members](https://github.com/orgs/pangeo-data/people)
1. Email threads involving the NSF-funded project participants

Let's simplify this so that we can communicate more effectively and eliminate stale channels.

**Comment by mrocklin** [comment]
I'm probably responsible for several e-mail chains to particular individuals (typically @rabernat and @jhamman).  I'm happy to move these to a public channel.  Should it be the mailing list or github issues?  Usually my motivation here is to avoid spamming people that I anticipate will not be interested in a topic.  Balancing between large-scale and operational communication can be a challenge.

**Comment by rabernat** [comment]
I don't propose eliminating emails. It's mainly 2-4 that need to be consolidated somehow.

**Comment by jhamman** [comment]
There is also our [gitter channel](https://gitter.im/pangeo-data/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) now.
