### ISSUE TITLE
Setup guide: `set -e`?

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#641]
Is there any particular reason to `set -e` here: https://github.com/pangeo-data/pangeo/blob/07b4b7508c69090bc0285f945d64ef3971b56db9/gce/setup-guide/1_create_cluster.sh#L3? 

On my end it results in annoying situations where every typo quits my session. I was wondering whether there is any particularly compelling reason to use this.

**Comment by DPeterK** [comment]
The purpose of `set -e` is that it tells the shell script to quit immediately on any error – typos included.  It's possible in a setup script like this that one of the cloud setup commands will error but not exit cleanly, or there will be a concurrent process running. If we don't exit the script immediately on an error then we might end up creating a badly-formed cluster that's unusable, and, possibly, hard to delete. The value of using `set -e` here then is that we avoid such badly-formed clusters.

If it's causing a problem you could always comment it out while you're developing changes to the script and just replace it when you commit..?
