### ISSUE TITLE
Interest in a Climate & Weather BOF at SuperComputing 2019?

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo#644]
Is there anyone in the community planning on going to [SuperComputing 2019](https://sc19.supercomputing.org/) in Denver this year?  Some of us here at NCAR are thinking about organizing a Climate & Weather Birds-of-a-Feather session.  Pangeo would be a good thing to include in the session, I think.

Deadlines for "Birds of a Feather" submissions are July 31.

**Comment by JiaweiZhuang** [comment]
There is a [SC19 SuperCompCloud: Workshop on Interoperability of Supercomputing and Cloud Technologies](https://sites.google.com/view/supercompcloud). Seems that Pangeo is a perfect fit.

**Comment by rabernat** [comment]
This issue was moved to https://discourse.pangeo.io/t/interest-in-a-climate-weather-bof-at-supercomputing-2019/41
