### ISSUE TITLE
[Education]: tutorials on bivariate time-series analysis in dask?

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#645]
For a workshop that I am doing next week, I would like to teach a tutorial demonstrating the use of dask for bivariate timeseries analysis. Think correlation/coherence between every pair of time-series in a large multi-channel recording. 

Does anyone have good examples of doing/teaching this? My current plan is to use the first few notebooks from the [dask tutorial repo](https://github.com/dask/dask-tutorial) and then extend that with a notebook that applies dask array to this kind of thing. It's growing over [here](https://github.com/learning-2-learn/dask-timeseries-tutorial). If someone has pointers to materials on this topic, that would be helpful! Thanks!

**Comment by arokem** [comment]
Materials from the tutorial I ran yesterday are [here](https://github.com/learning-2-learn/dask-timeseries-tutorial). The last notebook has some time-series analysis of neuroscience data with xarray and zarr, which we will follow up on in our research code. I'll close this issue for now.

**Comment by rabernat** [comment]
Thanks for sharing! Sorry no one replied to your query.
