### ISSUE TITLE
Batch processing mode

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#649]
I have a use-case where users are going to want to do the following: 

```
def func(params):
    # Read input data from GCS
    ...
    # Do some computations
    ...
    # Write output data to GCS
    return something


cluster.map(func, list_of_param_settings)
```

I would like the cluster to provide as many workers as len(list_of_param_settings) as fast as possible, do the work and then for each worker to immediately cease to exist as soon as it's done with its piece of the work. Basically, I would like to have something like AWS Batch with submission through my Pangeo.

Is that currently possible? How would I go about implementing this?

**Comment by willirath** [comment]
You probably can get close with the existing behaviour of `cluster.adapt` and `dask.bag`.  See this gist <https://gist.github.com/willirath/b5bb9be7941ecc06a6bb0d8dcd62998e> for a relatively dirty version of this.

**Comment by arokem** [comment]
Thanks! Here is what I have for now:

```
from dask.distributed import Client
from dask_kubernetes import KubeCluster
from tqdm import tqdm_notebook as tqdm

def batch_process(func, params, client=None, cluster=None, 
                  scale_factor=1000, startup_cost="0.01s", 
                  target_duration="0.01s", interval="200ms", 
                  return_futures=False, scale_down=True):
    """ 
    Map `params` onto `func` and submit to a dask kube cluster.
    
    Parameters
    ----------
    func : callable
        For now, accepts a single tuple as input and unpacks that tuple internally. 
        See below in `params`.
    
    params : sequence 
        Has the form [(a1, b1, c1, ...), (a2, b2, c2, ...), ...., (an, bn, cn, ...)], 
        where each tuple is the inputs to one process.
        
    client : a dask Client, optional. 
        Defaults to start a new client.
    
    cluster : a dask Cluster, optional.
        Defaults to start a new cluster.
        
    scale_factor : integer, optional.
        `cluster.adapt` argument. Scale up to max immediately by picking a large number.
         Default: 1000.

    startup_cost : string, optional.
        `cluster.adapt` argument. Default: "0.01s" (target very fast completion; unsure if necessary).
    
    target_duration : string, optional.
        `cluster.adapt` argument. Default: "0.01s"
    
    interval : string, optional.
        `cluster.adapt` argument. Default: "200ms" (to adapt every 0.5 seconds).
    """
    if cluster is None:
        cluster = KubeCluster(n_workers=0, threads_per_worker=1)
    ca = cluster.adapt(minimum=0, 
                       maximum=len(params),  # set max number of workers
                       scale_factor=1000,  
                       startup_cost=startup_cost, 
                       target_duration=target_duration, 
                       wait_count=1,
                       interval=interval) 
    client = Client(cluster)
    results = client.map(func, params)
    
    # Otherwise, we're blocking and showing progress:
    all_done = False 
    pbar = tqdm(total=len(params))
    n_done = 0
    while not all_done:
        n_done_now = sum([r.done() for r in results])
        if n_done_now > n_done:
            pbar.update(n_done_now - n_done)
            n_done = n_done_now
        all_done = n_done == len(params)

    cluster.scale(0)
    
    return client, cluster
```

This is really only useful for cases (such as my use-case) where the `func` reads data from storage and each worker also writes out its result (rather than passing it on for further processing).

I am wondering: what is the advantage of using the `dask.bag` approach, over `client.map`?

**Comment by TomAugspurger** [comment]
`dask.bag` and the `concurrent.futures`-like interface provided by `Client` are just two different APIs. For your use case, I'd recommend sticking with `Client.map`.

One question @arokem: how do you "submit" this job? Do first need to log into your pangeo, get dropped into a juptyerlab session, and then run the script? Would it be useful to avoid the jupyterlab step, and just have an authenticated way to submit jobs and somehow view the status?

**Comment by arokem** [comment]
The current usage is indeed by logging into the pangeo and submitting through a Jupyter notebook. I do think that other interfaces might be useful. For example, I can imagine a CLI that looks something like: 

```
pangeo-submit code.py inputs.json --auth ~/.pangeo/key.json
```
That returns something like: 

```
Submitting 1048 jobs to cluster: panneuro (project: learning2learn-22161)
............
1048 jobs submitted. 
To view progress, please visit http://learning2learn.pangeo.io/user/arokem/proxy/8787/status
```

With maybe the tqdm bar under that. I think that would be neat. But it's not urgent for us to have that. For now, I think that our users are going to go through the Jupyter interface. One of the advantages of the current state of affairs is that it's relatively easy to test the function on one input, before submitting it for processing of a large number of inputs, and dependencies can be tightly controlled to be identical between the submitting node and the workers. I think that would be a bit harder to control with the CLI. In [Cloudknot](https://richford.github.io/cloudknot/), we control this a bit by allowing users to define a docker image into which the function is installed (and that is then sent to AWS batch)

**Comment by arokem** [comment]
One of the challenges of this is that we get a lot of `dask-jovyan` pods appearing on the cluster, and sometimes when a lot of jobs get submitted none of the pods can take on any work. It seems like the only way out of that is to kill all of the `dask-jovyan` pods on the cluster. Which is sub-optimal, because the users can't do that. 

This seems to be particularly the case when clusters are repeatedly initialized by using "restart kernel and run all", which is something that I do all the time. 

What steps can I take within Jupyter to clear out `dask-jovyan` pods off of the cluster?
