### ISSUE TITLE
dask labextension for HPC deployment

### ISSUE THREAD

**Issue by filippo82** [pangeo-data/pangeo#650]
Dear all,

I was able to follow (and modify) [this gide](http://pangeo.io/setup_guides/hpc.html) to set up Pangeo on the HPC system of my university (which uses LSF). I was able to deploy it and run it but not to use/connect the dask dashboard. I've installed dask_labextension but the buttons remain grey.

Any thoughts?

Thank you!

jupyter serverextension list says that everything is OK/enabled

**Comment by guillaumeeb** [comment]
Hi @filippo82,

Could you be a little more specific?
For the dashboard, do you use nbserverproxy (or it's new name jupyter-server-proxy), with dashboard relative link? Or do you have an IP shown in cluster or client link?

For dask-lab-extension, did you fill the field of the dashboard link? But if you cannot see the dashboard, it's not surprising the extension doesn't work.

**Comment by filippo82** [comment]
Dear @guillaumeeb, I apologize for the very slow reply but I had not time to look into this again till last week. I think I was able to resolve this issue thanks to an `issuu` on the dask_jobqueue repo.
