### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by dcherian** [pangeo-data/pangeo#651]
I'm using `ocean.pangeo.io` to make some cool visualizations of the LLC4320 data. How do I acknowledge the project, NSF (& NASA?) in my talk?

**Comment by rsignell-usgs** [comment]
I don’t know but I would love to see the cool visualizations!

**Comment by rabernat** [comment]
Thanks for asking about this @dcherian!

We don't have a good system in place to track the impact of Pangeo. This is something we need to solve!

For now, we are citing this Figshare document.
https://figshare.com/articles/Pangeo_NSF_Earthcube_Proposal/5361094

```
@article{Abernathey2017,
author = "Ryan Abernathey and kevin paul and joe hamman and matthew rocklin and chiara lepore and michael tippett and Naomi Henderson and Richard Seager and Ryan May and Davide Del Vento",
title = "{Pangeo NSF Earthcube Proposal}",
year = "2017",
month = "8",
url = "https://figshare.com/articles/Pangeo_NSF_Earthcube_Proposal/5361094",
doi = "10.6084/m9.figshare.5361094.v1"
}
```

**Comment by dcherian** [comment]
@rsignell-usgs 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/2448579/58830869-8cb45680-8608-11e9-92c1-9a9c58c452a0.png">

@rabernat : Thanks.

**Comment by patrickcgray** [comment]
Hey @rabernat is there an updated preference for citing pangeo? I'm referencing the pangeo docker env in a data availability statement and want to cite. Still the figshare DOI?
