### ISSUE TITLE
test GCP cluster on geotiff / landast

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#66]
I am sitting at the [ESIP meeting](http://www.esipfed.org/meetings/upcoming-meetings/esip-winter-meeting-2018) hearing about public Earth Science data that is already in the cloud.

One great example is landsat:
https://cloud.google.com/storage/docs/public-datasets/landsat

In theory, xarray should be able to read this data already via rasterio integration. Since these are [cloud optimized geotiffs](http://www.cogeo.org/), hypothetically, they should play very well with chunked reading, if the dask chunks are aligned with the geotiff tile boundaries.

It would be awesome if someone could dig into this and figure out if it actually works with pangeo.pydata.org. (And, if not, figure out what needs to be done to enable it.) It would be a great example of good design leading to automatic synergy between independent projects.

@jhamman is the obvious one to tag here (since he helped a lot with rasterio in xarray). But this could also be a good issue for any new collaborators out there who want to get more involved in pangeo.

**Comment by mrocklin** [comment]
This early blogpost shows using dask.array with image data stored on remote servers.  It might provide some ideas: http://matthewrocklin.com/blog/work/2017/01/17/dask-images

Though this was with many small standard image files, which may be a different case.

**Comment by mrocklin** [comment]
@rabernat is there any chance that we could engage one of these groups in doing this work with us?

**Comment by rabernat** [comment]
Let's explicitly try to recruit collaborators. I'll mention this in my talk.

When do you get here?

**Comment by mrocklin** [comment]
My flight arrives at the airport at 4:10pm.  With luck I'll be there by 5ish?  I'll ping you by e-mail or phone when I'm around.

**Comment by rabernat** [comment]
Just to be provocative, if we could somehow get this working *before* our talks, I think we might really raise some eyebrows.

**Comment by mrocklin** [comment]
I'd be happy to screw around with this this evening if you like.  Do you
have a sense for how to do these operations locally, how to get chunk
shapes, etc.?

**Comment by jreadey** [comment]
AWS also has landsat available: https://aws.amazon.com/public-datasets/landsat/. 

I think this is a good idea - xarray can be the universal API for variety of data formats.

I'm at ESIP too.  @rsignell-usgs will be demoing xarray with HDF Cloud on Thursday.

**Comment by rabernat** [comment]
@jreadey--thanks for your interest in this issue! To clarify, we already have a working xarray / dask-distributed / netcdf prototype running on google cloud. This issue is specifically about whether we can read the landsat geotiff data.

@mrocklin--I will try to get a local demo working this afternoon. Then we can decided whether it's worth trying to run on GCP. (It will definitely at least require us to add rasterio / gdal to the docker images.)

**Comment by mrocklin** [comment]
> I'm at ESIP too. @rsignell-usgs will be demoing xarray with HDF Cloud on Thursday.

Awesome.  I'm looking forward to seeing this :)

If you all want to try running things from http://pangeo.pydata.org let us know.  There are mechanisms to control your environment and the environments of the workers if you're interested.  

https://youtu.be/rSOJKbfNBNk

**Comment by jreadey** [comment]
@mrocklin - Do you have any Pangeo users interested in running on the AWS platform?  We could help out with this.

**Comment by jhamman** [comment]
@jreadey - absolutely. We've only just started with GCP but AWS is on the horizon. What do you have in mind?

**Comment by rabernat** [comment]
Yes, we would absolutely love to deploy on AWS. Our goal is to create a tool that is cloud-agnostic. (Hopefully kubernetes makes that easy!) 

@jreadey, want to meet up today to discuss? I don't know anyone here at ESIP.

**Comment by mrocklin** [comment]
Everything for our current deployment is at https://github.com/pangeo-data/pangeo/pull/57 .  The only GCE specific system is the gcsfs Python library for accessing GCS, the S3 equivalent.  This could be replaced with s3fs pretty trivially.  The FUSE stuff wouldn't carry over without some more work, but that probably doesn't interest you immediately anyway.  

It would be very valuable to have someone else deploy this on AWS, if only to understand where issues might arise.

**Comment by mrocklin** [comment]
The instructions in the setup.py file might suffice to launch things *now* if you have convenient access to a Kubernetes cluster.  Eventually we might consider hosting a few of these at gce.pangeo.org, aws.pangeo.org, azure.pangeo.org, etc. to facilitate data locality

**Comment by jreadey** [comment]
@rabernat - let's sit together for lunch today.  I'll be in the hallway ~12:45 and hopefully we can spot each other.

@mrocklin - AWS just came out with Kubernetes support, so it could be fairly trivial.  I'll give it a shot next week and report back.

**Comment by jreadey** [comment]
@mrocklin - do you mean this: https://github.com/pangeo-data/pangeo/blob/master/setup.py? 

Looks like just a placeholder.

**Comment by mrocklin** [comment]
@jreadey see https://github.com/mrocklin/pangeo/tree/gce/gce

**Comment by jreadey** [comment]
Ok, got it.  There's actually only a couple of lines of Google-specific code there.

**Comment by mrocklin** [comment]
Yup.  We're trying to build general systems.  Please let us know if you
come across opportunities to improve the generality here.  Glad to have you
engaged here.

**Comment by jhamman** [comment]
ping @atlehr and @robfatland who may be interested in following along with any AWS developments.

**Comment by rabernat** [comment]
Looks like rasterio only supports s3 for now. The issue linked above is about adding google support.

Incompatibility between cloud storage APIs seems like a big point of friction in general for cloud computing.

**Comment by mrocklin** [comment]
Do they accept a Python-like file object?  All of the dask file system
objects provide this.

**Comment by rabernat** [comment]
> Do they accept a Python-like file object?

Yes. I can't find the API documentation for `rasterio.open` in their docs, but the docstring clearly states:
```
    fp : str or file object
        A filename or URL, or file object opened in binary ('rb') mode
```

**Comment by mrocklin** [comment]
Then you might try creating a gcsfs file

```python
from gcsfs import GCSFileSystem
fs = GCSFileSystem()
fp = fs.open('/bucket/path/to/file.geotiff')
```

**Comment by rabernat** [comment]
The point of using the gdal API is that it understands
cloud-optimized-geotiff, so it can use http GET range requests to
intelligently subset the data from within the S3 (or gcs) bucket. I imagine
that using gcsfs would suppress that capability. But I could be wrong.

In this case, it sounds like it could be a pretty easy upstream fix.

**Comment by mrocklin** [comment]
> so it can use http GET range requests to intelligently subset the data from within the S3 (or gcs) bucket

I would hope that S3 connection details aren't written directly into the spec.  All of the dask-related filesystems support random access with `seek`, `tell`, `read` and friends.  Do we have any information about how this is implemented in GDal and how Rasterio interacts with it?

**Comment by mrocklin** [comment]
Alternatively, if we just need to point it to a URL then maybe we make the files visible to standard HTTP requests.

Also, is there anything stopping us from reading S3 data from our GCE system short term?  Is the data publicly available?

**Comment by rabernat** [comment]
GDAL has an extensive implementation of "virtual file systems"
http://www.gdal.org/gdal_virtual_file_systems.html

rasterio has a lightweight wrapper around a subset of these files
https://github.com/mapbox/rasterio/blob/master/rasterio/vfs.py

**Comment by jreadey** [comment]
You can implement posix-like seek() and read() operations, but for data formats like hdf5, the latency involved in a large number of read operations is a performance killer.  We looked at this for a NASA study last year and after a point it ended being faster to copy the file locally and then use normal posix calls.

**Comment by rabernat** [comment]
Trying the gcsfs option. It's not working so far. I'm trying to read one of [these files](https://console.cloud.google.com/storage/browser/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342016259LGN00?_ga=2.38806243.1562264431.1515594734-1348765089.1507054149&_gac=1.209324454.1512527297.EAIaIQobChMIjvKgm6v01wIVU1cNCh22bgQNEAAYASAAEgJH_fD_BwE).

```python
fs = GCSFileSystem(project='pangeo-181919')
gs_url = ('/storage.cloud.google.com/gcp-public-data-landsat/LC08/PRE/044/034/'
          'LC80440342016259LGN00/LC80440342016259LGN00_B1.TIF')
fp = fs.open(gs_url)
```

I get
```
~/miniconda3/envs/geo_scipy/lib/python3.6/site-packages/gcsfs/core.py in validate_response(r, path)
    111             print(r.url, r.headers, sep='\n')
    112         if "Not Found" in m:
--> 113             raise FileNotFoundError(path)
    114         elif "forbidden" in m:
    115             raise IOError("Forbidden: %s\n%s" % (path, msg))

FileNotFoundError: b//o/
```

I guess I am not pointing it to the correct path, but I can't figure out what is the right one to use.

**Comment by mrocklin** [comment]
> You can implement posix-like seek() and read() operations, but for data formats like hdf5, the latency involved in a large number of read operations is a performance killer. We looked at this for a NASA study last year and after a point it ended being faster to copy the file locally and then use normal posix calls.

Do we know if this carries over to GeoTIFF as well or only HDF5?  

I'm curious, did you guys try any tricks like reading ahead?  Our initial foray into this seemed to show that a bit of file-system style optimizations had decent impact.

**Comment by mrocklin** [comment]
@rabernat the urls you want for gcsfs are of the form `/bucket/path/to/file`.  It looks like you're handing it a normal URL

My guess is that  `gcp-public-data-landsat` is the bucket name.

**Comment by mrocklin** [comment]
However, looking more deeply at this I no longer think that the file-like object is the right approach.  This thing isn't a file, it's many files.  If I were to solve this quickly I would just create a dask graph that individually downloaded each of the chunks.  It looks like these are set up to be served on the open internet.  

I recommend navigating to a page like https://console.cloud.google.com/storage/browser/gcp-public-data-landsat/LC08/PRE/003/003/LC80030032014142LGN00/?authuser=0

and then looking at the `Public link` link.  Here is one such example: https://storage.googleapis.com/gcp-public-data-landsat/LC08/PRE/003/003/LC80030032014142LGN00/LC80030032014142LGN00_B10.TIF

So we can just wrap a a function like `skimage.imread` in dask.delayed, call it a bunch of times, and construct a dask.array by concatenating and stacking those images together.  This is the approach taken in http://matthewrocklin.com/blog/work/2017/01/17/dask-images .  Obviously it would be nice to create a convenience function that read a bit of metadata to determine the kinds of function calls to make.  I wonder if anyone knows the structure of this metadata already?

**Comment by mrocklin** [comment]
It looks like rasterio supports http/https virtual file systems.  Given that these files are all served on the public internet those might suffice.

**Comment by mrocklin** [comment]
I wonder if pointing rasterio to this link would work: https://storage.googleapis.com/gcp-public-data-landsat/

**Comment by mrocklin** [comment]
Not GCSFS, but using the https backend

**Comment by rabernat** [comment]
I don't understand why gcsfs can't read this data. This works
```
$ gsutil ls -l gs://gcp-public-data-landsat/LC08/PRE/044/034/LC80440342017117LGN00/LC80440342017117LGN00_B10.TIF
  56620417  2017-04-30T00:52:50Z  gs://gcp-public-data-landsat/LC08/PRE/044/034/LC80440342017117LGN00/LC80440342017117LGN00_B10.TIF
TOTAL: 1 objects, 56620417 bytes (54 MiB)
```

But this doesnt'
```python
gs_url = ('/gcp-public-data-landsat/LC08/PRE/044/034/LC80440342017117LGN00/LC80440342017117LGN00_B10.TIF')
fp = fs.open(gs_url)
```

Still getting `FileNotFoundError`.

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by rabernat** [comment]
A few experiments are here:
https://nbviewer.jupyter.org/gist/rabernat/6821def682f5e56937d586aff65a34bd

**Comment by martindurant** [comment]
The URL should have been
```
gs_url = 'gcp-public-data-landsat/LC08/PRE/044/034/LC80440342017117LGN00/LC80440342017117LGN00_B10.TIF'
```
(without the leading `'/'`) @rabernat

**Comment by mrocklin** [comment]
I've run into this error as well in the past.  Is there a clean way to make
gcsfs robust to this in the future?

**Comment by martindurant** [comment]
@mrocklin , I guess `bucket=''` in this case, which can never refer to a file - but is the path used when listing buckets. Note that `'gs://gcp-public-data-landsat/LC08/...'` (same URL as for gsutil) would also have worked.

**Comment by mrocklin** [comment]
> Note that GCSFileSystem.info (or ls with details) provides a 'mediaLink' key for direct http access, which may be a quicker way to look things up than in the console.

Good to know :)

**Comment by rabernat** [comment]
It works if I remove the leading slash!

However, this line:
```
fp = fs.open(gs_url)
```
Triggers the whole object to be downloaded. Is that how it's supposed to work?

**Comment by mrocklin** [comment]
> @mrocklin , I guess bucket='' in this case,

Where is this parameter?

> which can never refer to a file - but is the path used when listing buckets. Note that 'gs://gcp-public-data-landsat/LC08/...' (same URL as for gsutil) would also have worked.

I don't disagree that there are probably cleaner ways to do this.  However this user speedbump has come up often enough that I think we should address it in some way.

**Comment by mrocklin** [comment]
@rabernat are you sure it's not just downloading the first few megabytes?

**Comment by martindurant** [comment]
> Where is this parameter?

The first thing that `open()` (and many other methods) does is 
```
bucket, key = split_path(path)
```
where `split_path()` removes `'g[c]s://` and does `path.split('/', 1)`. 

@rabernat , `f = gcs.open()` does not download any data, but it does get the metadata if that does not exist in the cache. The next read, even of on byte, will trigger downloading of 1-2 "blocksize"s worth of data. Exactly how much depends on previous reads and will be at 5MB boundaries.

**Comment by rabernat** [comment]
Let's put it this way:

after running that command, my inbound bandwidth has been saturated at 400
KB/s (I'm on the conference wifi) for the past 10 minutes.

**Comment by mrocklin** [comment]
> The first thing that open() (and many other methods) does is
>     bucket, key = split_path(path)
> where split_path() removes 'g[c]s:// and does path.split('/', 1).

Perhaps we need a check then like the following?

```python
if not path.startswith('/'):
    path = '/' + path
```

**Comment by martindurant** [comment]
@rabernat , are you running on master gcsfs? I can't now find the commit, but in the past, metadata would be fetched by downloading a complete file-list for the bucket, which in this case is massive. Now, `open()` (and `info()`) directly queries the specific file in case the file-list does not exist in memory.

@mrocklin , it would be the other way around
```
if path.startswith('/'):
    path = path[1:]
```
and I *think* this is safe to put into `split_path`, let me check.

**Comment by martindurant** [comment]
^ or should it be `lstrip`, for the case that people provide URLs like "//bucket/key"?

**Comment by rabernat** [comment]
@martindurant: I am just using whatever gcsfs I got from pip. Sounds like you have nailed the issue.

Any plans for a release soon? These sounds like really important features that have been added recently.

**Comment by martindurant** [comment]
Yes, a release is on the cards pretty soon to incorporate the work done since new year. There are still a couple of PRs that we may want to include.

**Comment by mrocklin** [comment]
@rabernat you might want to become comfortable operating from gcsfs git master 

    pip install git+https://github.com/dask/gcsfs

**Comment by rabernat** [comment]
Ok, using the latest master solves that issue.

Now on to the next one:
```python
ds_gs = xr.open_rasterio(fp)
```

```
~/miniconda3/envs/geo_scipy/lib/python3.6/site-packages/rasterio/__init__.py in open(path, mode, driver, width, height, count, crs, transform, dtype, nodata, **kwargs)
    150     """
    151     if not isinstance(path, string_types):
--> 152         raise TypeError("invalid path: {0!r}".format(path))
    153     if mode and not isinstance(mode, string_types):
    154         raise TypeError("invalid mode: {0!r}".format(mode))

TypeError: invalid path: <GCSFile gcp-public-data-landsat/LC08/PRE/044/034/LC80440342017117LGN00/LC80440342017117LGN00_B10.TIF>
```

Looks like rasterio doesn't accept that type of object after all.

**Comment by mrocklin** [comment]
Oh well, back to https?

**Comment by martindurant** [comment]
It seems like there is special code in rasterio to deal with s3 only. Perhaps the limitation is with gdal? There is some stuff to deal with in-memory datasets, so maybe something could be done.

**Comment by mrocklin** [comment]
We can just deal with the data over normal https. I don't think we need to
engage gcsfs here.

**Comment by rabernat** [comment]
@martindurant: this is a pretty easy upstream fix in rasterio: mapbox/rasterio#991.

I am not as optimistic as @mrocklin that we can get the same performance boost with GOG's over normal ftp. But he knows a lot more than me, so I am probably wrong.

**Comment by mrocklin** [comment]
It's not ftp, it's https, which is what gcsfs is using under the hood.

**Comment by jhamman** [comment]
Keeping this open as https://github.com/mapbox/rasterio/issues/991 is still not resolved.
