### ISSUE TITLE
pangeo github membership

### ISSUE THREAD

**Issue by cpatrizio88** [pangeo-data/pangeo#663]
Hello,

I am a PhD student in the atmospheric sciences program at Colorado State University and would like to become a member of Pangeo GitHub if possible. 

I am interested in using pangeo to aid in analysis of output from Estimating the Circulation and Climate of the Ocean (ECCO). I have been using the pangeo binder deployment, but I am wondering if maybe I should be using hub.pangeo.io, or some other deployment that is suited to research work.

**Comment by rabernat** [comment]
Hi @cpatrizio88 - thanks for your message and welcome!

I recommend you log in to https://ocean.pangeo.io. You will just need and ORCID ID, not any github membership.

You can find example of working with the ECCOv4 dataset here: https://github.com/pangeo-data/pangeo-ocean-examples/blob/master/ecco_v4_example.ipynb

**Comment by rabernat** [comment]
p.s. Feel free to ask any questions you want here!

**Comment by cpatrizio88** [comment]
Thanks @rabernat ! 

I successfully logged in to [https://ocean.pangeo.io](https://ocean.pangeo.io). Is there a way to configure my own conda environment here? Typically I would add dependencies to an environment.yaml file, but I'm not sure that will work now.

**Comment by rsignell-usgs** [comment]
Do you need your dask workers to have additional packages, or just the notebook environment?

**Comment by cpatrizio88** [comment]
@rsignell-usgs I think I just need my notebook environment to have different packages.

**Comment by rabernat** [comment]
> Is there a way to configure my own conda environment there?

No. This is one of the main bottlenecks in our system now. You can pip or conda install in your notebook, but those changes will not persist after logging out.

The images are quite full featured. The base environment is here: https://github.com/pangeo-data/pangeo-stacks/tree/master/pangeo-notebook/binder

You are welcome to propose adding packages to that environment if you wish!

**Comment by rabernat** [comment]
> You can pip or conda install in your notebook, but those changes will not persist after logging out.

And they will not propagate to dask workers.

**Comment by cpatrizio88** [comment]
OK, thanks for the heads up! It looks like most of the dependencies are covered by the base environment already, so I should be good to go.
