### ISSUE TITLE
Who's at SciPy 2019?

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#664]
A bit late to open this issue, given that the conference is already underway, but here goes...

There are quite a few Pangeo related talks going on, including
- Wednesday, 2:05 pm - 2:35 pm: Zarr - Scalable Storage of Tensor Data for Use in Parallel and Distributed Computing (@alimanfoo)
- Thursday, 10:20 am - 10:50 am - Xgcm: Analyzing General Circulation Models in Python (@rabernat)
- Thursday, 10:55 am - 11:25 am - How to Track Plastic in the Ocean? The Parcels Lagrangian Ocean Framework (@delandmeterp)
- _In fact, the whole "Earth, Ocean, Geo and Atmospheric Science" mini-symposium is quite relevant, and I won't bother listing all the talks here_
- Friday: 2:35 pm - 3:05 pm - "Turning HPC Systems Interactive " (@andersy005)

Of course, there is tons of other Pangeo-adjacent stuff as will, including @mrocklin's recent work on heterogeneous computing at NVIDIA and all of the PyViz stuff.

In addition, we are holding an Xarray sprint on Saturday: https://www.scipy2019.scipy.org/sprints-schedule

I'm curious to know **who is at SciPy this year?** and **if you're interested in a Pangeo dinner meetup Thursday or Friday night?**

**Comment by mrocklin** [comment]
I'm around all week.  I'm somewhat busy today and tomorrow morning but free afterwards.

**Comment by andersy005** [comment]
> Friday: 2:35 pm - 3:05 pm - "Turning HPC Systems" (@andersy005 et al; who is actually presenting this?

I am giving this talk. 

Thursday would work for me since I'm flying back to Denver Friday evening.

**Comment by delandmeterp** [comment]
But Thursday is also the social event
https://www.scipy2019.scipy.org/social-events

**Comment by rabernat** [comment]
I have not been to the conference before. Is it common for everyone to attend the social events? If so, we should just plan on meeting there. 

I did not register for the game night but hopefully can still attend somehow.

**Comment by delandmeterp** [comment]
First time, I don't know... 

And yes, looking forward to the xarray sprint on Saturday!

**Comment by mrocklin** [comment]
People tend to go to the reception tonight and to the Schulz's beer garden event.  The other event has historically not been attended much because Continuum ran a competing event.  This stopped happening last year, so it's a bit uncertain.  My default plan was to go to the happy hour Thursday night for a bit, and then probably grab dinner. 

I recommend that we meed up at the happy hour on Thursday night, and then meet outside at around 8pm to go to dinner.

**Comment by mrocklin** [comment]
To be clear, I don't recommend signing up for the game night.  That's not necessary for the happy hour also on Thursday night.

**Comment by rabernat** [comment]
Where can one find the listing of BoFs? I couldn't track it down on the conference website. I think there is a Pangeo BoF, but I'm not sure when.

**Comment by mrocklin** [comment]
The physical booklet that is handed out at registration is probably best

**Comment by dopplershift** [comment]
I might be going to a matplotlib dev thing on Thursday, but would be open to anything that didn't conflict with that.

**Comment by jbednar** [comment]
BoF: Pangeo: Scaling Science Analytics using Python is on 7/11/2019 1pm-1:55pm in room 203. Annoyingly, like last year it is scheduled at the same time as my Python Data Visualization BoF, which is in the ballroom. BoFs are listed in the main schedule https://www.scipy2019.scipy.org/confschedule

I'm happy to meet up.  The game night is definitely optional, and seems like an otherwise open slot.

**Comment by rsignell-usgs** [comment]
I'm here also and +1 on the plan of hitting the the happy hour thursday and then dinner with Pangeans.   Also staying for sprints.

**Comment by alimanfoo** [comment]
Hi folks, I'm around until Friday evening, will definitely come to Pangeo BOF and will happily tag along for beers at any other time if you'll let me :-)

**Comment by rabernat** [comment]
I plan to go to the "BoF pyOpenSci: Building an Open Community to Promote Python Software Best Practices, Review, Discovery and Curation" tonight 6-7 pm. After that I would like to attend the happy hour with whoever Pangeo folks are around / interested.

**Comment by dopplershift** [comment]
I'll be heading over to the happy hour (at "Easy Tiger") after the "beaks" BoF.

**Comment by rabernat** [comment]
@mrocklin has floated the idea of renting kayaks and going out on the river. It's ambitious and appealing. Anyone here interested in that?

**Comment by delandmeterp** [comment]
Friday PM? Or Saturday PM after the sprints? Or Sunday or Monday morning?
For those dates I'm in.
