### ISSUE TITLE
pangeo and earth science

### ISSUE THREAD

**Issue by christine-e-smit** [pangeo-data/pangeo#667]
Hi! I'm the engineer from NASA Goddard's GES-DISC. I work on Giovanni (https://giovanni.gsfc.nasa.gov/giovanni/). I talked with you folks at the SciPy BOF. I gather that you are already working with some of the folks in ESDIS who work on earthdata login. (ESDIS is the GESDISC's parent organization.)

I would love to talk about data formats. I would love to know what your definition of "analysis ready" data is in terms of what metadata you are looking for. I assume we're talking CF-1.

I found your website a few months ago and I was extremely excited to read through it. You introduced me to intake (fabulous!) and confirmed the dask/zarr/xarray stack was the way to go.

Thanks!
Christine

**Comment by christine-e-smit** [comment]
The vision we currently have is to put data in the cloud in cloud-friendly data formats that we can provide a range of tools for. So, for people who are scared of coding - a not insignificant audience - we want to make an updated version of giovanni that is much faster and more interactive. For people who aren't afraid of coding, we want to make our datasets available via whatever. We're currently thinking docker images or AMIs with <stuff> installed like the pangeo stack or ???

In order to get to this vision, we are very interested in data formats. We are currently working on a version of Giovanni that uses parquet as the file format behind the scenes with unrolled multi-dimensional arrays. This decision was made a couple years ago. Parquet has the advantage of being compatible with pythonic and non-pythonic stuff. E.g. - parquet works natively with AWS's Athena. It works in Java. It works with pandas. It works with Spark. It works with fastparquet. It works with dask (I believe). But, it also has disadvantages: no easy metadata beyond column headers, no multi-dimensional arrays. In other words, no easy correspondence with a netcdf-like model.

**Comment by scottyhq** [comment]
Hi @christine-e-smit! Great to hear about your work with Giovanni and your interest in exploring Pangeo efforts. I wanted to draw your attention to a few places with current activity (you may have already seen these repos)!:

We're nearing the halfway point in a NASA ACCESS award described here (https://github.com/pangeo-data/nasa-access-17). One goal of this project is to demonstrate analysis of data on AWS and we've mostly focused on zarr and cloud-optimized geotiff to-date. Regarding metadata, we're currently exploring STAC catalogs integrated with the intake library (https://github.com/pangeo-data/intake-stac). 

There is a working group that meets occasionally to discuss these sorts of topics in more detail: https://github.com/pangeo-data/pangeo-datastore

**Comment by christine-e-smit** [comment]
Thanks for the info! I assume that https://github.com/radiantearth/stac-spec is the STAC standard you are referring to. @jhamman mentioned it to me at SciPy.

I look forward to seeing where your ACCESS project goes, particularly as it relates to search and earthdata login. I thought that we at the GES-DISC were using a standard apache module to handle earthdata login for our data, but it turns out that we are actually using a custom-built module created by the earthdata login team. I see now why the earthdata login team is going to need to write something custom to work with data in s3.

I am particularly interested because in the next few months, the GES DISC will start to put some of our archive products in s3 via Cumulus (https://earthdata.nasa.gov/eosdis-cumulus-project), ESDIS's data processing workflow solution for the DAACs. Presumably, these data products will need to end up somehow behind earthdata login and be registered in earthdata search.

**Comment by christine-e-smit** [comment]
For now, there are unfortunately no plans to do anything other than archive the data in the same cloud-unfriendly formats that we currently store on disk. This is obviously quite frustrating and seems rather short-sighted. However, my boss Hegde - whom @jhamman talked with at the ESDSWG - is interested in potentially adding an extra step to our pipeline to convert the data to zarr and store that in addition to the traditional format. If you are interested in partnering with us to do that, we are all ears.
