### ISSUE TITLE
Hello Pangeo!

### ISSUE THREAD

**Issue by tommylees112** [pangeo-data/pangeo#668]
Hi all,

I recently met @jacobtomlinson at a hackathon in London, with the [Software Underground (SWUNG)](https://softwareunderground.org/) group. He introduced us to the Pangeo community and ecosystem and mentioned that introducing myself on here might be the best way to be involved. I am a PhD student at Oxford looking at drought monitoring and prediction in East Africa. 

I am a frequent user of xarray and have recently been working on a project to combine seasonal forecast models with machine learning methods to better predict drought. The project ([repo here](https://github.com/esowc/ml_drought)) is part of the [ECMWF Summer of Weather Code](https://www.ecmwf.int/en/learning/workshops/ecmwf-summer-weather-code-2019) and I am working with my collaborator and friend @gabrieltseng. I am already so grateful for people's help with my questions on StackOverflow and GitHub. 

I am particularly interested in using Dask and the compute resources / datasets that you guys have collected. This would really help working with datasets and processes that I struggle to fit into my laptop's memory!

The binder repositories are such a great help and I am super grateful for the time you have spent sharing these tools and resources with the wider geoscientific community. Something that I think would be interesting would be to explore how meterological drought indices (SPI / SPEI) change in the future CMIP6 model scenarios under different global warming conditions (may have already been done!).

Thanks again for setting up this group! Let me know how I can get involved and if there's anything that sounds interesting to you!

Kind Regards
Tommy

**Comment by mrocklin** [comment]
cc'ing @alimanfoo , just due to geographic proximity

**Comment by tommylees112** [comment]
Thankyou @mrocklin ! @alimanfoo Would love to catch up in Oxford if possible! The work on Zarr looks super interesting! 

Thanks guys :D

**Comment by alimanfoo** [comment]
Hi Tommy, sounds like a cool project, I'm at the Big Data Institute on the
old road campus, let me know if you'd like to swing by some time. I don't
know much about xarray but do have some experience with dask.

**Comment by rabernat** [comment]
This issue was moved to https://discourse.pangeo.io/t/hello-pangeo/47
