### ISSUE TITLE
Supporting cyclic co-ordinates

### ISSUE THREAD

**Issue by SimonTett** [pangeo-data/pangeo#670]
Hi
  though I like xarray a lot  one of the annoying things about it is that it does not support cyclic co-ordinates -- for example longitude. The CF standard does, I think, support such co-ordinates. My understanding of xarray is that they do not intend for it to support such co-ordinates directly seeing it as a role of other packages that build on xarray. So which package should I use/modify if I want to this functionality? 

Simon  Tett

**Comment by rabernat** [comment]
Hi @SimonTett! Thanks for raising this important issue. It has come up several times in different contexts.

Could you clarify what time would be to "support" cyclic coordinates? Could you be more specific about what exactly you want to do with cyclic coordinates that does not currently work?

I am going to assume for a minute that by "support cyclic coordinates" you mean "support indexing on cyclic coordinates", i.e you would like to do something like
```python
da.sel(longitude=slice(-170, 170)
```
and have it correctly wrap around the date line.

If so, our best hope is with Xarray's support for [more flexible indexes](https://github.com/pydata/xarray/issues/1603). This has been a work in progress for a long time.

My view is that we need a small, lightweight "geoindexers" package that lives outside of xarray which implements these indexers.

There has been some recent discussion on related issues in https://github.com/pangeo-data/pangeo/issues/629. @fbriol is interested in this topic.

**Comment by willirath** [comment]
Also ping @jk-rieck who's done some work on selecting from curvilinear grids.

**Comment by SimonTett** [comment]
That's exactly what I'd like! Also handle plotting across the date line -- though that might be fixed in more recent versions of  xarray. Here is my hacky code that does it... 

def wrap_sel2(ds, wrap=360, **kwargs):
    """
    from    https://gis.stackexchange.com/questions/205871/xarray-slicing-across-the-antimeridian
    wrap selection assuming 360 degrees. xarray core is not likely to include this. Shame as would make nice method.
    Maybe someone builds something on xarray that supports geographical co-ordinates..
    :param ds: dataset
    :param wrap: default 360 -- period of co-ordinate.
    :param kwargs -- dimension= slice. Only provide one.
    :return:
    """

    dim, sliceObj = next(iter(kwargs.items()))

    l = (ds[dim] + 2 * wrap) % wrap
    lstart = (sliceObj.start + 2 * wrap) % wrap
    lstop = (sliceObj.stop + 2 * wrap) % wrap
    if lstop > lstart:
        ind = (l <= lstop) & (l >= lstart)
    else:
        ind = (l <= lstop) | (l >= lstart)

    result = ds.isel(**{dim: ind})

    # need to make data contigious which may require rolling it and adjusting co-ord values.

    # step 1 work out how much to roll co-ordinate system. Need to find "break"
    # break is last place in array where ind goes from False to True
    brk = np.max(np.where(ind.values[:-1] != ind.values[1:]))
    brk = len(l) - brk - 1
    result = result.roll(**{dim: brk})
    # step 2 fix co-ords
    v = result[dim].values
    v = np.where(v < 180., v, v - 360)
    result = result.assign_coords(**{dim: v})

    return result

**Comment by spencerahill** [comment]
FWIW in aospy we created a `Longitude` class and accompanying logic to make dealing with longitudes, date line crossings, etc. less error-prone.  Although I'm not sure it's directly relevant to the specific indexing needs you're describing.  The use-case for us is defining lat-lon rectangular regions for averaging over.

Docs [here](https://aospy.readthedocs.io/en/stable/api.html#module-aospy.utils.longitude) and source code [here](https://github.com/spencerahill/aospy/blob/master/aospy/utils/io.py)

**Comment by fbriol** [comment]
We have created for our needs an [interpolation library](https://github.com/CNES/pangeo-pyinterp/) that manages these longitude discontinuity problems. It is the [Axis class](https://pangeo-pyinterp.readthedocs.io/en/latest/api/pyinterp_core.html#pyinterp.core.Axis), used for regular or irregular grids, which manages the search for values on an axis. The class transparently handles regular and irregular axes in order to use the best algorithm to locate the value on an axis: ``int(coordinate - start) / step`` for a regular axis, or a binary search in the case of a regular axis.

Concretely to obtain the indexes from a dataset:

```python
>>> import pyinterp.core as core                                                                                       
>>> import numpy as np                                                                                                 
>>> x=np.arange(-180, 180, 1) 
>>> x_axis=core.Axis(x, is_circle=True, is_radian=False)
>>> x_axis.find_index(np.arange(0, 360, 5))
array([180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355,   0,   5,  10,
        15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
        80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140,
       145, 150, 155, 160, 165, 170, 175], dtype=int64)
```

The purpose of this library is to offer interpolation objects and geographical indexes for structured and [unstructured grids](https://pangeo-pyinterp.readthedocs.io/en/latest/api/pyinterp.rtree.html#rtree-spatial-index) and to include them in "xarray". A while ago, I looked at how to integrate these indexes into "xarray", to be honest, the code is a little complicated and I haven't made any progress. And I hope to find someone to help me....
