### ISSUE TITLE
Using xmitgcm LLC reader on the cloud

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo#676]
Are there plans to be able to access the LLC data (https://medium.com/pangeo/petabytes-of-ocean-data-part-1-nasa-ecco-data-portal-81e3c5e077be) from Pangeo cloud? 

When I tried it, I get the following error: 
ImportError: The llcreader module requires fsspec version 0.2.1 or or greater to be installed. To install it, run `pip install fsspec`. See https://filesystem-spec.readthedocs.io/en/latest/ for more info.

Should fsspec be added to the pangeo environment file?

**Comment by rabernat** [comment]
Closed by https://github.com/pangeo-data/pangeo-cloud-federation/pull/335
