### ISSUE TITLE
Issue running xarray notebook, getting plot in cell [5]

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#68]
I'm trying to run the xarray notebook, and it seems to sort of hang in cell [5], in that I've been waiting about 5 minutes, and no plot.  (and it does say "a quick plot", so I'm thinking something is wrong...)

![2018-01-12_12-33-17](https://user-images.githubusercontent.com/1872600/34887656-403664fe-f795-11e7-9a9e-c32339f61e88.png)
![2018-01-12_12-25-06](https://user-images.githubusercontent.com/1872600/34887659-43c6502a-f795-11e7-9c86-bed2eeb5218d.png)

**Comment by rsignell-usgs** [comment]
I just discovered [Matthew's excellent 3 minute video](https://www.youtube.com/watch?v=rSOJKbfNBNk) on how to run the xarray notebook, and yes, that plot should be delivered in only a few seconds.  

Clearly something is wrong, although I admit it could just be user error!  :stuck_out_tongue_closed_eyes:

**Comment by jmunroe** [comment]
I am playing around with this as well. Same issue.

Could it be related to 
  ModuleNotFoundError: No module named 'google'

The worker log shows:

distributed.worker - INFO - Start worker at: tcp://10.20.36.11:43162
distributed.worker - INFO - Listening to: tcp://10.20.36.11:43162
distributed.worker - INFO - nanny at: 10.20.36.11:45402
distributed.worker - INFO - Waiting to connect to: tcp://10.20.45.6:45646
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Threads: 2
distributed.worker - INFO - Memory: 8.00 GB
distributed.worker - INFO - Local Directory: /dask-worker-space/worker-3vk75087
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Registered to: tcp://10.20.45.6:45646
distributed.worker - INFO - -------------------------------------------------
distributed.worker - ERROR - Worker failed to read message. This will likely cause the cluster to fail. Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 1175, in compute_stream msgs = yield comm.read() File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) File "<string>", line 4, in raise_exc_info File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run yielded = self.gen.throw(*exc_info) File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 191, in read msg = yield from_frames(frames, deserialize=self.deserialize) File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) File "<string>", line 4, in raise_exc_info File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper yielded = next(result) File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 75, in from_frames res = _from_frames() File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 61, in _from_frames return protocol.loads(frames, deserialize=deserialize) File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 119, in loads value = _deserialize(head, fs) File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 158, in deserialize return f(header, frames) File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 20, in <lambda> deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))} File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads return pickle.loads(x) ModuleNotFoundError: No module named 'google'
distributed.worker - ERROR - No module named 'google' Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 1175, in compute_stream msgs = yield comm.read() File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) File "<string>", line 4, in raise_exc_info File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run yielded = self.gen.throw(*exc_info) File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 191, in read msg = yield from_frames(frames, deserialize=self.deserialize) File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) File "<string>", line 4, in raise_exc_info File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper yielded = next(result) File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 75, in from_frames res = _from_frames() File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 61, in _from_frames return protocol.loads(frames, deserialize=deserialize) File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 119, in loads value = _deserialize(head, fs) File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 158, in deserialize return f(header, frames) File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 20, in <lambda> deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))} File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads return pickle.loads(x) ModuleNotFoundError: No module named 'google'
```

```

**Comment by mrocklin** [comment]
Taking a look now

**Comment by mrocklin** [comment]
I suspect that this is due to a version mismatch between the notebook and worker containers.  I was screwing around yesterday and this likely caused an issue.  Can either of you verify that the dask-array notebook works fine?

**Comment by jmunroe** [comment]
Yes. The dask-array notebook works great.

**Comment by mrocklin** [comment]
I recommend trying now with the xarray notebook.  I've updated the docker containers.  They may take a minute to launch the first time around.

**Comment by mrocklin** [comment]
Things work fine for me now.  Thank you all for reporting.  We should get better about managing the environments of the workers and notebook.

**Comment by rsignell-usgs** [comment]
@mrocklin , yes, working now for me too.   Phew!
