### ISSUE TITLE
Sharing Jupyter Notebooks on Pangeo JupyterHubs

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#680]
Binder is awesome, but it would be great to have a quick way to share notebooks in Pangeo. 

In [Dan Allan's nice post on sharing Jupyter Notebooks](https://blog.danallan.com/posts/2019-07-01-sharing-jupyter-notebooks/), he describes the [jupyterhub-share-link](https://github.com/danielballan/jupyterhub-share-link) code developed to share notebooks on JupyterHubs in a simple way:

> The sender right-clicks a notebook (or any file) and clicks "Copy Shareable Link." The sender gives that link to any other user on the same Hub. When another user clicks the share link, the last saved version of the file is copied from the sender's notebook server to the recipient's. If the sender changes the file, the recipient can click the link again to make another copy reflecting the changes. After a given time interval, the link expires.
>
> On Hubs using a container-based spawner, the share link encodes both the notebook and the container image that the sender was running that notebook in. The recipient will automatically be directed to a server running that same container image, and thus have some assurance that they will be running the notebook in a compatible software environment. (This is not the case when sharing notebooks via email or Dropbox.)

This seems like it would be a good match for Pangeo JH deployments, no?

**Comment by TomAugspurger** [comment]
Agreed this would be useful. On the call today I mentioned a potential auth issue, but I misread the docs (that was just for the demo).

**Comment by fmaussion** [comment]
Is pangeo using nbgitpuller btw? https://jupyterhub.github.io/nbgitpuller/index.html

We use it to share notebooks in an otherwise empty Binder / JupyterHub environment. It nicely allows to separate env from content (see e.g. https://discourse.jupyter.org/t/tip-embed-custom-github-content-in-a-binder-link-with-nbgitpuller/922 and http://edu.oggm.org/en/latest/user_content.html for an application example).
