### ISSUE TITLE
Convert to Zarr and directly push to remote server/cloud

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo#681]
I would like to know if there is some way to convert data to Zarr, and instead of storing the Zarr files on the local machine, and push it directly to google cloud. 
I am struggling with an issue where I have a data set (MITgcm output) that is larger in size than the free HD space on my machine. I would like to convert this to Zarr format and push it to the cloud for further analysis. However, I don't have enough space on my machine to be able to convert to Zarr, as I will not be able to store the Zarr files without running out of memory. 

Has anyone encountered or solved this?

**Comment by rabernat** [comment]
Dhruv, this is easily accomplished by writing out to a zarr cloud store, i.e.
```python
gcs = gcsfs.GCSFilesystem(token='browser') # you need credentials to write
gcsmap = gcsfs.GCSMap('bucket/path', gcs=gcs)
ds.to_zarr(gcsmap)
```

This will effectively stream the output to the cloud.

If you want to use a distributed cluster, you need [this gcsfs trick](https://gist.github.com/rabernat/4cc2eca3868abda7ddf89ed10f8007fb).
