### ISSUE TITLE
Hello Pangeo

### ISSUE THREAD

**Issue by PhenoloBoy** [pangeo-data/pangeo#682]
Hi everybody, 

For a long time I have been using all the modules that are the basis of Pangeo and for a long time I follow the evolution of the group even if I have never introduced myself. Where I work have recently begun to call me as xarray/dask evangelist for my enthusiasm and I really would like to push them to use Pangeo over the two facility that we have here.
In this last period I was trying to test xarray/dask on GC but meeting some difficulties @martindurant suggested me to try with Pangeo and here I'm. 
Today I got courage and I pulled up Pangeo on GC following the tutorial. 
Everything was perfect until once I entered my notebook Jupiter I realized that all the modules that I had defined in the jupyter_config.yaml are not there... 
Since I'm a beginner I definitely got something wrong in the configuration. 
In the configuration file I added under extraENV the following keys:

`      EXTRA_PIP_PACKAGES: git+https://github.com/......
      EXTRA_APT_PACKAGES: libzstd1
      EXTRA_CONDA_PACKAGES: numpy pandas scipy rasterio xarray matplotlib netcdf4 nomkl statsmodels numba gcsfs pyhdf -c conda-forge` 

the EXTRA_APT_PACKAGES is due to a problem that I've got deploying a Dask following this instructions. 
https://ramhiser.com/post/2018-05-28-adding-dask-and-jupyter-to-kubernetes-cluster/

Can anyone help me to understand where I'm wrong ?

**Comment by rabernat** [comment]
That guide is a bit stale. The current recommended way to configure packages in your environment is at the repo2docker level. See the setups in https://github.com/pangeo-data/pangeo-cloud-federation for more detailed examples.

**Comment by PhenoloBoy** [comment]
Following the instruction, I discover that the link [Zero to Jupyterhub](http://pangeo.io/setup_guides/cloud.html) in the first note wrongly points to an empty page.

@rabernat it's a shame that I didn't know that you are spending your vacation in Italy otherwise I would have suggested something special for Florence.

**Comment by rabernat** [comment]
> Following the instruction, I discover that the link [Zero to Jupyterhub](http://pangeo.io/setup_guides/cloud.html) in the first note wrongly points to an empty page.

PR welcome! 😉  https://github.com/pangeo-data/pangeo/blob/master/docs/setup_guides/cloud.rst

> @rabernat it's a shame that I didn't know that you are spending your vacation in Italy otherwise I would have suggested something special for Florence.

Mia moglie e Italiana (di Salerno), quindo sono in Italia al meno due volte all'anno. L'anno prossimo (2020-2021) mi tocca un anno sabbatico, e speriamo di andare tutti in Italia. Per ora sto pensando Bologna, pero vorrei studiare un po' le opzioni. Cosa fate a Firenze?

**Comment by PhenoloBoy** [comment]
Thanks, I was looking for it but I haven't been able to find it. Now it's done. 

@rabernat  Answered in private @ ldeo.columbia.edu
