### ISSUE TITLE
EGU 2020 short-course 

### ISSUE THREAD

**Issue by fmaussion** [pangeo-data/pangeo#685]
Hi Pangeo,

@jhamman and myself have been discussing about proposing a pangeo short-course as a "second-part" of a general xarray tutorial at the upcoming EGU: https://egu2020.eu/guidelines/short_courses_guidelines.html

For the record, here is what we proposed two years ago: https://meetingorganizer.copernicus.org/EGU2017/session/25651 It was quite a success - full room, many questions and interest from the audience. 

The way I see it for 2020: we'd apply for a two-blocs short course, the first one as a general introduction to xarray for geosciences, and the second one as a more advanced "pangeo + binder + big data on the cloud" session.

Please answer here or [email me](https://fabienmaussion.info/) if you plan to participate to EGU2020 and feel ready to help organizing the tutorial. The current team we have is quite atmo / climate oriented, and it would be nice to have people from remote sensing as well.

**Comment by fmaussion** [comment]
A short follow-up (deadline is in one week). @jhamman , you are best placed to ping the EU pangeo community here - or should you and I just get the ball rolling and look for co-conveners later? It might be possible to add collaborators afterwards, but the short course proposal submission deadline is a hard one.

**Comment by willirath** [comment]
I'm not sure about my own participation at EGU this year, butthere definitely will be people from GEOMAR who regularly work with the Pangeo stack on HPC. So if you go ahead ad submit a short course and need assistance in preparing, dry-running, or teaching / supporting the course in Vienna, we'll find someone from Kie to join you.

**Comment by fmaussion** [comment]
OK, here is a tentative abstract: https://docs.google.com/document/d/1AmW_-nIlvojV_LmnBs08etYqBvq9mBx-4gtiNc0ZK3Q/edit?usp=sharing 

Feel free to comment / edit at wish 

Ping also @gidden and @byersiiasa

**Comment by guillaumeeb** [comment]
I'm still a little too far from science to attend EGU, but thanks for thinking about me!

**Comment by jhamman** [comment]
I'm hoping to attend EGU this year so I'd be happy to help with the short course (provided my hopes turn out). In any event, I'm happy to be listed on the abstract. I've made a few small edits to the document linked above. Thanks @fmaussion for putting it together.

**Comment by fmaussion** [comment]
@willirath @jhamman thanks for your support - let's add you both as co-conveners and hope that at least one of you (or someone new) can jump in to help

**Comment by willirath** [comment]
Sounds good.

**Comment by benbovy** [comment]
I'm not yet sure to attend EGU next year, but I'd like to. I'd be happy to jump in and help with the preparation of tutorial! I've made just one small suggestion in the abstract, which looks good to me. Thanks @fmaussion for the initiative!

**Comment by fmaussion** [comment]
OK, proposal is in: https://meetingorganizer.copernicus.org/index.php?trg=provisionalprogramme&cotree=601.3990&tpl=page_sp#SC1 

Modifs accepted until Sept 5th

**Comment by jhamman** [comment]
Thanks @fmaussion!

**Comment by fmaussion** [comment]
Our short course is accepted! See: https://meetingorganizer.copernicus.org/EGU2020/session/36380 

I'll get back in touch with you for the organization (we still have time), and @jhamman can find a way to visit us in Europe next year ;-) Maybe worth organizing a pangeo side event around EGU to use the time well.

**Comment by benbovy** [comment]
This is great, well-done!

> Maybe worth organizing a pangeo side event around EGU to use the time well

A nice venue somewhere in the Austrian Alps?

**Comment by willirath** [comment]
> A nice venue somewhere in the Austrian Alps?

Sounds good. Only concern: EGU is really packed. The closer to the Austria Center the easier it will be to include everyone.

**Comment by byersiiasa** [comment]
I can look into locations nearby the conference for side-meeting and beer drinking after the short course

**Comment by benbovy** [comment]
> The closer to the Austria Center the easier it will be to include everyone.

I fully agree :wink: !

**Comment by willirath** [comment]
Let's keep this open.

**Comment by fmaussion** [comment]
Dear all, the EGU abstract submission deadline is approaching (Jan 15th). I think it's the right time to make an assessment of who is going to be here?

I'm definitely going to attend, what about @byersiiasa , @willirath , @jhamman , @benbovy ?

**Comment by benbovy** [comment]
I'll be there too.

**Comment by gidden** [comment]
:+1:

**Comment by jhamman** [comment]
I am likely to attend (75% confidence). I will be submitting at least one abstract.

**Comment by fmaussion** [comment]
Thanks @jhamman! What about @willirath for 100% confidence about the Pangeo part?

**Comment by willirath** [comment]
Sorry for the delay. I'm not fully certain yet. But let's say, it's 75% as well. :)

**Comment by byersiiasa** [comment]
Hi - yes, I am 90% certain I will attend also!

**Comment by jhamman** [comment]
Hi folks. It looks like our session was accepted and we have a date/time to announce: 

SC1.11
Short Course: Working with big, multi-dimensional geoscientific datasets in Python: an interactive tutorial introduction to xarray and pangeo
Thu, 07 May, 08:30-12:30, room -2.16

**Comment by fmaussion** [comment]
Thanks @jhamman ! There is one action item to do before Feb 24th, which is to provide a coarse schedule for the course, which looks like this (dummy schedule):

![Selection_039](https://user-images.githubusercontent.com/10050469/74844454-c0b5e000-532d-11ea-9cdc-7d2826d58baa.png)

At this stage I don't think we can provide a precise schedule yet, so I asked the EGU organization if we can provide a rough one now, and change the details at a later stage.

**Comment by fmaussion** [comment]
OK, EGU wants this fixed by Feb 24th. In order to avoid noise here I'd like to move the discussion to a dedicated repository.

@jhamman are you OK with me creating a pangeo/egu2020-tutorial repository, or would you rather (re-)use the pangeo-tutorials repo and add an egu2020 section to it?

**Comment by jhamman** [comment]
> @jhamman are you OK with me creating a pangeo/egu2020-tutorial repository, or would you rather (re-)use the pangeo-tutorials repo and add an egu2020 section to it?

Either way works for me. I've generally found it useful to keep reusing the pangeo-tutorial repo and creating a new branch for each event. But I don't have strong feelings either way.

**Comment by leifdenby** [comment]
I'll be attending too

**Comment by willirath** [comment]
I have booked everything for the trip to Vienna now. So I'll be available for the short course as well.

**Comment by fmaussion** [comment]
Great news! Looking forward to meet you.

For all interested - we just started a new branch on https://github.com/pangeo-data/pangeo-tutorial/tree/egu2020 where we will be able to build upon all the material that the project gathered already. I'll try to start coordinating the work in mid-March.

**Comment by fmaussion** [comment]
Yes, sorry for not mentioning this earlier: our short course was cancelled of course. 

Thanks everyone for participating, and let's try again next year!
