### ISSUE TITLE
Large image size

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#69]
Our images are a few gigabytes.  This makes for an unpleasant experience for users because they have to wait for a minute or so for their containers to start up (if the image or node has changed recently).  

We should investigate the size of our containers at various stages and see if there is anything we can do to reduce their size, either on our own or by raising concerns upstream, such as the conda package maintainers.

**Comment by yuvipanda** [comment]
There's ongoing work on better pre-pulling for dynamic clusters (see WIP PR https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/399) which should also help a little bit. Agree that reducing image size is also a good thing (one of the reasons I prefer pip!)

**Comment by jhamman** [comment]
Would it be advantageous/possible to cache images coming from dockerhub on Google's Container Registry? I'm wondering if this would help with the spin-up time for large images. BTW, this is an option for binder (repo2docker).

**Comment by jacobtomlinson** [comment]
I'm currently exploring this for our Pangeo setup.

We build our image and push it to Docker Hub automatically. I am keen on also pushing it to our AWS container registry.

**Comment by yuvipanda** [comment]
Using SSD base disks for your nodes gives you at least an order of magnitude performance boost. If your images are > 5G, I highly recommend it. This does come with a cost increase though.
