### ISSUE TITLE
Warning Message: FutureWarning: The `numpy.moveaxis` function is not implemented by Dask array

### ISSUE THREAD

**Issue by stb2145** [pangeo-data/pangeo#690]
I keep getting a warning message that repeats itself until 1) I am kicked out of the server when using clusters; or 2) the kernel just keeps running when not using clusters and repeating the error message, to the point where I have to interrupt the cell. I think it might have something to do with some updates that went through yesterday affecting the numpy/dask interface, but I'm not completely sure. 

#### Reproducible Code:
```
import xarray as xr
import dask
import dask.array as dsa
import numpy as np
import intake
from xmitgcm.llcreader.llcmodel import faces_dataset_to_latlon
```
I also get a warning message after I run the cell importing all the necessary packages:

```
/srv/conda/envs/notebook/lib/python3.7/site-packages/tqdm/autonotebook/__init__.py:18: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)
/srv/conda/envs/notebook/lib/python3.7/site-packages/intake/source/discovery.py:136: FutureWarning: The drivers ['esm_metadatastore'] do not specify entry_points and were only discovered via a package scan. This may break in a future release of intake. The packages should be updated.
  FutureWarning)
```

```
ecco_url = 'https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml'
ecco_cat = intake.Catalog(ecco_url)
ds = ecco_cat["ECCOv4r3"].to_dask()

ds_ll = faces_dataset_to_latlon(ds)
ds_ll
```

Here is the error message (the cell runs for a while if not using clusters):

```
/srv/conda/envs/notebook/lib/python3.7/site-packages/dask/array/core.py:1263: FutureWarning: The `numpy.moveaxis` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  FutureWarning,
/srv/conda/envs/notebook/lib/python3.7/site-packages/dask/array/core.py:1263: FutureWarning: The `numpy.moveaxis` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  FutureWarning,
/srv/conda/envs/notebook/lib/python3.7/site-packages/dask/array/core.py:1263: FutureWarning: The `numpy.moveaxis` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  FutureWarning,
```
I'd appreciate some insight to resolve this issue, thank you.

**Comment by TomAugspurger** [comment]
FYI https://github.com/dask/dask/pull/4822 was just merged, so the next version of dask (like 2.2.1) will work nicely with `np.moveaxis`, regardless of the numpy version.

FWIW, as a library maintainer, I'm happy to have all of NumPy's dispatching unified under `__array_function__`, rather than scattered around various `hasattr(object, 'moveaxis')`-type checks. In theory, this breakage could have been avoided if that Dask PR had been merged before NumPy 1.17 came out. It's unfortunate that this one slipped through the cracks, but I hope we'll get through the `__array_function__` growing pains relatively quickly.

**Comment by rabernat** [comment]
meta comment: this discussion would have been impossible (or at least a lot slower) on discourse (see #677).

**Comment by stb2145** [comment]
@TomAugspurger, your workaround fix for creating a cluster after importing `os` doesn't work when I include the `env={"NUMPY_EXPERIMENTAL_ARRAY_FUNCTION": "0"})` part. It seems to be blocking the workers from starting. But I am able to run the `ds_ll` cell if I omit that specification and run the Kubernetes cluster cell!

**Comment by TomAugspurger** [comment]
Hmm that's strange. I just tried it out on ocean.pangeo.io with `cluster = KubeCluster(n_workers=10, env={"NUMPY_EXPERIMENTAL_ARRAY_FUNCTION": "0"})`, and my workers came up fine.

Do you specify anything else when you create the KubeCluster?


FYI, this is fixed on Dask master now. We're doing a 2.2.1 release today hopefully, so the workaround won't be necessary once the cluster is updated to use it.

**Comment by stb2145** [comment]
No, I just copied and pasted the same code. Will try again now.

That's great to hear!

**Comment by stb2145** [comment]
I tried it again (with the environment specification) and waited around 10 min for workers to load and the dask dashboard was still blank - but when I omitted that part, it took about 2 minutes for workers to load.

Looking forward to that dask update!
