### ISSUE TITLE
bibtex build script incompatible with research.gov reporting

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#703]
Our new publication bibtex build script:

https://github.com/pangeo-data/pangeo/blob/05fc5af41e5c8c984d68ed5e90951af06ed1f610/docs/build_pangeo_bib.py#L1-L16

Is apparently incompatibly with NSF's bibtex parsing:
![image](https://user-images.githubusercontent.com/1197350/63886051-9b13d380-c9a7-11e9-940d-dbe9d1c7ed5c.png)

This is troubling, because the bibtex is generated by crossref, the official DOI registrar.

I would open an issue in the NSF repo, but something tells me that their system is not changing any time soon. ;) Maybe we can find a workaround.

reported by @kmpaul

**Comment by rabernat** [comment]
This website is informative: https://www.research.gov/common/robohelp/public/WebHelp/Project_Reports.htm

**Comment by kmpaul** [comment]
I found that, too, but I was unable to get a hint as to the problem. I also found these slides:

https://www.nsf.gov/od/oia/programs/epscor/presentations/PDPA_Winter_2015/Byers_RPPR.pdf

But those didn’t offer a hint at the problem, either.

**Comment by kmpaul** [comment]
I may be forced to call them. :-)

**Comment by kmpaul** [comment]
I got a response from NSF's Research.gov team after submitting a help ticket:

> Thank you for contacting the Fastlane Helpdesk.  The Published articles need to be added via NSF-PAR, not RPPR using bibtex. This award is subject to Public Access Mandate. Bibtex can only be used for products other than publised artciles.  In addition, the report was submitted.

So, there is no easy way to upload published articles.  Sigh.
