### ISSUE TITLE
shutting down astro.pangeo.io, polar.pangeo.io, atmos.pangeo.io

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#709]
These clusters were deployed as experiments, but are now largely unused. Instead people have gravitated towards other deployments. Meanwhile, they are eating up valuable credits on Google Cloud. We would like to shut them down.

Is anyone still using them? 

cc @pangeo-data/pangeo-astro, @NicWayand @pangeo-data/pangeo-atmos 

If we don't hear anything within 48 hours, we will delete them.

**Comment by jhamman** [comment]
Also pinging @cmbitz who seems to have recently been working on polar.pangeo.io (https://github.com/cmbitz/polar.pangeo.io-deploy/commit/63272ad777d64cdb4599e1ce0b62838d9e693b72).

**Comment by rabernat** [comment]
That would be fantastic to learn that Ceci has been using Pangeo! I definitely don't want to discourage anyone who is using these resources. Just trying to find the most cost-effective path forward.

**Comment by cmbitz** [comment]
Unfortunately, I wound up giving up on polar pangeo about a month ago. Sorry for not informing you. I couldn't figure out how to make it work properly, and don't have the time to figure it out now. Thanks for letting us try it out.

**Comment by rabernat** [comment]
Thanks for the feedback Ceci. We are experimenting with a lot of different approaches here. I'm curious to learn from you what it might mean for pangeo to "work properly" for you and your group, as there are a lot of different possible use cases. Perhaps we could find time for a quick phone chat at some point this fall.

**Comment by cmbitz** [comment]
That would be great Ryan. I'm busy the next 3 weeks but then my work load should ease up. Thanks!

**Comment by Cadair** [comment]
I don't think any of the solar people have the cycles to do anything with astro. at the moment. Thanks a lot for all your work on this :smile:
