### ISSUE TITLE
Speaker for CEOS WGISS-48 Meeting

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#710]
Is anyone from @pangeo-data/pangeo-members planning on attending the [CEOS WGISS-48 Meeting](http://ceos.org/meetings/wgiss-48/)? The organizers are looking for someone from the Pangeo Project to give a talk about leveraging  zarr for computation. The presentation could be done remotely. They gave a tentative date/time of 10/9 at 11:00 am Vietnam time, which would be 9pm on 10/8 PDT.

**Comment by rabernat** [comment]
This issue was moved to https://discourse.pangeo.io/t/speaker-for-ceos-wgiss-48-meeting/45
