### ISSUE TITLE
Long running idle dask clusters on ocean.pangeo.io

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#712]
Here is a screenshot from the activity monitor of a dask worker pod in the ocean.pangeo.io namespace:

![image](https://user-images.githubusercontent.com/1197350/64288944-4df8aa00-cf31-11e9-8273-b03bb954f616.png)

The pod has been running for almost 12 hours with zero visible activity. There are 40 others like it.

Because of https://github.com/dask/dask-kubernetes/issues/173, there is currently no easy way to figure out who owns this pod. I imagine it is a new user who simply doesn't understand that this is a waste of credits.

This issue brings to mind several related questions:
- How do we inform new users about best practices on the cloud?
- How do we monitor user usage?
- How do we potentially restrict user usage, i.e. via dask-gateway.

I'm eager to get thoughts on this.

**Comment by mrocklin** [comment]
Also, as of a relatively recent version of Dask:

```
$ dask-scheduler --help | grep idle
  --idle-timeout TEXT           Time of inactivity after which to kill the scheduler
```

**Comment by scottyhq** [comment]
@rabernat, @mrocklin (and adding @rsignell-usgs) we just noticed some long-running dask pods on aws clusters today which makes me think this might not be user error and actually something going on at the cluster level. dask-worker nodes were left running on the aws clusters even after user-notebook pods and nodes shut down. Here are some relevant kubectl outputs... but unfortunately i'm not exactly sure why this is happening

`kubectl get pods --all-namespaces -o wide`
> esip-prod      dask-rsignell-usgs-0b2bf9f0-1kc48v    0/1     ContainerCreating   0          9d      <none>          ip-192-168-38-94.us-west-2.compute.internal     <none>           <none>

`kubectl describe pod dask-rsignell-usgs-0b2bf9f0-1kc48v  -n esip-prod`

>    State:          Waiting
      Reason:       ContainerCreating


` kubectl get nodes -o wide`
> ip-192-168-38-94.us-west-2.compute.internal    Ready    worker   9d      v1.13.7-eks-c57ff8   192.168.38.94    34.223.66.115    Amazon Linux 2   4.14.128-112.105.amzn2.x86_64   docker://18.6.1

` kubectl logs cluster-autoscaler-6575548656-74955 | grep dask`
> I0904 23:59:46.094549       1 cluster.go:104] Fast evaluation: node ip-192-168-38-94.us-west-2.compute.internal cannot be removed: esip-prod/dask-rsignell-usgs-0b2bf9f0-1kc48v is not replicated

and finally, 

```python
import dask
import dask.config
dask.config.config
{'distributed': {'logging': {'bokeh': 'critical'},
  'dashboard': {'link': '/user/{JUPYTERHUB_USER}/proxy/{port}/status'},
  'admin': {'tick': {'limit': '5s'}}},
 'kubernetes': {'name': 'dask-{JUPYTERHUB_USER}-{uuid}',
  'worker-template': {'spec': {'restartPolicy': 'Never',
    'containers': [{'name': 'dask-${JUPYTERHUB_USER}',
      'image': '${JUPYTER_IMAGE_SPEC}',
      'args': ['dask-worker',
       '--nthreads',
       '2',
       '--no-dashboard',
       '--memory-limit',
       '7GB',
       '--death-timeout',
       '60'],
      'resources': {'limits': {'cpu': '1.75', 'memory': '7G'},
       'requests': {'cpu': 1, 'memory': '7G'}}}]}}},
 'labextension': {'factory': {'module': 'dask_kubernetes',
   'class': 'KubeCluster',
   'args': [],
   'kwargs': {}}},
 'temporary-directory': None,
 'array': {'svg': {'size': 120}}}
```

**Comment by mrocklin** [comment]
What do the full logs look like?  

If memory serves, the dask-workers themselves are given a 60s death timeout with `--death-timeout 60`.  This means that the dask-worker  process itself should shut down after 60s of not being able to connect to the scheduler.

**Comment by scottyhq** [comment]
thanks @mrocklin - which logs are you referring to? If you have some specific kubectl or dask commands to try and diagnose let me know.

**Comment by scottyhq** [comment]
Okay, I can reproduce the dask pods (and nodes) in limbo by logging onto esip.pangeo.io and launching a dask cluster. if no worker nodes are available it seems to be taking too long to scale up and there are network errors:

`kubectl describe pod dask-scottyhq-527e3b25-ag48fq   -n esip-prod`
```
Name:         dask-scottyhq-527e3b25-ag48fq
Namespace:    esip-prod
Priority:     0
Node:         ip-192-168-78-224.us-west-2.compute.internal/192.168.78.224
Start Time:   Wed, 04 Sep 2019 19:55:16 -0700
Labels:       app=dask
              component=dask-worker
              dask.org/cluster-name=dask-scottyhq-527e3b25-a
              user=jovyan
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Pending
IP:           
Containers:
  dask-scottyhq:
    Container ID:  
    Image:         783380859522.dkr.ecr.us-west-2.amazonaws.com/pangeo-esip:e6ec0b9
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      dask-worker
      --nthreads
      2
      --no-dashboard
      --memory-limit
      7GB
      --death-timeout
      60
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1750m
      memory:  7G
    Requests:
      cpu:     1
      memory:  7G
    Environment:
      DASK_SCHEDULER_ADDRESS:  tcp://192.168.4.168:35189
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-l8cgz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-l8cgz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-l8cgz
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     k8s.dask.org/dedicated=worker:NoSchedule
                 k8s.dask.org_dedicated=worker:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                    From                                                   Message
  ----     ------                  ----                   ----                                                   -------
  Warning  FailedScheduling        7m42s (x2 over 7m42s)  default-scheduler                                      0/2 nodes are available: 1 Insufficient cpu, 2 Insufficient memory.
  Normal   TriggeredScaleUp        7m32s                  cluster-autoscaler                                     pod triggered scale-up: [{eksctl-pangeo-esip-nodegroup-dask-worker-v2-NodeGroup-UKEXL45VXVA7 0->1 (max: 100)}]
  Warning  FailedScheduling        6m12s (x3 over 6m14s)  default-scheduler                                      0/3 nodes are available: 1 Insufficient cpu, 1 node(s) had taints that the pod didn't tolerate, 2 Insufficient memory.
  Normal   Scheduled               6m4s                   default-scheduler                                      Successfully assigned esip-prod/dask-scottyhq-527e3b25-ag48fq to ip-192-168-78-224.us-west-2.compute.internal
  Warning  FailedCreatePodSandBox  6m2s                   kubelet, ip-192-168-78-224.us-west-2.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "77c187a18ff7974198302f452bfb89cf126689939ff7fe72bb4598c55ea4d360" network for pod "dask-scottyhq-527e3b25-ag48fq": NetworkPlugin cni failed to set up pod "dask-scottyhq-527e3b25-ag48fq_esip-prod" network: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused", failed to clean up sandbox container "77c187a18ff7974198302f452bfb89cf126689939ff7fe72bb4598c55ea4d360" network for pod "dask-scottyhq-527e3b25-ag48fq": NetworkPlugin cni failed to teardown pod "dask-scottyhq-527e3b25-ag48fq_esip-prod" network: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused"]
```

then it becomes a kubernetes autoscaler problem (see my first comment) where "the node cannot be removed because the pod is not replicated". This seems relevant https://github.com/kubernetes/autoscaler/issues/351

**Comment by rabernat** [comment]
Thanks for digging into this. In my case, I'm pretty sure this is just a user who doesn't know any better.

@mrocklin - so is it possible to add an `idle-timeout` to the default dask scheduler settings? I think that would be an excellent safeguard against accidentally wasting large sums of money.

**Comment by mrocklin** [comment]
It won't be default in Dask itself, but it should be an easy thing for us
to add in Pangeo configuration files that we distribute as part of our
deployments.
