### ISSUE TITLE
Open Source Software @ OceanObs19 

### ISSUE THREAD

**Issue by biavillas** [pangeo-data/pangeo#716]
Hi all, 
@cgentemann is leading a breakout session at OceanObs19 on Open Source Software, Wednesday, 9/18 2pm-4pm (see the description below). 

There will be short presentations from folks representing funding agencies as well as a couple of panelists talking about OSS from a scientist point of view. The goal is to come up with a set of recommendations on OSS to be added to the OceanObs19 recommendations. We believe input from the Pangeo community could add a lot of value to this breakout session, so please help circulate this announcement amongst people who might be attending the conference and feel free to contact  @cgentemann, @jhausman or me if you have any comments/suggestions.

-----
LEAD: Chelle Gentemann, Earth and Space Research
Room: 317A
*The evolution of open source software coupled with modern computing platforms enables new scalable scientific approaches. This session will explore applications of open source software to science, discuss popular tools and best practices, identify potential barriers to this rapidly advancing form of collaboration, and generate ideas on how open source software can further benefit the scientific community.*

**Comment by rabernat** [comment]
This issue was moved to https://discourse.pangeo.io/t/open-source-software-oceanobs19/48
