### ISSUE TITLE
Strange UI glitch

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#717]
Has anyone else seen this? https://discourse.jupyter.org/t/strange-red-frames-in-jlab/2097

Would it cause trouble with any other elements of the pangeo stack if I upgrade jupyterlab to 1.1 (currently on 1.0.4 -- I believe this was inherited from the pangeo notebook docker)?

**Comment by mrocklin** [comment]
Yup.  See https://github.com/dask/dask-labextension/issues/88

**Comment by arokem** [comment]
Indeed, updating jupyterlab to 1.1.2 resolved this issue.
