### ISSUE TITLE
Mysteriously killed Dask workers 

### ISSUE THREAD

**Issue by jsadler2** [pangeo-data/pangeo#719]
Title kinda sounds like a murder mystery 

I don't have very much experience running dask on the cloud, so I don't know exactly what info is relevant for debugging, but I'll try my best to provide the necessary clues:

- I am trying to run a distributed job on esip.pangeo.com. 
- I copied an ran an example script from @rsignell-usgs on the same cluster without error
- I am reading a zarr dataset stored on an S3 bucket that requires my credentials.
- The zarr dataset is read into an xarray dataset and on that dataset I am taking the mean along one of the dimensions of one of the data arrays.
- I can successfully do the mean operation without calling the cluster
- When I call the cluster the workers get killed and if I look into the logs of the workers, I see the following error message:

> distributed.worker - ERROR - group not found at path '' Traceback (most recent call last): File "/srv/conda/envs/notebook/lib/python3.7/site-packages/s3fs/core.py", line 1155, in _fetch_range **kwargs) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call return self._make_api_call(operation_name, kwargs) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call raise error_class(parsed_response, operation_name) botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py", line 74, in __getitem__ result = self.fs.cat(key) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/spec.py", line 544, in cat return self.open(path, 'rb').read() File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/spec.py", line 1060, in read out = self.cache._fetch(self.loc, self.loc + length) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/core.py", line 481, in _fetch self.cache = self.fetcher(start, bend) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/s3fs/core.py", line 1043, in _fetch_range return _fetch_range(self.fs.s3, self.bucket, self.key, self.version_id, start, end) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/s3fs/core.py", line 1169, in _fetch_range raise translate_boto_error(e) PermissionError: Access Denied During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/hierarchy.py", line 110, in __init__ meta_bytes = store[mkey] File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py", line 78, in __getitem__ raise KeyError(key) KeyError: 'esip-pangeo-nwm/hru_percentiles/historical_gwres_stor_out/.zgroup' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/worker.py", line 857, in handle_scheduler comm, every_cycle=[self.ensure_communicating, self.ensure_computing] File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/core.py", line 460, in handle_stream msgs = await comm.read() File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/tcp.py", line 216, in read frames, deserialize=self.deserialize, deserializers=deserializers File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper yielded = next(result) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/utils.py", line 80, in from_frames res = _from_frames() File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/utils.py", line 66, in _from_frames frames, deserialize=deserialize, deserializers=deserializers File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads value = _deserialize(head, fs, deserializers=deserializers) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 188, in deserialize return loads(header, frames) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 62, in pickle_loads return pickle.loads(b"".join(frames)) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads return pickle.loads(x) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/hierarchy.py", line 271, in __setstate__ self.__init__(*state) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/hierarchy.py", line 112, in __init__ err_group_not_found(path) File "/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/errors.py", line 29, in err_group_not_found raise ValueError('group not found at path %r' % path) ValueError: group not found at path ''

I think the most important parts are `Access Denied` and `ValueError: group not found at path ''`

Any ideas of how to address these or what's going on? Is it possible that the dask workers don't have access to my S3 data? 

What about the "group not found?" That seems like a zarr issue, but I can do an operation on the zarr dataset without the cluster...

**Comment by rsignell-usgs** [comment]
@jsadler2, it does seem the dask pods do not have access to the S3 bucket, while the notebook pod does.   The S3 data you are trying to access is not public read, correct? 

 I have some notes from @scottyhq that say: 

> Rather than bucket settings, we are attaching policies to the ec2 nodes on the cluster.

But I'm not sure where or how those policies are specified.  @scottyhq?

**Comment by jsadler2** [comment]
Correct. The S3 data is not public read.

**Comment by scottyhq** [comment]
So there are a few ways to go about solving this. AWS permissions can be somewhat perplexing at first.

**1) Change settings on the Hub:**
AWS has the concept of permission "roles" which automatically attach to any instance running a notebook or dask pod (`eksctl-pangeo-esip-nodegroup-dask-NodeInstanceRole-OTEN67KZ455C` and `eksctl-pangeo-esip-nodegroup-user-NodeInstanceRole-10GM79PHL2WAE`). To these roles you attach "policies" that give access to specific S3 buckets. Rich or another esip admin would could add a new bucket, but then all users have access.

**2) Pass personal credentials to dask workers:**
*Note that this is probably not the most secure thing to do and your keys could show up in logs?*

Alternatively you can move your own credentials to the dask workers. One approach is to mount the home directory `/home/jovyan` on dask workers:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/nasa/image/binder/dask_config.yaml 

Then if you have your own credentials in `~/.aws/credentials` they will be found. 

Or maybe you can pass credentials as environment variables to dask workers when you create the cluster: https://github.com/pangeo-data/pangeo-cloud-federation/issues/254#issuecomment-514743372 

**3) Change settings on @jsadler2's s3 bucket**
Alternatively and arguably more secure, add a policy to the s3 bucket to allow access from the hub. For example, https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/ or https://aws.amazon.com/premiumsupport/knowledge-center/block-s3-traffic-vpc-ip/

**Comment by jsadler2** [comment]
Thanks, @scottyhq . So for three, we can just add the IP address of the hub to the bucket policy?

**Comment by rsignell-usgs** [comment]
@jsadler2 I think we just need to add your bucket to the policy used by these roles:    
![2019-09-17_13-35-05](https://user-images.githubusercontent.com/1872600/65071145-0b38c800-d95c-11e9-82d6-594dd525e1e1.png).   We can try this offline and report back.

**Comment by jsadler2** [comment]
And if so, is the IP address coming from the hub consistent?
