### ISSUE TITLE
Best single document to learn about Pangeo?

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#724]
Some computer scientist colleagues are interested in learning more about Pangeo. 

Is this position paper the best current document to send them? 

https://arxiv.org/abs/1908.03356?

**Comment by jhamman** [comment]
There is also @guillaumeeb's conference proceeding with some more technical detail: 

> Eynard-Bontemps, G., R Abernathey, J. Hamman, A. Ponte, W. Rath, 2019: The Pangeo Big Data Ecosystem and its use at CNES. In P. Soille, S. Loekken, and S. Albani, Proc. of the 2019 conference on Big Data from Space (BiDS’2019), 49-52. EUR 29660 EN, Publications Office of the European Union, Luxembourg. ISBN: 978-92-76-00034-1, doi:10.2760/848593.
