### ISSUE TITLE
"Getting Started with Pangeo on HPC" docs are out of date

### ISSUE THREAD

**Issue by spencermathews** [pangeo-data/pangeo#727]
It appears that the `nbsesrverproxy` project was renamed to `jupyter-server-proxy` way back in January (jupyterhub/jupyter-server-proxy#71). Is there any reason why that shouldn't be reflected in the [Getting Started with Pangeo on HPC](https://github.com/pangeo-data/pangeo/blob/master/docs/setup_guides/hpc.rst) docs? Perhaps there are other things there that are out of date?

**Comment by jhamman** [comment]
Hi @spencermathews - absolutely, our HPC docs are getting stale and could use a freshening. We would very much appreciate a pull request making some updates to this guide. 

cc @wtbarnes who has also been working on a yet to be deployed hpc.pangeo.io guide (details below).

- https://github.com/pangeo-data/pangeo-for-hpc
- https://discourse.pangeo.io/t/how-about-creating-a-pangeo-hpc-github-repo/150

**Comment by mrocklin** [comment]
I wonder also if some of these docs should now refer to upstream projects
like jobqueue.dask.org and mpi.dask.org, and if we might concentrate some
of our writing effort there.
