### ISSUE TITLE
Error running jupyter lab on Cheyenne

### ISSUE THREAD

**Issue by edougherty32** [pangeo-data/pangeo#733]
Hi all, 

I recently installed a package (scikit-learn) from my pangeo virtual env that updated a bunch of other python packages, and now when I deploy jupyterlab on Cheyenne, it won't launch. 

I am able to launch jupyterlab just fine using
`jupyter lab --no-browser --ip=`hostname` --port=8877`

and pasting this into a separate terminal window: 
`ssh -N -L 8877:r6i6n31:8877 -L 8878:r6i6n31:8878 doughert@cheyenne.ucar.edu`

The issue is that when I open a browser window at this address: http://localhost:8877

I receive a blank Jupyter notebook screen:
<img width="1046" alt="Jupyter_window" src="https://user-images.githubusercontent.com/40123935/66936227-9314ff00-effa-11e9-9d28-197599936046.png">

and the following error message:
```
[I 09:47:00.675 LabApp] 302 GET / (10.148.0.5) 1.07ms
[W 09:47:01.479 LabApp] 500 GET /lab/api/settings/?1571240821387 (10.148.0.5): Failed validating schema (@jupyterlab/apputils-extension:package): '^0.18.4' is not valid under any of the given schemas
    
    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}
    
    On schema['dependencies']['@jupyterlab/application']:
        '^0.18.4'
[W 09:47:01.479 LabApp] Failed validating schema (@jupyterlab/apputils-extension:package): '^0.18.4' is not valid under any of the given schemas
    
    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}
    
    On schema['dependencies']['@jupyterlab/application']:
        '^0.18.4'
[E 09:47:01.480 LabApp] {
      "Host": "localhost:8877",
      "Connection": "keep-alive",
      "Sec-Fetch-Mode": "cors",
      "Authorization": "token d626368d1a5875c2a9bf043bc94d6af07b7ab18c37000e2d",
      "X-Xsrftoken": "2|c1970c2b|61ca2797f43db55ac2ee612a43a8bcf1|1570895945",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://localhost:8877/lab?",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|c1970c2b|61ca2797f43db55ac2ee612a43a8bcf1|1570895945; username-localhost-8888=\"2|1:0|10:1571235373|23:username-localhost-8888|44:MjA5ZDRiNjM2NGVmNDg1Njk3NTc5ZDU4MDgzMTRiODE=|196701bd7eb6f6bd07ae3adb842674c6c7c6caf120212075ec8b06dca9e768bb\"; username-localhost-8877=\"2|1:0|10:1571240739|23:username-localhost-8877|44:OWE3NGUwZTdhYTI1NDQ3ZGFiMTY5ZWNmZmU3NmNjNzE=|3dd6211e99997362728720c8c6a44667fc78e9b937f0bae63db06110de9e672b\""
    }
[E 09:47:01.480 LabApp] 500 GET /lab/api/settings/?1571240821387 (10.148.0.5) 19.41ms referer=http://localhost:8877/lab?
[I 09:47:03.199 LabApp] Build is up to date
```
I am guessing the issue is something to do with some packages being updated, while others aren't, or are incompatible with each other now?

**Comment by jhamman** [comment]
@edougherty32 - do you know about https://jupyterhub.ucar.edu/?

**Comment by edougherty32** [comment]
@jhamman– I'm aware of it, but haven't used it yet. Looks like it solves my issue of launching a Jupyter notebook, so thank you! 

A quick question: the jupyterhub launches from /glade/u/home/doughert, but I usually launch Jupyter from /glade/work/doughert (where all my code is)–is there a way to change this when launching jupyterhub?

**Comment by mnlevy1981** [comment]
@edougherty32 unless something has changed recently, you're stuck with `/glade/u/home` -- the work around most of us use is to softlink our work directory into our home directory; jupyterhub will be able to traverse the link correctly.

**Comment by edougherty32** [comment]
Great, thank you @mnlevy1981 – that did the trick! 

However, now when I try to import the python modules as I did before using the pangeo deployment described [here](https://pangeo.io/setup_guides/index.html),  I receive an error that the modules (including matplotlib) aren't found. 

Do I need to  activate the pangeo environment prior to spawning a notebook via jupyterhub?

**Comment by edougherty32** [comment]
I figured it out–I just needed to select the correct kernel. 

It looks like there are many kernels available for use, which is great, but I'm wondering if I need to install packages in the future, is that possible using jupyterhub?

**Comment by jhamman** [comment]
@edougherty32 - sorry for the late reply. Yes, this is possible, you'll need to either install the kernel manually (https://ipython.readthedocs.io/en/stable/install/kernel_install.html) or rely on the jupyterhub picking up your environment and offering it as a kernel (the hub should be using `nb_conda_kernels`).

**Comment by edougherty32** [comment]
@jhamman–thanks! I believe I have this working.
