### ISSUE TITLE
apache2 service available through a binder instance?

### ISSUE THREAD

**Issue by DanielMichelson** [pangeo-data/pangeo#739]
I'm transitioning a vagrant/VirtualBox project to binder/pangeo (https://github.com/openradar/oss_weather_radar_vm), and part of it involves hosting a page similar to http://se.baltrad.eu/ to the new environment. The service is hosted by an apache2 server, and it is accessible in the VM by a browser at localhost:8080. This is mainly for educational purposes.
Is hosting such a service on apache2 accessible through a binder/pangeo instance, and if so how?
Many thanks in advance.

**Comment by jhamman** [comment]
@DanielMichelson - Your use case seems quite interesting and should be possible to get going. Binder uses a tool called repo2docker to turn a Git (or similar) repository into a docker image. There are various configuration options that determine what environment gets built in the docker image and what services start on launch. 

For your application I think you'll need to focus on three initial aspects:

1) setting up the environment. If this runs on Python, this is quite easy and can be done with conda or pypi tools: https://repo2docker.readthedocs.io/en/latest/config_files.html#config-files
2) To automatically start a service before Binder launches your notebook, you'll want to look at the `start` config file. This should be sufficient to start your web service.
3) Use [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy) to route your port through the Binder/JupyterHub.

**Comment by DanielMichelson** [comment]
@jhamman Many thanks! I will investigate.

**Comment by DanielMichelson** [comment]
@jhamman I would appreciate a little guidance.
If I'm currently running an instance of my build at:
https://hub.binder.pangeo.io/user/danielmichelson-ausopenradar2019-p2tc8zqa/lab
I can paste that URI into another browser window and get an active session:
https://hub.binder.pangeo.io/user/danielmichelson-ausopenradar2019-p2tc8zqa/lab/workspaces/auto-K
Can I add specific ports to either of these addresses to access a web service mapped through e.g. port 8080?
That would be amazing!

However, in order to configure my apache2 server to serve up the right thing, I need to swap out its configuration files and restart it. How can I do that when building with binder?

**Comment by TomAugspurger** [comment]
Typically you access a port by appending /proxy/<port> to the url. So /proxy/8080

The Apache restart might be done in a binder postBuild file.

**Comment by jhamman** [comment]
Hi @DanielMichelson, how did this go for you?

**Comment by DanielMichelson** [comment]
Hej @jhamman,
Thanks for following up. 
I ran out of time when preparing for the course in November, so I didn't get to the bottom of this. As you can imagine, once the course was done I had to get back to other things. So this issue remains unresolved for me, although I'd love a solution for the next foreseeable course in August.
