### ISSUE TITLE
Jupyterlab extension to browse/load remote datasets

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#740]
I am looking into ways to create a Jupyterlab extension that will provide a new tab in the Jupyterlab left area to explore and load remote Zarr datasets. One possibility might be to use the [jupyterlab-data-explorer](https://github.com/jupyterlab/jupyterlab-data-explorer), however it is not clear to me that this will work with remote datasets out of the box. It might though with some coaxing. The other option is building an entirely new Jupyterlab extension so that this works exactly like we want it to work. [Building Jupyterlab extensions](https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html#extension-tutorial) is not super difficult but it would require enough of a time investment that I do not want to start down this road before pinging on this community for a discussion about best ways forward. Has anyone looked into making this happen? Any thoughts, suggestions, or solutions? Any input would be greatly appreciated!

**Comment by jsignell** [comment]
If you are using intake, then the [intake GUI](https://intake.readthedocs.io/en/latest/gui.html) aspires to fill this role. It'll get a lot closer once it incorporates [dfviz](https://dfviz.readthedocs.io/en/latest/) and xrviz(https://xrviz.readthedocs.io/en/latest/). Both of those should be integrated within the next month.

@martindurant in case you have anything to add :)

**Comment by martindurant** [comment]
Note that the jupyterlab data explorer is also discussing integrating intake ([issue](https://github.com/jupyterlab/jupyterlab-data-explorer/issues/51)), but that would give you the selection of datasets and metadata, not visualisation - because that requires data processing.

**Comment by jsignell** [comment]
It occurs to me that the new html_repr in xarray might already fill a lot of the needs.

**Comment by tjcrone** [comment]
@jsignell the new html xarray repr is awesome! Just looking at it for the first time now. Very cool. Also intake and the intake gui are fantastic, and it might be worth including the intake gui in the extension if there is a way to do that. What I really think would be cool is a Jupyterlab extension that adds a new left panel, incorporating possibly the Intake gui, but also having a list of datasets that are pre-populated from a Pangeo dataset registry. Functionality to search and slice, sortof like ERDDAP would be very cool too. I know this sounds ambitious but this is the sort of thing that we have been discussing in Pangeo for a long time. I wonder if it might be time to push for this.

**Comment by jsignell** [comment]
> incorporating possibly the Intake gui, but also having a list of datasets that are pre-populated from a Pangeo dataset registry

It is very easy to pre-populate the intake gui. 

I think the biggest chunk of work would be to put a panel object (which the intake gui is based on) in a new jupyterlab area. This [doesn't work right now](https://github.com/pyviz/pyviz_comms/issues/3), but it could probably be made to work.

Another option would be to write a custom jupyterlab extension for the intake GUI. This might be fairly easy (similar to the dask dashboard).

**Comment by tjcrone** [comment]
The Pangeo extension could be as simple as a notebook code injector that draws from a Pangeo dataset registry and pre-populates the Intake gui in a notebook in the main Jupyterlab window. It could be fancier perhaps and have an ERDDAP-like search capability to slice and dice and then inject code or datasets directly into the working notebook to make it ultra easy for Pangeo users to find the data they need and load them chunked in ways that will work well using Dask and Xarray. Because I am working on the OOI-Pangeo system, I'm looking for ways to make this very large and complex data store easier for users to access and use, but we definitely want something that would be general purpose.

**Comment by rabernat** [comment]
What you are describing is essentially the eWaterCycle jupyterlab_thredds extension
https://github.com/eWaterCycle/jupyterlab_thredds

![gif](https://github.com/eWaterCycle/jupyterlab_thredds/raw/master/jupyterlab_thredds.gif)

I have always loved that tool and thought it would be awesome to expand it / integrate it more with Pangeo.

**Comment by martindurant** [comment]
That was the very impetus behind the intake GUI. Note that the jlab-only version discussed would do this easily, but also you can embed the panel-viz one already with jlab-widget sidecar I think, or wait for panel to be totally ipywidget compatible.
