### ISSUE TITLE
Join as member of pangeo-data

### ISSUE THREAD

**Issue by bwhite-envfluids** [pangeo-data/pangeo#742]
Can you add me to the list of pangeo users so I can access pangeo-data? Was having difficulty parsing how to join. Thanks!

My information (following the format in 'people.yml' file):

- first_name: Brian
  last_name: White
  institution: UNC Chapel Hill
  website: http://fluids.web.unc.edu  
  email: bwhite@unc.edu
  github: bwhite-envfluids
  tags:
    - physical oceanography
    - climate
    - environmental fluid dynamics

**Comment by rabernat** [comment]
Hi @bwhite-envfluids - thanks a lot for this message! We are excited to see your interest in Pangeo (and sorry for the slow reply here).

There is no official list of pangeo users (for now). If you want to use one of our cloud-based jupyterhubs, just head over to https://ocean.pangeo.io/!

If you want to learn more about the project and share your use cases, feel free to stop by one of our weekly meetings:
http://pangeo.io/meeting-notes.html
