### ISSUE TITLE
Create Binder example with JupyterLab auto-start

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#743]
I would like to create a binder example to show off integration between dask-kubernetes and dask-labextension.  My goal is to make an example where the user doesn't touch dask-kubernetes at all, it just starts up in adaptive mode automatically.

I could use help answering a few questions:

1.  What is a good recent example to work from?  The last time I did this was a year or so ago. (cc @jhamman @scottyhq) 
2.  How can I set the "auto-start Dask" option with configuration?  (cc @ian-r-rose)

**Comment by rabernat** [comment]
A recent binder configuration is here:
https://github.com/pangeo-data/pangeo-cmip6-examples

Most of our binders now use a Dockerfile with the onbuild machinery set up by @yuvipanda, which allows us to build on top of our base containers from [pangeo stacks](https://pangeo-data.github.io/pangeo-stacks/).

For auto-starting dask, if I had to hack this myself, I would use Binder's [start script](https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts) option to launch the cluster.

**Comment by ian-r-rose** [comment]
The "Auto-start dask" option from `dask-labextension` can be enabled by distributing a JupyterLab settings file in the repository. An example of this is shown [here](https://github.com/ian-r-rose/binder-workspace-demo#custom-settings).

If you have a repo that you are working on that you can point me towards, I could make a PR against it.

**Comment by mrocklin** [comment]
@ian-r-rose https://github.com/mrocklin/dask-auto-start-example
