### ISSUE TITLE
Google sign-up on Pangeo discourse site appears to be broken

### ISSUE THREAD

**Issue by shoyer** [pangeo-data/pangeo#745]
When click on signing up with Google, I see this error page:
![image](https://user-images.githubusercontent.com/1217238/69027563-35226100-0984-11ea-8730-d5269b577751.png)

**Comment by rabernat** [comment]
Thanks for the tip Stephan. I tried fixing it by adding the full URI for the callback:

![image](https://user-images.githubusercontent.com/1197350/69116407-535a9080-0a5a-11ea-918e-bb9a7f1d3e35.png)

I think this fixed it.
