### ISSUE TITLE
Looking for 5-15s video clip of Pangeo workloads

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#747]
Hi all,

I'm putting together an introduction to Dask video.  The current state is here: https://youtu.be/nnndxbr_Xq4

For this video I would like to include a montage of a variety of different use cases, spending 5-15s on each.  I would like to include a couple such use cases from the Pangeo community, maybe for 

1.  simulation output in the geosciences
2.  analysis of satellite imagery

Does anyone have visually attractive video clips or gifs in either of these topics?

**Comment by rabernat** [comment]
Matt thanks for raising this issue. It's something we've wanted to do for Pangeo for a while. This is a good excuse for us to get it done.

Can you be a bit more verbose about the requirements here? What should the video clips or gifs show? Just generic attractive videos of simulation / satellite data? Or screencasts of someone executing notebooks cells?

We have many notebooks, and we have many pretty pictures. But we might not have the screencast you're looking for already made.

**Comment by Thomas-Moore-Creative** [comment]
Hey Matt, happy to help if I can.  

We have a fledgling 5D reanalysis output from a coupled atmospheric & ocean model with data assimilation over the past 50+ years.  While we are having some specific Dask issues on our HPC system that might not make for a good video ( https://discourse.pangeo.io/t/very-big-memory-load-when-using-fast-parallel-file-system/160 ) we could do some ensemble mean & spread calculations with spatial reductions and rolling mean window taking a single ~2TB ocean 5D variable to a small computed timeseries that might be used to answer a specific scientific question?

Not clear if you'd like an "HPC" example or exactly what you'd like to see in the frame over the 5-15 seconds?

**Comment by mrocklin** [comment]
> Can you be a bit more verbose about the requirements here? What should the video clips or gifs show? Just generic attractive videos of simulation / satellite data? Or screencasts of someone executing notebooks cells?

I don't have strict requirements here.  It would be nice if the screencast was genuinely using Dask in some way.  This might be a Jupyter notebook output, sure, it might be something else as well.  i asked the same question of the Napari folks and got [this video](https://napari.org/tutorials/resources/dask2.gif), which I think is nice.  Ideally this is something that if one of your colleagues saw it would think "hmm, that looks interesting, I should give this Dask thing a shot".

**Comment by Thomas-Moore-Creative** [comment]
And @dougiesquire - I see you have some great looking Dask visuals flashing across your screen?

**Comment by rabernat** [comment]
Here is one I have used often:

https://drive.google.com/open?id=1IswZ5dQdk-2mm2z7iUPZ1ag63crkCUxQ

**Comment by rabernat** [comment]
Also just created this:
https://vimeo.com/380061373

**Comment by mrocklin** [comment]
Thanks all.  A first cut of this is in
https://www.youtube.com/watch?v=KyZ722VO15g
