### ISSUE TITLE
The long-tailed distribution of zarr read times from GCS

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#749]
Just posting a technical issue here for discussion. I have been doing some benchmarking experiments to understand how much throughput we can get from Google Cloud Storage to dask clusters using zarr. The results are promising, but I've also noticed some interesting behavior. 

In the figure below, I load a 1 TB dataset using 90 dask workers, with chunks of roughly 150 MB. The majority of the reads take less than a second. But there is clearly a "long tail" of reads that can take much longer. I found a handy trick in the dashboard; if I refresh the status page after the job has completed, I can see the tasks sorted by their run time, almost like a histogram. The figure below is an example. Some of the reads take up to 40s, and in general, towards the end of the computation, most of the cluster is sitting idle while we wait for the final stragglers to finish their reads. This hurts our parallel scaling.

<img width="1038" alt="zarr_dask_tasks-2" src="https://user-images.githubusercontent.com/1197350/70721069-f8b3fd80-1cc2-11ea-8bcf-5a66fa630bc6.png">

One way around this is to just use larger total array sizes, such that the total run time is much larger and these straggles matter less. But then you bump up against new sources of overhead to making the dask graph too large.

It would be great if someone with a deeper understanding of cloud storage could help us understand: is this normal, expected behavior with cloud storage? Or is there something we can do within zarr / dask to eliminate this long tail?

cc @lila, who could maybe connect us to some Google Cloud Storage engineers.

**Comment by lila** [comment]
can you provide some more information on the number and type of the nodes in the dask cluster?  Are you sure you are not saturating the bandwidth of any of the nodes?  (check the GCE monitoring page when you run the tests to see if any of the nodes saturate the network).

It looks like (from https://github.com/rabernat/pangeo-throughput-benchmarks/blob/master/plot_results.ipynb ) that you are getting about 16GBytes / sec with 175 processes.  

I know the cern folks for kubecon reached almost 200GBytes/sec to their GKE cluster reading 70TB of data across 25k cores.    see details https://indico.cern.ch/event/773049/contributions/3581373/attachments/1939661/3215578/chephiggs.pdf 

![Screenshot 2019-12-17 at 1 17 05 PM](https://user-images.githubusercontent.com/99220/71029611-60a88080-20d5-11ea-9b89-415216ddb155.png)

**Comment by domZippilli** [comment]
Hey @rabernat, another Googler here, I work with @lila. I'm a specialist solutions architect, where that specialty is GCS.

One quick note: the above graph's caption mentions Gbps-per-core, but this Stackdriver graph shows GB/s. I see people get mixed up by this a lot.

On the long tail question -- it's normal for TTFB to have a long tail, though not *that* long. On 150MB transfers (excellent size for chunks btw) it shouldn't be very noticeable. One question I'd have is, what kind of bucket are you reading from? Regional/Dual-Regional/Multi-Regional, specifically?

**Comment by rabernat** [comment]
Thanks for the replies!

> can you provide some more information on the number and type of the nodes in the dask cluster?

This is a bit tricky because there are several layers of abstraction involved. Each dask worker has two threads. The dask workers run in a kubernetes pod. The kubernetes pods are assigned to nodes in a gke cluster. The dask nodepool uses `n1-highmem-4` nodes. It looks like there are two workers getting packed into each node.

> I know the cern folks for kubecon reached almost 200GBytes/sec to their GKE cluster reading 70TB of data across 25k cores.

If my scaling holds, I should be able to get that same throughput with only 2k cores, an order of magnitude improvement. (But I'm not doing any computing, just load and discard.)

> this Stackdriver graph shows GB/s.

Can you explain how I might generate such a graph of my own?

> One question I'd have is, what kind of bucket are you reading from? Regional/Dual-Regional/Multi-Regional, specifically?

We are reading from a regional bucket (`us-central`) into a bucket in `us-central1-b`.

**Comment by domZippilli** [comment]
Hey Ryan,

Good to hear it's a regional bucket. Should be tighter tail latency within that region for readers. 

As far as creating that chart... I get that and a related question so often, I decided to put my answer to you in a [blog post](https://medium.com/@dzippilli/monitoring-bytes-sent-from-google-cloud-storage-buckets-e5324660111c). HTH!

From an engineering, GCS diagnostic perspective, I could probably help you. I'll touch base with you via email.

**Comment by rabernat** [comment]
Here's another one:

![image](https://user-images.githubusercontent.com/1197350/76077597-01893800-5f6f-11ea-86bd-83796217120f.png)

Thanks for sharing the blog post @domZippilli - next week I should have some bandwidth (no pun intended) to revive this investigation. I'll follow up via email.
