### ISSUE TITLE
Server times out while we're working on it

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#750]
While sitting and running stuff in a notebook on Jupyterlab, the cluster might time out, at which point we get a window saying "server not running" and we have to go and restart the server in a separate window. Is there some way to tell jupyterhub not to kick us out while we're in the middle of working? Should this somehow be configured through the `hub: cull` configuration variables? How would I set those to be minimally agressive?

**Comment by hmkhatri** [comment]
I am facing the same issue. Is there a way to switch off the automatic timeout?
