### ISSUE TITLE
Add WeatherBench repository to pangeo-data

### ISSUE THREAD

**Issue by raspstephan** [pangeo-data/pangeo#751]
Hi everyone,
we have been working on a data-driven weather forecasting benchmark over the last months which is now almost ready. You can see the project here: https://github.com/raspstephan/weather-benchmark

I was wondering whether it could be nice to transfer the project to the `pangeo-data` organization. This would make it a little more official and hopefully foster collaborations.

I think this project could tie in well with the efforts of the ML working group. For starters the dataset will be hosted on a traditional data repository as NetCDF files for download only but we are actively looking to store it on the cloud as well. 

Let me know if this sounds good to you and I will transfer the repo.

Stephan

**Comment by raspstephan** [comment]
@rabernat @jhamman What do you think?

**Comment by rabernat** [comment]
Yes sounds great to me! Thanks for your persistence Stephan. I’m back at work Jan 8 and can work on the transfer then. Maybe @jhamman can tackle it sooner.

**Comment by raspstephan** [comment]
Thanks, no rush. The project is now located at https://github.com/ai4environment/WeatherBench. I am already a member of pangeo-data, so I can transfer the repo. However I would like to keep admin rights to the repo. Maybe you could create a new team (eg pangeo-ml) with me in it and admin rights to the WeatherBench repo?

**Comment by jhamman** [comment]
+1 from me. @raspstephan, go ahead and transfer the repo. I'll set up a ML team here shortly.

**Comment by raspstephan** [comment]
I transferred the repo. I think one of you now just needs to give the pangeo-ml group admin access to the repo.
BTW, I think at some point we should talk about how we can extend this run on the cloud. Maybe in an upcoming ML working group call.

**Comment by jhamman** [comment]
@raspstephan - the @pangeo-data/pangeo-ml group now has admin access there. I'm going to close this now but I agree, we should discuss next week how to use pangeo's cloud infrastructure to extend this project.
