### ISSUE TITLE
Deployment page is out of date

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#752]
http://pangeo.io/deployments.html

We need someone to update this with the latest information about our existing hubs.

**Comment by green-juniper** [comment]
I'd be happy to help with this. How would I get the latest info on the hubs? I noticed some of the deployments weren't working, but I'm not sure if that's due to lack of access on my end or if the deployment is no longer operational.

**Comment by guillaumeeb** [comment]
@green-juniper I'm not sure where the latest information can be found. Maybe someone activly working on the cloud environment could give some hints?

cc @TomAugspurger @jhamman

**Comment by TomAugspurger** [comment]
I think https://github.com/pangeo-data/pangeo-cloud-federation is the source for our hubs. Right now thats

* hub.pangeo.io (gcp)
* ocean.pangeo.io (gcp)
* hydro.pangeo.io (gcp)
* aws-uswest2.pangeo.io (aws)
* ooi.pangeo.io (azure)

In https://github.com/pangeo-data/pangeo-cloud-federation/issues/599 we're talking about consolidating the GCP hubs (ocean, hydro, hub) down to one.
