### ISSUE TITLE
Speeding up the creation of new nodes

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#753]
I have been working to speed up the creation of new nodes when they are required for new single user pods or for Dask worker pods. One thing I have noticed is that because we are pulling our primary image from within the same region (i.e. datacenter), image layer downloads are very fast, and the vast majority of time to start a new node comes from the time it takes to extract layers in the image. Because we have a staging and a prod Pangeo deployment, two sets of images are downloaded to the same machine (leading to complaints about a conflict), and the extraction of two sets of layers happen simultaneously, also on the same machine. The process can take longer than 20 minutes, after which time the single user pod will timeout, and if the user doesn't try to log in again soon after the node becomes available, the node is scaled down. Very frustrating for users, most of whom are not able to monitor the cluster in detail and therefore do not know what is happening.

By deleting the staging deployment I was able to speed up the process. Here is a typical set of elapsed times (MM:SS) for a user log in that triggers a scale up since deleting the staging deployment:

00:00 spawn trigger scale up
03:41 new node provisioned, init container 1 started (image-pull-singleuser)
16:54 single user image pulled, init container 2 started (image-pull-metadata-block)
17:01 continuous image puller done, server is ready

So now, usually, after waiting nearly 20 minutes, a user can log in to a new node, but still a really long wait. What I have learned during my investigation is that the majority of this wait time is the single user image pull, and the majority of that time appears to be the image extraction. Pulling and extracting a new image for every node seems like a waste of time, considering that the image has already been downloaded and extracted on all the other nodes of the cluster. So here are a couple of potential solutions:

1) figure out how to get kubernetes to install an image on a new node using [save and load](https://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-using-a-repository)
2) figure out how to create a docker image with layers that are not compressed, so that extraction is faster

I'm not really sure if either of these are possibilities, but if we can figure out how to cut out the layer extraction step, new nodes both for Dask workers and for users should start up much much faster. Does anyone know if either of these are possible? Are there other potential solutions that I am not aware of? Thanks in advance for any ideas!

**Comment by sodre** [comment]
@tjcrone, I am working on benchmarking node start-up times for Dask, but I am fairly new to pangeo. 

Do you have a quick pointer to an environment.yml file that I could use to replicate/simulate your worker images?

**Comment by tjcrone** [comment]
@sodre, the Pangeo images are build using [hubploy](https://github.com/yuvipanda/hubploy) and [repo2docker](https://github.com/jupyter/repo2docker) from the files in [pangeo-cloud-federation](https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments). The images we are using for the OOI deployment are in an Azure Container Registry, and I am currently working with Azure engineers to enable anonymous pull access to our registry. I am hopeful that this will be set up today. When it is available, I will send a link so you can pull the image from ACR. Until then, you can try using [jupyter-repo2docker](https://repo2docker.readthedocs.io/en/latest/index.html) to build the image yourself:
```
jupyter-repo2docker --no-run --ref 18884f973301696e94e102a967ee34c0b348d245 https://github.com/pangeo-data/pangeo-cloud-federation
```

**Comment by sodre** [comment]
@tjcrone, thank you for the pointers.

I was able to build the base image using `jupyter-repo2docker` as you described, and the OOI binder image using straight `docker build`. Given the difference in image sizes, 1.8GB vs 7.3GB, I am going to investigate starting dask workers with the larger image, if that is incorrect please let me know. 

I'll reach out to you if I get good results.

**Comment by tjcrone** [comment]
@sodre, the images we are currently pulling are 1.8 GB in size. I am not sure why the binder image is larger, but we are not using that image. We use the 1.8 GB image.
