### ISSUE TITLE
GCE deployment scripts out of sync

### ISSUE THREAD

**Issue by patrickmineault** [pangeo-data/pangeo#755]
I've followed the guide here: https://github.com/pangeo-data/pangeo/blob/master/docs/setup_guides/cloud.rst, and ran into a similar issue to https://github.com/pangeo-data/pangeo-cloud-federation/issues/479. Since https://github.com/pangeo-data/pangeo-cloud-federation/pull/477, the secret-config.yaml files will not work with the latest helm charts. There's two easy solutions:

- Ship 3_deploy_helm.sh with a version that predates pull #477. I had good luck with    --version=19.03.05
- Update secret-config.yaml and the setup guide to reflect the new two token setup

Happy to take a stab at either, which solution would you prefer?

**Comment by tjcrone** [comment]
@patrickmineault, thank you for opening this issue. It would be great to have the setup guide updated. I think that the second option is preferred IMO. Thank you for helping out!

**Comment by guillaumeeb** [comment]
There is a duplicate issue in #773 where the discussion is more active.

@patrickmineault if you still want to update the guide, please do!
