### ISSUE TITLE
Dot product of two zarr stores slow with Dask

### ISSUE THREAD

**Issue by jsadler2** [pangeo-data/pangeo#756]
I am running a dot product using xarray/dask between two zarr data stores, `w.dot(v)`, and it is quite slow. 

- `w` has two coordinates - one has 11 chunks, the other 4. The data chunks are around 500 KB in size (so very small - altogether 60 MB)
- `v` originally had three coordinates. I stack two of those so there are only 2 coordinates. The data chunks are about 100 MB in size (altogether about 2.8 GB)

Here is the [dask performance report](https://nbviewer.jupyter.org/github/jsadler2/testing/blob/master/dask_report_dot_product.html) from the operation.

It took about 22 minutes to perform the dot product.

@mrocklin pointed me to this issue: https://github.com/dask/dask/issues/2225 which makes me think I should rechunk along the axes over which the dot product is performed.

cc @wdwatkins

**Comment by rabernat** [comment]
Just to simplify this problem, can we take zarr out of the equation? If you create synthetic dask data with the same chunk structure, is the performance the same?

**Comment by mrocklin** [comment]
Looking at the performance report, this is spending all of its time in `einsum`.  So neither zarr nor communication are the bottleneck.  You are strictly bound by on-node computation here.

There are *many* chunks here, far more than something like 11 by 4.  

You might want to verify that you're using a single-threaded blas implementation along with Dask.  See https://stackoverflow.com/questions/52895211/how-do-dask-threads-interact-with-openblas-mkl or https://stackoverflow.com/questions/45086246/too-many-memory-regions-error-with-dask/45086247#45086247

**Comment by jsadler2** [comment]
>There are many chunks here, far more than something like 11 by 4.

Yes. There is this warning: 
```dask/array/einsumfuncs.py:241: PerformanceWarning: Increasing number of chunks by factor of 17```

**Comment by jsadler2** [comment]
>You might want to verify that you're using a single-threaded blas implementation along with Dask.

Okay. I will try that.
