### ISSUE TITLE
Mysterious Killed Workers Error

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo#757]
Transferring this over from [dask/issue5868](https://github.com/dask/dask/issues/5868) as per @rabernat s recommendation.

I am encountering problems when using dask to analyze CMIP6 data on [ocean.pangeo.io](ocean.pangeo.io).

I have had similar problems popping up in a variety of tasks, but I was able to isolate one case today (EDIT: or so I thought, see below). At the very least this is a minimal code example that has failed several times for me.

When I execute the following code in a notebook on ocean.pangeo.io

```
import xarray as xr
import matplotlib.pyplot as plt

# this should be replaced with the details of a new kubecluster
from dask.distributed import Client
client = Client("tcp://10.32.2.135:36151")

path = 'gs://cmip6/ScenarioMIP/MOHC/UKESM1-0-LL/ssp585/r1i1p1f2/Omon/uo/gn/'

import fsspec
ds = xr.open_zarr(fsspec.get_mapper(path), consolidated=True)
da = ds.uo
da.mean([di for di in da.dims if di != 'time']).load()
```

I often (see below) get an error at some point, that some workers are killed.

```
distributed.client - WARNING - Couldn't gather 14 keys, rescheduling {"('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 34)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 38)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 14)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 46)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 72)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 18)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 81)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 26)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 32)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 58)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 47)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 27)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 40)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 17)": ()}
distributed.client - WARNING - Couldn't gather 16 keys, rescheduling {"('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 38)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 68)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 57)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 60)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 26)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 64)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 16)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 22)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 25)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 29)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 76)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 46)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 67)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 45)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 36)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 37)": ()}
distributed.client - WARNING - Couldn't gather 4 keys, rescheduling {"('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 82)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 63)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 12)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 84)": ()}
distributed.client - WARNING - Couldn't gather 30 keys, rescheduling {"('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 34)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 7)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 38)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 80)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 50)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 31)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 18)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 15)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 77)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 1)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 64)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 47)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 16)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 78)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 29)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 44)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 83)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 79)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 30)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 46)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 65)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 49)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 62)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 66)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 45)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 27)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 41)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 40)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 37)": (), "('mean_agg-aggregate-bf048e4378819584ad36ec07f170c773', 3)": ()}
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<ipython-input-10-c6abd58150d7> in <module>
      4 ds = xr.open_zarr(fsspec.get_mapper(path), consolidated=True)
      5 da = ds.uo
----> 6 da.mean([di for di in da.dims if di != 'time']).load()

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/dataarray.py in load(self, **kwargs)
    809         dask.array.compute
    810         """
--> 811         ds = self._to_temp_dataset().load(**kwargs)
    812         new = self._from_temp_dataset(ds)
    813         self._variable = new._variable

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/dataset.py in load(self, **kwargs)
    647 
    648             # evaluate all the dask arrays simultaneously
--> 649             evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    650 
    651             for k, data in zip(lazy_data, evaluated_data):

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2571                     should_rejoin = False
   2572             try:
-> 2573                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2574             finally:
   2575                 for f in futures.values():

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1871                 direct=direct,
   1872                 local_worker=local_worker,
-> 1873                 asynchronous=asynchronous,
   1874             )
   1875 

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    766         else:
    767             return sync(
--> 768                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    769             )
    770 

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332     if error[0]:
    333         typ, exc, tb = error[0]
--> 334         raise exc.with_traceback(tb)
    335     else:
    336         return result[0]

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/utils.py in f()
    316             if callback_timeout is not None:
    317                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 318             result[0] = yield future
    319         except Exception as exc:
    320             error[0] = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1727                             exc = CancelledError(key)
   1728                         else:
-> 1729                             raise exception.with_traceback(traceback)
   1730                         raise exc
   1731                     if errors == "skip":

KilledWorker: ("('zarr-0b5b4c291486f7719b8838d4f61ec999', 37, 0, 0, 0)", <Worker 'tcp://10.32.35.48:38757', memory: 0, processing: 2>)
```

If I execute this code without connecting to the dask distributed cluster it **always** works fine (but takes very long!). 

The frustrating thing about this behaviour is that it does not always occur. I just shut down the dask cluster, restarted the notebook and it went through fine. 
After doing that a couple of times, the error appears again. I have not found a way to reliably reproduce this behaviour. 
In more realistic workflows this makes working with the CMIP6 archive almost impossible for me (I have done some work by not invoking dask at all, and letting it run overnight. But that is a bit ridiculous).

So far I have tried to rechunk the dataset, but that did not change the error. 
I am curious how to dig deeper into what is happening here, since this has been messing with my science on many occasions.

Apologies if this is a bit fuzzy in the description, but I am at this point quite confused as to what is happening. Would appreciate any kind of pointer.

cc: @jhamman 

EDIT: @rabernat tested the code and found no error. Could there be a configuration that is custom to my account that messes with things? I even tried restarting my server, which should reset to a clean environment?

**Comment by RPrudden** [comment]
I had a (possibly) similar [issue](https://github.com/dask/distributed/issues/2164) a while back, but didn't manage to get to the bottom of it. My best guess was that it was a memory issue, and I've sometimes been able to avoid it by making my code more parallel. 

I know this isn't a very useful answer, hopefully others will have some ideas!

**Comment by jbusecke** [comment]
It literally seems to have gone away overnight...I am currently running on 6 workers and am not seeing a single warning/error. I did log in with a different email through globus (I have both my princeton and columbia email linked), could that affect the deployment?

I would exclude the memory issue at this point, because it seems to run fine without rechunking now (and did occasionally yesterday).

I was also using many workers yesterday (adaptive scaling from 2 to 30) in order to deal with the high-resolution GFDL model. Could that have an effect?

Another detail from yesterday, it seemed that these killed workers were only happening after several warnings were displayed and operations were retried, perhaps this was an issue with the data storage being funky? Is there a way to check integrity on a very basic level to exclude that possibility?


Just trying to outline all the circumstances in case other people run into this. 

For now I am super happy it works. I have to mention how absolutely amazing this whole system is. I am literally crunching TB of data on a phone, while riding on a train to NJ. Pangeo rocks! Thanks to everyone.

**Comment by jbusecke** [comment]
Oh noooo, now its doing it again...

But I might have a better idea how to make it fail...Currently I only experience this when using **adaptive scaling** on the dask clusters.

I am able to run this without any warnings on 10 workers (which is pretty uneconomical use of the computing obviously)...

For testing I have used a heavily variable cluster (min 1 worker, max 10), which leads to tons of the reschedule warnings (see above)  and eventual failure. 

If I use a cluster with 4 fixed workers, it executes without error and is also much faster. 

Could there be a bug in the way adaptive workers are spawned? If anybody has a few minutes  it would be lovely if you could test this on another account.

**Comment by jbusecke** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Will take a look later today :)

**Comment by willirath** [comment]
From using adaptivity with Dask-jobqueue, I’ve gained the impression that there’s some race condition allowing for workers to shut down before they have really released their data. This could be fixed by slowing down shutting down via the `wait_count` arg of https://docs.dask.org/en/latest/setup/adaptive.html#distributed.deploy.Adaptive <https://docs.dask.org/en/latest/setup/adaptive.html#distributed.deploy.Adaptive>.

Default is that workers considered obsolete are killed after `interval * wait_count` with interval=1000ms and wait_count=3. Try setting wait_count to 10?

**Comment by jbusecke** [comment]
>  I’ve gained the impression that there’s some race condition allowing for workers to shut down before they have really released their data.

That seems like a plausible explanation, why this was so hard to pin down. Thx Willi.

I have tested this some more with synthetic data for the above example

```
import dask.array as dsa

da =xr.DataArray(dsa.random.random(size=(500,200, 400, 1000)), dims=['x', 'y', 'lev', 'time'])
da.max([di for di in da.dims if di != 'time']).load()
```

I have had this error out, but not as consistently as the test with the cloud data (perhaps that is due to the comparably long read times from the cloud storage + the behaviour @willirath outlined). It seems that if the array is large enough, it will eventually error out.

**Comment by rabernat** [comment]
@jbusecke - did you try playing around with with scheduler options @willirath suggested? Did they make any difference?

**Comment by jbusecke** [comment]
I am not sure how to modify these on ocean.pangeo.io

**Comment by jbusecke** [comment]
Oh wait, can I just change it in the cluster object. Ill try that now.

**Comment by willirath** [comment]
cluster.adapt(minimum=1, maximum=10, interval=“1s", wait_count=10)

**Comment by jbusecke** [comment]
Sorry if this is a dumb question: How to I get the `cluster` object? I only have a `client`.

**Comment by willirath** [comment]
Not sure. Create the Kubecluster in the notebook? But there probably also is a cluster attribute attached to the client.

**Comment by jbusecke** [comment]
I have tried this: 
```
from dask_kubernetes import KubeCluster
from dask.distributed import Client

cluster = KubeCluster()
cluster.adapt(minimum=1, maximum=10, interval='1s', wait_count=10)
client = Client(cluster)
```

which seems to work (still running atm), but it doesnt actually scale. It just runs on 1 worker.

**Comment by jbusecke** [comment]
Oh now it did scale. And it seems to work. I ran it a couple of times and could not see the error.

Ran it with defaults as a comparison: 
```

cluster = KubeCluster()
cluster.adapt(minimum=1, maximum=25)
client = Client(cluster)
```

which errors out. Seems like you got it @willirath.

**Comment by jbusecke** [comment]
is this a setting that should be changed in the dask defaults or in the pangeo deployment?

**Comment by rabernat** [comment]
The config is here: https://github.com/pangeo-data/pangeo-stacks/blob/master/base-notebook/binder/dask_config.yaml

We would love to get a pull-request to update these to better defaults!

**Comment by willirath** [comment]
Not sure this can be solved with dask.config. The adaptive defaults seem rather hard coded: https://github.com/dask/distributed/search?q=wait_count&unscoped_q=wait_count <https://github.com/dask/distributed/search?q=wait_count&unscoped_q=wait_count>

**Comment by rabernat** [comment]
Can we open an issue in distributed then? It seems like these parameters really need to match the properties of the deployment, so they should be customizable in a config file. We don't want to burden end users with this soft of detail.

**Comment by jbusecke** [comment]
Should I open that over there? Or does anyone else (more versed in dask) want to do it?

I think this should be a fairly high priority since wider adoption of adaptive scaling could make the use of resources a lot more efficient?

**Comment by rabernat** [comment]
@willirath seems to know the most about this, so hopefully we can persuade him to open the issue! 😉

**Comment by willirath** [comment]
Opened.

**Comment by TomAugspurger** [comment]
This is potentially the same root cause as https://github.com/dask/distributed/issues/1674. I spent a few hours yesterday working on Rich's example. I think I'm making some progress, but no concrete solutions yet. I'll have more time to look into these today.

**Comment by TomAugspurger** [comment]
I tried this a few times on https://github.com/TomAugspurger/distributed-memory-pressure/blob/master/test.ipynb (binder: http://binder.pangeo.io/v2/gh/TomAugspurger/distributed-memory-pressure/master) and didn't see any errors. Hopefully https://github.com/dask/distributed/pull/3455 resolved it.

**Comment by jbusecke** [comment]
Now that [dask/distributed#3509](https://github.com/dask/distributed/pull/3509) is merged, can we adjust the settings in the pangeo deployments? Pinging @willirath.

**Comment by TomAugspurger** [comment]
FYI, you can adjust them yourself by setting those in your dask config. We'll need distributed>=2.13 first though.

**Comment by jbusecke** [comment]
Is that possible also for the workers on ocean.pangeo.io? Or just for a local deployment? 
Either way I think that it would be nice to change the default values, so that users can avoid problems with adaptive scaling.

> We'll need distributed>=2.13 first though

Ah, good to know. I was trying to update/add a few things on ocean.pangeo.io, perhaps we can add the newest distributed version aswell.

**Comment by TomAugspurger** [comment]
I'm also trying to update ocean.pangeo.io right now, and it's not going well 😄 https://github.com/pangeo-data/pangeo-cloud-federation.

You'll want to verify, but the config should be read locally when you start the scheduler.

**Comment by jbusecke** [comment]
So maybe Ill hold off for now until the update works, to not add even more loose strings? I am still very new to the behind the scenes of these deployments...is [pangeo-data/pangeo-stacks-dev/#2](https://github.com/pangeo-data/pangeo-stacks-dev/issues/2) the right issue to track for this?

**Comment by TomAugspurger** [comment]
Perhaps... I'm still not sure how best to manage environments for something like ocean.pangeo.io. If some users have experiments that require specific versions of packages, then upgrading may cause breakages.

It seems like we would want to provide users the option to select an image (with specific versions of packages) to ensure we don't break their code.

**Comment by jbusecke** [comment]
That would be a dream! If I could have the choice of my own customized image, this would solve a lot of issues for me right now. 
Regarding the breaking versions: Would it be possible to 'version' the images (e.g. for breaking xarray releases)? But I guess that would lead to a mess pretty quickly. Just a few thoughts.

**Comment by TomAugspurger** [comment]
That might be possible.  This is all controlled at https://github.com/pangeo-data/pangeo-cloud-federation/blob/2322bc516119fd98bb8afb195b2be99477661227/deployments/ocean/config/common.yaml#L39-L69

Right now, ocean provides a list of container options. It might be possible to also select an image, or provide a field for user-provided images (so you could have one per xarray version).

**Comment by TomNicholas** [comment]
Just commenting to say that I was having this same issue for a long time (I was trying to do something similar to Julius, using xarray.open_mfdataset to open hundreds of netCDF files), but after updating to dask v2.30.0 and dask-labextension v3.0.0 it seems to be working now!
