### ISSUE TITLE
Error running Re-chunking MUR SST Zarr dataset on Pangeo hub using shared filesystem

### ISSUE THREAD

**Issue by abarciauskas-bgse** [pangeo-data/pangeo#765]
Cross-posting with https://discourse.pangeo.io/t/error-running-re-chunking-mur-sst-zarr-dataset-on-pangeo-hub-using-shared-filesystem/533

I am looking to rechunk the MUR SST dataset which is currently published to AWS public datasets in Zarr format, using a chunk configuration of {‘time’: 5, ‘lat’: 1799, ‘lon’: 3600} to something greater in the time dimension. I am planning to test 60 x 1799 x 3600, 180 x 1023 x 2047 and 379 x 439 x 360.

If possible, I would like to do this using an existing Pangeo hub, since these resources are already part of the Pangeo efforts. However, I have run into an error using the shared file system which appears on at least 1 of N dask workers:

`ValueError: array not found at path 'mask'`

When I inspect the worker logs, it's usually just 1 of N workers who see this error, which makes me think there is latency in the NFS mount consistency. And when I look at the files on each worker, they look the same. Could this be a race time condition?

I'm using https://aws-uswest2.pangeo.io/, with 4 workers configured to share the volume mount and each allocated 62GB memory (since 64 is the max per instance available, as I understand)

The notebook with the error and corresponding dask config file are here: https://gist.github.com/abarciauskas-bgse/4a6cdda3bbaa29da80aa4e10d5532b45

**Comment by rabernat** [comment]
@abarciauskas-bgse - thanks for this useful post.

Without diving in too deeply, my quick recommendation would be to avoid the shared filesystem entirely. You want to stream this calculation directly from one S3 location to the next.

Something like this:
```
# need credentials to write
fs = s3fs.S3FileSystem(key=key, secret=secret)
source = fs.get_mapper('/bucket/path/to/mur/original.zarr')
target = fs.get_mapper('/bucket/path/to/mur/rechunked.zarr')
ds = xr.open_zarr(source)
ds = ds.chunk(**new_chunk_scheme)
ds.to_zarr(target)
```

This should work just fine in distributed mode.

My feeling is that these shared NFS-based filesystems are a crutch. We should prefer to use the cloud-native mechanism for reading / writing data, i.e. s3.

**Comment by abarciauskas-bgse** [comment]
Thanks @rabernat, I have tried this approach in the past and it was pretty slow compared to using a local filesystem (if I recall correctly, prohibitively slow). But I will try again and let you know what experience more specifically.

For converting large datasets (to Zarr or performing other operations) it would be nice if a shared file system were an option if it is more performant than reading anD writing to S3.

**Comment by rsignell-usgs** [comment]
Would SageMaker + dask-cloudprovider + Lustre be a solution?
https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-sagemaker-works-with-amazon-fsx-lustre-amazon-efs-model-training/
ping @zflamig

**Comment by zflamig** [comment]
Yeah! I would suggest using two Lustre instances. Have one that is read-only which imports the public dataset you already have, and then have another which you will use to store the results which will get saved to S3 once you are done. You'll want to make them both big enough to hold the entire dataset. For the read-only once since you are hydrating from an S3 bucket it may be preferable to make it larger too so that you get better performance on the hydration step. 

There is some discussion of this here: https://aws.amazon.com/blogs/storage/using-amazon-fsx-for-lustre-for-genomics-workflows-on-aws/

Note that the FSx team released new features, but I think you can use the "scratch 2" option.

**Comment by abarciauskas-bgse** [comment]
Using a local cluster with FSx is my current implementation.

The reason to use Pangeo is so we don't have to secure additional funding.

**Comment by rabernat** [comment]
> I have tried this approach in the past and it was pretty slow compared to using a local filesystem

This does not match with my personal experience. Which part was slow? Reading? Writing? Computation? Direct S3 to S3 is the simplest possible architecture, so I'd be surprised if it was not performant. Are you sure you had your configuration right?

> I would suggest using two Lustre instances. Have one that is read-only which imports the public dataset you already have, and then have another which you will use to store the results which will get saved to S3 once you are done.

This just sounds like overkill. Zarr, dask, and s3fs are built for cloud-native operations on object stores. Let's use this issue to resolve any performance bottlenecks there, rather than adding further complexity by layering on top of Lustre.

**Comment by zflamig** [comment]
> > I would suggest using two Lustre instances. Have one that is read-only which imports the public dataset you already have, and then have another which you will use to store the results which will get saved to S3 once you are done.
> 
> This just sounds like overkill. Zarr, dask, and s3fs are built for cloud-native operations on object stores. Let's use this issue to resolve any performance bottlenecks there, rather than adding further complexity by layering on top of Lustre.

I think getting the performance to meet expectations is well worth the effort here. Just a note that in this setup, Lustre would replace s3fs. Its purpose is to get you a POSIX interface to a bucket. So the overall complexity increase isn't that large.

**Comment by abarciauskas-bgse** [comment]
Thanks @rabernat I will try the S3 to S3 approach. Using S3 as the file system to write to was an approach I tried a long time ago so I would not be surprised if my experience is different if I try it again given changes too my code since then.

I will also make sure to try the direct S3 to S3 approach although this does imply I have to put all the source netCDF files onto S3 which itself will take some time.

**Comment by rabernat** [comment]
> this does imply I have to put all the source netCDF files onto S3 which itself will take some time.

ah, ok so I misunderstood this part...I thought you were trying to transform the existing MUR S3 dataset to a new chunking scheme. Have you considered trying that, rather than going back to the netCDF files?

If you are dealing with netCDF files, I agree that the Lustre approach would offer major benefits.

**Comment by rsignell-usgs** [comment]
@zflamig , thanks for joining in here.  I'm going to check out that post about using Lustre for genomics workflows.

**Comment by abarciauskas-bgse** [comment]
@rabernat we have considered using the existing zarr store to re-chunk but I don't think it is possible given we are "chunking up" (creating larger chunks) and it doesn't appear this is supported. You get the error mentioned in https://github.com/pydata/xarray/issues/2300 

>NotImplementedError: Specified zarr chunks (63170,) would overlap multiple dask chunks ((63170, 63170, 63170, 63170, 63170, 63170, 63170, 63169),). This is not implemented in xarray yet.  Consider rechunking the data using `chunk()` or specifying different chunks in encoding.

**Comment by rabernat** [comment]
This seems like a bug. I'm going to look into it.

**Comment by abarciauskas-bgse** [comment]
Thanks @rabernat let me know if I can help

**Comment by rabernat** [comment]
@abarciauskas-bgse: I looked into this in https://github.com/pydata/xarray/issues/2300#issuecomment-598790404. I think I understand the problem and found a simple work around. Could you read that comment and let me know if it works?

I really think direct zarr s3 to zarr s3 is the way to go. I want to help make this work
