### ISSUE TITLE
Unable to use "Deploying Pangeo on the Cloud"

### ISSUE THREAD

**Issue by Boes-man** [pangeo-data/pangeo#773]
Hello
I am trying to install pangeo on my kubernetes cluster based on your guide but get the following error when running 3_deploy_helm.sh

./3_deploy_helm.sh 
"pangeo" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "pangeo" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Error: render error in "pangeo/charts/dask-gateway/templates/web-proxy-deployment.yaml": template: pangeo/charts/dask-gateway/templates/web-proxy-deployment.yaml:23:28: executing "pangeo/charts/dask-gateway/templates/web-proxy-deployment.yaml" at <include (print .Template.BasePath "/secret.yaml") .>: error calling include: template: pangeo/charts/dask-gateway/templates/secret.yaml:9:19: executing "pangeo/charts/dask-gateway/templates/secret.yaml" at <required "gateway.proxyToken must be a 32 byte random string" .Values.gateway.proxyToken>: error calling required: gateway.proxyToken must be a 32 byte random string

Thanks

[secret_config.txt](https://github.com/pangeo-data/pangeo/files/4556374/secret_config.txt)
[jupyter_config.txt](https://github.com/pangeo-data/pangeo/files/4556375/jupyter_config.txt)

**Comment by scottyhq** [comment]
@Boes-man we're in the midst of some major changes adding dask-gateway currently (https://github.com/pangeo-data/helm-chart/pull/128), so the instructions are out of date for the latest pangeo helm chart version.

@TomAugspurger, @consideRatio, or @jhamman is there a way to fully disable dask-gateway? If not, going forward your secrets file will need some additional tokens:

````
pangeo:
  jupyterhub:
    proxy:
      secretToken: AAAAAAAAA
    auth:
      type: github
      github:
        clientId: "BBBBBBBB"
        clientSecret: CCCCCCCC
        callbackUrl: "https://myhub.io/hub/oauth_callback"
    hub:
      services:
        dask-gateway:
          #NOTE: same token used under dask-gateway
          apiToken: "DDDDDDDDD"
  dask-gateway:
    gateway:
      proxyToken: "EEEEEEEEEEE"
      auth:
        type: jupyterhub
        jupyterhub:
          apiToken: "DDDDDDDDD"
```

**Comment by TomAugspurger** [comment]
Not sure.

Some could probably be removed with something like

```
dask-gateway:
  gateway:
    auth:
      type: basic
```

but you might still need the jupyterhub service token.

**Comment by Boes-man** [comment]
Thanks @TomAugspurger @scottyhq I tried adding to my secrets yaml and playing with the versions but still getting an error, different one... sort of.

Error: render error in "pangeo/charts/jupyterhub/templates/proxy/deployment.yaml": template: pangeo/charts/jupyterhub/templates/proxy/deployment.yaml:26:32: executing "pangeo/charts/jupyterhub/templates/proxy/deployment.yaml" at <include (print $.Template.BasePath "/hub/secret.yaml") .>: error calling include: template: pangeo/charts/jupyterhub/templates/hub/secret.yaml:9:19: executing "pangeo/charts/jupyterhub/templates/hub/secret.yaml" at <required "Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!" .Values.proxy.secretToken>: error calling required: Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!


[3_deploy_helm.txt](https://github.com/pangeo-data/pangeo/files/4562382/3_deploy_helm.txt)
[secret_config.txt](https://github.com/pangeo-data/pangeo/files/4562383/secret_config.txt)

**Comment by Boes-man** [comment]
hey @TomAugspurger  @scottyhq do you have a rough eta on when the new install will be ready? at this stage i am busy with a test lab environment, so no big rush. thanks

**Comment by TomAugspurger** [comment]
I don't know that anyone is actively working on making `dask-gateway` an optional dependency in the helm chart right now. It'll be a while before I can attempt that.

**Comment by Boes-man** [comment]
Thanks @TomAugspurger any pointers or options on using a previous non dask-gateway version? I tried
helm install pangeo/pangeo --devel --version=0.1.1-86665a6 \
   --namespace=pangeo --name=pangeohub  \
   -f secret_config.yaml \
   -f jupyter_config.yaml

and --version=19.09.27-86dd66c

but looks like something else is required?

**Comment by consideRatio** [comment]
```
Error: render error in "pangeo/charts/jupyterhub/templates/proxy/deployment.yaml": template: pangeo/charts/jupyterhub/templates/proxy/deployment.yaml:26:32: executing "pangeo/charts/jupyterhub/templates/proxy/deployment.yaml" at <include (print $.Template.BasePath "/hub/secret.yaml") .>: error calling include: template: pangeo/charts/jupyterhub/templates/hub/secret.yaml:9:19: executing "pangeo/charts/jupyterhub/templates/hub/secret.yaml" at <required "Proxy token must be a 32 byte random string generated with openssl rand -hex 32!" .Values.proxy.secretToken>: error calling required: Proxy token must be a 32 byte random string generated with openssl rand -hex 32!
```

This error is very clear to me, you need a config like this for your pangeo helm chart.

```yaml
jupyterhub:
  proxy:
    # generated with: openssl rand -hex 32
    secretToken: 94e5adc3d34eb4004b36cc8acd969736295cecbc329606bc33d17b11eb1441eb
```

**Comment by Boes-man** [comment]
Hey all @scottyhq @TomAugspurger @consideRatio @jhamman I trust you're all well. I haven't tried the last suggestion yet. Just want to check whether the "Deploying Pangeo on the Cloud" guide will live again? Thanks

**Comment by TomAugspurger** [comment]
I don't know if anyone is actively working on it. If you're interested, I'm guessing an update would be welcome.

**Comment by Boes-man** [comment]
Thanks Tom. Unfortunately my knowledge and understanding of Pangeo is very superficial. There are however interest from scientists in my region (ANZ) and so I am looking at how to provide it for them based on Kubernetes. What are the options for scientist who are interested in Pangeo to start using it? Thanks

**Comment by TomAugspurger** [comment]
I think the best guide at the moment is
https://zero-to-jupyterhub.readthedocs.io/en/latest/ and the README at
https://github.com/pangeo-data/helm-chart. But there are likely things that
need to be updated in the README.

**Comment by scottyhq** [comment]
@Boes-man, I've been pointing interested scientists to http://gallery.pangeo.io, where we have examples that utilize dask-gateway. These interactive examples are currently open to anyone.

If you're interested in rolling your own infrastructure I encourage you to join the Pangeo Cloud working group meetings (one this Monday). https://discourse.pangeo.io/t/cloud-deployments-working-group/342/23 . I've added reviewing the current cloud deployment guide to the agenda.

**Comment by Boes-man** [comment]
Thanks @TomAugspurger i have installed Pangeo on a lab kubernetes cluster using the zero-to-jupyterhub. I was hoping to use the gallery.pangeo.io to find a notebook i can use to test it. I tried http://gallery.pangeo.io/repos/pangeo-gallery/physical-oceanography/01_sea-surface-height.html but looks like further module need to be installed for it to work. Are there any example notebooks to demonstrate pangeo's capabilities?

**Comment by TomAugspurger** [comment]
http://gallery.pangeo.io/repos/TomAugspurger/pangeo-dask-gateway/using-dask-gateway.html
is probably the simplest example, since it uses just Dask.

You might also try https://examples.dask.org/xarray.html, but change the
Client / cluster creation to use dask-gateway.

**Comment by Boes-man** [comment]
Hey @TomAugspurger in both examples further installs are required (dask gateway and xarray). I havent been able to get either done. The kubernetes https://zero-to-jupyterhub.readthedocs.io/en/latest/ is up and running. Hope there is a way to see what it can do? @scottyhq

**Comment by Boes-man** [comment]
Is there perhaps a `conda env` environment.yml i need for http://gallery.pangeo.io/repos/TomAugspurger/pangeo-dask-gateway/using-dask-gateway.html or https://examples.dask.org/xarray.html ? Thanks @TomAugspurger

**Comment by TomAugspurger** [comment]
Those use
https://github.com/pangeo-gallery/default-binder/blob/b379cd59c8ce4cf4e43af07f685351fd7883257d/binder/environment.yml

**Comment by Boes-man** [comment]
hey @TomAugspurger great news, i have been able to run through https://examples.dask.org/xarray.html upto "Custom workflows and automatic parallelization". Thanks for persisting with me!

i would like to see if  http://gallery.pangeo.io/repos/TomAugspurger/pangeo-dask-gateway/using-dask-gateway.html can work too... i have gotten as far as installing dask gateway on my kube cluster, as per https://gateway.dask.org/install-kube.html#install-the-helm-chart
`kubectl -n dask-gateway get po
NAME                                       READY   STATUS    RESTARTS   AGE
api-dask-gateway-5476bd845b-2lkm9          1/1     Running   0          31m
controller-dask-gateway-85f4dd5688-cl6zq   1/1     Running   0          31m
traefik-dask-gateway-844466d6db-wxd74      1/1     Running   0          31m
`
`kubectl -n dask-gateway get svc
NAME                   TYPE           CLUSTER-IP    EXTERNAL-IP                                                              PORT(S)        AGE
api-dask-gateway       ClusterIP      10.0.18.165   <none>                                                                   8000/TCP       10m
traefik-dask-gateway   LoadBalancer   10.0.17.104   acec64f0043b54245916d87e9fbf6b63-437305456.us-west-2.elb.amazonaws.com   80:32412/TCP   10m
`
running
`from dask_gateway import Gateway
gateway = Gateway("http://acec64f0043b54245916d87e9fbf6b63-437305456.us-west-2.elb.amazonaws.com")
`
completes but
`gateway.list_clusters()`
errors with
`ClientResponseError: 502, message='Bad Gateway', url=URL('http://acec64f0043b54245916d87e9fbf6b63-437305456.us-west-2.elb.amazonaws.com/api/v1/clusters/')
`

**Comment by Boes-man** [comment]
i am unable to see what the various config options should be, https://gateway.dask.org/configuration-user.html and whether the zero-to-jupyterhub installation means the dask-gateway installation needs to change? Perhaps there are ~/.config/dask/*.yaml files that would help me understand? what are those for the http://gallery.pangeo.io/repos/TomAugspurger/pangeo-dask-gateway/using-dask-gateway.html instance?

I am guessing for my "as simple as possible" example, i need to understand `gateway.address` and  `gateway.proxy-address`?

**Comment by Boes-man** [comment]
Hey @TomAugspurger @scottyhq I have been able to find a few more example nb to run from the gallery. Its pretty clear that where dask is concerned dask-gateway is required. I would like to be able it. I have gone back and reviewed the Openshift and other docs (including dask's), but they all lead back to the Kubernetes guide (which at the moment doesn't include dask-gateway?) or is too sparse  Do you have any suggestions? Thanks

**Comment by rabernat** [comment]
In relation to this issue in #780, I have removed this out-of-date setup guide and instead just point people to https://github.com/pangeo-data/pangeo-cloud-federation/. My feeling is that this is better and less confusing than having an incorrect guide up.

Do you all agree? If not, what exactly should we be documenting in our cloud setup guide.

**Comment by guillaumeeb** [comment]
I feel bad about not aving a proper Pangeo cloud setup guide. I know the one online is deprecated, but I think it is really useful to have such a detailed guide. 

The https://github.com/pangeo-data/pangeo-cloud-federation README point to the setup guide by the way.

I'd also like to have the choice to deploy a Pangeo cloud platform with Dask-gateway or just with Dask-kubernetes, I think the latter can still be useful (but I may be wrong about that).

All that said, I don't have any suggestion on how to keep the guide up to date, this is the part were we need contributions and I personnaly don't have any bandwidth right now.

**Comment by rabernat** [comment]
I agree with you @guillaumeeb. But no one seems able to maintain this guide. A broken guide is worse than nothing!

Perhaps a more sustainable solution would be to have a shorter, less comprehensive guide that describes how to compose the various pieces. We could link out to
- z2jhk8s
- pangeo docker images
- [dask_kubernetes helm chart](https://docs.dask.org/en/latest/setup/kubernetes-helm.html)
- dask gateway helm chart

**Comment by Boes-man** [comment]
I think you might be right rabernat a high level guide would be useful.

Some progress from my side, I think.

Found [pangeo-helm](https://github.com/pangeo-data/helm-chart) and it seems to install, but there are issues with kubespawner/user-scheduler.

Error: "Start My Server" errors with "Spawn failed"

I
![Screen Shot 2020-07-02 at 5 19 26 pm](https://user-images.githubusercontent.com/26314583/86355988-df01f400-bcae-11ea-9145-db65dfd16072.png)
<img width="1306" alt="Screen Shot 2020-07-02 at 5 23 11 pm" src="https://user-images.githubusercontent.com/26314583/86355994-e0cbb780-bcae-11ea-8bbd-d574af140304.png">
<img width="1410" alt="Screen Shot 2020-07-02 at 5 20 59 pm" src="https://user-images.githubusercontent.com/26314583/86356002-e3c6a800-bcae-11ea-95be-f5bc9e7b76f3.png">
<img width="1381" alt="Screen Shot 2020-07-02 at 5 20 43 pm" src="https://user-images.githubusercontent.com/26314583/86356004-e45f3e80-bcae-11ea-9a55-a44d73cf5d83.png">



Install Pangeo:
helm install pangeo/pangeo --name=pangeo --namespace=pangeo -f helm-pangeo-values.yaml

Patch kubespawner to "fix" 500 internal server error
kubectl patch deploy -n pangeo hub --type json --patch '[{"op": "replace", "path": "/spec/template/spec/containers/0/command", "value": ["bash", "-c", "\nmkdir -p ~/hotfix\ncp -r /usr/local/lib/python3.6/dist-packages/kubespawner ~/hotfix\nls -R ~/hotfix\npatch ~/hotfix/kubespawner/spawner.py << EOT\n72c72\n< key=lambda x: x.last_timestamp,\n---\n> key=lambda x: x.last_timestamp and x.last_timestamp.timestamp() or 0.,\nEOT\n\nPYTHONPATH=$HOME/hotfix jupyterhub --config /srv/jupyterhub_config.py --upgrade-db\n"]}]'

Browse to Jupyter landing page
Login as random user, i.e. testing123
Click "Start My Server"

**Comment by Boes-man** [comment]
[helm-pangeo-values.txt](https://github.com/pangeo-data/pangeo/files/4864124/helm-pangeo-values.txt)

**Comment by consideRatio** [comment]
Following https://github.com/pangeo-data/helm-chart/pull/132, you will have a functional kubespawner by default and not need such advanced hotfix. I think that will also fix your issue which I think stem from the user-scheduler needed a fix for 1.16.

Btw, where does the `3_deploy_helm.sh` originate from?

**Comment by consideRatio** [comment]
> @TomAugspurger, @consideRatio, or @jhamman is there a way to fully disable dask-gateway? If not, going forward your secrets file will need some additional tokens:

Yes, we can use either a condition or "tag" as they call it for the helm dependency on the dask-gateway helm chart. I created a PR: https://github.com/pangeo-data/helm-chart/pull/133 for this.

I also created a PR to bump z2jh to 0.9.0.

**Comment by Boes-man** [comment]
Please let me know if there is a release I can test this with?
E.G.
`helm install pangeo/pangeo --version=v0.2.2-patch --name=<release name> --namespace=<namespace> -f /path/to/custom/values.yaml`
Thanks

**Comment by Boes-man** [comment]
Hey All, I came across this [blog](https://blog.jupyter.org/jupyter-meets-the-earth-1b0eb33c83f) and it again references [Z2JH for K8s](http://z2jh.jupyter.org/en/latest/) I would like to use k8s upstream (open source) in my own on prem datacenter (this is where some of our data is). My understanding is that if we can get gangeo-data/helm-chart working, then Pangeo can be provisioned in my lab and thus make Pangeo accessible to more users. I am sure, there are other folks that have the same situation. Thanks

**Comment by Boes-man** [comment]
Hey @rabernat, is there any update? Is this case where Pangeo is moving away from being suitable for "generic" kubernetes? Or is it a case that lower level dependencies and direction for Pangeo, e.g. dask.kubernetes and/or dask.gateway needs to be decided first? I assume "generic" kubernetes should be achievable, but Pangeo need to decide on underlying direction before finalising what "generic" kubernetes needs? Once that is done, the high level  "generic" kubernetes Pangeo can be described?

https://github.com/pangeo-data/pangeo/issues/773#issuecomment-651868974

**Comment by Boes-man** [comment]
Hey Everyone, I am still around :) Any update on getting Pangeo on DIY, on perm kubernetes up and running? Some form of minimal option via pangeo-data/helm-chart?
@rabernat @TomAugspurger @scottyhq @jhamman 
Thanks

**Comment by TomAugspurger** [comment]
They aren't minimal, but the charts in
https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments
are hopefully a guide. That uses hubploy, but at the end of the day it's
doing `helm upgrade --install` on the pangeo chart with that configuration.

**Comment by Boes-man** [comment]
Thanks @TomAugspurger I have "Pangeo" up and running. Its diy kubernetes + kubeflow, which gets me to a Jupyter notebook. Then I take worker-spec.yml from the [Dask QS](https://kubernetes.dask.org/en/latest/#quickstart) and a conda env, based on one you provided. I create a kernel via `conda env create` from there. With this approach I am able to run the [Pangeo Dask Tut](http://gallery.pangeo.io/repos/pangeo-data/pangeo-tutorial-gallery/dask.html) and [Pangeo Xarray Tut](http://gallery.pangeo.io/repos/pangeo-data/pangeo-tutorial-gallery/xarray.html). I am using dask kubernetes (not gateway). From here I'll be able to mount on perm datasets via CSI into the jupyter instance.

A year or so ago, I was able to take "Deploying Pangeo on the Cloud" and get Pangeo up and running, even collaborated a bit on mounting git via init containers. With my current approach I feel its too removed from Pangeo Project architecture to collaborate.

I have read numerous blogs and charts and can see the reason for the architectures, but I am unable to join the effort. Perhaps my understanding is incomplete? It looks like the current Pangeo Kubernetes builds are for cloud based SaaS models only?

[Your blog](https://medium.com/pangeo/managing-environments-5604d848367a) is great, exactly where I would like to start. Since I have felt all the pains that it works towards fixing. How do i build this?

Thanks
