### ISSUE TITLE
Write blogpost on new environment setup

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo#775]
@scottyhq I think a blogpost laying out what we've learned about environment management would be helpful for pangeo users & people doing similar stuff.

![pangeo environments](https://user-images.githubusercontent.com/1312546/80978432-a7301a80-8deb-11ea-8153-3d4dc50a1b85.png)

* High-level overview (upstream packages, conda metapcakges, docker images, final user environments (e.g. ocean, binder, ...)). My outline above is missing the final user environments.
* Discussion on repo2docker and why we needed to replace some components
* Details use of conda-metapackages, bots, and conda-forge's tooling to incorporate updates to upstream packages
* Detail docker images (including recopmmendations on what to use)
* Aside on pangeo-gallery/default-binder and nbgitpuller?

I can put together a draft later today.
 
cc @jhamman @rabernat if you have additional questions you'd like to see answered.

**Comment by scottyhq** [comment]
Sounds great @TomAugspurger! I like the schematic, we need more of these illustrating how everything fits together. If you start a draft I'd be happy to work with you on it. I think there are 2-3 posts worth of content in your bullet points, maybe we can leave the CI and bot discussion for a follow-up?

**Comment by rabernat** [comment]
Great idea Tom. FYI, I am planning a blog post on binderbot and one on the new gallery, both of which relate tangentially to what you're describing here. In particular, I could cover your final point (pangeo-gallery + nbgitpuller).

**Comment by jhamman** [comment]
close by https://medium.com/pangeo/managing-environments-5604d848367a
