### ISSUE TITLE
Pangeo binder failing

### ISSUE THREAD

**Issue by jkingslake** [pangeo-data/pangeo#776]
Hi all, 
I am a newcomer to Pangeo. 
I made a simple notebook that I want to try out as a pangeo binder. 

When I follow the instructions [here](https://binder.pangeo.io) and use the url of my GitHub repo: https://github.com/jkingslake/Melt21CenturyTrusel.git

It seems to try and build the environment but fails, saying it can't find many of the packages.
I exported the environment.yml from my local machine, after creating a fresh environment with 
`conda create --name geo_scipy_3 python numpy xarray scipy jupyter matplotlib cftime pandas nc-time-axis holoviews hvplot cartopy`

The binder link is here: 
https://staging.binder.pangeo.io/v2/gh/jkingslake/Melt21CenturyTrusel.git/master

What I am doing wrong?
Thanks for any help!

**Comment by TomAugspurger** [comment]
Perhaps try `conda env export --no-builds --from-history`. Binder builds docker images on Linux. If you're on a different platform you might get different packages / build strings.

**Comment by rabernat** [comment]
Or maybe easier, create an `environment.yaml` with `numpy xarray scipy jupyter matplotlib cftime pandas nc-time-axis holoviews hvplot cartopy`.

**Comment by jkingslake** [comment]
Thanks @TomAugspurger, this worked! 
My first pangeo binder. Very exciting! 
Only strange thing is that a hvplot animation doesn't run (different issue I guess).
Thanks again!

**Comment by rabernat** [comment]
Jonny, there are some tricks we could use to make this much simpler. Your environment is compatible with our [default binder](https://github.com/pangeo-gallery/default-binder/) repo, meaning that you don't even have to build a new environment. Plus that environment has all holoviews stuff working perfectly. 

The trick is described here:
https://discourse.jupyter.org/t/tip-embed-custom-github-content-in-a-binder-link-with-nbgitpuller/922

But that is too technical for most people to follow. We will work on an easier path.

**Comment by jkingslake** [comment]
Thanks Ryan. This makes sense. 
This is much faster: https://binder.pangeo.io/v2/gh/pangeo-gallery/default-binder/master/?urlpath=git-pull?repo=https://github.com/jkingslake/Melt21CenturyTrusel%26amp%3Burlpath=lab/tree/Melt21CenturyTrusel

And the holoviews stuff works perfectly!

When it comes to adding packages to the default binder repo, where do we make suggestions? 
I found that I needed nc_time_axis and so using the default binder it seems I will need to install it each time (not an issue, but a small barrier for sharing with colleagues etc.).

**Comment by jkingslake** [comment]
Incidentally, the format of this url was not obvious to me, so it was a little bit of trial and error, but for future reference for anyone else looking at this (who's as much of a beginner as me). The format is 
https://binder.pangeo.io/v2/gh/pangeo-gallery/default-binder/master/?urlpath=git-pull?repo= **[url of GitHub repo]** %26amp%3Burlpath=lab/tree/ **[name of GitHub Repo]**

**Comment by rabernat** [comment]
> When it comes to adding packages to the default binder repo, where do we make suggestions?

So this goes down a bit of a rabbit hole. The binder for the default image is very simple and just uses a Dockerfile: https://github.com/pangeo-gallery/default-binder/blob/master/binder/Dockerfile

with a single line
```
FROM pangeo/pangeo-notebook:35caf6a
```

This is pointing at a Docker image generated by this repo:
https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/environment.yml

(I personally think we should move this configuration to default-binder.)

As a result of this complexity, to update the binder env right now requires 2 pull requests:
- First to https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/environment.yml 
- And then to https://github.com/pangeo-gallery/default-binder/blob/master/binder/Dockerfile to point to a more recent docker image.

We should find a way to make that easier.
