### ISSUE TITLE
unknown field "apiGroup"

### ISSUE THREAD

**Issue by clundst** [pangeo-data/pangeo#777]
Greetings,
I've been trying to launch the pangeo helm charts on our in-house kubernetes cluster.  The documentation seems a little stale, and I'm very green at kubernetes/helm.  I created a config.yaml as best I could, and I can share most of that if needed.
helm install pangeotest pangeo/pangeo  --namespace=pangeo -f config.yaml

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(RoleBinding): unknown field "apiGroup" in io.k8s.api.rbac.v1beta1.RoleBinding, ValidationError(RoleBinding.roleRef): missing required field "apiGroup" in io.k8s.api.rbac.v1beta1.RoleRef]

version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

This looks like an issue in rbac template, and I believe this is new as the old deploy scripts seem to depend on helm2+tiller.  

Whom do I ask for help?  

Thanks,
Carl

**Comment by ZihengSun** [comment]
Same problem here
