### ISSUE TITLE
package xgcm not able to import

### ISSUE THREAD

**Issue by qyxiao** [pangeo-data/pangeo#785]
I wonder if the package xgcm has been updated lately? Today when I tried to use it an error pop up:  "AttributeError: 'NoneType' object has no attribute 'expandtabs'

The full error message is:
AttributeError                            Traceback (most recent call last)
<ipython-input-1-814b32b375aa> in <module>
----> 1 import xgcm

/srv/conda/envs/notebook/lib/python3.7/site-packages/xgcm/__init__.py in <module>
      4 del get_versions
      5 
----> 6 from .grid import Grid, Axis
      7 from .autogenerate import generate_grid_ds

/srv/conda/envs/notebook/lib/python3.7/site-packages/xgcm/grid.py in <module>
    757 
    758 
--> 759 class Grid:
    760     """
    761     An object with multiple :class:`xgcm.Axis` objects representing different

/srv/conda/envs/notebook/lib/python3.7/site-packages/xgcm/grid.py in Grid()
   1065         return out
   1066 
-> 1067     @docstrings.dedent
   1068     def _apply_vector_function(self, function, vector, **kwargs):
   1069         # the keys, should be axis names

/srv/conda/envs/notebook/lib/python3.7/site-packages/docrep/decorators.py in update_docstring(self, *args, **kwargs)
     24             return func(self, *args, **kwargs)
     25         elif len(args) and callable(args[0]):
---> 26             doc = func(self, args[0].__doc__, *args[1:], **kwargs)
     27             _set_object_doc(args[0], doc, py2_class=self.python2_classes)
     28             return args[0]

/srv/conda/envs/notebook/lib/python3.7/site-packages/docrep/__init__.py in dedent(self, s, stacklevel)
    515             encountering an invalid key in the string
    516         """
--> 517         s = inspect.cleandoc(s)
    518         return safe_modulo(s, self.params, stacklevel=stacklevel)
    519 

/srv/conda/envs/notebook/lib/python3.7/inspect.py in cleandoc(doc)
    617     onwards is removed."""
    618     try:
--> 619         lines = doc.expandtabs().split('\n')
    620     except UnicodeError:
    621         return None

AttributeError: 'NoneType' object has no attribute 'expandtabs'

**Comment by jbusecke** [comment]
Dear @qyxiao,
this is a problem with the docrep dependency (see [xgcm/210](https://github.com/xgcm/xgcm/issues/210). 
Can you try downgrading docrep to a version smaller than 0.3? 

If the problem persists please feel free to reach out again (preferably as an xgcm issue, I monitor these much closer than pangeo).

**Comment by qyxiao** [comment]
Hi @jbusecke, thank you very much for your reply. I have a dump question though. After I create a new environment, how can I open a new notebook under this environment in Pangeo? If I don't use a new environment and just type: conda install dorep=0.2.7 then a message like this will pop up and I'm not sure if I should proceed...
"
 The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
  - conda-forge/linux-64::tiledb-py==0.5.9=py37ha852a99_1
  - conda-forge/noarch::geoviews-core==1.8.1=py_0
  - conda-forge/linux-64::libgdal==3.0.4=he6a97d6_10
  - conda-forge/linux-64::gdal==3.0.4=py37h4b180d9_10
  - conda-forge/noarch::rioxarray==0.0.31=py_0
  - conda-forge/noarch::intake-geopandas==0.2.3=py_0
  - conda-forge/noarch::geopandas==0.8.1=py_0
  - conda-forge/noarch::metpy==0.12.2=py_0
  - conda-forge/linux-64::tiledb==1.7.7=h8efa9f0_3
  - conda-forge/noarch::trollimage==1.13.0=py_0
  - conda-forge/noarch::satpy==0.22.0=py_0
  - conda-forge/linux-64::fiona==1.8.13=py37h0492a4a_1
  - conda-forge/linux-64::rasterio==1.1.5=py37h0492a4a_1
  - conda-forge/noarch::supermercado==0.1.1=pyh9f0ad1d_0
  - conda-forge/noarch::rio-cogeo==1.1.10=py_0
  - conda-forge/linux-64::cartopy==0.18.0=py37h4b180d9_0
failed with initial frozen solve. Retrying with flexible solve.
"

**Comment by dhruvbalwada** [comment]
This is a problem when trying to use the pangeo default environment. Somehow xgcm's version has gone out of sync with the other modules installed. 

Maybe someone from the pangeo team can look into this? 

PS - you can have your custom environment modifications by using the suggestion here: https://discourse.pangeo.io/t/suggestions-for-additional-modules/765/5?u=dhruvbalwada

**Comment by rabernat** [comment]
It's a big problem that this is broken in Pangeo Cloud. @jbusecke, could you work with @TomAugspurger to try to fix this problem? This will be a good opportunity for you to learn how the Pangeo Cloud environments are configured.

**Comment by TomAugspurger** [comment]
The best fix is to probably update
https://github.com/pangeo-data/pangeo-docker-images/blob/8bbb9ea0f5467d7aeb324343ed229be45a9d0e6a/pangeo-notebook/environment.yml#L73
to the fixed version of xgcm.

Then we can tag a release of the docker images to rebuild those. Bots
should pick up from there and we'll get it deployed to prod.

**Comment by jbusecke** [comment]
@TomAugspurger , we have released v0.4.0 a while ago (which includes a pin to an earlier docrep version), can we just retrigger the build? Or do you need me to pin the precise version of xgcm?

**Comment by jbusecke** [comment]
This is now fixed for me. @qyxiao could you try it and close the issue if it's fixed for you aswell? 

Thanks for the help in resolving this quickly @TomAugspurger .

**Comment by qyxiao** [comment]
Hi @jbusecke, yes it is working now. 
Thank you all!
