### ISSUE TITLE
Landing page for cloud deployments

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo#787]
I am just actually starting working on the new pangeo cloud deployments a few days ago. Thanks for the amazing work everyone.

To log in I often google `pangeo cloud` and then click myself to e.g. central1-b.gcp.pangeo.io.
But I find myself missing a simple memorable page to navigate to like `ocean.pangeo.io`.

Would it be hard to have a landing page like `pangeo.cloud.io` or `cloud.pangeo.io`  that has two or more big buttons with `AWS` `google` or similar, which lead to aws-uswest2.pangeo.io and us-central1-b.gcp.pangeo.io?

**Comment by TomAugspurger** [comment]
I think adding it to http://pangeo.io/cloud.html might be easiest.

That source is at
https://github.com/pangeo-data/pangeo/blob/master/docs/cloud.rst. A couple
HTML buttons there would go a long way.

**Comment by jbusecke** [comment]
Just pushed a PR for that in #795, if you could have a look some time, that would be amazing!
