### ISSUE TITLE
common modules missing?

### ISSUE THREAD

**Issue by qyxiao** [pangeo-data/pangeo#794]
Hi,
Today when I tried to use Pangeo, it looked like some common packages like intake, xarray, matplotlib, xgcm, xhistogram are gone. I can't import them and can't find them from the modules list( !pip list ). Is that me making some mistakes accidentally or it's something wrong with the default environment?

**Comment by TomAugspurger** [comment]
Was this on the deployment as us-central1-b.gcp.pangeo.io/? If so, it was likely my fault from debugging another issue. https://github.com/pangeo-data/pangeo-cloud-federation/pull/776 is hopefully fixing things.

**Comment by qyxiao** [comment]
Hi Tom,
Yes it is on us-central1-b.gcp.pangeo.io and I'm afraid the issue still remains.

**Comment by TomAugspurger** [comment]
Can you try again now?

You may need to restart your JupyterHub session. File > Hub Control Panel > Stop My Server.

**Comment by qyxiao** [comment]
Thanks. It is working now.
