### ISSUE TITLE
Pangeo meetup at Ocean Sciences in Portland (Feb. 2018)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#80]
I know several of us will be at [OSM18](https://osm.agu.org/2018/) this February (e.g. @pwolfram, @gmaze). 

There are several sessions relevant to Pangeo, mostly under the theme of [Ocean Data Management](https://agu.confex.com/agu/os18/meetingapp.cgi/Program/1316):
- Using Cloud Infrastructure and Annotation Tools to Manage Complex and Voluminous Oceanographic Data Files ([posters](https://agu.confex.com/agu/os18/meetingapp.cgi/Session/28447))
-  Big Data for a Big Ocean: Progress on Tools, Technology, and Services ([posters](https://agu.confex.com/agu/os18/meetingapp.cgi/Session/28354), [oral I](https://agu.confex.com/agu/os18/meetingapp.cgi/Session/36977), [oral II](https://agu.confex.com/agu/os18/meetingapp.cgi/Session/36983))
- Visualization, Statistics, and Model Validation of Big Data for Oceanography ([posters](https://agu.confex.com/agu/os18/meetingapp.cgi/Session/28299), [oral](https://agu.confex.com/agu/os18/meetingapp.cgi/Session/36975))

There is a huge amount of overlap between these sessions of course. I am speaking about Pangeo in the "Visualization" oral session ([abstract](https://agu.confex.com/agu/os18/meetingapp.cgi/Paper/321028)).

I definitely want to organize a Pangeo get together, either a happy hour or a dinner. Give a 👍 to this issue if you are interested in meeting up and participating in such an event.

**Comment by rabernat** [comment]
I propose a dinner / drinks get together on Thursday night (Feb. 15).

If this sounds good to people, I will try to find a venue that can accommodate us.

**Comment by jhamman** [comment]
cc @ocefpaf

**Comment by ocefpaf** [comment]
@rabernat I don't want to crash pangeo's dinner meeting but I'll be around during OSM and I'd love to grab a coffee with some of you.

**Comment by rabernat** [comment]
There is absolutely nothing exclusive in any way about this get together. If you have found your way to this page, you are welcome to join! @ocefpaf in particular, we would love to chat with you as you have lots of valuable expertise that could benefit our project.

**Comment by pwolfram** [comment]
@xylar, @mark-petersen, @toddringler and @vanroekel you may be interested in this event in Portland next week ...

**Comment by rabernat** [comment]
We will meet at 7pm on Thursday at [Basecamp Brewery](http://basecampbrewingco.com/index.html). There is no reservation, but I called and it sounds like they should be able to accommodate us.

Looking forward to seeing you all there! Anyone and everyone is welcome.

**Comment by rabernat** [comment]
Just a reminder this is happening tonight.

**Comment by rabernat** [comment]
![img_6407 2](https://user-images.githubusercontent.com/1197350/36296055-1befafd0-12a0-11e8-8067-a29d50ad90ff.JPG)
