### ISSUE TITLE
Xref: pangeo github site links to some japanese site on payment methods?

### ISSUE THREAD

**Issue by willirath** [pangeo-data/pangeo#805]
Raised in https://github.com/xgcm/xgcm/issues/284

**Comment by rabernat** [comment]
I really don't understand how this is possble:

https://pangeo-data.github.io/ redirects to https://www.pangeo-data.org/

https://www.pangeo-data.org/ is a spam website.

I don't know where this redirection is configured nor who owns pangeo-data.org!
