### ISSUE TITLE
Moving Pangeo docs publishing CI over to GitHub Actions

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/pangeo#806]
Pangeo's website (along with various other repos in the organization) use Travis CI via [travis-ci.org](https://travis-ci.org), which is [shutting down on December 31, 2020.](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D) 

In light of this, we _could_ move our Travis CI over to [travis-ci.com](https://travis-ci.com), but in doing that we must also consider their [new pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), which only allots OSS build minutes past the 1000 minute free trial on a case-by-case basis through requests, which must be submitted every time we run out of minutes.

Personally, I think this gives us large motivation to move most of our existing Travis CI workflows over to GitHub Actions, if possible. We currently have a [Sphinx site being published using GitHub Actions](https://github.com/pangeo-data/pangeo-cmip6-cloud), so transitioning this repo shouldn't be too difficult.

**Comment by rabernat** [comment]
Thanks for noting this Charles! It would be awesome if you could migrate the website build to github actions.

**Comment by charlesbluca** [comment]
Opened up #807 to switch over to a GitHub Actions workflow!

**Comment by charlesbluca** [comment]
Now that the website CI is fully migrated to GHA, we can close this.
