### ISSUE TITLE
Add support for slurm to pangeo object 

### ISSUE THREAD

**Issue by jedwards4b** [pangeo-data/pangeo#81]
I like the pangeo/pbs.py module and think that it should be extended.  To this end I have moved some of the code from there to a parent module I call JobQueue and created a slurm module.  I've confirmed that the test_pbs still works and added a test_slurm, but I haven't managed to get the test_slurm working yet and I'm looking for help in debugging.
My fork is git@github.com:jedwards4b/pangeo.git branch is addslurm

**Comment by mrocklin** [comment]
I'm very glad to hear this.  Can I recommend that you issue a PR marked
with WIP (work in progress)?  The PR interface is really nice for having
conversations around code, even if a PR isn't ready for inclusion.

**Comment by jedwards4b** [comment]
opened PR #83

**Comment by jhamman** [comment]
closed via #83
