### ISSUE TITLE
Add Pangeo Showcase page

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#821]
As discussed on https://discourse.pangeo.io/t/new-weekly-meeting-format-logistics/1156 the weekly meeting format will shift to having "Pangeo Showcase" talks every other week.    These will have recording links and DOIs so we would like to create a web page for Pangeo Showcase instead of just a google doc.

**Comment by rabernat** [comment]
I love it. Let's start with just a simple static page. As the list of speakers grows, we can refactor it into some kind of yaml database + jinja template.
