### ISSUE TITLE
Modify HPC instructions to use base env for jupyterlab

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#825]
I would like to modify the [Pangeo software environment instructions for HPC](https://pangeo.io/setup_guides/hpc.html#installing-a-software-environment) to be more aligned with what I recommend people do, but wanted to check to see if others agree.  

The basic procedure is:
* install miniconda  (unchanged)
* specify conda-forge as the only channel in the config
* install mamba (for faster dependency solving)
* update all packages in the base env
* in the base env, install the jupyterlab stuff (jupyterlab, jupyter-server-proxy, dask-labextension, ipywidgets, nb_conda_kernels, nodejs)
* create one or more custom environments that contain other packages like (dask, dask-jobqueue, xarray, holoviz, ipykernel, ipywidgets and extra packages). 
* pick a random port to use on the server instead of assuming 8888 will be available. 
* launch jupyterlab from the base environment on that port

Would it be okay for me to submit a PR with these changes, or is this too opinionated (or someone has a better best practice)?

**Comment by rsignell-usgs** [comment]
What do you think @andersy005 ?

**Comment by guillaumeeb** [comment]
Hi @rsignell-usgs, I think this is all very good. 

On the specific part of creating one environment with jupyter and one or several others with specific tools, there are pros and cons. I think you could update the doc and give the choice, either only one big env with everything, or several env if you need to switch. In that last case, you need to explain kernel creation, or is this not required anymore?

**Comment by rsignell-usgs** [comment]
@guillaumeeb , thanks so much for the feedback!    I'm happy to write it as a choice, but are you aware of advantages to one big environment other than simplicity (if so, I'd like to mention them!).  

For multiple environments, you just need to have `nb_conda_kernels` in the environment from which you launch jupyter, and `ipykernel` in other environments so that they are discovered.   I can certainly document that.   Is that what you meant?

**Comment by guillaumeeb** [comment]
> but are you aware of advantages to one big environment other than simplicity

I can see one other: better handling of jupyterlab extension compatibility with kernel libraries, even if it does not prevent from mistakes.

>  I can certainly document that. Is that what you meant?

I think so, I don't know nb_conda_kernel, it automatically creates kernel description for new environments? I'm use to call ipykernel from an new environment to make them available in Jupyterlab.

**Comment by rsignell-usgs** [comment]
@guillaumeeb, I decided not to introduce the multiple environment option here, for simplicity.  I merely updated to mamba and adding the ipywidgets package, allowing the cluster widget to render nicely, and suggested a jupyter_startup script for those who don't have them.  Please take a look if you get a chance.

**Comment by guillaumeeb** [comment]
I'm a little sad you didn't pursue the multiple environment option, I would have liked to see the advantages you see in both and the way you do it. But I understand this would have been more complicated to present.
