### ISSUE TITLE
Move Dask-pbs (and dask-slurm) to separate repository

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#85]
I might want to move the pbs / slurm modules out to a separate repository at some point after they have solidified.  In general I view the `pangeo` repo as a bit of a temporary play-space.  Any objections?

**Comment by rabernat** [comment]
I agree.

In the long term, I see this repo as housing only documentation. Any other products we develop should be spun off to their own repos.

**Comment by jhamman** [comment]
@mrocklin - is there a dask space that you see some of this fitting or should we start something of our own?

**Comment by mrocklin** [comment]
I think that this should become a standalone repository within the dask github org.  Prior to @jedwards4b work on SLURM I was planning to move this to a dask-pbs project.  However given the code sharing we'll probably need to find some other name.

**Comment by jhamman** [comment]
Moving the conversation from #83 to here. 

On the question of testing, @mrocklin responded with 

> In the dask-drmaa project (https://github.com/dask/dask-drmaa) we set up an SGE cluster in travis-ci with docker

So it seems reasonable that we can test against generic deployments of SGE, PBS, or Slurm. As I see it, this issue has a few todo items:

1. create a new repository for housing these tools (name tbd but something like dask-jobqueue)
2. develop CI and testing for the existing PBS and Slurm clusters
3. remove the PBS and Slurm cluster code from this repo

**Comment by mrocklin** [comment]
Point two there is probably the most challenging.  The other bits are
relatively straightforward.

**Comment by jhamman** [comment]
@mrocklin - if you want to start a new repository for these adaptive clusters, I'd be happy to start contributing in that space.

**Comment by jakirkham** [comment]
> develop CI and testing for the existing PBS and Slurm clusters

Posted some thoughts in issue ( https://github.com/dask/dask-jobqueue/issues/2 ) if anyone is interested.

**Comment by mrocklin** [comment]
https://github.com/dask/dask-jobqueue
