### ISSUE TITLE
Euro-Cordex datasets in the cloud

### ISSUE THREAD

**Issue by larsbuntemeyer** [pangeo-data/pangeo#862]
Hi everybody,
i wanted to drop some of my thoughts here on bringing WCRP [EURO-CORDEX](https://www.euro-cordex.net/) datasets to the cloud. That would be cmorized datasets on the European Cordex domain that are currently available only for access by download from, e.g., ESGF or the [Coperniucs Climate Data Store](https://cds.climate.copernicus.eu/cdsapp#!/dataset/projections-cordex-domains-single-levels?tab=overview). 

I have been reading and browsing through some similar issues here (eg. #763, #686) and I am also aware of the [guide to prepare cloud optmized data](https://pangeo.io/data.html#guide-to-preparing-cloud-optimized-data). I personally think it would be great to have that data easily accessible from the cloud because right now, you are only able to really work with the whole ensemble if you have direct access to the data at one of the ESGF-nodes. Right now, this is just an idea, but i guess i would be able to get support from [DKRZ-ESGF](https://esgf-data.dkrz.de/projects/esgf-dkrz/) where i usually work with the ensemble and where also an intake collection is maintaned. The ensemble contains about:

* up to **150 datasets** on the `EUR-11` Cordex domain each for a number of frequently requested variables,
* about **75 TB** of data volume for the complete ensemble and all variables on the `EUR-11` domain.

To get some more idea of the dataset, i have a [notebook](https://nbviewer.org/github/euro-cordex/py-cordex/blob/master/notebooks/euro-cordex-ensemble.ipynb) that shows access to the 2m surface temperature EURO-CORDEX ensemble dataset at DKRZ.

I am especially wondering what license would be required for the data to be made available publicly and if you think that the [Cordex terms of use](https://is-enes-data.github.io/cordex_terms_of_use.pdf) would be a problem for distributing the data freely? Right now, on ESGF only CMIP5 and CMIP6 data are freely available while for Cordex you still have to register.

I would be interested in your thoughts on whether that data could be successively made available through PANGEO cloud storage. As i said, right now this is just an idea, but the *Euro-Cordex General Assembly* is coming up in the end of January 2022 and i wanted to bring that up and discuss it in the community. Thanks a lot!

**Comment by rabernat** [comment]
Hi @larsbuntemeyer - thanks a lot for this great suggestion!

Our efforts regarding cloud data are focused on Pangeo Forge right now. I have copied your issue to https://github.com/pangeo-forge/staged-recipes/issues/96 for further discussion.
