### ISSUE TITLE
Update the tools mentioned as the "pangeo stack"

### ISSUE THREAD

**Issue by abarciauskas-bgse** [pangeo-data/pangeo#864]
Should we update https://pangeo.io/quickstart.html, https://pangeo.io/packages.html, https://pangeo.io/architecture.html and how?

Some ideas:
* @andersy005 mentioned a flowchart on scikit learn for how to decide which estimator to use: https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
* @TomAugspurger Suggested to write up why we like a certain package

**Comment by rabernat** [comment]
One idea we discussed a while back was to try to align somehow with pyOpenSci to provide formal a formal review and stamp of approval for certain packages. That was discussed in https://github.com/pyOpenSci/contributing-guide/issues/82. The pyOpenSci effort stalled a bit with COVID, but I hope it can come back.

**Comment by kmpaul** [comment]
There has been discussion in Project Pythia around doing the same thing.  Currently, Pythia has focused on more core technology, but I think having this kind of content would be beneficial in that context, too.
