### ISSUE TITLE
Clarify relationship with Project Pythia on the Pangeo website

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#866]
Following todays SC meeting, I am making a note of the idea of formalizing project Pythia as the "official" education / onboarding channel for Pangeo and pointing to it via our website.

The idea for Pythia emerged at least partially from the new defunct POETs (Pangeo Outreach Education and Training efforts) working group. So I have been thinking about it as closely related to the Pangeo effort. On the [website](https://pangeo.io/meeting-notes.html#working-group-meetings), Pythia is described as "formerly the education working group".

However, if you go look at the Pythia [website](https://projectpythia.org/), there is no mention of Pangeo whatsoever. (Neither in the [pythia foundations book](https://projectpythia.org/search.html?q=pangeo).) So perhaps have I have been misunderstanding this relationship.

I'm pinging @kmpaul and @ktyle for some feedback on this. Is it okay if we point to Pythia as the go-to educational resource for Pangeo?

**Comment by kmpaul** [comment]
@rabernat:  Absolutely, and in fact, I would say that we need to do the reverse, too.  The Python website should mention Pangeo and point to Pangeo, too.  I don't think there is any fear that the two efforts will wander away from each other, but I do think we should make the tie explicit.  (As a side note, I think this was just an oversight on our part, and one that the sudden interest in Pythia thanks to AGU and AMS has highlighted.  I think, and hope, it is a quick fix.)

**Comment by rabernat** [comment]
Sounds great Kevin!

I'm looking at the pythia foundations book. It is an awesome 0-60 introduction to the stack. I'm wondering if there is scope within Pythia to go to the next level: scaling out to big data with dask and Pangeo deployments? Is that something you want to include? I think Pangeo folks would be keen to contribute.

Alternatively, that material could continue to live in other locations like http://gallery.pangeo.io/repos/pangeo-data/pangeo-tutorial-gallery/

**Comment by kmpaul** [comment]
It is absolutely something we want to include!  And we are currently discussing how to deploy our own BinderHub with Dask capability (like 2i2c) to deploy these.  I'm not sure if we can leverage an existing Pangeo 2i2c hub, or if we should deploy our own, but I lean toward going with 2i2c because they have the experience that we do not.

**Comment by rabernat** [comment]
So binder.pangeo.io is currently down due to abuse by crypto miners (see https://github.com/pangeo-data/pangeo-binder/issues/195 for the sad story). When it comes back (under 2i2c operation, hopefully within a few months), it will likely be more like https://hub.aws-uswest2-binder.pangeo.io/, with a github login required.

Given the effort involved in running a binderhub (particularly given the constant threat of crypto-minders), I feel like it makes sense to minimize the number of deployments. It would be great if Pythia and Pangeo could be using the same binderhub for demos that require dask gateway and / or enhanced resources (e.g. memory). It would be great to align on this. I personally would love it if NCAR / Pythia would just own binder.pangeo.io, because it would be one less thing for me to worry about! 😉  But we should chat about this and try to find a solution that makes sense for everybody.

**Comment by kmpaul** [comment]
> I personally would love it if NCAR / Pythia would just own binder.pangeo.io, because it would be one less thing for me to worry about! 😉

😄 I think that would be cool, too.  At the moment, I'm not sure who to get in the room to decide that one.  Our ability to deploy in the cloud is still pretty muddled.  (This is mostly due to lack of a defined policy about how to pay for cloud services without reimbursing personal credit cards.)  But I think these issues are being ironed out.  Slowly.

**Comment by clyne** [comment]
Apologies, @rabernat. The Pangeo omission was an oversight due to too many competing priorities. We will get it addressed. 

Re binder.pangeo.io: that's a longer conversation that I hope @kmpaul and others on the Pythia infrastructure team will continue.

**Comment by ktyle** [comment]
@rabernat Thanks for the ping and I echo @clyne and @kmpaul's comments. We'll be holding our biweekly Education Working Group meeting tomorrow, and I expect that you'll soon be seeing some PR's to our Foundations and Pythia website repos. Additionally, we've specifically addressed Pythia's links to and inspiration from Pangeo in our soon-to-be-submitted SciPy'22 abstract.
