### ISSUE TITLE
Update homepage to point to guideance for our core expected user groups

### ISSUE THREAD

**Issue by abarciauskas-bgse** [pangeo-data/pangeo#873]
My current assessment of who the core users of Pangeo might be:

* For scientists ([Guide for Scientists — Pangeo documentation](https://pangeo.io/quickstart.html)) - This already provides a general “set of options for scientists” - contribute a package, explore the gallery
* For systems admins: How to create and manage a pangeo environment on HPC or cloud (zero to jupyter hub) - Should we maintain and update these guides?
* For data scientists/data engineers: How to create a Zarr dataset and upload it to the cloud (Pangeo and Data) - Should this become a reference to pangeo-forge documentation?
* For data scientists: [How to use existing pangeo cloud federation environments](https://pangeo.io/cloud.html)

If we agree these are the main groups I think we determine which guidance we should link to or create and open an issue to refine or create that page and make sure it's up to date, and add those "quick links" to the home page

**Comment by rabernat** [comment]
I like the idea of breaking down different personas of people accessing the website.

> My current assessment of who the core users of Pangeo might be:

Even "core users" might be too restrictive. I think there will be people accessing the website who are not users at all, but rather might want to just get basic information.

The groups you have outlined seem to have quite a bit of overlap. What's the difference between "scientist", "data scientists /  data engineers", and "data engineers"? I know many people who might identify with all three. I would probably break it down as follows:

- General interest, non-technical audience
- Pangeo "users":
  - Domain Scientists
  - Data / ML Scientists 
  - Data Engineers
  - [Might be useful also to single out "cloud users" vs. other users somehow]
- System admins

**Comment by RichardScottOZ** [comment]
and there is the systems problem of 'solve the politics of getting this started'

**Comment by abarciauskas-bgse** [comment]
@abkfenris I like this breakdown of tasks and structuring the guides around tasks. It seems like we can either move forward with the set that you have proposed and/or discuss further which ones should be included.

I think I would also add: See examples of what others and I can do with Pangeo (which links to the pangeo showcase)

Should we prioritize this list? I'm inclined to starting with some of the low-hanging fruit / most beginner friendly:
* get a general overview of Pangeo and who is involved
* see examples of what others and I can do with Pangeo
* get access to Pangeo

Then
* setup a Pangeo style environment
* work with cloud hosted datasets
* make a dataset easier to access

Finally
* scale my analysis (maybe split between pandas/xarray and ML)

**Comment by paigem** [comment]
Reviving this issue after @abarciauskas-bgse and I had some discussions + hacking today! 

Please see #878 for details
