### ISSUE TITLE
Pangeo binder link not working anymore

### ISSUE THREAD

**Issue by kratzert** [pangeo-data/pangeo#876]
Hi all,

not sure if this is the correct place to raise this issue but I hope someone sees it and in the worst case can direct me to the correct repository.

A while ago @jhamman asked me to write an application example (train a small LSTM on a rainfall-runoff dataset) that can be run on pangeo's binder service. The repository with the jupyter notebook can be found at https://github.com/kratzert/pangeo_lstm_example

Today, someone raised an issue there because the binder link is not working anymore. I haven't checked this repository in while, so I don't know if this is something recent or not. I just wanted to ask if you know what is the issue here and if yes, if that can be resolved or not. The example was specifically written to run on the pangeo server and if the binder link can't be restored, I would either need to change the notebook or at least leave a message that the code is not running anymore.

Thanks for your help,
Freddy

**Comment by scottyhq** [comment]
@kratzert unfortunately the binder was shut down due to crypto mining (https://github.com/pangeo-data/pangeo-binder/issues/195), it may be revived at a future date...

**Comment by kratzert** [comment]
I am sorry to hear that and apparently missed the other thread. Thanks for the information though and fingers crossed that there is a solution to this problem at one point. For now, I will update the repository of my tutorial to include that information.
