### ISSUE TITLE
Improve navigation to cloud deployment instructions

### ISSUE THREAD

**Issue by jonmjoyce** [pangeo-data/pangeo#886]
I recently was searching for the deployment setup guide and found that several linked references are outdated now. I know that there is an ongoing effort to redesign the site so hopefully this feedback is useful.

Starting from Pangeo.io, I navigated to https://pangeo.io/setup_guides/index.html#setup-guides. From there I went to [Deploying Pangeo in the Cloud](https://pangeo.io/setup_guides/cloud.html). 

That page could probably be updated to point to the Dask Helm chart which includes JupyterHub already (https://helm.dask.org/). The zero-to-JupyterHub guide only installs JupyterHub without dask, and the other link to Pangeo Cloud Federation is not what I was looking for as a user looking to install Pangeo on my own K8s cluster.

**Comment by guillaumeeb** [comment]
Hi @jonmjoyce, it's a really good feedback and I second you!

Just to be sure, your title is about "navigation to the instructions", do you think the way you browsed to the (not up to date) instructions need to be changed?

About updating the https://pangeo.io/setup_guides/cloud.html page, I totally agree. So what should we put in this page?

- A link to Zero to Jupyterhub seems important (even if its on the Daskhub documentation page).
- I'd also put a few words about Dask-gateway (and maybe Dask-kubernetes ?). A Pangeo Cloud platform is mainly a Dask on Kubernetes enabled Jupyterhub.
- Then, we should definitely point to [Daskhub installation doc](https://docs.dask.org/en/stable/deploying-kubernetes-helm.html#helm-install-dask-for-multiple-users), and maybe the associated github repo you mention. 
- We should probably also talk a bit about how current community available Pangeo deployments are maintained by 2i2c and some links. Actually, just a link to https://pangeo.io/cloud.html in the beginning of the page?
- We could stop there, but I'd also add some information or tips on topics that came close after the basic Daskhub deployment: how to get a static IP and DNS name associated with it, https, Authentication. We could give some examples with GCP or AWS and github authentication? We can also just point to the relevant pages on Jupyterhub doc just saying these are often the next things to look at.

I can propose a PR to talk about all this if this is OK for everyone.
