### ISSUE TITLE
The showcase archive has disappeared

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#892]
https://pangeo.io/pangeo-showcase.html

<img width="889" alt="Screen Shot 2023-01-24 at 9 47 00 PM" src="https://user-images.githubusercontent.com/1197350/214469325-bff8e9d7-413d-4f7d-95e7-ed11086ac877.png">

The cause is a formatting error introduced in f06b4cba0801cee5fca578c0ef6e22e6e6867dbb. The traceback in the error log is useful.

https://github.com/pangeo-data/pangeo/actions/runs/3989098036/jobs/6841106416#step:4:113

**Comment by paigem** [comment]
Thanks @rabernat for pointing this out. I'm planning to update this page shortly with the correct dates and added speakers, and can fix this error as well. See PR #891 (which I am updating locally at the moment)

**Comment by paigem** [comment]
Fixed in #891
