### ISSUE TITLE
modules / conda environment for cheyenne

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#90]
I am back to cheyenne for some actual science calculations.

In our current [guide for cheyenne](https://pangeo-data.github.io/pangeo/setup_guides/cheyenne.html), we recommend installing miniconda in user space and creating a new conda environment for pangeo.

Is this still the recommended workflow? At some point there was discussion of a system-level module or other way to support the pangeo environment.

cc @jhamman, @davidedelvento

**Comment by jhamman** [comment]
@rabernat - we're still doing user installs of miniconda.

**Comment by davidedelvento** [comment]
*conda is not supported and can not be supported by CISL. If you'd like anything CISL-supported, have a look at https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/software/python and see if that could be adapted for your goals, otherwise user installs are the way to go.

**Comment by rabernat** [comment]
Maybe we could create a shared project-level location for conda environments and package dirs. This would avoid having to duplicate very similar environments and package in home space (yet still not require CISL support).

For example, the following `.condarc` file:
```
envs_dirs:
  - /glade/p/pangeo/conda/envs
pkgs_dirs:
  - /glade/p/pangeo/conda/pkgs
```
would allow us to share packages.

/glade/p/pangeo does not exist yet. In order to make this happen, we would need to request project space from CISL.

Worth the effort?

**Comment by jedwards4b** [comment]
I believe that CISL does support user installed modules if one of us wanted to maintain a conda module on cheyenne.

**Comment by mrocklin** [comment]
CC'ing @jjhelmus in case he knows of nice workflows for many users to
freely safely share conda package directories (and maybe environments?) on
NFS systems

**Comment by jhamman** [comment]
@kmpaul recently mentioned that there is already a custom anaconda module, so that may be an option. The problem I see is that if I still have to do a number of steps to setup my environment.

```
module load miniconda  # add shared miniconda install to $PATH
source activate pangeo
# or
source activate my-custom-pangeo-env
...stuff we do with pangeo...
```

That isn't much easier than just doing:

```
# do this stuff once
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod +x Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh

conda create -n my-custom-pangeo-env python=...

# do this everytime
source activate my-custom-pangeo-env
...stuff we do with pangeo...
```

**Comment by kmpaul** [comment]
You're right.  It's still a multi-step process.  I believe the current process goes like this on Cheyenne:

module use /glade/scratch/abanihi/ch/test_installs/modulefiles/idep/
module load conda

...then create your own conda environment.  Once you create your own conda environment, though, I think you just have to:

module use /glade/scratch/abanihi/ch/test_installs/modulefiles/idep/
module load conda
source activate my-env

You don't believe that is easier?

**Comment by jhamman** [comment]
I personally don't but I also don't really have a horse in this race either. I can see reason to support both approaches:

1) If you are an HPC guru, the module concept will be familiar to you and maybe this makes managing python environments easier for you
2) for everyone else, especially those with python experience outside of the HPC universe, the module approach is just another abstraction to a pretty simple system.

**Comment by kmpaul** [comment]
Fair enough. If miniconda is the approved approach by the community, then I don’t think we should worry about a module. I prefer one approved approach to installation and use, rather than confusing people with multiple approaches.

**Comment by jhamman** [comment]
CISL recently [posted this](https://dailyb.cisl.ucar.edu/bulletins/new-python-versions-cheyenne-new-script-loading-packages):

> New Python versions on Cheyenne with new script for loading packages
> CISL has installed new versions of Python (2.7.14 and 3.6.4) for users of the Cheyenne system, with new functionality for loading NCAR-provided Python packages. Users now load all of the latest packages at once by running a new ncar_pylib script that activates the NCAR package library in a virtual environment. Packages for earlier versions of Python can be loaded only with module load commands.
> 
> Implementing virtual environments enables users to quickly access multiple versions of their package-development codes. Users who want to customize their Python environment can simply clone the package environment as a starting point, then make modifications. The new approach also will help users avoid errors when installing their own packages by using the virtual environment rather than home directories on GLADE.
> 
> Python 2.7.14 and 3.6.4 and the NCAR package library methodology will become the default on the Cheyenne system in February, on a date to be announced. The CISL Python documentation page has been updated to describe the new procedures.

So, not exactly either workflow we have discussed here but perhaps a step in the right direction?

**Comment by mrocklin** [comment]
@kmpaul currently we recommend the following in our [documentation](https://pangeo-data.github.io/pangeo/setup_guides/cheyenne.html):

```python
conda create -n pangeo -c conda-forge python=3.6 dask distributed xarray jupyterlab mpi4py
```

Although you might want to install those directly into the root environment (drop the `-n pangeo`).  I think it's important that we be able to change this environment in the future as we find new packages 

Alternatively, we might consider having a blessed conda repository somewhere on the NFS to which users can point if desired.  This is a bit outside of the module approach but might be easier for the masses to maintain.

**Comment by kmpaul** [comment]
@mrocklin, I know the canonical Python version to use with the Pangeo platform is 3.6, but does it work with Python 2.7, as well?  Just curious.

**Comment by mrocklin** [comment]
Yes, everything there should be fine either way.  Most of the modern
scientific ecosystem supports both with a single codebase.

**Comment by jhamman** [comment]
@kmpaul - Just as an FYI, xarray is probably going to drop support for Python 2 at the end of this year: https://github.com/pydata/xarray/issues/1830

**Comment by kmpaul** [comment]
@mrocklin Great.  Thanks!  I figured, but I just wanted to know.  

@jhamman  That doesn't surprise me.  I know that Python 2 is planning to go away in the near future, but we have a lot of Python users here at NCAR that still haven't made the transition to 3.  I suspect that until they are forced to switch, they will kick and scream the whole way.

**Comment by kmpaul** [comment]
@mrocklin I almost have a conda module available on Cheyenne, but I'm trying to figure out one last step.  What's the best way to make the miniconda environments "read-only" so that other users cannot modify the contents of the "system" environments?

**Comment by kmpaul** [comment]
Okay!  I think I figured it out (see conda/conda#4888).  The "system" environments (including the root environment) are all "read-only".  That means they will yield an error if you try to do an update or install of new software into the system environments.

Here's what you need to do to use my "system" install of miniconda:

    module use /glade/p/work/kpaul/software/modulefiles
    module load conda

You can put the "module use..." line in your .bashrc or .profile file so that it is enabled every time you log in.  

Then, once you load the conda module, you can list the available "system" environments (and your own environments) with "conda env list".  There should be 3 "system" environments:

    root
    pangeo
    pangeo-py2

For convenience, the "root" environment is the same as the pangeo environment (or as the same packages installed), so you don't actually need to activate the "pangeo" environment to use dask+xarray on Cheyenne.

Please test this out and let me know that it worked for you!

**Comment by kmpaul** [comment]
Has anyone had a chance to try this?  If it appears to work for people, then I think I'll take the time to set up a cron job to update the "system" environments...maybe once a week?

**Comment by jhamman** [comment]
@kmpaul - did you get any feedback here? I'm guessing most of us just kept using our own conda environments...
