### ISSUE TITLE
The problem of using pangeo-data

### ISSUE THREAD

**Issue by LiYfeng917** [pangeo-data/pangeo#907]
When I used follow codes,
```python
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
list(cat)
ds  = cat["sea_surface_height"].to_dask()
ds
``` 
 I face this error.
```python
ValueError: Bad Request: https://storage.googleapis.com/download/storage/v1/b/pangeo-cmems-duacs/o/.zmetadata?alt=media
User project specified in the request is invalid.
``` 
And I get into this website, it told me that 
Bucket is a requester pays bucket but no user project provided.

I think maybe the problem is about i have no pangeo account.But how I can check whether i have got the account，for I had delievered my application for twice.
Thanks for all reply！

**Comment by jhamman** [comment]
Hi @LiYfeng917 - I'm sorry no one ever responded here. Most discussions like this have moved to the pangeo discourse forum now (https://discourse.pangeo.io). If this is still an issue for you, I suggest asking your question there.
