### ISSUE TITLE
Lack of resource constraints allows for killed pods

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#91]
I just put a new dataset into zarr storage. From pangeo.pydata.org, I am trying to persist about 70GB of data into a 50-node cluster with 400 GB of memory.

The workers are dying. I would like some advice on how to debug what is going on. Is there a log file I can examine somewhere?

Here is the code to reproduce the error:

```python
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt

# connect to clsuter
from daskernetes import KubeCluster
cluster = KubeCluster(n_workers=50)
client = Client(cluster)

# load dataset
import gcsfs
gcsmap = gcsfs.mapping.GCSMap('pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt')
ds = xr.open_zarr(gcsmap)

# persist a variable
sla = ds.sla.persist()
```

**Comment by mrocklin** [comment]
Please note that pangeo.pydata.org doesn't actually implement resource constraints on pods yet.  The entire cluster only has around 100GB of RAM.  It's likely that your workers are co-located on the same node and ar gobbling up more memory than they should, causing the node to crash.  Short term you should add more nodes in one of the worker pools using the console:

https://console.cloud.google.com/kubernetes/list?project=pangeo-181919

Go to the pangeo cluster, click Edit, scroll down to the bottom where it says `preemptible-pool`, click the edit button (it looks like a pen), and increase the current size to something larger, like 20.  You may want to reverse this process at some point, the adaptive scaling doesn't seem to be very responsive.

**Comment by mrocklin** [comment]
Implementing proper resource constriants is one of the many things we need to fix on the kubernetes side.

**Comment by rabernat** [comment]
Good to know. I didn't understand these details.

**Comment by jhamman** [comment]
@mrocklin wrote: 

> Implementing proper resource constriants is one of the many things we need to fix on the kubernetes side.

Is there an open issue with dask_kubernetes for this todo item?
