### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#923]
I'd like to understand traffic to this website.  I asked @rabernat about access to this in checking on that he found that apparently GA is currently broken on this site (maybe the GA-4 migration?).  So now we have two questions:

- Can I get access to GA
- We should fix GA

@rabernat is it only you who has access?  If I can get access then I'll probably want to also grant access to @scharlottej13 who has handled GA-4 transitions before and generally does a great job thinking about traffic and messaging in technical/community situations. Alternatively, if the old GA project isn't broadly and sharing access is hard for some reason  we can also have Sarah create a fresh project and then having her share it with others.

**Comment by scharlottej13** [comment]
Happy to help here. Indeed, when I looked at the google analytics id in the source html, it is pointing to the Universal Analytics ID `UA-120544092-1`, which was replaced with GA-4 in July (and so stopped sending any data). (For anyone who is maybe less familiar w/ google analytics) it's pretty easy to fix after creating the new ID in GA and then we could update it [here](https://github.com/pangeo-data/pangeo/blob/master/docs/_templates/layout.html#L116-L123) or even add it to the conf.py so it's less hidden.

**Comment by jhamman** [comment]
Turns out that I have access to our Google Analytics account. The GA-4 setup is here: 

```js
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4K4N4RYC53"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4K4N4RYC53');
</script>
```

**Comment by jhamman** [comment]
It also turns out that we were getting analytics forwarded from our old tag to this new property. Here's a look at the top 10 pages over the last 28 days:

<img width="909" alt="image" src="https://github.com/pangeo-data/pangeo/assets/2443309/eea4ecfc-a7c5-4b78-bfb7-31bbea1e4dbe">

**Comment by jhamman** [comment]
I've also given @mrocklin, @paigem, and @andersy005 analyst privileges here on the GA account. @rabernat and I are remain as admins.

**Comment by mrocklin** [comment]
Thanks @jhamman !  Can I ask you to add @scharlottej13 `sarah` at coiled.io as well?

Some observations based on that data:

1.  People don't really navigate the site, the ratio of visits between `/` and all other pages is pretty high
2. The pages that people visit the most are some indication of either availability (about is the top listed page on the TOC) and interest (cloud and packages are further down but have the same traffic)
3. Time on page is generally pretty low.  Usually this indicates poorly performing content (not a surprise, but confirms thoughts in other discussion).  The more technical pieces (packages and architecture) seem to buck this trend a little.
