### ISSUE TITLE
Update documentation for using Pangeo with Geyser/Caldera

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#94]
The [documentation](https://pangeo-data.github.io/pangeo/setup_guides/geyser_and_caldera.html) for running Jupyter notebooks on Geyser/Caldera is no longer current/valid.

This is due to changes that were made in the system configuration when Geyser/Caldera were ported from Yellowstone to Cheyenne (LSF to Slurm). After this change, CISL removed the documentation for how to launch Jupyter Notebooks on Geyser/Caldera ([docs](https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/software/python)).

I've been going back and forth with CISL Help trying to get this to work but we haven't had any luck yet. I'm hoping someone else on the NCAR/UCAR team has some bandwidth for helping with this.

Just as a reminder for why we want to have support for running Pangeo on Geyser/Caldera: 

- "The Geyser and Caldera clusters are specialized data analysis and visualization resources that users access through the Cheyenne system." -- We should be able to run our data and visualization tools on NCARs data and visualization system.
- Geyser/Caldera have access to the outside network so accessing remote datastores is possible (e.g. pushing data to GCP)
- Geyser has 1 TB memory per node and as such is a nice platform for doing memory intensive processing
- Caldera has GPUs available 

cc @davidedelvento, @kmpaul, @dopplershift, @jedwards4b

**Comment by jhamman** [comment]
To be clear, I have followed these instructions and have not been able to get this to work. I would be interested to see if anyone else, other than @davidedelvento, is able to successfully do this.

**Comment by kmpaul** [comment]
I've followed the instructions for the Geyser/Caldera launch, and these are the errors I see:

```
kpaul@geyser07:~> start-notebook 
Logging this session in /glade/scratch/kpaul/.jupyter-notebook/log.20180215T141952

Starting jupyter notebook server, please wait ... something went wrong
---
[I 14:19:54.053 NotebookApp] Serving notebooks from local directory: /glade/u/home/kpaul
[I 14:19:54.053 NotebookApp] 0 active kernels 
[I 14:19:54.054 NotebookApp] The Jupyter Notebook is running at: http://geyser07:8888/
[I 14:19:54.054 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
---

Killing Jupyter Notebook Server with PID=26932 ... done
```

**Comment by jhamman** [comment]
@kmpaul - this is the same error I was getting so I'm glad to see you're getting it too. @davidedelvento indicated that he thought something was wrong with my environment but I never managed to figure it out.

**Comment by jhamman** [comment]
@kmpaul - were you able to work past this somehow? If not, I can supply a jupyter lab launch script that fixes the problems we've all been running into.

**Comment by kmpaul** [comment]
No.  I'm getting different errors, now, but I haven't reconnected with Brian V about this.  Here are the errors that I am getting these days:

```
Logging this session in /glade/scratch/kpaul/.jupyter-notebook/log.20180301T151102

Starting jupyter notebook server, please wait ... something went wrong
---
[I 15:11:07.607 NotebookApp] The port 8888 is already in use, trying another port.
[I 15:11:07.607 NotebookApp] The port 8889 is already in use, trying another port.
[I 15:11:07.636 NotebookApp] Serving notebooks from local directory: /glade/u/home/kpaul
[I 15:11:07.636 NotebookApp] 0 active kernels 
[I 15:11:07.636 NotebookApp] The Jupyter Notebook is running at: http://r8i4n1:8890/
[I 15:11:07.636 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
---

Killing Jupyter Notebook Server with PID=30280 ... done
```

**Comment by kmpaul** [comment]
Okay.  I've testing the approved notebook startup method (from @davidedelvento) and I've finally gotten it to work.  Apparently, I had an old password key/hash in my jupyter config file, which is what was causing the problem...not obvious.  I blew away my $HOME/.jupyter directory, tried again, and it worked.

Anyway, the approved method seems to work fine, namely (what I did):

1.  `qinteractive` (wait for interactive job to start)
2.  `module load python`
3.  `module load jupyter`
4.  `start-notebook`
5.  Create the ssh tunnel on my laptop (as prompted)
6.  Go to `localhost:8888`
7.  Enter the key given me by the prompt from step 4

That still seems complicated.  I'd like to clean that up a bit.

**Comment by rabernat** [comment]
Does the "approved method" work with custom conda environments?

Given the complexity of the approved method, I don't see much advantage
over our own "non approved" method.

**Comment by matt-long** [comment]
I have been using this script to start a notebook server on geyser/caldera.  

```/glade/u/home/mclong/bin/start-jlab```

It assumes that python is implemented via conda, though this could easily be changed.  It forwards the SSH tunnel from the login node, so you get steps 1-4 all wrapped into one.  There may be some outdated aspects related to the environment you get on the geyser/caldera node with Slurm.  @davidedelvento may be able to evaluate this.  I like the single step and the ability to reconnect to a server if my SSH connection goes down. 

```
$ start-jlab --help
Usage: start jupyter lab using slurm
Launch jupyter lab using default slurm PARTITION.
Possible options are:
 -a,--account: account
 -t,--walltime: walltime
 -m,--memory: amount of memory (e.g. 80G)
 -c,--constraint: constraint (e.g. geyser, caldera)
 -p,--port: port for jupyter
 -j,--jid_id: dont't start new notebook server, but connect to one at existing job
 -e,--env: Conda environment
```

**Comment by kmpaul** [comment]
@rabernat I thought I replied to your question, but I don't see it here, so I must have forgotten to hit comment.

Anyway, the "approved method" will not work with conda.  All of the python modules on Cheyenne will inherently conflict with a conda install.

However, I'm going to try out @matt-long's approach and see if that will work from Cheyenne and Geyser.

**Comment by mkyoungs** [comment]
I was having a different problem.  When following documentation (https://github.com/pangeo-data/pangeo/blob/master/docs/setup_guides/geyser_and_caldera.rst) for geyser and caldera, the wrong version of python and jupyter end up loading and the modules that I set up in the conda environment are no longer there when I started a job on geyser/caldera.

**Comment by rabernat** [comment]
@mkyoungs thanks for your feedback! This documentation has unfortunately become a bit stale. We are planning a big update within a week or two. I'll update you as soon as we have something more useful for you.

**Comment by jhamman** [comment]
I'm cool with closing this now. Our new documentation is more complete now and should be generally applicable clusters like Geyser/Calder.
