### ISSUE TITLE
SciPy Talks/ Tutorials

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#97]
I hope can have a significant Pangeo presence at [SciPy 2018](https://scipy2018.scipy.org/ehome/299527/648104/). The submission deadline is Feb. 9.

In particular, there are at least two things we can contribute:
1. A talk on the overall effort, emphasizing the science problems associated with big climate data and the cloud / HPC solutions we are developing (composed from other SciPy-type projects, e.g. dask, jupyterhub, etc.)
2. A tutorial on xarray

Is anyone interested in leading either of these two talks?

I am still uncertain as to whether I can personally attend SciPy. (I hope to work my schedule  out very soon.) If it turns out that I can, I would be keen to give talk 1.

Just wanted to raise this for discussion and see what people are thinking.

**Comment by jhamman** [comment]
@rabernat - I was planning on submitting an abstract for for talk 1 on your list but I'm happy to defer that to you if you end up going. Another talk could be more xarray for big-data focused but still not a tutorial. 

I'd also be happy to help with a tutorial on using Xarray and dask if anyone want to team up in that area.

**Comment by mrocklin** [comment]
I agree that a tutorial would be useful.  Perhaps we should raise an issue on the XArray issue tracker?

@yuvipanda and I have a submission for PyCon on the jupyterhub/dask/pangeo stuff behind the pangeo.pydata.org site.  We could repeat that for scipy (Yuvi, are you planning to attend SciPy?).  I'd also be happy to have Yuvi give that solo if interested.

We should probably also organize a BoF.

**Comment by rabernat** [comment]
@jhamman - I am very happy for you to take the lead on 1. Please go ahead with your abstract submission. I'm happy to review if you like before you submit.

What's a BoF?

**Comment by mrocklin** [comment]
Birds of a Feather session.  It's typically about an hour and more
informal.  We might invite attendees to present their work for five minutes
or so.  Hopefully that generates conversation.

**Comment by yuvipanda** [comment]
I probably won't make it to SciPy, but I think @choldgraf is planning on making it. He can talk about JupyterHub specific stuff!

**Comment by choldgraf** [comment]
I am flip flopping since this is 1 week after my wedding in Kansas City...if I do make it, I will obviously be thrilled to hang out with y'all and chat about all this stuff

**Comment by rabernat** [comment]
@choldgraf I honestly cannot imagine a more thrilling honeymoon. I'm sure your new spouse will agree.

**Comment by dopplershift** [comment]
I'll be at SciPy, submitting for a MetPy talk and applying to give an unrelated tutorial (on setting up infrastructure for open source projects).

**Comment by jhamman** [comment]
I submitted two abstracts to Scipy today:

1. Talk: ***Pangeo: A Big-data Ecosystem for Scalable Earth System Science***
2. Tutorial: ***Xarray for Scalable Scientific Data Analysis***

More information to come as we get closer to the conference.

**Comment by mrocklin** [comment]
Good luck!

**Comment by shoyer** [comment]
I also submitted a SciPy abstract, "Typing for multi-dimensional arrays: challenges and opportunities". So I'm not sure yet, but there's a decent chance I'll attend.

**Comment by jhamman** [comment]
1 out of 2! While the Xarray tutorial was not selected for Scipy this year (https://github.com/pydata/xarray/issues/1882#issuecomment-377845565), the Pangeo talk was. They didn't provide a date or time for the talk yet but once I know that information, I'll post that here.

**Comment by shoyer** [comment]
Still TBD on my static typing talk:

> Thank you for submitting a talk to the SciPy Tools Plenary Session at SciPy 2018. This is a new session for the conference and we are quite excited about it. The SciPy Tools chairs have been in discussion with the conference chairs and have decided to set the talks by invitation rather than through the regular submission process. This will give us the best chance for an interesting mix of talks on various tools that will appeal to a broad cross-section of the community. 

> All submissions to the SciPy Tools tracks, including Typing for multi-dimensional arrays, have been added to the list of possible invitations. The chairs will be reaching out to various (core) developers over the next week or two to invite them to present. You will not receive an email from the SciPy Program Committee this week on the acceptance of your talk. Instead, the SciPy Tools plenary session chairs or I will follow up with you directly in the next few days.
